### ISSUE TITLE
Suggestion with some commands

### ISSUE THREAD

**Issue by Chromaah** [diamond-rip/Eden#100]
Hey! im not sure if this is the right place to leave a suggestion, but i suggest that there should be commands to join specific kits? for example:

 **/queue unranked \<kitname\>**
 **/queue ranked \<kitname\>**

This would add a lot of flexibility for custom menus and stuff. I hope you take this into consideration!

**Comment by GoodestEnglish** [comment]
Yes you are in the right place! This feature is highly suggested by community members and it is going to be add soon!

**Comment by Chromaah** [comment]
Thanks! Looking forward to it :)

**Comment by GoodestEnglish** [comment]
Added in https://github.com/diamond-rip/Eden/releases/tag/1.0.29-BETA-6f105b9
