### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by gabrielvicenteYT** [diamond-rip/Eden#110]
**Additions**
`[+] Add a boxing combo display placeholder like MMC's, allowing you to see the enemy's combos`
`[+] Add a hit difference placeholder, but without brackets, or colors.`

**Comment by GoodestEnglish** [comment]
You are already able to see enemy's combos with `{match-solo-boxing-difference}` (if solo) and `{match-team-boxing-difference}` (if teams)
In the next update brackets will be removed. I will also add a colorless placeholder into it
