### ISSUE TITLE
Placeholder Question

### ISSUE THREAD

**Issue by Chromaah** [diamond-rip/Eden#111]
Hello, I just wanted to ask if there are placeholders for this plugin? (i did '/papi list' in placeholder api and saw that 'Eden' was one) If so what are they?

**Comment by GoodestEnglish** [comment]
Right now it doesn't have any placeholder yet. I will start implement placeholders in the future.

**Comment by GoodestEnglish** [comment]
I am going to add a few simple placeholders first. What placeholder do you currently want?

**Comment by HierarchyMan** [comment]
Queing playing wins losses kdr matches-played top-3-winstreak highest-elo highest-rank

**Comment by Chromaah** [comment]
i think mostly just wins and kills is important lol

**Comment by HierarchyMan** [comment]
I listed all of those because I use deluxemenus to make MMC style queue menu
And the listed placeholders are required for it to look good/complete.

**Comment by Chromaah** [comment]
fair, i wanted mostly just those so i can make a clean leaderboard :)

**Comment by GoodestEnglish** [comment]
The latest release added bunch of papi placeholders. And I've created a list of placeholders in https://github.com/diamond-rip/Eden/wiki/Placeholders. Let me know if anything needs to be added/fixed

**Comment by Chromaah** [comment]
perfect!

**Comment by HierarchyMan** [comment]
yeah
