### ISSUE TITLE
Wiki question

### ISSUE THREAD

**Issue by HierarchyMan** [diamond-rip/Eden#114]
Is there a category in Eden wiki which shows all things that can be used in language.yml and stuff
Eg:- {match-duration} etc

**Comment by GoodestEnglish** [comment]
Will add soon

**Comment by HierarchyMan** [comment]
Wow this is what I was looking for
Thank you for putting in so much work

**Comment by HappyAreaBean** [comment]
> Wow this is what I was looking for Thank you for putting in so much work

You're welcome. I just use a bit of ✨magic✨ code to get it. 😳
