### ISSUE TITLE
NoSpeed doesnt work as Expected

### ISSUE THREAD

**Issue by HierarchyMan** [diamond-rip/Eden#115]
doing /nospeed does remove speed but it says "Succesfully force ended {0}'s Match"
doint /nospeed again doesnt give back speed effect

Suggestion:
allow us to specify nospeed kb for the same kit so kb doesnt feel wierd
i also got nospeedboxing so if u make /nospeed to also give back speed effect, only let it if the kit initially had speed

**Comment by GoodestEnglish** [comment]
I believe I imported the wrong message enum. I will fix it in the next update. 

I never use the nospeed command in mmc, so I thought it only remove the speed effect. The speed effect will be added soon

Knockback will not be made in my side. All knockback should be handle by spigot. Never use any plugin to modify player's knockback unless the plugin override java classes.

**Comment by HierarchyMan** [comment]
ok fair

**Comment by GoodestEnglish** [comment]
Fixed in latest release
