### ISSUE TITLE
some suggestions

### ISSUE THREAD

**Issue by Shzv** [diamond-rip/Eden#117]
• Modify kit When a person hasn't modified the kit he is still given the book, like lunar but in my opinion the method used on mmc (minemen) is more convenient which only when you modify the kit gives you the default books and the saved set .
(playing with my friends and other people i notice it is very annoying)

• Changing the combo counter.
now the combo counter only shows the number but it would be nice to have the possibility to have combo counter like minemen, esta, pvp.land etc.
with also the possibility if it is feasible to change the writing before the combos.

example:
NOT IN COMBO:

No combo/ 1st to 100! or whatever you want

COMBO:

"4/10/2.. Combo" with a variation from red for your opponent and green for you

I don't know if I explained myself well

**Comment by HierarchyMan** [comment]
I don't think the 1st option is needed
But for the second option we can have something like {solo-boxing-combo-counter-color} and then we can edit the text ourselves to make it like mmc

**Comment by GoodestEnglish** [comment]
Would let user to customize the combo '0 combo' text soon. 
Also the next update would take a while, cuz I have to rush apex ranked 😅

**Comment by GoodestEnglish** [comment]
Added in latest update: https://github.com/diamond-rip/Eden/releases/tag/1.0.33-BETA-bbeb449
