### ISSUE TITLE
WindSpigot Kb profile doesnt work

### ISSUE THREAD

**Issue by HierarchyMan** [diamond-rip/Eden#119]
i specified kb in kit and that kb is present but default kb is used no matter what

**Comment by GoodestEnglish** [comment]
What version of WindSpigot are you using?
I've take a look and looks like WindSpigot changed a lot of their API stuff in their latest update but the update didn't release to public.

**Comment by HierarchyMan** [comment]
Then tell me which version I should use I'm ok with using an older version

**Comment by GoodestEnglish** [comment]
Never mind, I apologize. Looks like I forgot to put the latest Eden SpigotAPI addon into the latest release of Eden. It will be fixed in the next update

**Comment by GoodestEnglish** [comment]
Fixed in latest update: https://github.com/diamond-rip/Eden/releases/tag/1.0.33-BETA-bbeb449
