### ISSUE TITLE
FIX and add new features

### ISSUE THREAD

**Issue by Mekvil** [diamond-rip/Eden#121]
Hi
1.Make when match end fast teleport to lobby like you need wait 5 seconds for teleport to spawn when match end make it 2 seconds.
2.fix pots display, when someone have 0 and other have more then 0 he says this 
![image](https://user-images.githubusercontent.com/40424128/216828429-4750c724-3562-417f-b9eb-e1027762b150.png)
3.when you play unranked 
![image](https://user-images.githubusercontent.com/40424128/216828838-3b3bf456-0f98-4847-a595-528e1e96f124.png)
when you play duel
![image](https://user-images.githubusercontent.com/40424128/216828883-287db7df-c530-4aff-aa1b-128f42996f9a.png)
it's just nothing
4.make command to acess settings pracsettings bc the default command(settings) its taken by core like aqua or other plugins
i hope you do this
and also if you can make fly for donators on lobby

**Comment by HierarchyMan** [comment]
I think we should get configurable end time

**Comment by HierarchyMan** [comment]
Fly in lobby for donators can be done using core
And pot display works fine for me

**Comment by Mekvil** [comment]
+ soups not uses

**Comment by GoodestEnglish** [comment]
Fixed all of these in latest update: https://github.com/diamond-rip/Eden/releases/tag/1.0.33-BETA-bbeb449
