### ISSUE TITLE
items

### ISSUE THREAD

**Issue by Mekvil** [diamond-rip/Eden#126]
when you que a game you get right items like if you red you get red wool if you blue you get blue but if you die you get default white wool fix it

**Comment by GoodestEnglish** [comment]
Send your kit.yml and let me know which kit are you using

**Comment by Mekvil** [comment]
BattleRush:
    enabled: true
    ranked: true
    display-name: BattleRush
    priority: 11
    damage-ticks: 19
    display-icon: |
      rO0ABXNyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAADbWFwdAAPTGph
      dmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFibGVNYXAk
      U2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAlsABGtleXN0ABNbTGphdmEvbGFuZy9PYmplY3Q7WwAG
      dmFsdWVzcQB+AAR4cHVyABNbTGphdmEubGFuZy5PYmplY3Q7kM5YnxBzKWwCAAB4cAAAAAJ0AAI9
      PXQABHR5cGV1cQB+AAYAAAACdAAeb3JnLmJ1a2tpdC5pbnZlbnRvcnkuSXRlbVN0YWNrdAAKV0FU
      RVJfTElMWQ==
    description: '[]'
    potion-effects: ''
    armor-loadout: |
      rO0ABXcEAAAABHNyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAADbWFw
      dAAPTGphdmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFi
      bGVNYXAkU2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAlsABGtleXN0ABNbTGphdmEvbGFuZy9PYmpl
      Y3Q7WwAGdmFsdWVzcQB+AAR4cHVyABNbTGphdmEubGFuZy5PYmplY3Q7kM5YnxBzKWwCAAB4cAAA
      AAR0AAI9PXQABHR5cGV0AAZkYW1hZ2V0AAZhbW91bnR1cQB+AAYAAAAEdAAeb3JnLmJ1a2tpdC5p
      bnZlbnRvcnkuSXRlbVN0YWNrdAADQUlSc3IAD2phdmEubGFuZy5TaG9ydGhNNxM0YNpSAgABUwAF
      dmFsdWV4cgAQamF2YS5sYW5nLk51bWJlcoaslR0LlOCLAgAAeHD//3NyABFqYXZhLmxhbmcuSW50
      ZWdlchLioKT3gYc4AgABSQAFdmFsdWV4cQB+ABAAAAAAc3EAfgAAc3EAfgADdXEAfgAGAAAABHEA
      fgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgANcQB+AA5xAH4AEXEAfgATc3EAfgAAc3EA
      fgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAABHEAfgANcQB+AA5xAH4A
      EXEAfgATc3EAfgAAc3EAfgADdXEAfgAGAAAABHEAfgAIcQB+AAlxAH4ACnEAfgALdXEAfgAGAAAA
      BHEAfgANcQB+AA5xAH4AEXEAfgAT
    contents-loadout: |
      rO0ABXcEAAAAJHBzcgAab3JnLmJ1a2tpdC51dGlsLmlvLldyYXBwZXLyUEfs8RJvBQIAAUwAA21h
      cHQAD0xqYXZhL3V0aWwvTWFwO3hwc3IANWNvbS5nb29nbGUuY29tbW9uLmNvbGxlY3QuSW1tdXRh
      YmxlTWFwJFNlcmlhbGl6ZWRGb3JtAAAAAAAAAAACAAJbAARrZXlzdAATW0xqYXZhL2xhbmcvT2Jq
      ZWN0O1sABnZhbHVlc3EAfgAEeHB1cgATW0xqYXZhLmxhbmcuT2JqZWN0O5DOWJ8QcylsAgAAeHAA
      AAADdAACPT10AAR0eXBldAAGYW1vdW50dXEAfgAGAAAAA3QAHm9yZy5idWtraXQuaW52ZW50b3J5
      Lkl0ZW1TdGFja3QABFdPT0xzcgARamF2YS5sYW5nLkludGVnZXIS4qCk94GHOAIAAUkABXZhbHVl
      eHIAEGphdmEubGFuZy5OdW1iZXKGrJUdC5TgiwIAAHhwAAAAQHNxAH4AAHNxAH4AA3VxAH4ABgAA
      AAJxAH4ACHEAfgAJdXEAfgAGAAAAAnEAfgAMdAAGU0hFQVJTcHBwcHBwcHBwcHBwcHBwcHBwcHBw
      cHBwcHBwcHBwcHBw
    game-rules: '{"receiveKitLoadoutBook":false,"deathOnWater":false,"boxing":false,"bed":false,"breakGoal":false,"portalGoal":true,"projectileOnly":false,"hypixelUHC":false,"spleef":false,"healthRegeneration":true,"showHealth":true,"foodLevelChange":true,"point":false,"rankedPoint":false,"resetArenaWhenGetPoint":false,"onlyLoserResetPositionWhenGetPoint":false,"build":true,"startFreeze":true,"noDamage":false,"instantGapple":false,"enderPearlCooldown":false,"clearBlock":true,"dropItemWhenDie":false,"noFallDamage":true,"giveBackArrow":false,"dropItems":true,"respawnTime":3,"maximumPoints":3,"newRoundTime":3,"clearBlockTime":10,"knockbackName":"default"}'
    kit-match-types: '["SOLO"]'
    kit-extra-item: '[]'

**Comment by GoodestEnglish** [comment]
Will fix soon, but right now please enable receiveKitLoadoutBook so the color can correctly changes
