### ISSUE TITLE
Eden crash

### ISSUE THREAD

**Issue by L30nard0100b** [diamond-rip/Eden#127]
![IMG_20230206_181656](https://user-images.githubusercontent.com/111870720/217043176-9760466f-90ae-4072-81ca-f6afbc95f628.jpg)
I have this issue, can anyone help me?

**Comment by GoodestEnglish** [comment]
Send your arena.yml file

**Comment by L30nard0100b** [comment]
arenas:
  pokemon:
    display-name: pokemon
    icon: |
      rO0ABXNyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAADbWFwdAAPTGph
      dmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFibGVNYXAk
      U2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAlsABGtleXN0ABNbTGphdmEvbGFuZy9PYmplY3Q7WwAG
      dmFsdWVzcQB+AAR4cHVyABNbTGphdmEubGFuZy5PYmplY3Q7kM5YnxBzKWwCAAB4cAAAAAJ0AAI9
      PXQABHR5cGV1cQB+AAYAAAACdAAeb3JnLmJ1a2tpdC5pbnZlbnRvcnkuSXRlbVN0YWNrdAAFR1JB
      U1M=
    y-limit: 0
    build-max: -1
    portal-protection-radius: 3
    kits: []
    enabled: false
    details:
      '0':
        a: 'null'
        b: 'null'
        min: 'null'
        max: 'null'

**Comment by GoodestEnglish** [comment]
Never save your arena if your min, max, a, b point aren't set yet. 

To fix this, please remove your 'pokemon' arena in arena.yml, and recreate the pokemon arena with all point set.

**Comment by L30nard0100b** [comment]
Tysm
