### ISSUE TITLE
Bug postmatch

### ISSUE THREAD

**Issue by Mekvil** [diamond-rip/Eden#132]
you didnt fix postmatch https://i.imgur.com/px9HWeo.png

**Comment by GoodestEnglish** [comment]
Please try this version and if this version didn't work for you, make a new issue. https://github.com/diamond-rip/Eden/releases/tag/1.0.34-BETA-84a7d27

**Comment by Mekvil** [comment]
It's newest version 😑

**Comment by GoodestEnglish** [comment]
>

**Comment by GoodestEnglish** [comment]
> It's newest version 😑

What do you mean?

**Comment by GoodestEnglish** [comment]
https://github.com/diamond-rip/Eden/releases/tag/1.0.35-BETA-7dbab08 Fixed in latest version (For real this time)
