### ISSUE TITLE
Party fight

### ISSUE THREAD

**Issue by Mekvil** [diamond-rip/Eden#133]
when you play party fight's and it's more than 5 players it's bugged match never end

**Comment by GoodestEnglish** [comment]
Need more details. For example, what type of match? How the bug exactly occurs? Any video  I can view?

**Comment by GoodestEnglish** [comment]
Also, can someone try to replicate and reproduce this bug? Since I don't have 5 alts and my computer can't handle 5 minecraft instance 😅

**Comment by GoodestEnglish** [comment]
Closing this as no more information
