### ISSUE TITLE
New bug

### ISSUE THREAD

**Issue by Mekvil** [diamond-rip/Eden#134]
bug you'r plugin has soo much bug pls leet me sleep 
1.Miss bug. 1 throw pot = 1 miss
![image](https://user-images.githubusercontent.com/40424128/218333512-84c1bec4-cb3d-43e8-a804-81457a4b29e2.png)

**Comment by GoodestEnglish** [comment]
Stop use this plugin if you are blind. I literally said in the last release. Learn how to read and respect before you come. 

https://github.com/diamond-rip/Eden/releases/tag/1.0.34-BETA-84a7d27
