### ISSUE TITLE
 Cool Tips

### ISSUE THREAD

**Issue by Shzv** [diamond-rip/Eden#136]
**✦ Removing the bow hit for oneself, when one goes to bow boost or goes to hit himself with an arrow by himself the message (bowhit...... 18 heart) comes out and I think it is useless to see this for oneself. It's fine when you hit others it warns you but when you hit yourself it doesn't**

**✦ The possibility of having different queue messages (ranked, unranked ..) (one per mode) that can be customized**

**✦ Adding the kiteditor command to kit. Same as queue [kit]
     kit editor should also have the command (editkits [your kits]) for more flexibility.**

**✦  the possibility of having two types of book for edit kit one like the lunar which is already present but I would like the addition of the method that is on minemen.
I'm not saying to remove the method that is present now (like lunar) but I would like to have the possibility to choose the method I prefer.**

**✦ add game rules to make the parkour kit**

**✦ the ability to see players at spawn via a permission with an option in the practice settings that enables or disables or requests permission if you don't have it (customizable permission message)**

**✦ adding more placeholders  for example
 {match-solo-kill} to see the kills you make in bedwars or bridge or any mode (scoreboard in game)**

**"✦  (The addition of ffa and duo modes more events. I know they take a lot of time I would really like to see them in the future)"**
 
**EDIT AND ADDED:** 
**✦ the ability to create the scoreboard by kit for example: you want to have the bridge scoreboard different from the other modes with points,
simply calling the scoreboard with the kit you want example (bridge:
[scoreboard]) you will have the different scoreboard in game.
I don't know if I explained myself well and if this thing is feasible but it would be really interesting to see this function.**

**Comment by TehJays** [comment]
add {match-solo-duration}  {match-team-duration} placeholder

**Comment by GoodestEnglish** [comment]
> add {match-solo-duration} {match-team-duration} placeholder

Why and what's the difference between those?

**Comment by TehJays** [comment]
> > add {match-solo-duration} {match-team-duration} placeholder
> 
> Why and what's the difference between those?

it will show the match duration during a match

**Comment by GoodestEnglish** [comment]
> > > add {match-solo-duration} {match-team-duration} placeholder
> 
> > 
> 
> > Why and what's the difference between those?
> 
> 
> 
> it will show the match duration during a match

I believe there's already a placeholder, check wiki for more info

**Comment by GoodestEnglish** [comment]
Added some of the suggested features in the latest update. Parkour will be next after enderpearl issue fixes.
The others won't be added/have a low priority to be added.
