### ISSUE TITLE
eden doesnt load

### ISSUE THREAD

**Issue by L30nard0100b** [diamond-rip/Eden#137]
i have this issue, i think its bc the server stopped and i diddnt finished to setup the arena
![Cattura](https://user-images.githubusercontent.com/111870720/220089724-f8bbe211-b8a3-4d06-882e-29847a869d5c.PNG)

**Comment by diocan** [comment]
+1

**Comment by GoodestEnglish** [comment]
I will have a look into this. But right now please manually remove the unfinished arena in the arena.yml file.
