### ISSUE TITLE
Arena

### ISSUE THREAD

**Issue by TehJays** [diamond-rip/Eden#140]
is there a tutorial to making a bedfight arena? I'm having issues with it.
I can't place blocks and players can break the arena.

**Comment by GoodestEnglish** [comment]
It is the same with https://github.com/diamond-rip/Eden/wiki/Arenas-Setup. A lot of user has asked me about this and all of them are because they did't set the max/min correctly.

**Comment by TehJays** [comment]
I deleted my old arena.yml. Sorry. But how did I set the min/max wrong? Pleease help me out!

**Comment by GoodestEnglish** [comment]
Can't help if there's no data. Try to set a arena by yourself and if it doesn't work, send the arena.yml

**Comment by TehJays** [comment]
Do you have a bedfight arena i can use, please?

**Comment by GoodestEnglish** [comment]
Unfortunately I can't. I don't own a server. But I will keep this issue on for a week if you want and see if any community members can give you.

**Comment by GoodestEnglish** [comment]
You forgot to set your build-max

**Comment by TehJays** [comment]
I set the build-max to 50 but it still didn't work.
here is the arena: https://www.mediafire.com/file/heg0tbz1z0i6c2x/Bedfight.tar/file

**Comment by GoodestEnglish** [comment]
62 is larger than 50 thats why. Your build-max must be higher than your team spawn point

**Comment by TehJays** [comment]
so, 80 or 95 is a good build-max?

**Comment by GoodestEnglish** [comment]
Could be, that's all up to you.

**Comment by TehJays** [comment]
could u try it pls?

**Comment by GoodestEnglish** [comment]
Why?

**Comment by TehJays** [comment]
It works!! thanks for ur help.
