### ISSUE TITLE
Placeholder on party fight cant load (boxing)

### ISSUE THREAD

**Issue by diocan** [diamond-rip/Eden#141]
https://imgur.com/a/4lPGg6w

**Comment by GoodestEnglish** [comment]
Upgrade or reset your language.yml, you are using a WAY too old configuratiob

**Comment by diocan** [comment]
I just tried it and it hasn't changed precisely that I have the latest beta on github

**Comment by diocan** [comment]
you can add that items like
"unranked sword" and "ranked sword" have no duration? the only way to reset the duration of these swords is to move them into your inventory

**Comment by GoodestEnglish** [comment]
> you can add that items like "unranked sword" and "ranked sword" have no duration? the only way to reset the duration of these swords is to move them into your inventory

I can make it. Will be in the next update.

**Comment by GoodestEnglish** [comment]
> I just tried it and it hasn't changed precisely that I have the latest beta on github

I will double check

**Comment by diocan** [comment]
please fix build in battlerush all players cant build, in /kit battlerush is enable btw doesnt work

Thenks for your fantasty plugin!

**Comment by diocan** [comment]
MlGRUSH doesnt respawn bed why ? its a bug ?

**Comment by diocan** [comment]
ok no its my problem sorry
