### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by TehJays** [diamond-rip/Eden#143]
I have a few suggestions that should be added in!
⋄ Support for FoxSpigot (pls)
⋄ Make the settings menu FULLY editable (e.g. https://github.com/tehShifu/Practice/blob/main/src/main/resources/settings/menu.yml)
⋄ Change the solo post-match inventory msg to the teams post-match inventory msg

( also pls fix the spec menu being a diff language even tho i use the english config (https://imgur.com/dGsSgFK)

**Comment by GoodestEnglish** [comment]
I believe foxspigot is already supported. I don't own FoxSpigot so i am not sure if I did the reflecfion wrong or not.

Menu is not going to be customisable for now. You have to use extra plugins like delexemenu if you want to use customise menu.

I will fix the spectate menu language soon

**Comment by TehJays** [comment]
Also add:
Default enabled/disabled settings, basically u can enable certain player settings by default in config 
e.g.
Default-settings:
 Arena select: enable
 time: night
etc.

**Comment by GoodestEnglish** [comment]
Added in latest update
