### ISSUE TITLE
DeluxeMenus

### ISSUE THREAD

**Issue by diocan** [diamond-rip/Eden#144]
how can I create a custom gui with deluxemenus to choose the modes and that above all is compatible with the placeholders of Eden ?

**Comment by GoodestEnglish** [comment]
Here's an example from our community members: https://github.com/diamond-rip/Eden/discussions/130

**Comment by diocan** [comment]
where can i find deluxemenus 1.8.9 ? (compatible with those files ?)

**Comment by GoodestEnglish** [comment]
I believe spigotmc has. I don't use deluxemenu so im not sure

**Comment by diocan** [comment]
i find that thankx good work for new update <3
