### ISSUE TITLE
placeholder on hologram

### ISSUE THREAD

**Issue by diocan** [diamond-rip/Eden#145]

**Comment by diocan** [comment]
https://imgur.com/a/rM8x4Ks

**Comment by GoodestEnglish** [comment]
![image](https://user-images.githubusercontent.com/45838505/222302128-06a966a3-2eb7-4f1d-aadf-d443564de570.png)
Can't reproduce. Try to use the command `/papi parse <your ign> %eden_ranked_win%` and see if it works or not

**Comment by HappyAreaBean** [comment]
Only HolographicDisplays v3 have built-in support for the Placeholder API, update your HolographicDisplays to v3.

**Comment by diocan** [comment]
papi parse work, placeholder work only in latest holo v3.0.1
thanks <3
