### ISSUE TITLE
Nodebuff

### ISSUE THREAD

**Issue by TehJays** [diamond-rip/Eden#147]
![image](https://user-images.githubusercontent.com/111479184/222970960-f081c57f-b50d-4af1-9783-528d78b9217a.png)
i am getting this error in post-match inventory, currently its in only nodebuff

**Comment by GoodestEnglish** [comment]
Need a full image on it. You cut half of the error message.

**Comment by TehJays** [comment]
![image](https://user-images.githubusercontent.com/111479184/222971606-ed5ffb7f-03c9-42c6-aa2e-b8c22a695d1f.png)

**Comment by GoodestEnglish** [comment]
Can't reproduce error. Send your current language.yml here, or try to reset your language.yml.

**Comment by TehJays** [comment]
its fixed, thanks!
