### ISSUE TITLE
Settings Commmands

### ISSUE THREAD

**Issue by TehJays** [diamond-rip/Eden#150]
add all the settings cmds so people can make custom menus
e.g: 
/day
/night
/afternoon
/midnight
/tooglescoreboard
/togglearenaselector
/toggleduelreqs
/toggleinvites
/togglespectators
/toggleeventannouncement
**PING RANGE CMDS**
/pingunlimited
/ping 500
/ping 200
/ping 100
/ping 50
/ping 30

**Comment by TehJays** [comment]
Also allow editing match countdown
![image](https://user-images.githubusercontent.com/111479184/223587367-b5b57e56-027a-4984-a26f-669f82143400.png)

**Comment by Chromaah** [comment]
> Also allow editing match countdown 

i agree with that

**Comment by GoodestEnglish** [comment]
Will do in the next update.

**Comment by GoodestEnglish** [comment]
Added all of them in latest update ;)

**Comment by Chromaah** [comment]
> Added all of them in latest update ;)

One more thing, do you think it would be possible to edit the countdown format itself in like the language file? for example:

plugins/Eden/language.yml

>match:
#change the format in which the game start text will display.
  start-countdown: '&e{0}...'
  
  This would make the countdown editable in whatever format you'd like, '{0}' being the time configured for the game to start.

**Comment by GoodestEnglish** [comment]
> > Added all of them in latest update ;)
> 
> One more thing, do you think it would be possible to edit the countdown format itself in like the language file? for example:
> 
> plugins/Eden/language.yml
> 
> > match:
> > #change the format in which the game start text will display.
> > start-countdown: '&e{0}...'
> 
> This would make the countdown editable in whatever format you'd like, '{0}' being the time configured for the game to start.

Yes it is possible. Should be adding this soon

**Comment by TehJays** [comment]
> > Added all of them in latest update ;)
> 
> One more thing, do you think it would be possible to edit the countdown format itself in like the language file? for example:
> 
> plugins/Eden/language.yml
> 
> > match:
> > #change the format in which the game start text will display.
> > start-countdown: '&e{0}...'
> 
> This would make the countdown editable in whatever format you'd like, '{0}' being the time configured for the game to start.
thats what i meant in the first place 😭

**Comment by GoodestEnglish** [comment]
> > > Added all of them in latest update ;)
> > 
> > 
> > One more thing, do you think it would be possible to edit the countdown format itself in like the language file? for example:
> > plugins/Eden/language.yml
> > > match:
> > > #change the format in which the game start text will display.
> > > start-countdown: '&e{0}...'
> > 
> > 
> > This would make the countdown editable in whatever format you'd like, '{0}' being the time configured for the game to start.
> 
> thats what i meant in the first place 😭

I thought you mean the second of the countdown, but anyways, coming soon too.

**Comment by GoodestEnglish** [comment]
Added in latest update
