### ISSUE TITLE
tip

### ISSUE THREAD

**Issue by arm4xlll** [diamond-rip/Eden#156]
- titles like minemen for unranked mode (silver,iron,gold,dimonds etc.). 
Adding them to the statistics and the ability to change the name of the titles and wins to update the title
- the ability to customize the menu (menu size, location of kits etc.)

**Comment by GoodestEnglish** [comment]
Titles will be considered. However customize the menu will not be added. Use delexemenus or other type of plugin which allows to create custom menu.

**Comment by TehJays** [comment]
> Titles will be considered. However customize the menu will not be added. Use delexemenus or other type of plugin which allows to create custom menu.

DeluxeMenus does not allow the number of blocks to increase; for example the default menu (that eden has) increases when the kit playing count increases. But in deluxemenu that isnt possible

**Comment by HierarchyMan** [comment]
> > Titles will be considered. However customize the menu will not be added. Use delexemenus or other type of plugin which allows to create custom menu.
> 
> DeluxeMenus does not allow the number of blocks to increase; for example the default menu (that eden has) increases when the kit playing count increases. But in deluxemenu that isnt possible

Yes true,
Only if the number of blocks could be changed by a placeholder provided by eden
Eg: %kitname-ongoingmatches%

**Comment by GoodestEnglish** [comment]
Moved to #175
