### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by mallusrgreatv2** [diamond-rip/Eden#157]
Error 1, PlayerDeathEvent: https://pastes.dev/wtk2PNnzsA
Error 2, Task 53: https://pastes.dev/MeWu7bN98A

**Comment by GoodestEnglish** [comment]
PlayerDeathEvent could be an easy fix. But I cannot reproduce the error. May I know how to reproduce the error? By what I tested when two player fights, it doesn't happen

**Comment by mallusrgreatv2** [comment]
> PlayerDeathEvent could be an easy fix. But I cannot reproduce the error. May I know how to reproduce the error? By what I tested when two player fights, it doesn't happen

Not sure, here's the entire log: https://mclo.gs/UMcdOPI
It seems to happen randomly (at least on the console). Probably when a match is finished and the kit with the boxing feature enabled tries to kill the player after 100 hits?

**Comment by GoodestEnglish** [comment]
Should be fixed in the latest update
