### ISSUE TITLE
New settings command

### ISSUE THREAD

**Issue by TehJays** [diamond-rip/Eden#160]
![image](https://user-images.githubusercontent.com/111479184/224420706-ac08141f-3782-4e37-8c7e-472b3390caed.png)

this error shows up whenever run the new settings cmd that come out.

**Comment by GoodestEnglish** [comment]
This message is newly added in the latest release. If you see this kind of error message, it means you didnt/incorrectly update your language.yml file.

2 options:
- Re-add the missing fields into your language.yml file
- Reset your language.yml file

**Comment by TehJays** [comment]
its fixed. Thanks!

**Comment by TehJays** [comment]
![image](https://user-images.githubusercontent.com/111479184/224443689-f32cdba7-65ae-4126-8f2d-18bbd56742b2.png)
nvm it did not work, i reset my language file and its still thre

**Comment by mallusrgreatv2** [comment]
@GoodestEnglish close?

**Comment by GoodestEnglish** [comment]
Will be fixed in next release
