### ISSUE TITLE
[Eden] Prefix

### ISSUE THREAD

**Issue by TehJays** [diamond-rip/Eden#162]
![image](https://user-images.githubusercontent.com/111479184/224444485-c2aecd0c-2681-40aa-bd21-1e6435e7498e.png)
Make it so the [Eden] prefix is editable plz

**Comment by GoodestEnglish** [comment]
> ![image](https://user-images.githubusercontent.com/111479184/224444485-c2aecd0c-2681-40aa-bd21-1e6435e7498e.png) Make it so the [Eden] prefix is editable plz

Currently this is not editable. If you see this message that means Eden is trying to get your data through database.
This process should take around ~50ms aka 0.05 seconds. So I assume you did something wrong, or the database is too slow to react (which you should fix if this is the scenario)
