### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by TehJays** [diamond-rip/Eden#163]
[LOG] ERROR: Cannot find match when explosion happens (X: -43.17 Y: 91.81 Z: 41.61 Pitch: 0 Yaw: 92.04)

What does this mean?

**Comment by mallusrgreatv2** [comment]
That means the code couldn't find the match based on that coordinates. Probably, an explosion happened at that place while the match was not happening.

**Comment by GoodestEnglish** [comment]
> That means the code couldn't find the match based on that coordinates. Probably, an explosion happened at that place while the match was not happening.

Thanks for the explain. It's pretty much what you said. This error should not happen and I think it is related to #164. Please send us your arena configuration about the arena which the error occurs.

**Comment by TehJays** [comment]
it occurs in 2 of mine arenas:
  UFO:
    display-name: '&cUFO'
    icon: |
      rO0ABXNyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAADbWFwdAAPTGph
      dmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFibGVNYXAk
      U2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAlsABGtleXN0ABNbTGphdmEvbGFuZy9PYmplY3Q7WwAG
      dmFsdWVzcQB+AAR4cHVyABNbTGphdmEubGFuZy5PYmplY3Q7kM5YnxBzKWwCAAB4cAAAAAJ0AAI9
      PXQABHR5cGV1cQB+AAYAAAACdAAeb3JnLmJ1a2tpdC5pbnZlbnRvcnkuSXRlbVN0YWNrdAAJRU1Q
      VFlfTUFQ
    y-limit: 80
    build-max: 99
    portal-protection-radius: 3
    kits:
    - battlerush
    enabled: true
    details:
      '0':
        a: '#w;brUFO:#x;591940.5093813065:#y;92.0:#z;591964.4981254381:#p;0.23477094:#yaw;-359.8557'
        b: '#w;brUFO:#x;591940.5122195968:#y;92.0:#z;591974.5629626435:#p;0.0017578922:#yaw;-179.97632'
        min: '#w;brUFO:#x;591927.0:#y;84.0:#z;591925.0:#p;0.0:#yaw;0.0'
        max: '#w;brUFO:#x;591951.0:#y;103.0:#z;592013.0:#p;0.0:#yaw;0.0'

  Penguin:
    display-name: '&cPenguin'
    icon: |
      rO0ABXNyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAADbWFwdAAPTGph
      dmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFibGVNYXAk
      U2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAlsABGtleXN0ABNbTGphdmEvbGFuZy9PYmplY3Q7WwAG
      dmFsdWVzcQB+AAR4cHVyABNbTGphdmEubGFuZy5PYmplY3Q7kM5YnxBzKWwCAAB4cAAAAAJ0AAI9
      PXQABHR5cGV1cQB+AAYAAAACdAAeb3JnLmJ1a2tpdC5pbnZlbnRvcnkuSXRlbVN0YWNrdAAJRU1Q
      VFlfTUFQ
    y-limit: 79
    build-max: 99
    portal-protection-radius: 3
    kits:
    - BedFight
    enabled: true
    details:
      '0':
        a: '#w;bfPenguin:#x;836882.5527944909:#y;92.0:#z;836836.5089354635:#p;-1.048552:#yaw;89.88179'
        b: '#w;bfPenguin:#x;836844.4511913663:#y;92.0:#z;836836.4763670656:#p;0.058226675:#yaw;-90.173004'
        min: '#w;bfPenguin:#x;836813.0:#y;80.0:#z;836856.0:#p;0.0:#yaw;0.0'
        max: '#w;bfPenguin:#x;836906.0:#y;112.0:#z;836823.0:#p;0.0:#yaw;0.0'

**Comment by GoodestEnglish** [comment]
So yea, as you can see, when the explosion happens, there's no arena near it. That's why.
I am not sure what causes the explosion, as Eden should already cancel creeper natual spawn (unless someone in your server was playing with explosives)

**Comment by GoodestEnglish** [comment]
> So yea, as you can see, when the explosion happens, there's no arena near it. That's why. I am not sure what causes the explosion, as Eden should already cancel creeper natual spawn (unless someone in your server was playing with explosives)
> 
> Edit: I don't think this issue is related to #164 then

**Comment by TehJays** [comment]
I found a fix for it, thanks for the help :D
