### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by TehJays** [diamond-rip/Eden#164]
non opped players cannot build in arenas (build height is set perfectly btw)

my plugin list:
![image](https://user-images.githubusercontent.com/111479184/224486017-536aa849-1496-4bf1-a840-59d290e74b15.png)

**Comment by mallusrgreatv2** [comment]
Can you send the arena configuration?

**Comment by TehJays** [comment]
it actually happens inventory kit that has build enabled, im not sure whats the problem

**Comment by GoodestEnglish** [comment]
So I've looked though the code, Eden doesn't do anything with permission on building. If this keeps happening. I would like to see a short video which contain **Coordinate Mod**

**Comment by TehJays** [comment]
https://streamable.com/2ioo8n
i didnt make with coordinate mod

**Comment by GoodestEnglish** [comment]
Is this issue still exists?

**Comment by TehJays** [comment]
> Is this issue still exists?

I haven't tested yet

**Comment by TehJays** [comment]
I've tested it, and it is still there. A player who is deopped can't build

**Comment by GoodestEnglish** [comment]
Pretty awkward issue. Eden does not check for permissions when player tries to build. Eden only checks if player is in creative mode or not. Sorry but I do not think there's a solution right now, but I will keep track on this.

**Comment by TehJays** [comment]
is it cuz of l core? at this point im not even sure why its happening 😭

**Comment by HierarchyMan** [comment]
I think I know what's happening
1) try to set spawn protection to 0 in server.properties
2) recheck arena min/max, y limit, build limit

**Comment by TehJays** [comment]
Its fixed, I set the spawn protection to 0

**Comment by HierarchyMan** [comment]
:)
