### ISSUE TITLE
Kill effects

### ISSUE THREAD

**Issue by TehJays** [diamond-rip/Eden#171]
very self explantory, could be like mmc's kill effects or like cpractice's kill eeffect gui.

**Comment by GoodestEnglish** [comment]
We decided to not make kill effects in Eden. The main reason is because most of the server core has kill effects option. If you are a developer, please consider to use MatchPlayerDeathEvent to use your kill effects.

**Comment by GoodestEnglish** [comment]
On the other note: We might start to stop to accept new feature request from now on. Eden userbase is getting larger and larger which I understand and happy, but the feature request is also getting more and more and I start to couldn't follow the speed on coding new feature. This also allow me to make some long-decided feature like extra practice event like SumoEvent, BlockSumo, RedRover, etc.
