### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by liexes** [diamond-rip/Eden#178]
How can I put the total rating on the scoreboard with a placeholder?

**Comment by GoodestEnglish** [comment]
What do you mean by total rating?

**Comment by HierarchyMan** [comment]
He prolly could mean all wins or match tiers which aren't implemented yet (or something similar that includes stats)

**Comment by liexes** [comment]
> What do you mean by total rating?
> 
> Edit: If you mean the overall rating combined then there's no placeholder for it atm.

I say of the global elo

**Comment by GoodestEnglish** [comment]
> > What do you mean by total rating?
> > Edit: If you mean the overall rating combined then there's no placeholder for it atm.
> 
> I say of the global elo

I could add this to a placeholder

**Comment by GoodestEnglish** [comment]
Added global elo placeholder in latest update
