### ISSUE TITLE
Nametag Colour During Match

### ISSUE THREAD

**Issue by TehJays** [diamond-rip/Eden#182]
Allow changing players nametag colour in match.
e.g:
nametag-color:
 opponent-namecolor: '&c'
 own-namecolor: '&9'
**this could also support placeholderapi so ppl can use rank cores placeholders like aquacore**

**Comment by GoodestEnglish** [comment]
I could do this

**Comment by TehJays** [comment]
uhhhh also, could the boxing combo counter be like mmc's?
like this: https://www.youtube.com/watch?v=QmJJ1eIhJ-Y

**Comment by GoodestEnglish** [comment]
You should already able to do this. Check https://github.com/diamond-rip/Eden/wiki/Placeholders for placeholders

**Comment by GoodestEnglish** [comment]
Added in latest update
