### ISSUE TITLE
Enderpearl & Death on water bug

### ISSUE THREAD

**Issue by Chromaah** [diamond-rip/Eden#183]
when you pearl into the water when 'Death on water' is set to true, you dont die. This is pretty gamebreaking lol
![image](https://user-images.githubusercontent.com/123222872/226084042-e5d8a340-a661-487e-b83b-917d4f755f2a.png)

**Comment by GoodestEnglish** [comment]
What spigot are you using?

**Comment by Chromaah** [comment]
CarbonSpigot

**Comment by GoodestEnglish** [comment]
I will test it once I am free

**Comment by Chromaah** [comment]
Ok, what I did was pearl up and it landed in the water, and thats how you can reproduce. Not sure if they'res other ways to do the same thing

**Comment by GoodestEnglish** [comment]
> Ok, what I did was pearl up and it landed in the water, and thats how you can reproduce. Not sure if they'res other ways to do the same thing

I got what you mean. my current test environment is ImanitySpigot and I forgot my CarbonSpigot license key. In ImanitySpigot I cannot reproduce. I am currently asking for CarbonSpigot dev what my license key. So this will take some time.

**Comment by GoodestEnglish** [comment]
Tested and looks like it is a carbonspigot issue with "mmc mode" for pearl. Please disable mmc mode and try again if it still happens.

**Comment by Chromaah** [comment]
aah i see, thank you!
