### ISSUE TITLE
issues

### ISSUE THREAD

**Issue by arm4xlll** [diamond-rip/Eden#186]
i found 2 more bugs on my fireball fight after fixing tnt and fireballs. When a player dies he respawns and dies again, also, fall damage was not disabled, although it was disabled in the kit settings (that is, enabled). I also found another bug in boxing when one of the players reaches 10 hits game ends.

**Comment by GoodestEnglish** [comment]
Oppsie, was debugging and forgot to change back the value of the boxing hits. Will fix it soon.

I will also look to the other bugs you mentioned.

**Comment by GoodestEnglish** [comment]
Fixed in https://github.com/diamond-rip/Eden/releases/tag/1.1.3-df07856-BETA. Thanks for the report
