### ISSUE TITLE
stats problem

### ISSUE THREAD

**Issue by TehJays** [diamond-rip/Eden#187]
so basically i created a spleef kit and it did not get added to the stats menu or lb menu.
i already have 2 rows of kits on the stats menu and lb menu.

Is there a kit limiter or smth?

**Comment by GoodestEnglish** [comment]
> so basically i created a spleef kit and it did not get added to the stats menu or lb menu. i already have 2 rows of kits on the stats menu and lb menu.
> 
> Is there a kit limiter or smth?

There's a page button in the stats menu. Make sure you saved the kit and restarted the server.

**Comment by TehJays** [comment]
I have a suggestion which'll make lb and stats menu better.
the first kit should be on the one coloured aqua instead of where it i rn.
the kits of the stats and lb menu should starrt from aqua and end till orange.
![image](https://user-images.githubusercontent.com/111479184/226414974-4da74be1-bbdf-4fe4-9a17-0e8302cdb687.png)

_**(why? becuz it'll be clean and most servers set kit priority from most popular to least, ppl could easily view all the popular kits on one page instead of just 2 rows of kit on one page and more on other**_

**Comment by TehJays** [comment]
Also I've got suggestion for Party system.
- add /party chat 
  > aliases: /p chat, /p c
- allow changing party chat format
  > party-chat: '&d{0}'
_**ofc this party chat format could support papi to use rank cores**_

**Comment by Bermiin** [comment]
> Also I've got suggestion for Party system.
> 
> * add /party chat
>   > aliases: /p chat, /p c
Will be done in #189

**Comment by TehJays** [comment]
> Changed in the latest release
> 
> Edit: It will not display to slot 43. It will only display to slot 10-34. Kinda ugly imo and MMC only displays three rows.

what ab /partyffa and /partysplit?
