### ISSUE TITLE
the match does not start

### ISSUE THREAD

**Issue by joaofelipe34** [diamond-rip/Eden#193]
how to i set inventory for a kit boxing

**Comment by GoodestEnglish** [comment]
In the latest version of eden, you can simply set your kit inventory by using command `/kit`, choose your boxing kit on the menu, and click on slot 16 (the chest on the second row), then click confirm.

Make sure to save your kit afterwards by using command `/kit save boxing` to save your boxing kit!

Here's a guide on how to setup a kit: https://github.com/diamond-rip/Eden/wiki/Kits-Setup

**Comment by joaofelipe34** [comment]
![2023-03-21_19 10 07](https://user-images.githubusercontent.com/100873716/226752979-beb0ead4-d220-455a-90b0-66c3211eaac0.png)
the match does not start
