### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by arm4xlll** [diamond-rip/Eden#194]
again a bug with fireballs, fireball damage again cannot be edited (LightSpigot 8 Lite)

**Comment by GoodestEnglish** [comment]
I've tested on my side and cannot reproduce this bug. I will need someone to verify this issue so I can know what cause the fireball damage cannot be edited.

**Comment by arm4xlll** [comment]
i can help, or u can join on my server

**Comment by arm4xlll** [comment]
ip - starworld.su or 188.40.244.16:3055
