### ISSUE TITLE
the match does not start

### ISSUE THREAD

**Issue by joaofelipe34** [diamond-rip/Eden#197]
![2023-03-21_19 10 07](https://user-images.githubusercontent.com/100873716/226756226-8c67a7b6-7acd-4beb-87ce-69967ab42271.png)

the match does not start

**Comment by TehJays** [comment]
did u assign the kit to an arena? and is that arena enabled?

**Comment by joaofelipe34** [comment]
yes

**Comment by GoodestEnglish** [comment]
Any error in console?
Please also send us your kit.yml and arena.yml

**Comment by joaofelipe34** [comment]
thanks worked i enabled arena and its working
![2023-03-21_20 29 57](https://user-images.githubusercontent.com/100873716/226765960-2bf98596-f525-41bf-b150-3e26c0b937d8.png)
why doesn't the combo appear on the scoreboard

**Comment by GoodestEnglish** [comment]
Could you please try this language.yml?
https://pastebin.com/raw/pEsuQemX
