### ISSUE TITLE
Items bug

### ISSUE THREAD

**Issue by liexes** [diamond-rip/Eden#198]
The hotbar items are bugged, previously you told me that to remove an item I should put -1, well, now those items appear in the hotbar replacing the items that are enabled and it's quite annoying. How can I solve that?

**Comment by GoodestEnglish** [comment]
Looks like I've misunderstand some of the variables. I will revamp some of the item features soon.

**Comment by GoodestEnglish** [comment]
Added an option to toggle in latest update
