### ISSUE TITLE
How Can I Create Kit Boxing Without A Armor?

### ISSUE THREAD

**Issue by ABIGDachshunch** [diamond-rip/Eden#20]
PLease Help!!

**Comment by RealGoodestEnglish** [comment]
Hello, to create a kit without any armor is pretty simple! The save loadout button saves the kit loadout depends on your inventory, which means simply unequip all of your armor and click on the save loadout button. Remember to save your kit using the command '/kit save <kit name>' afterwards

If you have any questions, let me know by commenting in this issues😄

**Comment by ABIGDachshunch** [comment]
> 

the queue is not working

**Comment by RealGoodestEnglish** [comment]
Please briefly describe the issue. Perfectly with a video so I can know what is the issue you are facing 🙂

**Comment by HierarchyMan** [comment]
make sure to have added the kit in the arena config 
make sure to have enabled the arena after server restart
