### ISSUE TITLE
issues

### ISSUE THREAD

**Issue by arm4xlll** [diamond-rip/Eden#203]
- spectators can attack players in a match

- and one more bug. When a player dies and enters spectator mode, he can hit the player at the last moment before respawning (only 5 blocks away). this is what it looks like - https://youtu.be/QMt4NPlrXTo

- and you also need to remove the "-" from the {match-solo-boxing-difference-number} placeholder, because when a player goes into minus hits, he will be displayed allowable (--10)

- /party chat command give error in console - https://pastebin.com/Sbx8bb3e

- also i tried adding %eden_leaderboard_bestWinstreak_winstreak_<kit name>_<position>% placeholder in queue menu and it didn't work, any idea why?

**Comment by GoodestEnglish** [comment]
Refer to third point, I've messed up with the default language.yml. Please use this [language.yml](https://pastebin.com/raw/SfgGtLjz) with the latest version which I will release in the next few hours.

Refer to fifth point, the placeholder is `%eden_leaderboard_bestWinstreak_winstreak_<kit name>_<position>%`, you've missed some of the fields.

The other bug you've mentioned will be fixed soon.

**Comment by arm4xlll** [comment]
about the fifth point, I know about it, in my config it looks like this: *% eden_leaderboard_bestWinstreak_winstreak_{2}_1%*. But it still doesn't work

**Comment by GoodestEnglish** [comment]
> about the fifth point, I know about it, in my config it looks like this: ### %eden_leaderboard_bestWinstreak_winstreak_{2}_1%. But it still doesn't work

Did you type your kit name? What is {2} means?

**Comment by arm4xlll** [comment]
this outputs the name of kit, i also tried entering the name of kit manually and it didn't work

**Comment by arm4xlll** [comment]
> > about the fifth point, I know about it, in my config it looks like this: ### %eden_leaderboard_bestWinstreak_winstreak_{2}_1%. But it still doesn't work
> 
> Did you type your kit name? What is {2} means?

this outputs the name of kit, i also tried entering the name of kit manually and it didn't work

**Comment by GoodestEnglish** [comment]
> > > about the fifth point, I know about it, in my config it looks like this: ### %eden_leaderboard_bestWinstreak_winstreak_{2}_1%. But it still doesn't work
> > 
> > 
> > Did you type your kit name? What is {2} means?
> 
> this outputs the name of kit, i also tried entering the name of kit manually and it didn't work

I did some changes to placeholder, not sure if this is fixed or not. May you try again?

**Comment by GoodestEnglish** [comment]
> > > > > about the fifth point, I know about it, in my config it looks like this: ### %eden_leaderboard_bestWinstreak_winstreak_{2}_1%. But it still doesn't work
> > > > 
> > > > 
> > > > Did you type your kit name? What is {2} means?
> > > 
> > > 
> > > this outputs the name of kit, i also tried entering the name of kit manually and it didn't work
> > 
> > 
> > I did some changes to placeholder, not sure if this is fixed or not. May you try again?
> 
> still not working ![image](https://user-images.githubusercontent.com/109166895/227161697-b4353adb-7f66-472b-a31d-b84ef2058469.png)

Can you send your kit.yml?

**Comment by arm4xlll** [comment]
> > > > > > about the fifth point, I know about it, in my config it looks like this: ### %eden_leaderboard_bestWinstreak_winstreak_{2}_1%. But it still doesn't work
> > > > > 
> > > > > 
> > > > > Did you type your kit name? What is {2} means?
> > > > 
> > > > 
> > > > this outputs the name of kit, i also tried entering the name of kit manually and it didn't work
> > > 
> > > 
> > > I did some changes to placeholder, not sure if this is fixed or not. May you try again?
> > 
> > 
> > still not working ![image](https://user-images.githubusercontent.com/109166895/227161697-b4353adb-7f66-472b-a31d-b84ef2058469.png)
> 
> Can you send your kit.yml?

sure, https://pastebin.com/1E2hDALt

**Comment by arm4xlll** [comment]
> * and one more bug. When a player dies and enters spectator mode, he can hit the player at the last moment before respawning (only 5 blocks away). this is what it looks like - https://youtu.be/QMt4NPlrXTo

what about it?

**Comment by Stainded** [comment]
> > * and one more bug. When a player dies and enters spectator mode, he can hit the player at the last moment before respawning (only 5 blocks away). this is what it looks like - https://youtu.be/QMt4NPlrXTo
> 
> what about it?

Sexy lady.

**Comment by GoodestEnglish** [comment]
> > > > > > > about the fifth point, I know about it, in my config it looks like this: ### %eden_leaderboard_bestWinstreak_winstreak_{2}_1%. But it still doesn't work
> > > > > > 
> > > > > > 
> > > > > > Did you type your kit name? What is {2} means?
> > > > > 
> > > > > 
> > > > > this outputs the name of kit, i also tried entering the name of kit manually and it didn't work
> > > > 
> > > > 
> > > > I did some changes to placeholder, not sure if this is fixed or not. May you try again?
> > > 
> > > 
> > > still not working ![image](https://user-images.githubusercontent.com/109166895/227161697-b4353adb-7f66-472b-a31d-b84ef2058469.png)
> > 
> > 
> > Can you send your kit.yml?
> 
> sure, https://pastebin.com/1E2hDALt

Can you try to use `/papi parse me <the placeholder>` and see if it works or not?

**Comment by GoodestEnglish** [comment]
Also, what spigot are you using?

**Comment by arm4xlll** [comment]
> Also, what spigot are you using? I can't reproduce the second bug.

LightSpigot 8

**Comment by arm4xlll** [comment]
> > > > > > > > about the fifth point, I know about it, in my config it looks like this: ### %eden_leaderboard_bestWinstreak_winstreak_{2}_1%. But it still doesn't work
> > > > > > > 
> > > > > > > 
> > > > > > > Did you type your kit name? What is {2} means?
> > > > > > 
> > > > > > 
> > > > > > this outputs the name of kit, i also tried entering the name of kit manually and it didn't work
> > > > > 
> > > > > 
> > > > > I did some changes to placeholder, not sure if this is fixed or not. May you try again?
> > > > 
> > > > 
> > > > still not working ![image](https://user-images.githubusercontent.com/109166895/227161697-b4353adb-7f66-472b-a31d-b84ef2058469.png)
> > > 
> > > 
> > > Can you send your kit.yml?
> > 
Edit 2: Try the latest version and let me know if the issue still exists or not

**Comment by GoodestEnglish** [comment]
If the command worked, then something is wrong with your GUI plugin. Possibly your GUI plugin doesn't hook into PlaceholderAPI

**Comment by arm4xlll** [comment]
> If the command worked, then something is wrong with your GUI plugin. Possibly your GUI plugin doesn't hook into PlaceholderAPI

I don't use gui plugins

**Comment by GoodestEnglish** [comment]
I will have a look into this issue soon

**Comment by GoodestEnglish** [comment]
I apologize for that. Got what you mean now.
Will fix soon.

**Comment by GoodestEnglish** [comment]
Should be fixed in latest update. Check it out!
