### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by TehJays** [diamond-rip/Eden#205]
♢ add /chooseematchtype partyFFA & /chooseematchtype partysplit
♢ allow editing party chat message.
eg: party-chat-msg: '&b{player}&7: &f{message}'

**Comment by arm4xlll** [comment]
it would also be nice to add the ability to edit the countdown to respawn

**Comment by TehJays** [comment]
isn't that already a feature?

**Comment by arm4xlll** [comment]
my English is bad, but what's the difference?

**Comment by GoodestEnglish** [comment]
> and it would also be nice to add the ability to edit the countdown to respawn

This is already a feature. You can edit respawn countdown in kit gamerules editor gui. Check out this wiki post for more details: https://github.com/diamond-rip/Eden/wiki/Kits-Setup
This wiki is kinda old but it still works the same. I will add the missing field to wiki when I am free.

**Comment by arm4xlll** [comment]
> 


I meant changing the text of coutdown before respawn

**Comment by GoodestEnglish** [comment]
> > 
> 
> I meant changing the text of coutdown before respawn

Will be added

**Comment by GoodestEnglish** [comment]
> Even more useful suggstions: ♢ Allow renaming items in items.yml ♢ Allow cutomizing commands in items.yml e.g.
> 
> > unranked-queue:
> > enabled: true
> > name: "&bUnranked Queue &7(Right-Click)"
> > lore:
> > - ""
> > material: IRON_SWORD
> > command: /eden:queue unranked
> > durability: 0
> > slot: 0

What do you mean by renaming items?
Currently you cannot modify any items command in items.yml. If you wish to, you will have to wait for an addon which I am going to make after my exam.
