### ISSUE TITLE
Blockhits

### ISSUE THREAD

**Issue by Mekvil** [diamond-rip/Eden#207]
Make configurable blockhits limit. like if you set the limit 5 blockhits and player reach it then damage don't register like it's gonna get damage if he doesn't hold blockhit. You need make it bc people actually abusing blockhits and make it 50 per match

**Comment by GoodestEnglish** [comment]
So what you mean is you do not want blockhit exists? If then you would need to have another plugin to control it. Eden won't control the state of player's blocking
