### ISSUE TITLE
Carbon Error

### ISSUE THREAD

**Issue by Mekvil** [diamond-rip/Eden#21]
![image](https://user-images.githubusercontent.com/40424128/209583234-ebf65f20-08d9-4cc8-baf5-3ebbe100aa00.png)

**Comment by Mekvil** [comment]
i check another spigots it's problem of spigot

**Comment by RealGoodestEnglish** [comment]
Fixed this! Please try [this version of Eden](https://github.com/diamond-rip/Eden/releases/tag/1.0.16-BETA-f684452). If you still encounter issues, please let me know 🙂
