### ISSUE TITLE
Action of sending a message in the party not defined.

### ISSUE THREAD

**Issue by Stainded** [diamond-rip/Eden#211]
Obs: The command and states are working, but the end result when typing (/PartyChat) or interacting with "@" or "!" causes the [**party.party-char-format**]

![2023-03-23_02 29 52](https://user-images.githubusercontent.com/128519059/227112217-4a228d91-ae26-49ef-86d4-a107e6f1e72a.png)

**Comment by GoodestEnglish** [comment]
Could you please update your language.yml? Here's the list of what it needs to be updated: https://github.com/diamond-rip/Eden/commit/7bfa255b0317fc0ab186b081506ba5909f5dce58#diff-dfb83791c02884bcdfad0eb39d32a810976cf1320fa9b5144e2ae6373e38b99b
