### ISSUE TITLE
Latest Beta Bugs: Boxing isn't ending, Kill Messages bugged.

### ISSUE THREAD

**Issue by Chromaah** [diamond-rip/Eden#212]
I was testing boxing with the latest beta version (1.1.5) and boxing matches arent ending.
![image](https://user-images.githubusercontent.com/123222872/227131844-9258d110-3b3a-4d72-b523-a1ff7d84f8b5.png)

It also appears that the kill message returns Null in the color part for the player dead. 
![image](https://user-images.githubusercontent.com/123222872/227132384-214c54ec-de36-4ead-b3f8-4d4807519fbf.png)

I read and updated all necessary things from config.yml and language.yml

**Comment by Chromaah** [comment]
![image](https://user-images.githubusercontent.com/123222872/227134544-9201b0b3-bcb8-45ae-8b1b-800e0a768e7a.png)

**Comment by GoodestEnglish** [comment]
> ![image](https://user-images.githubusercontent.com/123222872/227134544-9201b0b3-bcb8-45ae-8b1b-800e0a768e7a.png)

May you send us your config?

**Comment by Chromaah** [comment]
do i still need to send the config?

**Comment by GoodestEnglish** [comment]
> do i still need to send the config?

yup

**Comment by Chromaah** [comment]
https://pastebin.com/qRhkdp7J

**Comment by GoodestEnglish** [comment]
> https://pastebin.com/qRhkdp7J

You haven't update the nametag part in the config. Check this default config.yml and add those missed field https://github.com/diamond-rip/Eden/blob/master/src/main/resources/config.yml

**Comment by Chromaah** [comment]
OHH
my bad, i completely missed it, thank you for the help, and i hope boxing bug is fixed soon :)

**Comment by GoodestEnglish** [comment]
> OHH my bad, i completely missed it, thank you for the help, and i hope boxing bug is fixed soon :)

It should be fixed in the latest version which I released in a few minutes ago. Check it out ;)

**Comment by Chromaah** [comment]
great, i will try it right now

**Comment by Chromaah** [comment]
everything seems to be working as expected, thanks!
