### ISSUE TITLE
boxing double hits

### ISSUE THREAD

**Issue by arm4xlll** [diamond-rip/Eden#213]
critical hits still causes a double hit in boxing, if it is disabled, I have a bug with disabling knockback

**Comment by GoodestEnglish** [comment]
Could you test this version and let me know if it is fixed or not? https://drive.google.com/file/d/1RPhJhe6A0-NhEMt5izkrm9SlUfYlQ0oC/view?usp=share_link

**Comment by GoodestEnglish** [comment]
> > Could you test this version and let me know if it is fixed or not? https://drive.google.com/file/d/1RPhJhe6A0-NhEMt5izkrm9SlUfYlQ0oC/view?usp=share_link
> 
> i tested, it fixed

Thank you. Will publish this version soon to github.
