### ISSUE TITLE
"Cannot Find ID, player will need to have logged onto the server atleast once to view there profile"

### ISSUE THREAD

**Issue by manrrr** [diamond-rip/Eden#214]
This might be a database issue but I reinstalled mongodb and everything but stats and leaderboard won't work either but MongoDB is active and everything else is working.
![image](https://user-images.githubusercontent.com/106720465/227363833-1c87cca0-d8af-4b0c-8fd2-5f51a88297ca.png)

**Comment by GoodestEnglish** [comment]
Because of you reinstalled your mongodb, all of your mongodb data is cleared. So since the player data is not in the mongodb, the system will display an error message like this because system cannot find the player data.

**Comment by manrrr** [comment]
> Because of you reinstalled your mongodb, all of your mongodb data is cleared. So since the player data is not in the mongodb, the system will display an error message like this because system cannot find the player data.

so will player data start saving again when I played ranked or unranked games etc

**Comment by manrrr** [comment]
> > > Because of you reinstalled your mongodb, all of your mongodb data is cleared. So since the player data is not in the mongodb, the system will display an error message like this because system cannot find the player data.
> > 
> > 
> > so will player data start saving again when I played ranked or unranked games etc
> 
> Yes, as long as you have mongodb enabled on Eden config.

![image](https://user-images.githubusercontent.com/106720465/227368881-666a5870-a060-4a5a-a7a0-3a5fdaa54279.png)
![image](https://user-images.githubusercontent.com/106720465/227369124-ab144b12-b58b-48d0-abf5-1c0b09ab9e78.png)
![image](https://user-images.githubusercontent.com/106720465/227369157-f203db36-ee73-455c-9d50-b37be62c173a.png)
![image](https://user-images.githubusercontent.com/106720465/227369201-2f81fffe-40d0-4a39-b1fb-d299464ca154.png)
As you can see I have played a game unranked and ranked but it still says the same error message

**Comment by GoodestEnglish** [comment]
What spigot are you using?

**Comment by manrrr** [comment]
> What spigot are you using?

def not one of the supported spigots but its flamepaper

**Comment by GoodestEnglish** [comment]
> > What spigot are you using?
> 
> def not one of the supported spigots but its flamepaper

Could you send your paper.yml?

**Comment by GoodestEnglish** [comment]
> > What spigot are you using?
> 
> def not one of the supported spigots but its flamepaper

Do you have `save-player-data` false in paper.yml?

**Comment by manrrr** [comment]
> 

there is no "save-player-data" but here is the config 
[paper.txt](https://github.com/diamond-rip/Eden/files/11056542/paper.txt)
![image](https://user-images.githubusercontent.com/106720465/227371052-e4973fc7-5d99-473c-bb9c-f28b5daaea93.png)

**Comment by GoodestEnglish** [comment]
What about `disable-saving` in spigot.yml? Is it false?

**Comment by manrrr** [comment]
> What about `stats.disable-saving` in spigot.yml? Is it false?

it is set to false

**Comment by GoodestEnglish** [comment]
Mhm interesting. Looks like your spigot somehow has player data disabled. By what I mean player data is when you open the world folder, there's a folder called playerdata which stores all player data (This folder is handled by bukkit, not Eden). 

Can you confirm your player uuid is in the playerdata folder?

**Comment by im-a-blobfish** [comment]
we had player data saving disabled in pandaspigot

**Comment by GoodestEnglish** [comment]
> we had player data saving disabled in pandaspigot

This is why. Player data has to be enabled as of right now. Might make an option to disable this check soon.

**Comment by im-a-blobfish** [comment]
ok i fixed now - thanks

**Comment by manrrr** [comment]
> we had player data saving disabled in pandaspigot

pandaspigot moment
