### ISSUE TITLE
When is it coming out ?

### ISSUE THREAD

**Issue by FastNinjax** [diamond-rip/Eden#215]
IS there any ETA for when the official version of Eden comes out ? becuz i keep changing the plugin in my server. it is kind of annoying

**Comment by GoodestEnglish** [comment]
This is why I've stated the plugin should not use in a production server. The last stable release is 1.0.39. But it is no longer supported and missed some of the features. 

I've run a server before, so I understand your concern. This is why I didn't add any big features as of right now. But as you can see, I am getting less and less bug report in the issues tab. And I believe I can have a stable release going to be public soon.

**Comment by GoodestEnglish** [comment]
About ETA, developing a plugin is not easy, so I cannot 100% confirm. But if there's no new bug report after a week. Then the current version should be stable enough.

**Comment by FastNinjax** [comment]
i understand that making a plugin is though and i respect u for making it because ur plugin, even though not stable is the best ik currently. so i hope it comes out soon. quick suggestion i am not really up to date but when i a make a game bridge the armor color in other servers is red and blue can u also make something like that. If it is already done thats great im not up to date the with the plugin so yeah.

**Comment by FastNinjax** [comment]
> > i understand that making a plugin is though and i respect u for making it because ur plugin, even though not stable is the best ik currently. so i hope it comes out soon. quick suggestion i am not really up to date but when i a make a game bridge the armor color in other servers is red and blue can u also make something like that. If it is already done thats great im not up to date the with the plugin so yeah.
> 
> It is already a built-in feature

Oh Great
