### ISSUE TITLE
Arenas not restoring themselves after a duel (Spleef)

### ISSUE THREAD

**Issue by Leoon-X** [diamond-rip/Eden#217]
Pretty much arenas aren't going back to how they where before the match and next match starts with the arena broken.

**Comment by GoodestEnglish** [comment]
> Pretty much arenas aren't going back to how they where before the match and next match starts with the arena broken.

Can't reproduce. May you send a short video showing how this bug occurs?

**Comment by Leoon-X** [comment]
For sure! If possible also send me a message through discord, would love to get in contact with you about the src itself: 

Leoon#8825

**Comment by Leoon-X** [comment]
https://user-images.githubusercontent.com/67242073/227749030-5d5ad2dc-c6e8-4569-aad8-3a64a61c3db1.mp4

This happens not only in parties but also in a 1v1 unranked match (Map does not regen).

----------

There are also errors in console currently which I believe might be from my side but I'll still send them In case you have interest.
https://pastebin.com/BHV9QU9b

**Comment by GoodestEnglish** [comment]
Does the error occurs when the match ends?

**Comment by Leoon-X** [comment]
Paper spigot 1.8.8, The error shown on console was when the server was closed.
The arena problem does not send any errors to console. It just doesn't reset the map.

**Comment by GoodestEnglish** [comment]
Is it only happen in spleef? I've tested on my side and I can't reproduce.

**Comment by Leoon-X** [comment]
It does only happen in spleef. 

Pretty much in the (Kit Spleef) you need to have both spleef and build/distruction options enabled to be able to break snow.
Only spleef option enabled in kit unfortunally does not work. (You can't break snow/sand if you don't have the build/distruction option enabled as well).
This is most likely the problem but in general, Spleef doesn't regen it's maps.

**Comment by GoodestEnglish** [comment]
Kinda weird as every match ends, the arena will be automatically reset, no matter what kit and what you've enabled.

I will keep investigate this issue. But at the same time can you try this version? https://drive.google.com/file/d/1WeYOq9nL2vaBwxpXhuR6-lXVpK5SX1wb/view?usp=share_link

**Comment by Leoon-X** [comment]
https://user-images.githubusercontent.com/67242073/227813064-cefeda35-cfa2-4c38-a180-d8383bfc0c38.mp4



This version now does not allow to break the blocks itself (Cannot verify if arena regens).

**Comment by GoodestEnglish** [comment]
> This version now does not allow to break the blocks itself (Cannot verify if arena regens).

Now this is why. The reason why the arena didn't regenerate is because your arena config is wrong. Possibly your min and max position is wrong. Please double check and see if they are set correctly.

**Comment by Leoon-X** [comment]
Min & Max are set each in one corner of the map (square)
Min is set in the lower corner point of the circle and max set in the highest point of the circle (once again following both points to make sure the full circle is selected). If that is wrong please let me know with detail so that I can fix and re-test for you!

**Comment by GoodestEnglish** [comment]
Can you send your arena.yml? 

The code I've changed is the cuboid of the arena. You cannot break the block is either:
- The block location you are trying to break is not in the arena
- The block Y-position is higher than the build max of the arena
- The block Y-position is lower than the y limit of the arena

Since you said the arena didn't reset, I am pretty sure it is the because of the first point, which causes the arena didn't save in cache.

**Comment by Leoon-X** [comment]
I just re-attempted with the last version issued by you (1.1.8) and re-doing the map itself
The mistake was from my side. I apologize for it.
I am glad that this was solved and thank you for such a fast response. 
I would like to inform 1 more small thing which I noticed that does not seem like a big problem at all but.
The event of opening the inventory for a player at the time of right-clicking the sword might be happening 2 times.
You see. When I right-click the sword and fastly close the menu open, It re-opens it for me. Just letting you know, Apart from that I will keep in contact if I find anything else. Once again I apologize and thank you.

**Comment by GoodestEnglish** [comment]
No worries! Glad to see problem is solved.

Could you tell me which menu is it?

**Comment by Leoon-X** [comment]
Unranked (Iron-Sword)

Also, Just got this error in console:

![image](https://user-images.githubusercontent.com/67242073/227817027-89ebd0e1-8d46-4a29-9ae6-5c1ea7bcd3bf.png)

**Comment by Leoon-X** [comment]
Here is some other bugs found for you! 

- At the time of doing (/settings) If done quickly/correctly you can eat/drinkpots/blockhit while running 
  Also if the command is done as spectator all spectator items are removed.
  
- It frequently happens that at the time of death (either in spleef or other game modules). Inventory is kept
 (as in, You see all the items in your inv, excepting the armor). 
 Even though you see all items in the inv: The paper item of (play again) is shown perfectly in it's place

**Comment by Leoon-X** [comment]
![image](https://user-images.githubusercontent.com/67242073/227819420-9ba9ad12-fd0f-4318-85ff-f0933ac17d4c.png)

- In a match of parties (when owner of party disconnects/disbands the party by disconnecting)
That error shows up and players are bugged in different ways (one of the players did not go to spawn, the other party could hit between allys).

![image](https://user-images.githubusercontent.com/67242073/227819647-6e0227a6-3502-484e-a222-992ed89fd99a.png)

**Comment by GoodestEnglish** [comment]
> Unranked (Iron-Sword)
> 
> Also, Just got this error in console:
> 
> ![image](https://user-images.githubusercontent.com/67242073/227817027-89ebd0e1-8d46-4a29-9ae6-5c1ea7bcd3bf.png)

The iron sword thing is due to a ping issue related to refreshing the menu. Menu refreshing will be removed in the next update.

The bug you sent is because paperspigot dropped 1.8 support and the url is no longer work. This error won't impact the server.



> Here is some other bugs found for you!
> 
> * At the time of doing (/settings) If done quickly/correctly you can eat/drinkpots/blockhit while running
>   Also if the command is done as spectator all spectator items are removed.
> * It frequently happens that at the time of death (either in spleef or other game modules). Inventory is kept
>   (as in, You see all the items in your inv, excepting the armor).
>   Even though you see all items in the inv: The paper item of (play again) is shown perfectly in it's place

The blockhit thing is a known client side glitch from 1.8, unfortunately there's no way to fix. 
Can't reproduce the error related to the spectator thing and the inventory thing. As always, send a video about this is a great idea to investigate.



> ![image](https://user-images.githubusercontent.com/67242073/227819420-9ba9ad12-fd0f-4318-85ff-f0933ac17d4c.png)
> 
> * In a match of parties (when owner of party disconnects/disbands the party by disconnecting)
>   That error shows up and players are bugged in different ways (one of the players did not go to spawn, the other party could hit between allys).
> 
> ![image](https://user-images.githubusercontent.com/67242073/227819647-6e0227a6-3502-484e-a222-992ed89fd99a.png)

Can you send your config?

**Comment by Leoon-X** [comment]
A good idea for the 1.8 eating/blockhitting while running would be to block the command /settings while in a match. 
That way it goes from a server-side problem to a client-side problem, I've seen this type of thing before where people block hit while running but in this case it's caused by the player.

Config:
https://hastebin.skyra.pw/vigidisofu.yaml
