### ISSUE TITLE
Database error

### ISSUE THREAD

**Issue by TehJays** [diamond-rip/Eden#218]
https://pastebin.com/aixvhUKd

**Comment by arm4xlll** [comment]
can u send ur config?

**Comment by GoodestEnglish** [comment]
If you are using Clevercloud, sometimes this error will occurs because of their system. Would recommend to switch your database provider.

**Comment by TehJays** [comment]
> If you are using Clevercloud, sometimes this error will occurs because of their system. Would recommend to switch your database provider.

any recommendations?

**Comment by GoodestEnglish** [comment]
Not really. Host in local is always your best option
