### ISSUE TITLE
Help please

### ISSUE THREAD

**Issue by liexes** [diamond-rip/Eden#219]
How do you add the "Bridge" arena start box which appears when you start the game or when a point is scored and disappears when the countdown ends?

**Comment by GoodestEnglish** [comment]
> How do you add the "Bridge" arena start box which appears when you start the game or when a point is scored and disappears when the countdown ends?

There's no start box. Bridge kit in Eden works like MMC, not Hypixel

**Comment by liexes** [comment]
You can add this option please? No for the bridge only, please, need this for my own arenas

**Comment by GoodestEnglish** [comment]
As of right now, no. I might consider this after my exam.
