### ISSUE TITLE
server killed itself

### ISSUE THREAD

**Issue by im-a-blobfish** [diamond-rip/Eden#221]
not 100% sure if its eden's fault but it seems to be

no crash report, but paper watchdog report
https://pastebin.com/YsZ1RJ78

pandaspigot
3 people online
java 11

**Comment by GoodestEnglish** [comment]
Looks like it is an issue in my side, will fix it soon

On the other hand, we would recommend to use java 8 as Eden uses java 8. Version which is higher than 8 is not recommended due to the java version spigot used.

**Comment by GoodestEnglish** [comment]
Also try this version and see if the bug still exists: https://drive.google.com/file/d/1WeYOq9nL2vaBwxpXhuR6-lXVpK5SX1wb/view?usp=share_link
