### ISSUE TITLE
Help please (Kb)

### ISSUE THREAD

**Issue by liexes** [diamond-rip/Eden#222]
How to add hit delay in Windspigot?

I was making a profile for the combo mode using your plugin, but the hits are recorded every second, which is not good for making a combo mode, I really don't know how to change that delay, could you help me?

This is the combo profile, if you help me configure it I would appreciate it:

combo:
      stop-sprint: false
      friction-horizontal: 2.0
      friction-vertical: 2.0
      horizontal: 0.4
      vertical: 0.4
      vertical-max: 0.4
      vertical-min: -0.8
      extra-horizontal: 0.6
      extra-vertical: 0.04
      wtap-extra-horizontal: 0.6
      wtap-extra-vertical: 0.2
      add-horizontal: 0.0
      add-vertical: 0.0
      projectiles:
        rod:
          horizontal: 0.5
          vertical: 0.5
        arrow:
          horizontal: 0.5
          vertical: 0.5
        pearl:
          horizontal: 0.5
          vertical: 0.5
        snowball:
          horizontal: 0.5
          vertical: 0.5
        egg:
          horizontal: 0.5
          vertical: 0.5

**Comment by liexes** [comment]
@GoodestEnglish Please, help me

**Comment by GoodestEnglish** [comment]
Looks like windspigot doesn't have an option to set hit delay. You can use Eden's built-in hit delay modifier which can be edited in kit management menu.

**Comment by liexes** [comment]
Ok, what is the name of the option?

**Comment by GoodestEnglish** [comment]
kit damage ticks

**Comment by liexes** [comment]
Ok, thx much

**Comment by liexes** [comment]
One last question and sorry for bothering you, what value do I put so that hits are detected every 0 ticks? Do I put 0 without more?

**Comment by GoodestEnglish** [comment]
> One last question and sorry for bothering you, what value do I put so that hits are detected every 0 ticks? Do I put 0 without more?

Use 1 if you want every hits registered. But most of the servers uses 2 or 3.

**Comment by liexes** [comment]
This option run because have windspigot sorry?

**Comment by GoodestEnglish** [comment]
Should be if windspigot doesn't override the default player hit delay.

**Comment by liexes** [comment]
Ok, thx
