### ISSUE TITLE
1.1.9 Glitch that 1.1.8 Didn't have

### ISSUE THREAD

**Issue by Leoon-X** [diamond-rip/Eden#226]
- This last update you made was a good fix for certain things, Sadly because of my own issue report I made you change something in the spleef module that unfortunally broke it. Snow blocks do not break in arena match (this time with arena config set correctly).

Sleef mode and Build/Destroy enabled in kit.

Attempted enabling and disabling both and alternating to check if it would work but it doesn't

I highly recommend going back to the 1.1.8 version in terms of the spleef. It was working just fine!

I Also suggest disabling the command /settings during a match.

**Comment by Leoon-X** [comment]
Another suggestion would be to add in the Kit Editor (Build/Destroy) blocks like TNT and Lighters
(Makes it so that there can be more variety when it comes to the practice game modules).

- Tried to use a lighter in builduhc kit with no results, also attempted having some fun with some TNT which is also not allowed even with Build/Destruction active. 

Do take in count that if this where to be added, please make it so that the map regens by a tnt explosion as well.

**Comment by GoodestEnglish** [comment]
The changes in 1.1.9 shouldn't break anything. I am currently in school so I couldn't test it. But in the meantime can you send your arena.yml and kit.yml?

**Comment by GoodestEnglish** [comment]
I still couldn't reproduce the bug which you mentioned in last issues report related to /settings. Could you provide a short video?

**Comment by Leoon-X** [comment]
- I had the build hight set in -1 (this made the players unable to break which I'm guessing didn't happen in the 1.1.8 version).
Once again it was on my side!!!! My bad. Thanks for the fast attention even though you are in school (that's dedication).


When it comes to the /settings during a match it happens when you bind the command to a hotkey with game clients like lunar or badlion & eat before pressing the binded key, right at the start of you eating you press the binded key, you close the menu opened and tada, you can run while eating or block hitting.

If you see that you still can't reproduce let me know and I'll send you a short video on how it happens.

**Comment by GoodestEnglish** [comment]
Tested and see this issue now. But settings is still plays a critical role since player might want to customize their settings in game. I've also tested on lunar and they have the same issue. 

I might add an config option which disallow some of the commands in game soon.

**Comment by Leoon-X** [comment]
![image](https://user-images.githubusercontent.com/67242073/228603120-005e9ba1-8a5e-4592-b0bd-89a5d38a637b.png)

-This doesn't usually happen, First time i've seen this error, It happened when the 3rd round ended and I won the match, After winning I was spawned again at the map and a countdown started as if I was going for a 4th round, Right when match started I was  teleported to spawn correctly.

-Btw, it's happened more than once that after a player dies the items are still in inventory. You get the paper to (play again) in slot 4 and then all other items from the match show up in the players inventory until the player is teleported back to spawn. When the player is teleported to spawn the paper disappears as well (it should stay for a couple of seconds more after being teleported to spawn just so the player has time to click "play again") .

**Comment by GoodestEnglish** [comment]
> ![image](https://user-images.githubusercontent.com/67242073/228603120-005e9ba1-8a5e-4592-b0bd-89a5d38a637b.png)
> 
> -This doesn't usually happen, First time i've seen this error, It happened when the 3rd round ended and I won the match, After winning I was spawned again at the map and a countdown started as if I was going for a 4th round, Right when match started I was teleported to spawn correctly.
> 
> -Btw, it's happened more than once that after a player dies the items are still in inventory. You get the paper to (play again) in slot 4 and then all other items from the match show up in the players inventory until the player is teleported back to spawn. When the player is teleported to spawn the paper disappears as well (it should stay for a couple of seconds more after being teleported to spawn just so the player has time to click "play again") .

What gamemode are you playing when the error occurs?

Currently the play again item is being used when the match is ended, not when they are in lobby and requeue the same ladder. Will be added in the future tho.

**Comment by Leoon-X** [comment]
I was in survival mode. 

- Sounds good! mostly wanted to notify about the items of the kit staying in your inventory after death/loosing.

**Comment by Leoon-X** [comment]
**Apart from the console Errors I sent:**
**Here are some Important Bugs For You!**


- There is a lot of trouble when a player leaves the party (Party leader or Normal member) while in match,  Just now I was left alive and I was the only player alive as well (This is for FFA).

- In a rounded match if you throw a pearl right before death, when the next round starts the pearl is still active and you teleport to where the pearl landed.

- It doesn't always happen but I've seen it multiple times where I die and I still have the kits items in my inv (together with the paper ofc). But it's as The items are not eliminated from my inv when the match ends (this is solved once you get teleported to spawn).

- A lot of these things don't send errors to console but I've seen it where you score 2 points in the first death in a rounded match instead of 1, I've seen that people stay in arenas even though they are the only ones alive (this happens A LOT in parties), I've seen people not get teleported to spawn and get teleported under the spawn (This doesn't happen often but it does if there are a lot of erros in console).

**Comment by GoodestEnglish** [comment]
Wow, there's a lot. Thanks for the report!
I will try to patch them asap.

**Comment by Leoon-X** [comment]
On my way home! (about an hour) As soon as I get there I'll test it out and let you know!

**Comment by Leoon-X** [comment]
- Pearl glitch still happens (The player gets teleported to where the pearl was last thrown at the start of the next round).

-  Also got this error in console by playing the tnt minigame.

![image](https://user-images.githubusercontent.com/67242073/228982611-1162fd1e-f46b-4642-807a-c8509ef9c0ec.png)


- Will test further with more players in a couple of minutes.

**Comment by GoodestEnglish** [comment]
Pearl glitch should be fixed in latest update. Check it out!

I am not too sure what happened to the error you sent to me. May you provide your kit.yml and more details about when is the error occurs? And also describe what does "tnt minigame" means?

**Comment by Leoon-X** [comment]
We Don't really do anything, we just play normally
Everything is working great! Only problem is We keep getting this error in console.
TNT game is not the only minigame we get it in, We just got it in a normal spleef match.
I've also seen it in NoDebuff, appart from that, once again the plugin as of right now is working GREAT!

![image](https://user-images.githubusercontent.com/67242073/229005945-5cc63d5d-f026-4e91-8cd6-61df05552788.png)

**Comment by GoodestEnglish** [comment]
Since I cant reproduce, I would like to have more detailed information, including:
- What mode will the error occurs? (For example, FFA, Solo, Team Match?)
- What happened when the error occurs? (From what I've seen in the error, the error occurs when someone is moving. But what else is happening? For example, did anyone left the server? Did anyone die from the match?)

**Comment by Leoon-X** [comment]
It happens in both FFA, Party, Solo, Team match, (all of em).

Apparently it happens when someone dies in the water (Not sure if it only happens then but I think its in that situation).

**Comment by GoodestEnglish** [comment]
Hey, do you still facing this issue?

**Comment by Leoon-X** [comment]
Hi there, Nope, Not that I know of, If I find anything else, I'll let you know! :)
