### ISSUE TITLE
My issue is how the heck is this plugin so good

### ISSUE THREAD

**Issue by HierarchyMan** [diamond-rip/Eden#23]
And also add autosave in config pls
And mlgrush setting for kits
Thanks

**Comment by underbone** [comment]
MLGRush you can settings

**Comment by RealGoodestEnglish** [comment]
We are planning to add MLGRush support very soon! Stay tuned 😉

**Comment by RealGoodestEnglish** [comment]
Please try this update: https://github.com/diamond-rip/Eden/releases/tag/1.0.17-BETA-d208404
This update allows you to create MLGRush kit by setting "Break Goal" to enabled.

This should be how MLGRush kit settings looks like:
![image](https://user-images.githubusercontent.com/45838505/210022054-0c5b1483-e9d3-44cd-8f39-75bfa656120a.png)

**Comment by RealGoodestEnglish** [comment]
Update: arena and kit autosave is also coming soon

**Comment by HierarchyMan** [comment]
Hey, you are a really skilled developer and I respect your work
Can you add me on discord so I can give you a detailed analysis on small bugs and some qol improvements that should be done?
Discord: cystol#8422
For eg: in bridges, white clay can't be broken
              Need per arena portal protection for bridges and battlerush seperately
              Can't make kits like pearl fight and stick fight cuz killing automatically makes the game end instead of counting as a point

If you dont wanna add me on discord it's fine, I will keep making new issues on this git to help you improve the plugin :D

**Comment by RealGoodestEnglish** [comment]
Hello, sorry but I would prefer record all suggestions and issues in github. Also discord support is planning to come soon. So don't worry!

About your suggestions 1 and 3, those will be fixed soon.
About suggestions 2, the latest update changed how arena portal protection works by calculating both team's spawn location (Here's the line of how the calculation works: [here](https://github.com/diamond-rip/Eden/blob/master/src/main/java/rip/diamond/practice/movement/impl/MatchMovementHandler.java#L64)). This update just released a few hours ago so let me know if you encounter any issues in this update 🙂
