### ISSUE TITLE
Citizens Bug

### ISSUE THREAD

**Issue by Chromaah** [diamond-rip/Eden#230]
Now I forgot to report this issue, but after updating to a newer version of eden, my citizens NPC's stopped working. For example, i can create them and they'll be visible, but as soon as the player leaves the server and joins again, its no longer visible. I know this isnt by citizens because i even updated to a newer version (latest dev build) and the issue persisted.

**Heres an image of the npc created:**
![image](https://user-images.githubusercontent.com/123222872/228743023-c24d2b60-d02b-4bc1-a587-968cc8f72719.png)

**Image after logging in:**
![image](https://user-images.githubusercontent.com/123222872/228742830-9f19f23a-2884-455e-aa8e-1dcf71ac5d48.png)

There are 0 errors in console/logs, and again, this only happened after updating eden's plugin version, nothing else changed. While troubleshooting, i attempted to use the latest citizens dev build, but i still had the same issue.

**Comment by GoodestEnglish** [comment]
Should be an issue in my side since Eden modified the visibility of NPC. Will fix it soon.

**Comment by Chromaah** [comment]
yay! this fixed it, NPC's are now visible

**Comment by Chromaah** [comment]
also quick question, are you gonna add '/queue <kit>'? or is this already a thing and im blind? I want this for a custom menu lol

**Comment by Chromaah** [comment]
sorry i meant 'queue _kit_name_'
