### ISSUE TITLE
issues with mongodb when using eden

### ISSUE THREAD

**Issue by im-a-blobfish** [diamond-rip/Eden#236]
im not sure that this is eden's fault, but you'll have a much better idea of what causes this then i will

i get "Interrupted operation as its client disconnected" in mongo logs, and a different issue on the server

do you know what could cause this? heres some server and mongo logs

mongo log snippet:
https://pastebin.com/raw/Ufckitu9

server log error:
https://pastebin.com/raw/L59RNGPp

**Comment by im-a-blobfish** [comment]
no, just sometimes after restarting the server this happens

spigot: pandaspigot
java version: 11

also irrelivent, but is it possible to add knockback support for pandaspigot, or is there no api allowing for this

**Comment by GoodestEnglish** [comment]
Eden only supports Java 8. That's why.
As I see from PandaSpigot github readme, they have knockback configuration, but they do not provide an API to edit the knockback, so I do not think it is possible.

**Comment by im-a-blobfish** [comment]
hey - switching to java 8 doesnt fix the issue, its still there

also the server generally works fine until doing /stop and then theres a chance the database breaks, but then it eventually starts working again. its strange

**Comment by im-a-blobfish** [comment]
wait it could be a compatability issue with another plugin il report back here when ive tested that

**Comment by im-a-blobfish** [comment]
i think it was a compatability issue with a different plugin, though due to this issue only occuring sometimes il still wait before closing this issue as its very possible that it wasnt the fix
