### ISSUE TITLE
The knockback profiles are weird with Carbon Spigot sometimes.

### ISSUE THREAD

**Issue by Chromaah** [diamond-rip/Eden#238]
Sometimes when entering a boxing match with knockback from carbon spigot profiles, the KB is like off and unbalanced and not how it should be. but after re-doing the game its fine?? I think this is Eden because its depending on joining and leaving games. Also I have two gamemodes which are Boxing and Gapple, and the KB is good on Gapple but not Boxing even though they are using the same profile in kits.yml (
![image](https://user-images.githubusercontent.com/123222872/230979649-aee717a0-8196-4dc2-ba9b-585a90668ec0.png)
)

Is this an Eden issue? Because this was not happening when i didnt have Different Knockback profiles.

**Comment by HierarchyMan** [comment]
I had this issue with rave (very old free version of carbon) when I wasn't using eden
So this could be carbonspigot's fault
The kb on the newer carbon versions does seem to be off... (I tested the latest release 3.5)
The same profile that worked wonders on previous versions of carbon now make every player fly out in just 4 hits

**Comment by HierarchyMan** [comment]
Players barely taking any kb was a problem in rave spigot I think you somehow triggered it in carbon

**Comment by GoodestEnglish** [comment]
I will try it myself when I have time.

**Comment by Chromaah** [comment]
yes as soon as we try another game its fine, thats the thing, seems to only happen in boxing

> Gapple, and the KB is good on Gapple but not Boxing even though they are using the same profile in kits.yml

(mentioned here ^)

I tried other gamemodes aswell and they were fine, but sometimes it decides to not be fine (even in bedfight for example, it happened once where the kb was weird)

**Comment by GoodestEnglish** [comment]
> yes as soon as we try another game its fine, thats the thing, seems to only happen in boxing
> 
> > Gapple, and the KB is good on Gapple but not Boxing even though they are using the same profile in kits.yml
> 
> (mentioned here ^)
> 
> I tried other gamemodes aswell and they were fine, but sometimes it decides to not be fine (even in bedfight for example, it happened once where the kb was weird)

I am guessing it is because I did some changes to boxing. I will fix that after I recovered from covid

**Comment by Chromaah** [comment]
ah alright! good luck with covid

**Comment by GoodestEnglish** [comment]
I will look into it soon

**Comment by GoodestEnglish** [comment]
> I dont want to open another issue, but i found a bug, that when a player spectates, they cant fly. But if the player is opped or has * permission, the player can fly in spectator

Can't reproduce this. 
![2023-04-25_16 06 19](https://user-images.githubusercontent.com/45838505/234390781-1ff933ab-9033-4668-af9f-cf08e4c551e8.png)
What spigot are you using?

**Comment by GoodestEnglish** [comment]
Added an experimental check in latest version of release: https://github.com/diamond-rip/Eden/releases/tag/1.1.11-BETA-388825c. Please test it and let me know the result

**Comment by Chromaah** [comment]
> > I dont want to open another issue, but i found a bug, that when a player spectates, they cant fly. But if the player is opped or has * permission, the player can fly in spectator
> 
> Can't reproduce this. ![2023-04-25_16 06 19](https://user-images.githubusercontent.com/45838505/234390781-1ff933ab-9033-4668-af9f-cf08e4c551e8.png) What spigot are you using?

Im using carbonspigot

**Comment by Chromaah** [comment]
> Added an experimental check in latest version of release: https://github.com/diamond-rip/Eden/releases/tag/1.1.11-BETA-388825c. Please test it and let me know the result
> 
> Edit: Please toggle off no damage in kit gamerules for boxing as of right now. It will be fixed in next update.

I will let you know when i try it

**Comment by Chromaah** [comment]
@GoodestEnglish this is still an issue

**Comment by GoodestEnglish** [comment]
> @GoodestEnglish this is still an issue

Yea i know. But I have put this issue in a low priority as it can be solved by simply putting everything in a single world.
