### ISSUE TITLE
Qol feature request

### ISSUE THREAD

**Issue by HierarchyMan** [diamond-rip/Eden#240]
- Option to disable/enable all in kit gamerules and arena gui
- option to import settings from other kits
- a wand to select bridge in bridge gamemode to prevent beaking of other concrete throughout the map

**Comment by HierarchyMan** [comment]
I need a status update on what's possible and what's not planned

**Comment by GoodestEnglish** [comment]
1 and 2 will be soon, but 3 might not be.

**Comment by HierarchyMan** [comment]
Cool 👍

**Comment by GoodestEnglish** [comment]
After consideration, it is better to not add option to disable/enable all in kit gamerules. Each settings are critical and it is better to manually set by the owners.

But second is still coming soon.

**Comment by GoodestEnglish** [comment]
Added in latest release
