### ISSUE TITLE
maps in the nether world not working

### ISSUE THREAD

**Issue by Antoniova1** [diamond-rip/Eden#245]
I had a problem when I want to make maps in the nether (for bedboom kit), if I can create the arenas but when I turn the server off and on the plugin is disabled and when I delete the map created in the nether from arena.yml the plugin comes back back to normal, is it a bug?, in the pasterbin link is the error that appears in the console

https://pastebin.com/fahycxpp

**Comment by HierarchyMan** [comment]
Creating arenas in the nether might not be supported.
Try using worldguard to //setbiome an area in overworld to get the same effect

**Comment by Antoniova1** [comment]
> Es posible que no se admita la creación de arenas en el inferior. Intente usar worldguard para //setbiome un área en overworld para obtener el mismo efecto

thanks now it works
