### ISSUE TITLE
Player dies instantly on match start

### ISSUE THREAD

**Issue by taildevelopment** [diamond-rip/Eden#246]
![image](https://user-images.githubusercontent.com/98679204/233865870-c000d84e-41a4-4d17-acf9-07b8ce706a37.png)
Hello! I had a question about Eden. I noticed whenever the match starts one player dies instantly for no apparent reason. I checked the y limit of the arena and it looks OK. I was wondering what would be causing this and how to fix it. Thanks!

**Comment by GoodestEnglish** [comment]
send your arena.yml

**Comment by diocan** [comment]
the problem is your Y kill everybody when reaced the y
set y to 0

**Comment by taildevelopment** [comment]
> send your arena.yml
https://hastebin.com/share/esegavuzig.yaml

I was able to fix it by changing the comparator sign in the code so I'm not exactly sure what happened as it seemed to be fine for others.

**Comment by GoodestEnglish** [comment]
Your y-limit is too high. Check https://github.com/diamond-rip/Eden/wiki/Arenas-Setup for more information.

**Comment by endygame** [comment]
Oh I thought y limit was the maximum height, sorry about that.
