### ISSUE TITLE
Boxing hit placeholder doesnt work

### ISSUE THREAD

**Issue by diocan** [diamond-rip/Eden#249]
Boxing hit placeholder doesnt work

    boxing:
      - ""
      - "&c✖ &fᴀᴠᴠᴇʀꜱᴀʀɪᴏ: &c{match-solo-opponent}"
      - ""
      - "&b&lʜɪᴛ: {match-solo-boxing-difference-color}({match-solo-boxing-difference-symbol}{match-solo-boxing-difference})"
      - "&a✔ &fᴛᴜ: &a{match-solo-boxing-self-hit}"
      - "&c☇ &fᴀᴠᴠᴇʀꜱᴀʀɪᴏ: &c{match-solo-boxing-opponent-hit}"
      - ""
      - "&a☁ &fᴘɪɴɢ: &a{match-solo-self-ping}ms"
      - "&2☄ &fᴘɪɴɢ ᴀᴠᴠᴇʀꜱᴀʀɪᴏ: &2{match-solo-opponent-ping}ms"
      - ""
      - "&7ᴄᴇʟᴇꜱᴛʏᴍᴄ.ɪᴛ"

**Comment by diocan** [comment]
in the modes SG cant place Flint and steel

**Comment by GoodestEnglish** [comment]
Using your config and looks fine for me.
![image](https://user-images.githubusercontent.com/45838505/235264509-a1934bdf-2b9d-4d40-9998-e1e3c2489d80.png)
What does yours look like?

**Comment by GoodestEnglish** [comment]
> in the modes SG cant place Flint and steel

![image](https://user-images.githubusercontent.com/45838505/235265021-e4ac65e2-313b-4128-bcc0-e650c6d2fd68.png)
Flint and steel also works fine for me.

**Comment by diocan** [comment]
https://imgur.com/deL0Tix

https://youtu.be/Xck7roB0xMo
https://youtu.be/AZgSSDkeCTg

**Comment by diocan** [comment]
https://imgur.com/EP0HLO7 ??

**Comment by GoodestEnglish** [comment]
Do you have no damage enabled for boxing?
If so, please disable it temporary. This is a known issue for the current version and will be fixed in next version.

**Comment by GoodestEnglish** [comment]
> https://imgur.com/EP0HLO7 ??

I will look into this soon

**Comment by GoodestEnglish** [comment]
> https://imgur.com/deL0Tix
> 
> https://youtu.be/Xck7roB0xMo https://youtu.be/AZgSSDkeCTg

About the flint and steel bug, could you send your sg kit settings so I can look into it?

**Comment by diocan** [comment]
SG:
    enabled: true
    ranked: false
    display-name: '&bSG'
    priority: 0
    damage-ticks: 19
    display-icon: |
      rO0ABXNyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAADbWFwdAAPTGph
      dmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFibGVNYXAk
      U2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAlsABGtleXN0ABNbTGphdmEvbGFuZy9PYmplY3Q7WwAG
      dmFsdWVzcQB+AAR4cHVyABNbTGphdmEubGFuZy5PYmplY3Q7kM5YnxBzKWwCAAB4cAAAAAJ0AAI9
      PXQABHR5cGV1cQB+AAYAAAACdAAeb3JnLmJ1a2tpdC5pbnZlbnRvcnkuSXRlbVN0YWNrdAANR09M
      REVOX0NBUlJPVA==
    description: '[]'
    potion-effects: ''
    armor-loadout: |
      rO0ABXcEAAAABHNyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAADbWFw
      dAAPTGphdmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFi
      bGVNYXAkU2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAlsABGtleXN0ABNbTGphdmEvbGFuZy9PYmpl
      Y3Q7WwAGdmFsdWVzcQB+AAR4cHVyABNbTGphdmEubGFuZy5PYmplY3Q7kM5YnxBzKWwCAAB4cAAA
      AAJ0AAI9PXQABHR5cGV1cQB+AAYAAAACdAAeb3JnLmJ1a2tpdC5pbnZlbnRvcnkuSXRlbVN0YWNr
      dAANTEVBVEhFUl9CT09UU3NxAH4AAHNxAH4AA3VxAH4ABgAAAAJxAH4ACHEAfgAJdXEAfgAGAAAA
      AnEAfgALdAASQ0hBSU5NQUlMX0xFR0dJTkdTc3EAfgAAc3EAfgADdXEAfgAGAAAAAnEAfgAIcQB+
      AAl1cQB+AAYAAAACcQB+AAt0AA9HT0xEX0NIRVNUUExBVEVzcQB+AABzcQB+AAN1cQB+AAYAAAAC
      cQB+AAhxAH4ACXVxAH4ABgAAAAJxAH4AC3QAC0lST05fSEVMTUVU
    contents-loadout: |
      rO0ABXcEAAAAJHNyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAADbWFw
      dAAPTGphdmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFi
      bGVNYXAkU2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAlsABGtleXN0ABNbTGphdmEvbGFuZy9PYmpl
      Y3Q7WwAGdmFsdWVzcQB+AAR4cHVyABNbTGphdmEubGFuZy5PYmplY3Q7kM5YnxBzKWwCAAB4cAAA
      AAJ0AAI9PXQABHR5cGV1cQB+AAYAAAACdAAeb3JnLmJ1a2tpdC5pbnZlbnRvcnkuSXRlbVN0YWNr
      dAALU1RPTkVfU1dPUkRzcQB+AABzcQB+AAN1cQB+AAYAAAACcQB+AAhxAH4ACXVxAH4ABgAAAAJx
      AH4AC3QAA0JPV3NxAH4AAHNxAH4AA3VxAH4ABgAAAAJxAH4ACHEAfgAJdXEAfgAGAAAAAnEAfgAL
      dAALRklTSElOR19ST0RzcQB+AABzcQB+AAN1cQB+AAYAAAACcQB+AAhxAH4ACXVxAH4ABgAAAAJx
      AH4AC3QADEdPTERFTl9BUFBMRXNxAH4AAHNxAH4AA3VxAH4ABgAAAANxAH4ACHEAfgAJdAAGZGFt
      YWdldXEAfgAGAAAAA3EAfgALdAAPRkxJTlRfQU5EX1NURUVMc3IAD2phdmEubGFuZy5TaG9ydGhN
      NxM0YNpSAgABUwAFdmFsdWV4cgAQamF2YS5sYW5nLk51bWJlcoaslR0LlOCLAgAAeHAAPHNxAH4A
      AHNxAH4AA3VxAH4ABgAAAANxAH4ACHEAfgAJdAAGYW1vdW50dXEAfgAGAAAAA3EAfgALdAANR09M
      REVOX0NBUlJPVHNyABFqYXZhLmxhbmcuSW50ZWdlchLioKT3gYc4AgABSQAFdmFsdWV4cQB+ACMA
      AAADc3EAfgAAc3EAfgADdXEAfgAGAAAAA3EAfgAIcQB+AAlxAH4AKHVxAH4ABgAAAANxAH4AC3QA
      BUFQUExFc3EAfgArAAAAAnNxAH4AAHNxAH4AA3VxAH4ABgAAAANxAH4ACHEAfgAJcQB+ACh1cQB+
      AAYAAAADcQB+AAt0AAZDT09LSUVzcQB+ACsAAAAEc3EAfgAAc3EAfgADdXEAfgAGAAAAA3EAfgAI
      cQB+AAlxAH4AKHVxAH4ABgAAAANxAH4AC3QABUJSRUFEcQB+ACxwcHBwcHBwcHNxAH4AAHNxAH4A
      A3VxAH4ABgAAAANxAH4ACHEAfgAJcQB+ACh1cQB+AAYAAAADcQB+AAt0AAVBUlJPV3NxAH4AKwAA
      AAhwcHBwcHBwcHBwcHBwcHBwcHA=
    game-rules: '{"receiveKitLoadoutBook":true,"deathOnWater":false,"boxing":false,"bed":false,"breakGoal":false,"portalGoal":false,"projectileOnly":false,"hypixelUHC":false,"spleef":false,"healthRegeneration":true,"showHealth":true,"foodLevelChange":true,"point":false,"rankedPoint":false,"resetArenaWhenGetPoint":false,"onlyLoserResetPositionWhenGetPoint":false,"build":false,"startFreeze":false,"noDamage":false,"instantGapple":false,"enderPearlCooldown":false,"clearBlock":false,"dropItemWhenDie":true,"noFallDamage":false,"giveBackArrow":false,"dropItems":true,"respawnTime":5,"maximumPoints":3,"matchCountdownDuration":5,"newRoundTime":5,"clearBlockTime":10,"knockbackName":"default"}'
    kit-match-types: '["FFA","SOLO","SPLIT"]'
    kit-extra-item: '[]'

**Comment by diocan** [comment]
now i have this error 

[16:11:15 WARN]: Exception in thread "Craft Scheduler Thread - 565" 
[16:11:15 WARN]: org.apache.commons.lang.UnhandledException: Plugin Eden v1.1.11-BETA-388825c generated an exception while executing task 46
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:58)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: no implementation set
        at net.citizensnpcs.api.CitizensAPI.getImplementation(CitizensAPI.java:92)
        at net.citizensnpcs.api.CitizensAPI.getNPCRegistry(CitizensAPI.java:132)
        at rip.diamond.practice.hook.plugin.citizens.CitizensHook.getOnlinePlayers(CitizensHook.java:20)
        at rip.diamond.practice.util.Util.getOnlinePlayers(Util.java:52)
        at rip.diamond.practice.util.nametags.NameTagManager$1.run(NameTagManager.java:44)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:65)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:55)
        ... 3 more

**Comment by diocan** [comment]
eden is not compatibility with citizens please fix

**Comment by GoodestEnglish** [comment]
> eden is not compatibility with citizens please fix

Details please.

**Comment by serumanooo** [comment]
> eden is not compatibility with citizens please fix

i was getting a lot of errors with citizens on console, thats what i did:
remove all npcs and create them again, the errors stopped

**Comment by serumanooo** [comment]
> Using your config and looks fine for me. ![image](https://user-images.githubusercontent.com/45838505/235264509-a1934bdf-2b9d-4d40-9998-e1e3c2489d80.png) What does yours look like?

for me it looks fine too in unranked 1v1
![image](https://user-images.githubusercontent.com/132185379/235597415-4555b12b-a7bb-4de1-a3af-246bc845a463.png)

but i noticed that in split mode it doesnt work properly
![image](https://user-images.githubusercontent.com/132185379/235597266-4eb2adef-ed18-45af-97c9-04b83b72b1d0.png)

**Comment by GoodestEnglish** [comment]
> > eden is not compatibility with citizens please fix
> 
> i was getting a lot of errors with citizens on console, thats what i did: remove all npcs and create them again, the errors stopped

May I see what's the error is?

**Comment by GoodestEnglish** [comment]
> > Using your config and looks fine for me. ![image](https://user-images.githubusercontent.com/45838505/235264509-a1934bdf-2b9d-4d40-9998-e1e3c2489d80.png) What does yours look like?
> 
> for me it looks fine too in unranked 1v1 ![image](https://user-images.githubusercontent.com/132185379/235597415-4555b12b-a7bb-4de1-a3af-246bc845a463.png)
> 
> but i noticed that in split mode it doesnt work properly ![image](https://user-images.githubusercontent.com/132185379/235597266-4eb2adef-ed18-45af-97c9-04b83b72b1d0.png)

Will be fixed soon

**Comment by GoodestEnglish** [comment]
Fixed in latest release
