### ISSUE TITLE
Scoreboard Bug

### ISSUE THREAD

**Issue by Gringitoo** [diamond-rip/Eden#250]
![sc](https://user-images.githubusercontent.com/131012481/235270405-ed6e6f36-ae9d-4190-881e-9f47917a51dd.PNG)

**Comment by GoodestEnglish** [comment]
You are using a wrong file encoding format.

**Comment by HierarchyMan** [comment]
Add this to your minecraft server startup command
" -Dfile.encoding=UTF-8 " 
It should look something like " java -Dfile.encoding=UTF-8 -Xms2G -Xmx2G -jar server.jar "
