### ISSUE TITLE
Spawn kill bridge

### ISSUE THREAD

**Issue by ushereats** [diamond-rip/Eden#253]
[
![image](https://user-images.githubusercontent.com/124885227/235349218-42638b4e-04c5-4457-a2b7-b6bb984511c7.png)
](url)

everytime i move it just instant kills me

**Comment by diocan** [comment]
set your Y coords under the bridge

**Comment by ushereats** [comment]
Yeah i did still happens

**Comment by GoodestEnglish** [comment]
Send your arena.yml.

**Comment by Chromaah** [comment]
i fixed it for him. He had an incorrect minimum and maximum value.
