### ISSUE TITLE
Custom Command & Items for items.yml

### ISSUE THREAD

**Issue by PattrickNguyen** [diamond-rip/Eden#258]
Add custom command in items.yml and also add the ability for configurator to add custom item and command into the lobby hotbar, tysm. Looking forward to this update asap

**Comment by HierarchyMan** [comment]
+1

**Comment by serumanooo** [comment]
+1

**Comment by serumanooo** [comment]
+1
also, if it already has I didn't find it, but could you add a /lobby command? it could be optional in config.yml in case someone uses a plugin that already has this function (I ask because I tried to use a separate plugin and I was simply taken to the lobby with the match items)

**Comment by Shzv** [comment]
+1

**Comment by Chromaah** [comment]
+1

**Comment by GoodestEnglish** [comment]
This will take a while, but is planned.

**Comment by GoodestEnglish** [comment]
Added in latest update
