### ISSUE TITLE
gapple doesnt give absorption

### ISSUE THREAD

**Issue by serumanooo** [diamond-rip/Eden#259]
![image](https://user-images.githubusercontent.com/132185379/235540696-05ba7f8d-5a5f-4b42-9a17-e6e1f151646b.png)
![image](https://user-images.githubusercontent.com/132185379/235540705-77acb2b8-daf4-46a8-874f-20527a2c3e92.png)

**Comment by HierarchyMan** [comment]
You can able that in config.yml
Try and read the plugin docs b4 spaming issues

**Comment by serumanooo** [comment]
> You can enable that in config.yml Try and reading the plugin docs b4 spaming issues

this was literally the only problem that was my mistake for not reading the config. im not spamming issues, im just pointing the problems I find so the plugin creator can see and fix. im sorry for this one

**Comment by serumanooo** [comment]
> > You can enable that in config.yml Try and reading the plugin docs b4 spaming issues
> 
> this was literally the only problem that was my mistake for not reading the config. im not spamming issues, im just pointing the problems I find so the plugin creator can see and fix. im sorry for this one

no, im not sorry:
![image](https://user-images.githubusercontent.com/132185379/235584146-2cea079e-0bc0-49f2-be81-d084da324a21.png)
i want the instant effects only in the bridge, not in the global config, and i have this, but the instant gapple doesnt give any absorption effect
