### ISSUE TITLE
DONE

### ISSUE THREAD

**Issue by underbone** [diamond-rip/Eden#26]
When I setup the map, I often get the error that the block cannot be placed and the move will die while pos1 and pos2 have enough square area and the map is in that square.

**Comment by HierarchyMan** [comment]
You've set up y-limit incorrectly make it lower to the place where players should die if they fall

**Comment by HierarchyMan** [comment]
And build needs to be enabled in kit

**Comment by underbone** [comment]
You can make tutorial ?

**Comment by underbone** [comment]
I've tried everything to no avail
