### ISSUE TITLE
in party split mode, a player keeps spawning in spectator mode when someone get a point

### ISSUE THREAD

**Issue by serumanooo** [diamond-rip/Eden#260]
![image](https://user-images.githubusercontent.com/132185379/235563332-e23f59cf-07ab-4b13-874b-ddd1006adb7f.png)

**Comment by serumanooo** [comment]
ty, i love this plugin, i was using strike practice before, but its so bad, i couldnt  even use different scoreboards on each mode

**Comment by serumanooo** [comment]
also, how can i use those labels?
![image](https://user-images.githubusercontent.com/132185379/235600255-b4541aae-0d15-4d1b-a9d3-fb0b88f6c4bd.png)

**Comment by HappyAreaBean** [comment]
> also, how can i use these labels? ![image](https://user-images.githubusercontent.com/132185379/235600255-b4541aae-0d15-4d1b-a9d3-fb0b88f6c4bd.png)

These label can only be assigned by a team member.

**Comment by GoodestEnglish** [comment]
This is my test result https://youtu.be/eMu6r5NoQPk, and it doesn't happen to me.

Try my settings and test it again:
```yml
  bridge:
    enabled: true
    ranked: false
    display-name: '&6Bridge'
    priority: 3
    damage-ticks: 19
    display-icon: "rO0ABXNyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAADbWFwdAAPTGph\r\
      \ndmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFibGVNYXAk\r\
      \nU2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAlsABGtleXN0ABNbTGphdmEvbGFuZy9PYmplY3Q7WwAG\r\
      \ndmFsdWVzcQB+AAR4cHVyABNbTGphdmEubGFuZy5PYmplY3Q7kM5YnxBzKWwCAAB4cAAAAAJ0AAI9\r\
      \nPXQABHR5cGV1cQB+AAYAAAACdAAeb3JnLmJ1a2tpdC5pbnZlbnRvcnkuSXRlbVN0YWNrdAAMU1RB\r\
      \nSU5FRF9DTEFZ\r\n"
    description: '[]'
    potion-effects: ''
    armor-loadout: "rO0ABXcEAAAABHNyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAADbWFw\r\
      \ndAAPTGphdmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFi\r\
      \nbGVNYXAkU2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAlsABGtleXN0ABNbTGphdmEvbGFuZy9PYmpl\r\
      \nY3Q7WwAGdmFsdWVzcQB+AAR4cHVyABNbTGphdmEubGFuZy5PYmplY3Q7kM5YnxBzKWwCAAB4cAAA\r\
      \nAAJ0AAI9PXQABHR5cGV1cQB+AAYAAAACdAAeb3JnLmJ1a2tpdC5pbnZlbnRvcnkuSXRlbVN0YWNr\r\
      \ndAANTEVBVEhFUl9CT09UU3NxAH4AAHNxAH4AA3VxAH4ABgAAAAJxAH4ACHEAfgAJdXEAfgAGAAAA\r\
      \nAnEAfgALdAAQTEVBVEhFUl9MRUdHSU5HU3NxAH4AAHNxAH4AA3VxAH4ABgAAAAJxAH4ACHEAfgAJ\r\
      \ndXEAfgAGAAAAAnEAfgALdAASTEVBVEhFUl9DSEVTVFBMQVRFc3EAfgAAc3EAfgADdXEAfgAGAAAA\r\
      \nAnEAfgAIcQB+AAl1cQB+AAYAAAACcQB+AAt0AA5MRUFUSEVSX0hFTE1FVA==\r\n"
    contents-loadout: "rO0ABXcEAAAAJHNyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAADbWFw\r\
      \ndAAPTGphdmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFi\r\
      \nbGVNYXAkU2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAlsABGtleXN0ABNbTGphdmEvbGFuZy9PYmpl\r\
      \nY3Q7WwAGdmFsdWVzcQB+AAR4cHVyABNbTGphdmEubGFuZy5PYmplY3Q7kM5YnxBzKWwCAAB4cAAA\r\
      \nAAJ0AAI9PXQABHR5cGV1cQB+AAYAAAACdAAeb3JnLmJ1a2tpdC5pbnZlbnRvcnkuSXRlbVN0YWNr\r\
      \ndAAKSVJPTl9TV09SRHNxAH4AAHNxAH4AA3VxAH4ABgAAAAJxAH4ACHEAfgAJdXEAfgAGAAAAAnEA\r\
      \nfgALdAADQk9Xc3EAfgAAc3EAfgADdXEAfgAGAAAAA3EAfgAIcQB+AAl0AARtZXRhdXEAfgAGAAAA\r\
      \nA3EAfgALdAAPRElBTU9ORF9QSUNLQVhFc3EAfgAAc3EAfgADdXEAfgAGAAAAA3EAfgAIdAAJbWV0\r\
      \nYS10eXBldAAIZW5jaGFudHN1cQB+AAYAAAADdAAISXRlbU1ldGF0AApVTlNQRUNJRklDc3IAN2Nv\r\
      \nbS5nb29nbGUuY29tbW9uLmNvbGxlY3QuSW1tdXRhYmxlQmlNYXAkU2VyaWFsaXplZEZvcm0AAAAA\r\
      \nAAAAAAIAAHhxAH4AA3VxAH4ABgAAAAF0AAlESUdfU1BFRUR1cQB+AAYAAAABc3IAEWphdmEubGFu\r\
      \nZy5JbnRlZ2VyEuKgpPeBhzgCAAFJAAV2YWx1ZXhyABBqYXZhLmxhbmcuTnVtYmVyhqyVHQuU4IsC\r\
      \nAAB4cAAAAANzcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAhxAH4ACXQABmFtb3VudHVxAH4ABgAA\r\
      \nAANxAH4AC3QADFNUQUlORURfQ0xBWXNxAH4AJQAAAEBwcHBzcQB+AABzcQB+AAN1cQB+AAYAAAAD\r\
      \ncQB+AAhxAH4ACXEAfgArdXEAfgAGAAAAA3EAfgALdAAMR09MREVOX0FQUExFc3EAfgAlAAAABHNx\r\
      \nAH4AAHNxAH4AA3VxAH4ABgAAAAJxAH4ACHEAfgAJdXEAfgAGAAAAAnEAfgALdAAFQVJST1dwcHBw\r\
      \ncHBwcHBwcHBwcHBwcHBwcHBwcHBwcHA=\r\n"
    game-rules: '{"receiveKitLoadoutBook":true,"deathOnWater":false,"boxing":false,"bed":false,"breakGoal":false,"portalGoal":true,"projectileOnly":false,"hypixelUHC":false,"spleef":false,"healthRegeneration":true,"showHealth":true,"foodLevelChange":false,"point":true,"rankedPoint":false,"resetArenaWhenGetPoint":false,"onlyLoserResetPositionWhenGetPoint":false,"build":true,"startFreeze":true,"noDamage":false,"instantGapple":true,"enderPearlCooldown":false,"clearBlock":false,"dropItemWhenDie":false,"noFallDamage":true,"giveBackArrow":true,"dropItems":true,"respawnTime":0,"maximumPoints":5,"matchCountdownDuration":5,"newRoundTime":5,"clearBlockTime":10,"knockbackName":"default"}'
    kit-match-types: '["SOLO","SPLIT"]'
    kit-extra-item: '[]'
    ```

**Comment by serumanooo** [comment]
> This is my test result https://youtu.be/eMu6r5NoQPk, and it doesn't happen to me.
> 
> Try my settings and test it again:
> 
> ```yaml
>   bridge:
>     enabled: true
>     ranked: false
>     display-name: '&6Bridge'
>     priority: 3
>     damage-ticks: 19
>     display-icon: "rO0ABXNyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAADbWFwdAAPTGph\r\
>       \ndmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFibGVNYXAk\r\
>       \nU2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAlsABGtleXN0ABNbTGphdmEvbGFuZy9PYmplY3Q7WwAG\r\
>       \ndmFsdWVzcQB+AAR4cHVyABNbTGphdmEubGFuZy5PYmplY3Q7kM5YnxBzKWwCAAB4cAAAAAJ0AAI9\r\
>       \nPXQABHR5cGV1cQB+AAYAAAACdAAeb3JnLmJ1a2tpdC5pbnZlbnRvcnkuSXRlbVN0YWNrdAAMU1RB\r\
>       \nSU5FRF9DTEFZ\r\n"
>     description: '[]'
>     potion-effects: ''
>     armor-loadout: "rO0ABXcEAAAABHNyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAADbWFw\r\
>       \ndAAPTGphdmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFi\r\
>       \nbGVNYXAkU2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAlsABGtleXN0ABNbTGphdmEvbGFuZy9PYmpl\r\
>       \nY3Q7WwAGdmFsdWVzcQB+AAR4cHVyABNbTGphdmEubGFuZy5PYmplY3Q7kM5YnxBzKWwCAAB4cAAA\r\
>       \nAAJ0AAI9PXQABHR5cGV1cQB+AAYAAAACdAAeb3JnLmJ1a2tpdC5pbnZlbnRvcnkuSXRlbVN0YWNr\r\
>       \ndAANTEVBVEhFUl9CT09UU3NxAH4AAHNxAH4AA3VxAH4ABgAAAAJxAH4ACHEAfgAJdXEAfgAGAAAA\r\
>       \nAnEAfgALdAAQTEVBVEhFUl9MRUdHSU5HU3NxAH4AAHNxAH4AA3VxAH4ABgAAAAJxAH4ACHEAfgAJ\r\
>       \ndXEAfgAGAAAAAnEAfgALdAASTEVBVEhFUl9DSEVTVFBMQVRFc3EAfgAAc3EAfgADdXEAfgAGAAAA\r\
>       \nAnEAfgAIcQB+AAl1cQB+AAYAAAACcQB+AAt0AA5MRUFUSEVSX0hFTE1FVA==\r\n"
>     contents-loadout: "rO0ABXcEAAAAJHNyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAADbWFw\r\
>       \ndAAPTGphdmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFi\r\
>       \nbGVNYXAkU2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAlsABGtleXN0ABNbTGphdmEvbGFuZy9PYmpl\r\
>       \nY3Q7WwAGdmFsdWVzcQB+AAR4cHVyABNbTGphdmEubGFuZy5PYmplY3Q7kM5YnxBzKWwCAAB4cAAA\r\
>       \nAAJ0AAI9PXQABHR5cGV1cQB+AAYAAAACdAAeb3JnLmJ1a2tpdC5pbnZlbnRvcnkuSXRlbVN0YWNr\r\
>       \ndAAKSVJPTl9TV09SRHNxAH4AAHNxAH4AA3VxAH4ABgAAAAJxAH4ACHEAfgAJdXEAfgAGAAAAAnEA\r\
>       \nfgALdAADQk9Xc3EAfgAAc3EAfgADdXEAfgAGAAAAA3EAfgAIcQB+AAl0AARtZXRhdXEAfgAGAAAA\r\
>       \nA3EAfgALdAAPRElBTU9ORF9QSUNLQVhFc3EAfgAAc3EAfgADdXEAfgAGAAAAA3EAfgAIdAAJbWV0\r\
>       \nYS10eXBldAAIZW5jaGFudHN1cQB+AAYAAAADdAAISXRlbU1ldGF0AApVTlNQRUNJRklDc3IAN2Nv\r\
>       \nbS5nb29nbGUuY29tbW9uLmNvbGxlY3QuSW1tdXRhYmxlQmlNYXAkU2VyaWFsaXplZEZvcm0AAAAA\r\
>       \nAAAAAAIAAHhxAH4AA3VxAH4ABgAAAAF0AAlESUdfU1BFRUR1cQB+AAYAAAABc3IAEWphdmEubGFu\r\
>       \nZy5JbnRlZ2VyEuKgpPeBhzgCAAFJAAV2YWx1ZXhyABBqYXZhLmxhbmcuTnVtYmVyhqyVHQuU4IsC\r\
>       \nAAB4cAAAAANzcQB+AABzcQB+AAN1cQB+AAYAAAADcQB+AAhxAH4ACXQABmFtb3VudHVxAH4ABgAA\r\
>       \nAANxAH4AC3QADFNUQUlORURfQ0xBWXNxAH4AJQAAAEBwcHBzcQB+AABzcQB+AAN1cQB+AAYAAAAD\r\
>       \ncQB+AAhxAH4ACXEAfgArdXEAfgAGAAAAA3EAfgALdAAMR09MREVOX0FQUExFc3EAfgAlAAAABHNx\r\
>       \nAH4AAHNxAH4AA3VxAH4ABgAAAAJxAH4ACHEAfgAJdXEAfgAGAAAAAnEAfgALdAAFQVJST1dwcHBw\r\
>       \ncHBwcHBwcHBwcHBwcHBwcHBwcHBwcHA=\r\n"
>     game-rules: '{"receiveKitLoadoutBook":true,"deathOnWater":false,"boxing":false,"bed":false,"breakGoal":false,"portalGoal":true,"projectileOnly":false,"hypixelUHC":false,"spleef":false,"healthRegeneration":true,"showHealth":true,"foodLevelChange":false,"point":true,"rankedPoint":false,"resetArenaWhenGetPoint":false,"onlyLoserResetPositionWhenGetPoint":false,"build":true,"startFreeze":true,"noDamage":false,"instantGapple":true,"enderPearlCooldown":false,"clearBlock":false,"dropItemWhenDie":false,"noFallDamage":true,"giveBackArrow":true,"dropItems":true,"respawnTime":0,"maximumPoints":5,"matchCountdownDuration":5,"newRoundTime":5,"clearBlockTime":10,"knockbackName":"default"}'
>     kit-match-types: '["SOLO","SPLIT"]'
>     kit-extra-item: '[]'
>     
> ```

ok ill try
