### ISSUE TITLE
the fishing rod can hit allies

### ISSUE THREAD

**Issue by serumanooo** [diamond-rip/Eden#261]
![image](https://user-images.githubusercontent.com/132185379/235565364-c7fd4db5-026b-4db0-bc48-af104bffa704.png)
![image](https://user-images.githubusercontent.com/132185379/235565372-6e3bdbaa-154d-4e0c-b433-7b52b5c748fa.png)
![image](https://user-images.githubusercontent.com/132185379/235565377-1e81b301-0bb5-4776-91cf-0d221579b1d0.png)

**Comment by GoodestEnglish** [comment]
This is normal because this alllows to rod boost

**Comment by serumanooo** [comment]
> This is normal because this alllows to rod boost

ohhh i didnt knew about it thx
