### ISSUE TITLE
teleportation tool doesnt work

### ISSUE THREAD

**Issue by serumanooo** [diamond-rip/Eden#262]
![image](https://user-images.githubusercontent.com/132185379/235571922-03f1e809-0d19-42d9-bdd5-07f4b133247d.png)
and the ending title is spelled wrong
![image](https://user-images.githubusercontent.com/132185379/235572098-cb527133-0762-4b8c-9401-34845ed047d8.png)
it should be "won"

**Comment by serumanooo** [comment]
and idk why but when someone die in split mode, the player get teleported to the world spawn instead of the spectator spawn, and spectators cant fly

**Comment by HierarchyMan** [comment]
When multiple people win its spelled win, not won
Won is used when 1 person wins

**Comment by GoodestEnglish** [comment]
> and idk why but when someone die in split mode, the player get teleported to the world spawn instead of the spectator spawn, and spectators cant fly

What spigot are you using?

**Comment by serumanooo** [comment]
> When multiple people win its spelled win, not won Won is used when 1 person wins

![image](https://user-images.githubusercontent.com/132185379/235583262-66f23a88-5f4e-4714-b31e-a4e104dfbaf7.png)
"serumano_ win"

**Comment by serumanooo** [comment]
> > and idk why but when someone die in split mode, the player get teleported to the world spawn instead of the spectator spawn, and spectators cant fly
> 
> What spigot are you using?

papermc 1.8.8

**Comment by HierarchyMan** [comment]
Yes I agree it should be fixed +1

**Comment by GoodestEnglish** [comment]
> > When multiple people win its spelled win, not won Won is used when 1 person wins
> 
> ![image](https://user-images.githubusercontent.com/132185379/235583262-66f23a88-5f4e-4714-b31e-a4e104dfbaf7.png) "sayuriuy win"

You can edit all language stuff in language.yml.

**Comment by serumanooo** [comment]
> > > When multiple people win its spelled win, not won Won is used when 1 person wins
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/132185379/235583262-66f23a88-5f4e-4714-b31e-a4e104dfbaf7.png) "sayuriuy win"
> 
> You can edit all language stuff in language.yml.

ok ty, ill do that

**Comment by serumanooo** [comment]
> > > When multiple people win its spelled win, not won Won is used when 1 person wins
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/132185379/235583262-66f23a88-5f4e-4714-b31e-a4e104dfbaf7.png) "sayuriuy win"
> 
> You can edit all language stuff in language.yml.

hey idk if you will see this becaause the issue is closed, but i could not find where to change this in language.yml
