### ISSUE TITLE
gapple still not giving absorption with instant gapple in kit configs

### ISSUE THREAD

**Issue by serumanooo** [diamond-rip/Eden#264]
yes, i tried changing the config to true, it didnt work
![image](https://user-images.githubusercontent.com/132185379/235602030-406b8498-39e3-4e6f-83a3-608ba1d5050c.png)
if the config.yml has any other options that I didnt see, im sorry.
![image](https://user-images.githubusercontent.com/132185379/235602114-e382d3c3-7f92-47cb-a799-3e70c5176f05.png)
![image](https://user-images.githubusercontent.com/132185379/235602124-0bcabdfc-e91f-47c7-b31d-a6377497cbd4.png)

**Comment by serumanooo** [comment]
just an idea, i think you could add a option here to teleport the player to the arena (it could be on spectator location), its complicated to check the coordinates everytime i want to change something on the arena
![image](https://user-images.githubusercontent.com/132185379/235773291-cb92f3d6-7d97-4590-a379-ff4adc9e5ca6.png)

**Comment by GoodestEnglish** [comment]
I've checked and looks like I've mistyped the path of the config in the code. It will be fixed.

**Comment by GoodestEnglish** [comment]
> just an idea, i think you could add a option here to teleport the player to the arena (it could be on spectator location), its complicated to check the coordinates everytime i want to change something on the arena ![image](https://user-images.githubusercontent.com/132185379/235773291-cb92f3d6-7d97-4590-a379-ff4adc9e5ca6.png)

Moved to https://github.com/diamond-rip/Eden/discussions/265

**Comment by GoodestEnglish** [comment]
Fixed in latest release
