### ISSUE TITLE
still having problems with insta kill

### ISSUE THREAD

**Issue by serumanooo** [diamond-rip/Eden#267]
now the player can walk after the arena limit, but doesnt work for what i want
they get insta killed when they pass the red line
![image](https://user-images.githubusercontent.com/132185379/236003839-57b0cdf5-fcb2-48a6-a1b6-c680cef9964f.png)
![image](https://user-images.githubusercontent.com/132185379/236004002-fef37d80-0817-47d6-9c54-1e936798b3e1.png)
here is my idea: make the instant death optional in config.yml or make a option so we can define how far can the player pass the limit
(if you dont want to do this ill just use worldguard to make a second limit)
im sorry for reporting another issue about this

**Comment by GoodestEnglish** [comment]
Your min and max should cover the whole area. Not just the "bridge"
Here's an example: 
![image](https://user-images.githubusercontent.com/45838505/236062135-1c6b51a4-72d7-483d-9bea-195eefeca3d7.png)
Your min and max should look like the green line.

**Comment by GoodestEnglish** [comment]
But if you really want this option, yes I can add into it.

**Comment by serumanooo** [comment]
> Your min and max should cover the whole area. Not just the "bridge" Here's an example: ![image](https://user-images.githubusercontent.com/45838505/236062135-1c6b51a4-72d7-483d-9bea-195eefeca3d7.png) Your min and max should look like the green line.

i made it like this because i wanted to prevent the player placing blocks in the base, just the entry to the portal and the bridge

**Comment by serumanooo** [comment]
before the last update of the plugin, i was making this:
red for eden area
green for worldguard build deny flag
![image](https://user-images.githubusercontent.com/132185379/236083866-4ac47fb7-6894-40bf-ae61-a125afdbb183.png)

**Comment by GoodestEnglish** [comment]
> > Your min and max should cover the whole area. Not just the "bridge" Here's an example: ![image](https://user-images.githubusercontent.com/45838505/236062135-1c6b51a4-72d7-483d-9bea-195eefeca3d7.png) Your min and max should look like the green line.
> 
> i made it like this because i wanted to prevent the player placing blocks in the base, just the entry to the portal and the bridge

mhm, then you should increase the portal protection radius for the map you are using.

**Comment by serumanooo** [comment]
> > > Your min and max should cover the whole area. Not just the "bridge" Here's an example: ![image](https://user-images.githubusercontent.com/45838505/236062135-1c6b51a4-72d7-483d-9bea-195eefeca3d7.png) Your min and max should look like the green line.
> > 
> > 
> > i made it like this because i wanted to prevent the player placing blocks in the base, just the entry to the portal and the bridge
> 
> mhm, then you should increase the portal protection radius for the map you are using.

but then the portal protection radius will make it impossible to do hippos

**Comment by GoodestEnglish** [comment]
I don't really play bridge. What do you mean by hippos?

**Comment by GoodestEnglish** [comment]
Anyway, adding option to toggle the instant kill in next update.

**Comment by serumanooo** [comment]
> I don't really play bridge. What do you mean by hippos?
![image](https://user-images.githubusercontent.com/132185379/236550137-d5a5a297-1e87-4eed-8566-f04cfeee8c56.png)
![image](https://user-images.githubusercontent.com/132185379/236550146-a1754e1d-49df-43c3-8541-1eba576c43f1.png)
this is a hippo

**Comment by serumanooo** [comment]
> Anyway, adding option to toggle the instant kill in next update.

ok ty
