### ISSUE TITLE
cant fly on spectator mode, is that normal?

### ISSUE THREAD

**Issue by serumanooo** [diamond-rip/Eden#269]
![image](https://user-images.githubusercontent.com/132185379/236309068-1e2a683b-b921-49fd-a464-f7915c14bbb3.png)

**Comment by ushereats** [comment]
It's just a bug which will be fixed.

**Comment by serumanooo** [comment]
> It's just a bug which will be fixed.

oh okay, also, there are moments that i cant use the teleportation tool, i hope this get fixed too

**Comment by GoodestEnglish** [comment]
> > It's just a bug which will be fixed.
> 
> oh okay, also, there are moments that i cant use the teleportation tool, i hope this get fixed too

Any error in console? Because there's no checks when opening the teleportation menu.

**Comment by GoodestEnglish** [comment]
I've also checked and it doesn't seems a issue for me. Does that occur everytime?
