### ISSUE TITLE
idk why but sometimes the arena just doesnt reset

### ISSUE THREAD

**Issue by serumanooo** [diamond-rip/Eden#270]
(not only in this kit and arena, also happened in other arenas)
![image](https://user-images.githubusercontent.com/132185379/236551476-e8d85955-e3d2-408b-970d-eb2b90009b41.png)

**Comment by serumanooo** [comment]
![image](https://user-images.githubusercontent.com/132185379/236569620-70db0daf-1e2d-4e02-ad39-9b18a30737f8.png)
i was on spectator mode and i got 2x post match inventories

**Comment by serumanooo** [comment]
> ![image](https://user-images.githubusercontent.com/132185379/236569620-70db0daf-1e2d-4e02-ad39-9b18a30737f8.png) i was on spectator mode after being kicked of the server and i got 2x post match inventories

**Comment by GoodestEnglish** [comment]
I will test it once I am free

**Comment by serumanooo** [comment]
> I will test it once I am free

ok

**Comment by serumanooo** [comment]
> I will test it once I am free

it generaly happens when i restart the server
no one is in match when i restart, but i think it would be good if this doesnt happen even if there are player in match

**Comment by GoodestEnglish** [comment]
Try to turn off auto saving by using command `/save-off`
