### ISSUE TITLE
suggestions and fixes

### ISSUE THREAD

**Issue by serumanooo** [diamond-rip/Eden#272]
idk if there is a plugin to do that, but i didnt found, but like
![image](https://user-images.githubusercontent.com/132185379/236582900-c5ded5b7-42e6-4491-a397-7aea5f419eab.png)
can you make the snow have 50% chance of giving 1 snowball like minemen? 
(if there is a plugin to decrease/increase the drop of items let me know please)

**Comment by serumanooo** [comment]
also, i dont know if its eden that doesnt let the player craft items, but if it is, can you make it optional on the /kit options? i want it because i want to make a gladiator 1v1, and in gladiator the player NEED to be able to recraft soups
recraft example video:
https://youtu.be/s26BkutHLr0

**Comment by serumanooo** [comment]
> also, i dont know if its eden that doesnt let the player craft items, but if it is, can you make it optional on the /kit options? i want it because i want to make a gladiator 1v1, and in gladiator the player NEED to be able to recraft soups recraft example video: https://youtu.be/s26BkutHLr0
(i said to make it optional, because i dont want to have player crafting like snowblocks in spleef)

**Comment by serumanooo** [comment]
boxing split party hit counter still not working when players hit eachother
![image](https://user-images.githubusercontent.com/132185379/236591522-5a01f05f-43e6-47c0-a690-ccbc10ed1672.png)
![image](https://user-images.githubusercontent.com/132185379/236591525-3d3df74e-6a00-4be0-a583-400d5ea5d622.png)
(before the last update it did not show "no combo", now it does, but it still does not work"

**Comment by serumanooo** [comment]
Can you add a anti spam for the commands? i can infinitely send party requests even if the player is already in the party
![image](https://user-images.githubusercontent.com/132185379/236592584-d9574a81-8f3d-463f-9aec-28e28bf3f775.png)
![image](https://user-images.githubusercontent.com/132185379/236592590-bdf675ee-8f71-417c-ad9e-5cfa5016373f.png)

**Comment by GoodestEnglish** [comment]
> boxing split party hit counter still not working when players hit eachother ![image](https://user-images.githubusercontent.com/132185379/236591522-5a01f05f-43e6-47c0-a690-ccbc10ed1672.png) ![image](https://user-images.githubusercontent.com/132185379/236591525-3d3df74e-6a00-4be0-a583-400d5ea5d622.png) (before the last update it did not show "no combo", now it does, but it still does not work"

Replace scoreboard.in-match-teams.boxing to this
```yml
    boxing:
      - "&7&m----------------------"
      - "&b&l┃ &bHits: {match-team-boxing-difference-color}({match-team-boxing-difference-symbol}{match-team-boxing-difference})"
      - "&b&l┃ &a You: &f{match-team-boxing-self-hit}"
      - "&b&l┃ &c Them: &f{match-team-boxing-opponent-hit}"
      - ""
      - "&b&l┃ &aTeam: &7(&b{match-team-self-alive}&7/&b{match-team-self-size}&7)"
      - "&b&l┃ &cOpponents: &7(&b{match-team-opponent-alive}&7/&b{match-team-opponent-size}&7)"
      - "&7&m----------------------"
```

**Comment by GoodestEnglish** [comment]
> Can you add a anti spam for the commands? i can infinitely send party requests even if the player is already in the party ![image](https://user-images.githubusercontent.com/132185379/236592584-d9574a81-8f3d-463f-9aec-28e28bf3f775.png) ![image](https://user-images.githubusercontent.com/132185379/236592590-bdf675ee-8f71-417c-ad9e-5cfa5016373f.png)

Adding this in next update.

**Comment by GoodestEnglish** [comment]
> also, i dont know if its eden that doesnt let the player craft items, but if it is, can you make it optional on the /kit options? i want it because i want to make a gladiator 1v1, and in gladiator the player NEED to be able to recraft soups recraft example video: https://youtu.be/s26BkutHLr0 i said to make it optional because i dont want to have players crafting like, snowblocks on spleef

Currently, by default it is disabled. I will add an option to toggle in next update.

**Comment by GoodestEnglish** [comment]
> idk if there is a plugin to do that, but i didnt found, but like ![image](https://user-images.githubusercontent.com/132185379/236582900-c5ded5b7-42e6-4491-a397-7aea5f419eab.png) can you make the snow have 50% chance of giving 1 snowball like minemen? (if there is a plugin to decrease/increase the drop of items let me know please)

Adding this in next update

**Comment by GoodestEnglish** [comment]
Added in latest release

**Comment by serumanooo** [comment]
> > boxing split party hit counter still not working when players hit eachother ![image](https://user-images.githubusercontent.com/132185379/236591522-5a01f05f-43e6-47c0-a690-ccbc10ed1672.png) ![image](https://user-images.githubusercontent.com/132185379/236591525-3d3df74e-6a00-4be0-a583-400d5ea5d622.png) (before the last update it did not show "no combo", now it does, but it still does not work"
> 
> Replace scoreboard.in-match-teams.boxing to this
> 
> ```yaml
>     boxing:
>       - "&7&m----------------------"
>       - "&b&l┃ &bHits: {match-team-boxing-difference-color}({match-team-boxing-difference-symbol}{match-team-boxing-difference})"
>       - "&b&l┃ &a You: &f{match-team-boxing-self-hit}"
>       - "&b&l┃ &c Them: &f{match-team-boxing-opponent-hit}"
>       - ""
>       - "&b&l┃ &aTeam: &7(&b{match-team-self-alive}&7/&b{match-team-self-size}&7)"
>       - "&b&l┃ &cOpponents: &7(&b{match-team-opponent-alive}&7/&b{match-team-opponent-size}&7)"
>       - "&7&m----------------------"
> ```

ill try
