### ISSUE TITLE
hits without sword not working on boxing

### ISSUE THREAD

**Issue by serumanooo** [diamond-rip/Eden#273]
https://youtu.be/GLJYBdDgODU
(im sorry for reporting so many issues, i just want to help :D)

**Comment by GoodestEnglish** [comment]
Knew something will happen. But didn't realize because I am dumb. This is why I said it is experimental in the update blog post.

Fixing this in next update.

**Comment by GoodestEnglish** [comment]
Leave it open first. I will close it after I fix it.

**Comment by GoodestEnglish** [comment]
Fixed in latest update
