### ISSUE TITLE
I cant build 

### ISSUE THREAD

**Issue by AruentXX** [diamond-rip/Eden#274]
I cant build even though i already enabled build.

**Comment by GoodestEnglish** [comment]
send your arena.yml

**Comment by AruentXX** [comment]
Chess:
    display-name: Chess
    icon: |
      rO0ABXNyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAADbWFwdAAPTGph
      dmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFibGVNYXAk
      U2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAlsABGtleXN0ABNbTGphdmEvbGFuZy9PYmplY3Q7WwAG
      dmFsdWVzcQB+AAR4cHVyABNbTGphdmEubGFuZy5PYmplY3Q7kM5YnxBzKWwCAAB4cAAAAAN0AAI9
      PXQABHR5cGV0AAZkYW1hZ2V1cQB+AAYAAAADdAAeb3JnLmJ1a2tpdC5pbnZlbnRvcnkuSXRlbVN0
      YWNrdAAEV09PTHNyAA9qYXZhLmxhbmcuU2hvcnRoTTcTNGDaUgIAAVMABXZhbHVleHIAEGphdmEu
      bGFuZy5OdW1iZXKGrJUdC5TgiwIAAHhwAA8=
    y-limit: 0
    build-max: -1
    portal-protection-radius: 3
    kits:
    - NoDebuffed
    - SoupPvP
    - Boxing
    - BuildUhc
    - Classic
    enabled: true
    details:
      '0':
        a: '#w;potpvp1:#x;-23.968568979804598:#y;104.0:#z;3.8237124678046994:#p;-4.0500045:#yaw;179.5503'
        b: '#w;potpvp1:#x;-24.025188023495193:#y;104.0:#z;-107.54345613789907:#p;-3.4500084:#yaw;359.7001'
        spectator: '#w;potpvp1:#x;-51.69864803226665:#y;114.7820739424373:#z;-58.081524122798186:#p;7.6499705:#yaw;270.75018'
        min: '#w;potpvp1:#x;4.0:#y;103.0:#z;5.0:#p;0.0:#yaw;0.0'
        max: '#w;potpvp1:#x;-53.0:#y;253.0:#z;-110.0:#p;0.0:#yaw;0.0'
      '1':
        a: '#w;potpvp1:#x;9976.031431020196:#y;104.0:#z;10003.823712467805:#p;-4.0500045:#yaw;179.5503'
        b: '#w;potpvp1:#x;9975.974811976504:#y;104.0:#z;9892.456543862101:#p;-3.4500084:#yaw;359.7001'
        spectator: '#w;potpvp1:#x;9948.301351967733:#y;114.7820739424373:#z;9941.918475877203:#p;7.6499705:#yaw;270.75018'
        min: '#w;potpvp1:#x;10004.0:#y;103.0:#z;10005.0:#p;0.0:#yaw;0.0'
        max: '#w;potpvp1:#x;9947.0:#y;253.0:#z;9890.0:#p;0.0:#yaw;0.0'
      '2':
        a: '#w;potpvp1:#x;10476.031431020196:#y;104.0:#z;10503.823712467805:#p;-4.0500045:#yaw;179.5503'
        b: '#w;potpvp1:#x;10475.974811976504:#y;104.0:#z;10392.456543862101:#p;-3.4500084:#yaw;359.7001'
        spectator: '#w;potpvp1:#x;10448.301351967733:#y;114.7820739424373:#z;10441.918475877203:#p;7.6499705:#yaw;270.75018'
        min: '#w;potpvp1:#x;10504.0:#y;103.0:#z;10505.0:#p;0.0:#yaw;0.0'
        max: '#w;potpvp1:#x;10447.0:#y;253.0:#z;10390.0:#p;0.0:#yaw;0.0'

**Comment by serumanooo** [comment]
> Chess: display-name: Chess icon: | rO0ABXNyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAADbWFwdAAPTGph dmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFibGVNYXAk U2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAlsABGtleXN0ABNbTGphdmEvbGFuZy9PYmplY3Q7WwAG dmFsdWVzcQB+AAR4cHVyABNbTGphdmEubGFuZy5PYmplY3Q7kM5YnxBzKWwCAAB4cAAAAAN0AAI9 PXQABHR5cGV0AAZkYW1hZ2V1cQB+AAYAAAADdAAeb3JnLmJ1a2tpdC5pbnZlbnRvcnkuSXRlbVN0 YWNrdAAEV09PTHNyAA9qYXZhLmxhbmcuU2hvcnRoTTcTNGDaUgIAAVMABXZhbHVleHIAEGphdmEu bGFuZy5OdW1iZXKGrJUdC5TgiwIAAHhwAA8= y-limit: 0 build-max: -1 portal-protection-radius: 3 kits: - NoDebuffed - SoupPvP - Boxing - BuildUhc - Classic enabled: true details: '0': a: '#w;potpvp1:#x;-23.968568979804598:#y;104.0:#z;3.8237124678046994:#p;-4.0500045:#yaw;179.5503' b: '#w;potpvp1:#x;-24.025188023495193:#y;104.0:#z;-107.54345613789907:#p;-3.4500084:#yaw;359.7001' spectator: '#w;potpvp1:#x;-51.69864803226665:#y;114.7820739424373:#z;-58.081524122798186:#p;7.6499705:#yaw;270.75018' min: '#w;potpvp1:#x;4.0:#y;103.0:#z;5.0:#p;0.0:#yaw;0.0' max: '#w;potpvp1:#x;-53.0:#y;253.0:#z;-110.0:#p;0.0:#yaw;0.0' '1': a: '#w;potpvp1:#x;9976.031431020196:#y;104.0:#z;10003.823712467805:#p;-4.0500045:#yaw;179.5503' b: '#w;potpvp1:#x;9975.974811976504:#y;104.0:#z;9892.456543862101:#p;-3.4500084:#yaw;359.7001' spectator: '#w;potpvp1:#x;9948.301351967733:#y;114.7820739424373:#z;9941.918475877203:#p;7.6499705:#yaw;270.75018' min: '#w;potpvp1:#x;10004.0:#y;103.0:#z;10005.0:#p;0.0:#yaw;0.0' max: '#w;potpvp1:#x;9947.0:#y;253.0:#z;9890.0:#p;0.0:#yaw;0.0' '2': a: '#w;potpvp1:#x;10476.031431020196:#y;104.0:#z;10503.823712467805:#p;-4.0500045:#yaw;179.5503' b: '#w;potpvp1:#x;10475.974811976504:#y;104.0:#z;10392.456543862101:#p;-3.4500084:#yaw;359.7001' spectator: '#w;potpvp1:#x;10448.301351967733:#y;114.7820739424373:#z;10441.918475877203:#p;7.6499705:#yaw;270.75018' min: '#w;potpvp1:#x;10504.0:#y;103.0:#z;10505.0:#p;0.0:#yaw;0.0' max: '#w;potpvp1:#x;10447.0:#y;253.0:#z;10390.0:#p;0.0:#yaw;0.0'

your build max is -1, just change it and it will work fine

**Comment by AruentXX** [comment]
Ohhh
