### ISSUE TITLE
still getting insta killed outside the arena and a bug

### ISSUE THREAD

**Issue by serumanooo** [diamond-rip/Eden#276]
![image](https://user-images.githubusercontent.com/132185379/236640259-eabfebc2-cd1f-4492-ac3d-41e94b5f6da7.png)
![image](https://user-images.githubusercontent.com/132185379/236640300-63d1991b-d122-4f4f-9ae6-24c34ca0f3f9.png)
![image](https://user-images.githubusercontent.com/132185379/236640302-a70cb635-fffd-450f-8964-9ec0023084e7.png)

**Comment by serumanooo** [comment]
and when a player quits the server and rejoin, its like he's still in the match
![image](https://user-images.githubusercontent.com/132185379/236640406-73228329-1a22-45d1-930f-adc76f81a749.png)
![image](https://user-images.githubusercontent.com/132185379/236640409-b81e8497-bb1c-4833-8335-a1e0855dcb72.png)

**Comment by serumanooo** [comment]
also, can you make players able to break like, grass, flowers, dead bush, etc. because its annoying to hit a grass trying to hit a player and it doesnt break, i tried to add these things in the config.yml but i think it just works for tnt/fireball
if you do that, make them dont drop anything

**Comment by serumanooo** [comment]
![image](https://user-images.githubusercontent.com/132185379/236656564-306910f9-e30f-4e93-be64-843fa38ca450.png)
and i still can invite players when they already is in the party

**Comment by GoodestEnglish** [comment]
Fixed in latest update
