### ISSUE TITLE
Wins commands 

### ISSUE THREAD

**Issue by Antoniova1** [diamond-rip/Eden#277]
If it is possible to add in the configuration some option to execute commands when a player wins a game.

**Comment by GoodestEnglish** [comment]
Might make an addon for this, but in a low priority

**Comment by Antoniova1** [comment]
that would be amazing, by the way what a great job you have done on this plugin it is really amazing

**Comment by GoodestEnglish** [comment]
Sorry it has been two months and I forgot about this. Adding this in next update.

**Comment by Antoniova1** [comment]
> Sorry it has been two months and I forgot about this. Adding this in next update.

Ty ty

**Comment by GoodestEnglish** [comment]
Added in latest release
