### ISSUE TITLE
inventory bug

### ISSUE THREAD

**Issue by serumanooo** [diamond-rip/Eden#278]
https://youtu.be/zyeKjhB8MeI

**Comment by serumanooo** [comment]
can you make the blocks dont go back to the player inventory, like, just make the wool infinite so this will not happen:
https://youtu.be/HtD5yDolR8E
or somehow fix this, its not a thing that make the game unplayable but its annoying

**Comment by GoodestEnglish** [comment]
Wool will not be infinite, because that's not now battlerush works. But I will fix it so it will looks like MMC

**Comment by GoodestEnglish** [comment]
Fixed in latest update
