### ISSUE TITLE
cant craft

### ISSUE THREAD

**Issue by serumanooo** [diamond-rip/Eden#279]
https://youtu.be/W7oRvCFCPXs
![image](https://user-images.githubusercontent.com/132185379/236652341-7fc2b893-dd48-47e0-92f2-bc98cfbe12c7.png)
![image](https://user-images.githubusercontent.com/132185379/236652344-652a55f6-4619-4a7f-8900-419af5e9b584.png)
I tried true and false and it didnt work, i thought it could be a plugin i was using, but i removed it and it didnt work, and i dont think its another plugin blocking the crafts because i can craft a crafting table

**Comment by GoodestEnglish** [comment]
Set it to false atm, I will fix it in next update.

**Comment by GoodestEnglish** [comment]
Should be fixed in latest release
