### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by AruentXX** [diamond-rip/Eden#280]
Make so you can set the team goals and bed because it sometimes bugged and the opponent goal and bed is close to the spawn.

**Comment by GoodestEnglish** [comment]
What bug did you face? Please explain with more details so I can help.

**Comment by AruentXX** [comment]
Sometimes the opponent's bed is the bed that is at our base instead of the opponent's base.

**Comment by AruentXX** [comment]
And also like I get a bug where i instantly died when i spawn

 Hut:
    display-name: Hut
    icon: |
      rO0ABXNyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAADbWFwdAAPTGph
      dmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFibGVNYXAk
      U2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAlsABGtleXN0ABNbTGphdmEvbGFuZy9PYmplY3Q7WwAG
      dmFsdWVzcQB+AAR4cHVyABNbTGphdmEubGFuZy5PYmplY3Q7kM5YnxBzKWwCAAB4cAAAAAJ0AAI9
      PXQABHR5cGV1cQB+AAYAAAACdAAeb3JnLmJ1a2tpdC5pbnZlbnRvcnkuSXRlbVN0YWNrdAAFR1JB
      U1M=
    y-limit: 0
    build-max: -1
    portal-protection-radius: 1
    kits:
    - Bedfight
    enabled: true
    details:
      '0':
        a: '#w;Bedfight:#x;-0.5:#y;165.0:#z;-66.5:#p;0.0:#yaw;0.0'
        b: '#w;Bedfight:#x;0.5:#y;165.0:#z;-4.5:#p;0.0:#yaw;-180.0'
        spectator: '#w;Bedfight:#x;-4.591665874816799:#y;178.34601725705957:#z;-35.42245746846926:#p;35.849995:#yaw;-91.350044'
        min: '#w;Bedfight:#x;-10.0:#y;151.0:#z;6.0:#p;0.0:#yaw;0.0'
        max: '#w;Bedfight:#x;12.0:#y;186.0:#z;-83.0:#p;0.0:#yaw;0.0'

**Comment by GoodestEnglish** [comment]
Your Y-limit is wrong, check out https://github.com/diamond-rip/Eden/wiki/Arenas-Setup#y-limit for more information

**Comment by GoodestEnglish** [comment]
> Sometimes the opponent's bed is the bed that is at our base instead of the opponent's base.

Eden uses an algorithm which detects the nearest spawn when you break a bed to determine if it is your own bed or opponent's bed. I am guessing you are doing something wrong. Please record a video so I can see what actually happens.

**Comment by AruentXX** [comment]
Ok will try

**Comment by AruentXX** [comment]
Ok i relize what i did wrong but like if i want to make like a bridge race like which person go to the other side first win is that like possible?

**Comment by GoodestEnglish** [comment]
Currently it is not possible.

**Comment by AruentXX** [comment]
Hello! So how do i set spawn build protection size?

**Comment by GoodestEnglish** [comment]
wdym by spawn build protection size?
