### ISSUE TITLE
team scoreboard combo counter not working

### ISSUE THREAD

**Issue by serumanooo** [diamond-rip/Eden#281]
![image](https://user-images.githubusercontent.com/132185379/236690466-4e602ddc-f85e-4ba9-814b-f87cc411a762.png)
![image](https://user-images.githubusercontent.com/132185379/236690593-439e06a2-b95e-4201-ae96-3a7ac4a50c45.png)
![image](https://user-images.githubusercontent.com/132185379/236690473-9b1aa568-78a2-45b9-a371-3248537756e9.png)

**Comment by serumanooo** [comment]
and idk if its eden's fault but i cant break the cactus by placing a block at the side of it
https://youtu.be/w2ezniM20p0

**Comment by GoodestEnglish** [comment]
I accidentally put a 's' in the config name. Please change `text-teams` to `text-team`. This will fix the issue.
