### ISSUE TITLE
a friend discovered a bug

### ISSUE THREAD

**Issue by serumanooo** [diamond-rip/Eden#282]
https://youtu.be/wjCzqMOBVmw

**Comment by serumanooo** [comment]
and i still dont know why the arena partially resets sometimes
![image](https://user-images.githubusercontent.com/132185379/236691038-62e97833-75b8-49c4-b244-762f9a3fdadf.png)
(also happens with other blocks, like obsidian and clay)

**Comment by HierarchyMan** [comment]
I think what @GoodestEnglish needs to do is
Allow players to mine all cobblestone when build is enabled, that's the only solution I can currently think of
Cuz there's no block tag that suggests it was made using lava and water
Or, What the plugin could do is add listeners for when lava and water mix and mark the obsidian/stone/cobblestone as Minable.

**Comment by serumanooo** [comment]
> I think what @GoodestEnglish needs to do is Allow players to mine all cobblestone when build is enabled, that's the only solution I can currently think of Cuz there's no block tag that suggests it was made using lava and water Or, What the plugin could do is add listeners for when lava and water mix and mark the obsidian/stone/cobblestone as Minable.

i think he needs to make the obsidian/stone/cobblestone to recognize if it was placed by a player
and how i said, idk why but the arena doesnt reset properly, i thought it was only with cobblestone and obsidian, but in bridges, almost everyday i need to break so much blocks and re-save the arena

**Comment by GoodestEnglish** [comment]
> I think what @GoodestEnglish needs to do is Allow players to mine all cobblestone when build is enabled, that's the only solution I can currently think of Cuz there's no block tag that suggests it was made using lava and water Or, What the plugin could do is add listeners for when lava and water mix and mark the obsidian/stone/cobblestone as Minable.

There's one, it is called BlockFromToEvent

Anyway, fixing this in next update

**Comment by serumanooo** [comment]
> 

ok ill do that if the arenas reset doesnt get fixed

**Comment by HierarchyMan** [comment]
> > I think what @GoodestEnglish needs to do is Allow players to mine all cobblestone when build is enabled, that's the only solution I can currently think of Cuz there's no block tag that suggests it was made using lava and water Or, What the plugin could do is add listeners for when lava and water mix and mark the obsidian/stone/cobblestone as Minable.
> 
> There's one, it is called BlockFromToEvent
> 
> Anyway, fixing cobblestone issue in next update Not sure why the arena didn't reset. But if next update didn't fix it, open another issue and let me know.

arena didnt reset prolly cuz the blocks werent placed by player? but generated by lava and water maybe idk

**Comment by GoodestEnglish** [comment]
> > > > I think what @GoodestEnglish needs to do is Allow players to mine all cobblestone when build is enabled, that's the only solution I can currently think of Cuz there's no block tag that suggests it was made using lava and water Or, What the plugin could do is add listeners for when lava and water mix and mark the obsidian/stone/cobblestone as Minable.
> > > 
> > > 
> > > There's one, it is called BlockFromToEvent
> > > Anyway, fixing cobblestone issue in next update Not sure why the arena didn't reset. But if next update didn't fix it, open another issue and let me know.
> > 
> > 
> > arena didnt reset prolly cuz the blocks werent placed by player? but generated by lava and water maybe idk
> 
> the blocks of the screenshot have been placed by a player, it also happens in the bridge with the blue and red clay blocks, i said the arena partially dont reset, but i think the arena completely dont reset. but @GoodestEnglish, i have a guess, test if it only ocurrs if the player has op in the server, maybe its the problem and can be fixed or not, if this is the problem and cant be fixed, ill just fix the permissions of admin and mod and dont use op

Do you have your lobby and arena in a separate world
