### ISSUE TITLE
in queue message do not exist

### ISSUE THREAD

**Issue by dndesi** [diamond-rip/Eden#283]
Fix the message that appears "You need to be in a lobby to send duel requests", because the player is actually in the lobby, but is in queue, or directly don't show the menu and send the message directly.
![ex](https://user-images.githubusercontent.com/51547832/236694469-78eebf0e-d12c-4b37-acf6-c935d8801fcd.gif)

**Comment by GoodestEnglish** [comment]
Every message is in language.yml.
