### ISSUE TITLE
is it possible for you to make like, a optional /lobby command?

### ISSUE THREAD

**Issue by serumanooo** [diamond-rip/Eden#284]
because all these /lobby plugins are made for bungeecord i think, so when i use on a common multi world server, the player just get teleported to the lobby like if he still is in the match, with all the match items (or im just dumb and dont know how to use it, but i think i have installed these plugins properly)

 so, if you make a /lobby that works different, like, it doesnt just tp for the player for another world location, when the player do /lobby, it would execute a cmd /kill command and then teleport to the lobby, i think this would work because the player got killed, so i dont think the issue i mentionated would happen (im just a common user here, i dont even know if thats possible, i dont create plugins, but i think this should work)
 and i said to make this optional because like, if someone want to use bungeecord and use a lobby plugin, eden /lobby could be incompatible with it, so it could cause errors

its just a suggestion, i dont even know what im talking about, just tell me if its possible

**Comment by serumanooo** [comment]
and im quite new at minecraft server creation so, i have seen a little bit about databases, and eden uses mongodb, right?
idk if its a dumb or useless thing but i have seen that the "most used" (at least i think it is) database is mysql, do you think it would be a good idea do add mysql support?

**Comment by Chromaah** [comment]
a simple thing for just /lobby by killing then teleporting wont work. It would be better to end the match. Why you ask? what about bridge games? or games with multiple points/goals? when doing /lobby it would kill them repeatedly and not end the match. Also, MySQL wouldn't be worth it because of reasons. MongoDB is the best for this, and it should stay like it. (also MySQL would be very hard to implement). And BTW, mysql and mongodb are not the same thing.

**Comment by Chromaah** [comment]
yep, something like that is definitely possible in the code, and im looking forward for GoodestEnglish to add this functionality. (aliases like /l, /leave, /hub, /forfeit would be nice as well).

**Comment by GoodestEnglish** [comment]
So you guys want a /leave command for player who can leave the match instantly right? Sure. But it will take a while.

**Comment by GoodestEnglish** [comment]
> because all these /lobby plugins are made for bungeecord i think, so when i use on a common multi world server, the player just get teleported to the lobby like if he still is in the match, with all the match items (or im just dumb and dont know how to use it, but i think i have installed these plugins properly)
> 
> so, if you make a /lobby that works different, like, it doesnt just tp for the player for another world location, when the player do /lobby, it would execute a cmd /kill command and then teleport to the lobby, i think this would work because the player got killed, so i dont think the issue i mentionated would happen (im just a common user here, i dont even know if thats possible, i dont create plugins, but i think this should work) and i said to make this optional because like, if someone want to use bungeecord and use a lobby plugin, eden /lobby could be incompatible with it, so it could cause errors
> 
> its just a suggestion, i dont even know what im talking about, just tell me if its possible

Also, it is better to make everything in a single world if it is a practice server. This avoid 'dirt screen' and popular servers like MMC does it too.

**Comment by serumanooo** [comment]
> > because all these /lobby plugins are made for bungeecord i think, so when i use on a common multi world server, the player just get teleported to the lobby like if he still is in the match, with all the match items (or im just dumb and dont know how to use it, but i think i have installed these plugins properly)
> > so, if you make a /lobby that works different, like, it doesnt just tp for the player for another world location, when the player do /lobby, it would execute a cmd /kill command and then teleport to the lobby, i think this would work because the player got killed, so i dont think the issue i mentionated would happen (im just a common user here, i dont even know if thats possible, i dont create plugins, but i think this should work) and i said to make this optional because like, if someone want to use bungeecord and use a lobby plugin, eden /lobby could be incompatible with it, so it could cause errors
> > its just a suggestion, i dont even know what im talking about, just tell me if its possible
> 
> Also, it is better to make everything in a single world if it is a practice server. This avoid 'dirt screen' and popular servers like MMC does it too.

yes thats what im doing, but i want to add a separate lobby and more games in the future, so the practice mode and all arenas are all in the same server

**Comment by serumanooo** [comment]
i want to know, do you prefer me to close the issue because you already said you will fix/add something, or just leave it open so you can close when you release an update with the fix?

**Comment by GoodestEnglish** [comment]
Don't close the issue yet. Issue should be close by me at all time.

**Comment by serumanooo** [comment]
> Don't close the issue yet. Issue should be close by me at all time.

ok
