### ISSUE TITLE
Spectator can't see user health

### ISSUE THREAD

**Issue by ushereats** [diamond-rip/Eden#286]
![image](https://user-images.githubusercontent.com/124885227/237030718-518a3bff-d9c1-4dc4-a14e-512177e165c9.png)

**Comment by serumanooo** [comment]
hey, when you /spectate, you can fly without any problem? for me spectators just cant fly

**Comment by Chromaah** [comment]
> hey, when you /spectate, you can fly without any problem? for me spectators just cant fly

same, they are only able to fly if OPPED

**Comment by GoodestEnglish** [comment]
I believe I found what happened for the spectator flying bug (oh my god finally)

Do you guys set the lobby and arena in a seperate world?

**Comment by Chromaah** [comment]
oh yes eactually, I did. I was planning on not doing that to avoid the dirt screen later, but thats what i have right now. Yeah

**Comment by GoodestEnglish** [comment]
> oh yes eactually, I did. I was planning on not doing that to avoid the dirt screen later, but thats what i have right now. Yeah

As of right now, Eden does not support that. I forgot to put it into the wiki, my bad.
After you moved everything into a single world, flying should work.

**Comment by GoodestEnglish** [comment]
Fixed in latest release
