### ISSUE TITLE
Pearls

### ISSUE THREAD

**Issue by djtheta** [diamond-rip/Eden#290]
Pearls only register 50% of the time. When thrown, sometimes they don't teleport the player at all.

**Comment by GoodestEnglish** [comment]
What spigot are you using?

**Comment by djtheta** [comment]
LightSpigot 8 LITE

**Comment by serumanooo** [comment]
> LightSpigot 8 LITE

i have a question, i never knew what the debug mode of any plugins does, so, what it does?

**Comment by GoodestEnglish** [comment]
> > Investigating this issue rn. Some of the users have experienced this problem but I have been thrown pearl for a day and still cannot reproduce this problem. I tried my best to add some changes in the next update and if you still encounter this problem, please send a video with debug mode on in eden.
> 
> i have a question, i never knew what the debug mode of any plugins does, so, what it does?

It is a feature for Eden which you can set in config.yml. It basically output some messages which allows me to have additional information of the bug.

**Comment by serumanooo** [comment]
> > > Investigating this issue rn. Some of the users have experienced this problem but I have been thrown pearl for a day and still cannot reproduce this problem. I tried my best to add some changes in the next update and if you still encounter this problem, please send a video with debug mode on in eden.
> > 
> > 
> > i have a question, i never knew what the debug mode of any plugins does, so, what it does?
> 
> It is a feature for Eden which you can set in config.yml. It basically output some messages which allows me to have additional information of the bug.

oh ty

**Comment by GoodestEnglish** [comment]
Closing this as of right now. If you still experience this issue, open another issues.
