### ISSUE TITLE
i have a question about mongodb

### ISSUE THREAD

**Issue by serumanooo** [diamond-rip/Eden#293]
i learned how to create a free mongodb host on their official site, and the limit of storage is 512mb, is it sufficient to store a lot of playerdata? idk, i think its a dumb question, but i want to know if it will be sufficient or not

**Comment by GoodestEnglish** [comment]
If your database only contains data from Eden, then 512mb is alright for a small server imo

**Comment by serumanooo** [comment]
> If your database only contains data from Eden, then 512mb is alright for a small server imo

Ok ty, and can you tell me if clevercloud is really free? I tried to create a mongodb in it and i didnt found the free option

**Comment by GoodestEnglish** [comment]
Here's a video from bghd development team explaining clevercloud mongodb https://youtu.be/EwzbShyg00E

**Comment by serumanooo** [comment]
> Here's a video from bghd development team explaining clevercloud mongodb https://youtu.be/EwzbShyg00E

ok tysm

**Comment by serumanooo** [comment]
> > Here's a video from bghd development team explaining clevercloud mongodb https://youtu.be/EwzbShyg00E
> 
> ok tysm

@GoodestEnglish 
![image](https://github.com/diamond-rip/Eden/assets/132185379/5934a85f-68b9-4087-a3b9-cdc7aa9a0345)

i think they removed the free plan, thx anyway, ill keep using the 512mb free plan, i think its sufficient
