### ISSUE TITLE
i have a problem

### ISSUE THREAD

**Issue by serumanooo** [diamond-rip/Eden#294]
like you said, eden does not support multiworlds, and i dont remember if you said you would add support to this
but to fix this, i just copy pasted the lobby in the arenas world, and it should work, but i realized that this cause a problem for me

im using a /fly plugin for vips, and to prevent the players flying in the arenas, i enabled it only in the lobby, and now the lobby is in the arenas world

so what i want to know is: will you add multi world support soon?
(before it was just one or two problems that i could maybe find a fix, but now there is so many, please add this)

**Comment by serumanooo** [comment]
another thing is that im using a antivoid plugin, to prevent the players from falling in the void for eternity

and if i enable this in the arenas world, this could happen: a player falls into the void while in a skywars duel and get teleported to the lobby with his items

**Comment by serumanooo** [comment]
another thing is that i made the tags not show in the arenas world, so you dont see a "OWNER serumano_" when your fighting me, you will just see the player nick as green or red. but now with the lobby in the arenas world, the players dont have the tag in their nicks

**Comment by GoodestEnglish** [comment]
> like you said, eden does not support multiworlds, and i dont remember if you said you would add support to this but to fix this, i just copy pasted the lobby in the arenas world, and it should work, but i realized that this cause a problem for me
> 
> im using a /fly plugin for vips, and to prevent the players flying in the arenas, i enabled it only in the lobby, and now the lobby is in the arenas world
> 
> so what i want to know is: will you add multi world support soon? (before it was just one or two problems that i could maybe find a fix, but now there is so many, please add this)

No as of right now. I realized adding multiworld support would break stuff like flying, and I believe arena didn't get reset is also because of this (not sure, need more testing)

Add complex feature like flying in lobbies should be done by coding a separate plugin by using Eden's API. But if you don't know how to code, I've also considered to code some addon for Eden (like kill effect which is requested by lots of users), but the current majority is to fix known bugs from the plugin.

**Comment by GoodestEnglish** [comment]
> another thing is that im using a antivoid plugin, to prevent the players from falling in the void for eternity
> 
> and if i enable this in the arenas world, this could happen: a player falls into the void while in a skywars duel and get teleported to the lobby with his items

Why do you need an antivoid plugin?

**Comment by GoodestEnglish** [comment]
> another thing is that i made the tags not show in the arenas world, so you dont see a "OWNER serumano_" when your fighting me, you will just see the player nick as green or red. but now with the lobby in the arenas world, the players dont have the tag in their nicks, and i dont want the players to have tags in their names when they are in a match

This could be a feature I add into the plugin, which allows user to customize the nametags when they are in the lobby

**Comment by serumanooo** [comment]
> > like you said, eden does not support multiworlds, and i dont remember if you said you would add support to this but to fix this, i just copy pasted the lobby in the arenas world, and it should work, but i realized that this cause a problem for me
> > im using a /fly plugin for vips, and to prevent the players flying in the arenas, i enabled it only in the lobby, and now the lobby is in the arenas world
> > so what i want to know is: will you add multi world support soon? (before it was just one or two problems that i could maybe find a fix, but now there is so many, please add this)
> 
> No as of right now. I realized adding multiworld support would break stuff like flying, and I believe arena didn't get reset is also because of this (not sure, need more testing)
> 
> Add complex feature like flying in lobbies should be done by coding a separate plugin by using Eden's API. But if you don't know how to code, I've also considered to code some addon for Eden (like kill effect which is requested by lots of users), but the current majority is to fix known bugs from the plugin.

Ok, its good to know you will creato addons in the future

**Comment by serumanooo** [comment]
> > another thing is that im using a antivoid plugin, to prevent the players from falling in the void for eternity
> > and if i enable this in the arenas world, this could happen: a player falls into the void while in a skywars duel and get teleported to the lobby with his items
> 
> Why do you need an antivoid plugin?

Because they fall into the void for eternity

**Comment by serumanooo** [comment]
> > another thing is that i made the tags not show in the arenas world, so you dont see a "OWNER serumano_" when your fighting me, you will just see the player nick as green or red. but now with the lobby in the arenas world, the players dont have the tag in their nicks, and i dont want the players to have tags in their names when they are in a match
> 
> This could be a feature I add into the plugin, which allows user to customize the nametags when they are in the lobby

I think you could do this while you dont do it: idk what is the lobby radius, but make it customizable, and you can add a prefix to the nick of the player while he is in this area, and please make it support luckperms placeholder or placeholderapi, if its possible, so i could just stop using the plugin to change their nametag and just use eden

**Comment by serumanooo** [comment]
> > > another thing is that im using a antivoid plugin, to prevent the players from falling in the void for eternity
> > > and if i enable this in the arenas world, this could happen: a player falls into the void while in a skywars duel and get teleported to the lobby with his items
> > 
> > 
> > Why do you need an antivoid plugin?
> 
> Because they fall into the void for eternity

And i think you could add this also in the lobby area, so they get teleported back to the spawn

**Comment by serumanooo** [comment]
> another thing is that i made the tags not show in the arenas world, so you dont see a "OWNER serumano_" when your fighting me, you will just see the player nick as green or red. but now with the lobby in the arenas world, the players dont have the tag in their nicks, and i dont want the players to have tags in their names when they are in a match

i havent tried this:
![image](https://github.com/diamond-rip/Eden/assets/132185379/564d66d0-cac2-44b7-b36c-e643da50d7c1)
ill try now

**Comment by serumanooo** [comment]
> > another thing is that i made the tags not show in the arenas world, so you dont see a "OWNER serumano_" when your fighting me, you will just see the player nick as green or red. but now with the lobby in the arenas world, the players dont have the tag in their nicks, and i dont want the players to have tags in their names when they are in a match
> 
> i havent tried this: ![image](https://user-images.githubusercontent.com/132185379/237560582-564d66d0-cac2-44b7-b36c-e643da50d7c1.png) ill try now

@GoodestEnglish 
![image](https://github.com/diamond-rip/Eden/assets/132185379/095cb69b-6d22-4628-ba7c-3b9fc3b45b05)
i tried this and everyone in the server got a error like this
![image](https://github.com/diamond-rip/Eden/assets/132185379/34fc58d0-09ea-4e75-9f8f-1d391926fe76)

**Comment by serumanooo** [comment]
> > > another thing is that i made the tags not show in the arenas world, so you dont see a "OWNER serumano_" when your fighting me, you will just see the player nick as green or red. but now with the lobby in the arenas world, the players dont have the tag in their nicks, and i dont want the players to have tags in their names when they are in a match
> > 
> > 
> > i havent tried this: ![image](https://user-images.githubusercontent.com/132185379/237560582-564d66d0-cac2-44b7-b36c-e643da50d7c1.png) ill try now
> 
> @GoodestEnglish ![image](https://user-images.githubusercontent.com/132185379/237562204-095cb69b-6d22-4628-ba7c-3b9fc3b45b05.png) i tried this and everyone in the server got a error like this ![image](https://user-images.githubusercontent.com/132185379/237562247-34fc58d0-09ea-4e75-9f8f-1d391926fe76.png)
![image](https://github.com/diamond-rip/Eden/assets/132185379/a9190a7e-0746-4731-b538-819a389397b9)

**Comment by serumanooo** [comment]
> > > > another thing is that i made the tags not show in the arenas world, so you dont see a "OWNER serumano_" when your fighting me, you will just see the player nick as green or red. but now with the lobby in the arenas world, the players dont have the tag in their nicks, and i dont want the players to have tags in their names when they are in a match
> > > 
> > > 
> > > i havent tried this: ![image](https://user-images.githubusercontent.com/132185379/237560582-564d66d0-cac2-44b7-b36c-e643da50d7c1.png) ill try now
> > 
> > 
> > @GoodestEnglish ![image](https://user-images.githubusercontent.com/132185379/237562204-095cb69b-6d22-4628-ba7c-3b9fc3b45b05.png) i tried this and everyone in the server got a error like this ![image](https://user-images.githubusercontent.com/132185379/237562247-34fc58d0-09ea-4e75-9f8f-1d391926fe76.png)
> > ![image](https://user-images.githubusercontent.com/132185379/237562421-a9190a7e-0746-4731-b538-819a389397b9.png)

**Comment by serumanooo** [comment]
i thought i fixed it, but when another player joined, it happened again for everyone in the server, resulting into a server that no one can enter, we can join just if i restart the server

**Comment by serumanooo** [comment]
> > > > another thing is that i made the tags not show in the arenas world, so you dont see a "OWNER serumano_" when your fighting me, you will just see the player nick as green or red. but now with the lobby in the arenas world, the players dont have the tag in their nicks, and i dont want the players to have tags in their names when they are in a match
> > > 
> > > 
> > > i havent tried this: ![image](https://user-images.githubusercontent.com/132185379/237560582-564d66d0-cac2-44b7-b36c-e643da50d7c1.png) ill try now
> > 
> > 
> > @GoodestEnglish ![image](https://user-images.githubusercontent.com/132185379/237562204-095cb69b-6d22-4628-ba7c-3b9fc3b45b05.png) i tried this and everyone in the server got a error like this ![image](https://user-images.githubusercontent.com/132185379/237562247-34fc58d0-09ea-4e75-9f8f-1d391926fe76.png)
> > ![image](https://user-images.githubusercontent.com/132185379/237562421-a9190a7e-0746-4731-b538-819a389397b9.png)

@GoodestEnglish just mentioning you here in case you havent see this

**Comment by serumanooo** [comment]
fixed it, dont know how
