### ISSUE TITLE
why cant i see the players if i tp them

### ISSUE THREAD

**Issue by serumanooo** [diamond-rip/Eden#296]
i want to see the players when i teleport to them for like, using vanish and spectating suspect players, but i cant see them
![2023-05-11_21 27 20](https://github.com/diamond-rip/Eden/assets/132185379/8be5adb6-f3a1-4e35-957d-7007bc91e19b)

**Comment by GoodestEnglish** [comment]
Because Eden thinks you are in lobby. You cannot just tp to the player because one arena can have multiple fights going on. Currently there's no vanish feature for Eden.

**Comment by serumanooo** [comment]
> Because Eden thinks you are in lobby. You cannot just tp to the player because one arena can have multiple fights going on. Currently there's no vanish feature for Eden.

ok ty, i hope you add it in the future
