### ISSUE TITLE
/duel while in match

### ISSUE THREAD

**Issue by serumanooo** [diamond-rip/Eden#301]
![image](https://github.com/diamond-rip/Eden/assets/132185379/80b93b24-ea32-4d7e-b5b7-b6762aa90f2d)
![image](https://github.com/diamond-rip/Eden/assets/132185379/164f1a24-827c-4cad-bdfa-7d2ec4339c6e)

**Comment by GoodestEnglish** [comment]
Yes but, you wont be able to send a duel request. You can only open the menu.,

**Comment by serumanooo** [comment]
> Yes but, you wont be able to send a duel request. You can only open the menu.,

i know, but it would be better if i cant even open the menu
also, could you fix eden compatibility with citizens?
![image](https://github.com/diamond-rip/Eden/assets/132185379/07c47a22-ebcd-4298-b254-99e0cdeeb1ad)
when i put these two together, my console dont stop receiving spam

**Comment by serumanooo** [comment]
i also mentionated it in another issue, but pls make the match inventory work properly, like, i cant see the inventory of the previous match i had, make it like mmc
![image](https://github.com/diamond-rip/Eden/assets/132185379/a9eab011-102d-4666-807c-72c25a6e0821)
![image](https://github.com/diamond-rip/Eden/assets/132185379/f2d1d5f2-15bd-4966-98b6-95da7e497bf9)
i think each inventory has a expiration time, but they dont replace eachother
also, in minemen i can see the match inventory while in match or a party, not only in lobby, could you make it like that? its so annoying to be in a party or a match and not being able to click on the match inventory

**Comment by serumanooo** [comment]
closed because i made a list
