### ISSUE TITLE
maps still not reseting properly

### ISSUE THREAD

**Issue by serumanooo** [diamond-rip/Eden#302]
i moved the arenas to the same world as the lobby but they still dont work, the worst ones are the bridge maps, like, the uhc maps have some cobblestone or something like this and they full reset most part of the time
but the bridge arenas almos everytime dont reset a single block

i think the possible cause of this problem could be the Y level, considering that i use 0 in most uhc maps, but in the bridge i use like 15-25, because sometimes i copy paste the map too high and dont want the player to wait too much to die

**Comment by serumanooo** [comment]
using the lobby and the arenas in the same world is causing me so much problems, like, i need to change or dont use 5 plugins that i wanted to use because of it
cant you make the spectators able to fly when the arena is in another world? i think thats the only thing eden is not supporting about multiworlds

**Comment by GoodestEnglish** [comment]
There's a lot of reports in issues. I am currently busy rn. I will get back to you in a few days. 

About the fly issues, I will see what I can do with it.

**Comment by endygame** [comment]
This tends to happen whenever the server has been restarted mid-match. It may happen otherwise but that's a good, but annoying measure to practice. I also recommend to turn off auto saving so at least the original arena is used after the start of a new game.

**Comment by serumanooo** [comment]
> This tends to happen whenever the server has been restarted mid-match. It may happen otherwise but that's a good, but annoying measure to practice. I also recommend to turn off auto saving so at least the original arena is used after the start of a new game.

it is off, and the arena used is the new arena with the blocks placed by player in here

**Comment by serumanooo** [comment]
> There's a lot of reports in issues. I am currently busy rn. I will get back to you in a few days.
> 
> About the fly issues, I will see what I can do with it.
> 
> Meanwhile, what plugin do you have?

ok, no problem, take your time
my plugin list
![image](https://github.com/diamond-rip/Eden/assets/132185379/a3f667ac-5a40-4c3e-88a5-80c09e469db6)
![image](https://github.com/diamond-rip/Eden/assets/132185379/63fb3550-ef25-4e3e-b598-1d1ebf688b9d)
![image](https://github.com/diamond-rip/Eden/assets/132185379/fc130f80-fb09-44b2-897f-91e63621e8d1)

the plugins i cant use because of eden non multiworld support is:
simplefly, any plugin of antivoid (because the player would fall in the void while in match and get tp to the lobby), any cosmetics plugin, because the pets would get tp to the match, etc

**Comment by serumanooo** [comment]
closed because i made a list
