### ISSUE TITLE
problem in boxing

### ISSUE THREAD

**Issue by serumanooo** [diamond-rip/Eden#306]
i was testing the anticheat in my server and there was a moment that the anti cheat canceled the hits of the cheater, but this happens (i recreated it with god mode)
https://youtu.be/ToEYT1nVhdg
(i know the hit counter having more than 100 hits happened because he cant hit me, this makes impossible for he to win, but if he was hacking, the anticheat does not cancel all the hits, so he could still win)

**Comment by Chromaah** [comment]
i feel like it would be better to open one big issue about all these bugs.. its a lot lol

**Comment by serumanooo** [comment]
> i feel like it would be better to open one big issue about all these bugs.. its a lot lol

i thought the same, i think im gonna close all and make a big list

**Comment by serumanooo** [comment]
closed because i made a list
