### ISSUE TITLE
list of issues and enhacements

### ISSUE THREAD

**Issue by serumanooo** [diamond-rip/Eden#307]
I made this because i think its better for you to see it all in one when you can

1-** Boxing Problem with blocked hits**
i was testing the anticheat in my server and there was a moment that the anti cheat canceled the hits of the cheater, but this happens (i recreated it with god mode)
https://youtu.be/ToEYT1nVhdg
(i know the hit counter having more than 100 hits happened because he cant hit me, this makes impossible for he to win, but if he was hacking, the anticheat does not cancel all the hits, so he could still win)

**-----------------------------------------------------------------------------------------------------------------------------------------------**

2- **Battle Rush problem with respawn protection**
https://youtu.be/myW3mIj1oAs
players cant hit eachother, and like i said before, please make the respawn time appear on the screen instead of the chat, like, a title
![image](https://github.com/diamond-rip/Eden/assets/132185379/3c145829-6924-4692-b985-18a7dc952b54)
![image](https://github.com/diamond-rip/Eden/assets/132185379/e591ae59-7e4f-4c99-895d-3668442223fd)

**-----------------------------------------------------------------------------------------------------------------------------------------------**

3- **Kit Editor problem**
![image](https://github.com/diamond-rip/Eden/assets/132185379/f77c84f7-f9fc-4472-9f49-1c1129a9b4a5)
bro just made a crafting table for the uhc kit, and also, can you make 2 options?
the first one is to make the player be able to see other players in the lobby
the second one is the same thing, but in the kit editor

im asking for two because i want the players being able to see others in lobby, and also, make the players not able to do this:
https://youtu.be/SIj2FzuSZio
https://youtu.be/VJ6D1WN02y4

**-----------------------------------------------------------------------------------------------------------------------------------------------**

4- **Maps still not reseting properly**
i moved the arenas to the same world as the lobby but they still dont work, the worst ones are the bridge maps, like, the uhc maps have some cobblestone or something like this and they full reset most part of the time
but the bridge arenas almos everytime dont reset a single block

i think the possible cause of this problem could be the Y level, considering that i use 0 in most uhc maps, but in the bridge i use like 15-25, because sometimes i copy paste the map too high and dont want the player to wait too much to die

**using the lobby and the arenas in the same world is causing me so much problems, like, i need to change or dont use 5 plugins that i wanted to use because of it
cant you make the spectators able to fly when the arena is in another world? i think thats the only thing eden is not supporting about multiworlds
(and of course the vanish support)**

the plugins i cant use because of eden non multiworld support is:
simplefly, any plugin of antivoid (because the player would fall in the void while in match and get tp to the lobby), any cosmetics plugin, because the pets would get tp to the match, etc

**PS: if this only happen when the server is restarted mid-match, meanwhile you dont find how to fix it, i think you should add like, a /finishall to finish all the matchs in the server, so i could use /restart after this without messing with the maps**

**-----------------------------------------------------------------------------------------------------------------------------------------------**

5- **/duel while in match**
![image](https://github.com/diamond-rip/Eden/assets/132185379/f07fa1ed-a463-4708-98c9-db704f758e5a)
![image](https://github.com/diamond-rip/Eden/assets/132185379/55931ba1-cdb9-4426-a967-eb5c5b17e3ff)
i know i cant send the duel, but it would be better if i cant even open the menu

**-----------------------------------------------------------------------------------------------------------------------------------------------**

6- **Make the queue menu like minemen**
![image](https://github.com/diamond-rip/Eden/assets/132185379/7b7c71ba-4f99-4fad-911d-fc8e0a1aceab)
![image](https://github.com/diamond-rip/Eden/assets/132185379/de48448c-7f5a-4369-bb04-ed8e47f94532)

**-----------------------------------------------------------------------------------------------------------------------------------------------**

7- **I have a doubt**
 Does eden have a elo reset command? for seasons and things like this, because i want to reset the elo of all playes monthly or something like this

**-----------------------------------------------------------------------------------------------------------------------------------------------**

8- **Cactus problem**
https://youtu.be/w2ezniM20p0
 I want the cactus to break when i put a block at the side of it, i think its eden, because it didnt happen before i started using it

**-----------------------------------------------------------------------------------------------------------------------------------------------**

9- **I keep getting this console error, i THINK its because i have Eden and Citizens, but i dont understand about these cmd errors, can someone explain to me whats causing this?
(it only happens when i have some npcs spawned)

https://pastebin.com/MVBsgni7

**Comment by Chromaah** [comment]
For number 9, i get that error too, but i just ignore it because it doesnt affect anything

**Comment by GoodestEnglish** [comment]
Well, there's a lot of issues. Thanks for reporting all of these. 

I am currently in school right now, so I can only replies to some of the issues you've mentioned. And as I said before, I am currently busy, I have already coded a few fixes in the plugin, just need to push and release. It will come around 1-3 days.



> 1-** Boxing Problem with blocked hits**
> i was testing the anticheat in my server and there was a moment that the anti cheat canceled the hits of the cheater, but this happens (i recreated it with god mode)
> https://youtu.be/ToEYT1nVhdg
> (i know the hit counter having more than 100 hits happened because he cant hit me, this makes impossible for he to win, but if he was hacking, the anticheat does not cancel all the hits, so he could still win)

What anticheat are you using? A good anticheat should cancel hits by using packets. If anticheat uses bukkit events to cancel hits, then the anticheat is not a good anticheat, and I wouldn't recommend to use it.



> 2- **Battle Rush problem with respawn protection**
> https://youtu.be/myW3mIj1oAs
> players cant hit eachother, and like i said before, please make the respawn time appear on the screen instead of the chat, like, a title

Could be a easy feature I can add in the next update. And I will fix it also.



> bro just made a crafting table for the uhc kit, and also, can you make 2 options? the first one is to make the player be able to see other players in the lobby the second one is the same thing, but in the kit editor
> 
> im asking for two because i want the players being able to see others in lobby, and also, make the players not able to do this: https://youtu.be/SIj2FzuSZio https://youtu.be/VJ6D1WN02y4

Will fix it. You can set the player lobby visibility in config.



> 4- **Maps still not reseting properly** i moved the arenas to the same world as the lobby but they still dont work, the worst ones are the bridge maps, like, the uhc maps have some cobblestone or something like this and they full reset most part of the time but the bridge arenas almos everytime dont reset a single block
> 
> i think the possible cause of this problem could be the Y level, considering that i use 0 in most uhc maps, but in the bridge i use like 15-25, because sometimes i copy paste the map too high and dont want the player to wait too much to die
> 
> **using the lobby and the arenas in the same world is causing me so much problems, like, i need to change or dont use 5 plugins that i wanted to use because of it cant you make the spectators able to fly when the arena is in another world? i think thats the only thing eden is not supporting about multiworlds (and of course the vanish support)**
> 
> the plugins i cant use because of eden non multiworld support is: simplefly, any plugin of antivoid (because the player would fall in the void while in match and get tp to the lobby), any cosmetics plugin, because the pets would get tp to the match, etc
> 
> **PS: if this only happen when the server is restarted mid-match, meanwhile you dont find how to fix it, i think you should add like, a /finishall to finish all the matchs in the server, so i could use /restart after this without messing with the maps**

I have to investigate more about this issue. I've tested it a lot of time and I don't have this problem. I am considering to open a test server for public currently so people can try to reproduce issues (and it is easier for me to fix anything)



> i know i cant send the duel, but it would be better if i cant even open the menu

Simple addition which I can add in next update.



> Make the queue menu like minemen

This is heavily requested by a lot of users. But as I said, I do not want to add new features when bugs are still in the plugin. But I can tell you this is planned.



> Does eden have a elo reset command? for seasons and things like this, because i want to reset the elo of all playes monthly or something like this

No, but coming soon.



> I want the cactus to break when i put a block at the side of it, i think its eden, because it didnt happen before i started using it

Yes, it is related to Eden. Fixing this in next update.



> 9- **I keep getting this console error, i THINK its because i have Eden and Citizens, but i dont understand about these cmd errors, can someone explain to me whats causing this?
> (it only happens when i have some npcs spawned)

Yes, this is also related to Eden. This happens when you tries to hit an NPC. Fixing this in next update.

**Comment by serumanooo** [comment]
i have a guess about what is making the arena not reseting properly:
(if thats not the cause, still a bug to be fixed)
![image](https://github.com/diamond-rip/Eden/assets/132185379/33dadff7-a6e9-4a4d-aed7-288c89608d78)

ghost blocks, this happens everytime in battlerush, because the arena resets when a player hits a point, the blocks arent real, they disappear when the player break it or put a block at the side of it, but maybe this is happening:
when the server restarts, the ghost blocks that are in the arena turn into real blocks, so now it is part of the arena
i think this could be the cause because i cant see if there is ghost blocks in uhc or the bridge, because the arena resets just after the match ends

also, i want to mentionate some issues that i have reported, just so you dont forget it (sorry if you already fixed it and i dont remember):
the cobblestone created with lava and water and the player cant break it
the craft whitelist not working
(ill add more things here if i remember)

**Comment by Chromaah** [comment]
More enchancement:
**10- Portal Goal Enter**
Make it so that in the last goal you need to win, instead of leaving the player in the portal, teleport them back to their spawn point, it will be wayy cleaner imo.

-----------------------------------------------------------------------------------------------------------------------------------------------

**11- Overall/Unranked/Ranked Winstreak Placeholder - KDR Placeholder**
Create a placeholder that will display winstreak overall, or overall for a certain mode (RANKED/UNRANKED) instead of just per-kit, also thoughts on kdr placeholder?

-----------------------------------------------------------------------------------------------------------------------------------------------

There were some more but i completely forgot them so ill probably post them later

**Comment by GoodestEnglish** [comment]
Can you send the error in txt file format here? The link you've sent related to citizens and Eden is broken. @serumanooo

**Comment by serumanooo** [comment]
> Can you send the error in txt file format here? The link you've sent related to citizens and Eden is broken. @serumanooo

ok ill do it

**Comment by serumanooo** [comment]
> For number 9, i get that error too, but i just ignore it because it doesnt affect anything

i mentionated it because it was spamming the console

**Comment by serumanooo** [comment]
**12 - Small bug when the match ends**
 I tried to reproduce the bug but i could not, this is what happens: when the player wins (if i remember it happens also in modes that have point system off) the loser gets insta teleported to the lobby instead of the title saying "you lose", it happened so many times but i dont know whats the cause, maybe its a random thing

ill not post the video trying to reproduce it here because like i said, i could not make the bug happen, but a thing happened, i dont think its eden fault and its just a bug of minecraft or something like this that i dont need to worry about, when the battle rush match started, the enemy player could not see me until i died
i dont think its eden fault because its the first time it happened, if it persist ill make a new commend here

**Comment by serumanooo** [comment]
**13 - The cactus nos is breakable by blocks, but the arena does not despawn the dropped item**
![image](https://github.com/diamond-rip/Eden/assets/132185379/59c1812c-1ff5-4b75-b508-119142850e26)

**Comment by serumanooo** [comment]
**14 - Can you make the bow damage alert optional?**
 I dont particularly like this
![image](https://github.com/diamond-rip/Eden/assets/132185379/4813e5d7-b432-4e00-b050-4dad68ba09e9)

**Comment by GoodestEnglish** [comment]
Do you still encounter the arena does not reset error?

**Comment by Chromaah** [comment]
**More enchancement:**

**15- Team Colors**
Kits that have Point System, portal goal, bed, etc (any option that adds teams) enabled, like bridge, battlerush, bedfight, etc have death messages according to the team color instead of enemies.

For example, instead of &aChromaah killed &cEnemy in games with point system, portal goal, bed, etc. (any option that adds teams) have it be the color of their team:

&cChromaah killed &9Enemy
(If Chromaah was on red team, and Enemy was on blue team)

**Comment by Chromaah** [comment]
> **14 - Can you make the bow damage alert optional?** I dont particularly like this

You can edit that message, thats what i did.

**Comment by GoodestEnglish** [comment]
> > Can you send the error in txt file format here? The link you've sent related to citizens and Eden is broken. @serumanooo
> 
> ok ill do it here it is: [latest.log](https://github.com/diamond-rip/Eden/files/11511139/latest.log)

Thanks for sending it. I will have a look into it soon.

Meanwhile, now I also know why your's arena doesn't reset. One of your arena has some problem which related to signs in chunk coordinates -2016,32. Try to reset that arena or remove the signs. 

In minecraft, there's something called tile entity, means a block which contains data a normal shouldn't have. For example, sign, chests, player head. Those are not recommended in.a practice server.

Also, I saw you have a lot of error in your console. I would recommend to fix all of those. And you should report all errors which related to Eden to me, since it might be very important.

**Comment by serumanooo** [comment]
> Do you still encounter the arena does not reset error?

not yet

**Comment by serumanooo** [comment]
> > > Can you send the error in txt file format here? The link you've sent related to citizens and Eden is broken. @serumanooo
> > 
> > 
> > ok ill do it here it is: [latest.log](https://github.com/diamond-rip/Eden/files/11511139/latest.log)
> 
> Thanks for sending it. I will have a look into it soon.
> 
> Meanwhile, now I also know why your's arena doesn't reset. One of your arena has some problem which related to signs in chunk coordinates -2016,32. Try to reset that arena or remove the signs.
> 
> In minecraft, there's something called tile entity, means a block which contains data a normal shouldn't have. For example, sign, chests, player head. Those are not recommended in.a practice server.
> 
> Also, I saw you have a lot of error in your console. I would recommend to fix all of those. And you should report all errors which related to Eden to me, since it might be very important.
> 
> Edit: Here's the coordinate for the problem (-2028,29,32). If the error still occurs, you might have to reset the whole world.

ohhh ok

**Comment by serumanooo** [comment]
> > **14 - Can you make the bow damage alert optional?** I dont particularly like this
> 
> You can edit that message, thats what i did.

sorry, ill do that the next time

**Comment by serumanooo** [comment]
> **12 - Small bug when the match ends** I tried to reproduce the bug but i could not, this is what happens: when the player wins (if i remember it happens also in modes that have point system off) the loser gets insta teleported to the lobby instead of the title saying "you lose", it happened so many times but i dont know whats the cause, maybe its a random thing
> 
> ill not post the video trying to reproduce it here because like i said, i could not make the bug happen, but a thing happened, i dont think its eden fault and its just a bug of minecraft or something like this that i dont need to worry about, when the battle rush match started, the enemy player could not see me until i died i dont think its eden fault because its the first time it happened, if it persist ill make a new commend here
> 
> **-----------------------------------------------------------------------------------------------------------------------------------------------**
> 
> **13 - The cactus nos is breakable by blocks, but the arena does not despawn the dropped item** ![image](https://user-images.githubusercontent.com/132185379/239623504-dccb738b-21cd-4650-b388-34552057ac1a.png)
> 
> **-----------------------------------------------------------------------------------------------------------------------------------------------**
> 
> **14 - Can you make the bow damage alert optional?** I dont particularly like this ![image](https://user-images.githubusercontent.com/132185379/239623658-ccb921e8-e461-4458-b35a-a798a52d5d6f.png)
> 
> **-----------------------------------------------------------------------------------------------------------------------------------------------**
> 
> **15 - Can you make the solo match and party match prefixes separately?** Because i would like the players to have white nametags when in solo match, and green and red nametags when they are in team match ![image](https://user-images.githubusercontent.com/132185379/239623970-3ffb1cdb-7472-4a3f-91a2-0629b8f70892.png) ![image](https://user-images.githubusercontent.com/132185379/239623938-8d024bbf-c2ae-490c-9594-9412406b4074.png)

 **-----------------------------------------------------------------------------------------------------------------------------------------------**

**16 - Instant death**

 The instant death when the player pass the arena limit is terrible for the players, but its good to spectators, because this prevents the spectator to explore the map while flying

 So here is my idea: make a new option just for spectators, and when they try to go further out of the arena limit they get tp back to the spectator location 
(make it like 30-35 blocks larger on each side of the real arena limit, make it a really big area, or make this limit configurable in the config.yml [i personally prefer the configurable limit because i can see whats better for my arenas])

**Comment by serumanooo** [comment]
**12 - Small bug when the match ends**
 I tried to reproduce the bug but i could not, this is what happens: when the player wins (if i remember it happens also in modes that have point system off) the loser gets insta teleported to the lobby instead of the title saying "you lose", it happened so many times but i dont know whats the cause, maybe its a random thing

ill not post the video trying to reproduce it here because like i said, i could not make the bug happen, but a thing happened, i dont think its eden fault and its just a bug of minecraft or something like this that i dont need to worry about, when the battle rush match started, the enemy player could not see me until i died
i dont think its eden fault because its the first time it happened, if it persist ill make a new commend here

**-----------------------------------------------------------------------------------------------------------------------------------------------**

**13 - The cactus nos is breakable by blocks, but the arena does not despawn the dropped item**
![image](https://github.com/diamond-rip/Eden/assets/132185379/dccb738b-21cd-4650-b388-34552057ac1a)

**-----------------------------------------------------------------------------------------------------------------------------------------------**

**14 - Can you make the bow damage alert optional?**
 I dont particularly like this
![image](https://github.com/diamond-rip/Eden/assets/132185379/ccb921e8-e461-4458-b35a-a798a52d5d6f)

**-----------------------------------------------------------------------------------------------------------------------------------------------**

**15 - Can you make the solo match and party match prefixes separately?**
Because i would like the players to have white nametags when in solo match, and green and red nametags when they are in team match
![image](https://github.com/diamond-rip/Eden/assets/132185379/3ffb1cdb-7472-4a3f-91a2-0629b8f70892)
![image](https://github.com/diamond-rip/Eden/assets/132185379/8d024bbf-c2ae-490c-9594-9412406b4074)

 **-----------------------------------------------------------------------------------------------------------------------------------------------**

**16 - Instant death**

 The instant death when the player pass the arena limit is terrible for the players, but its good to spectators, because this prevents the spectator to explore the map while flying

 So here is my idea: make a new option just for spectators, and when they try to go further out of the arena limit they get tp back to the spectator location 
(make it like 30-35 blocks larger on each side of the real arena limit, make it a really big area, or make this limit configurable in the config.yml [i personally prefer the configurable limit because i can see whats better for my arenas])

(without this i need to set areas with worldguard on every arena, it would be easier if you add that)

 **-----------------------------------------------------------------------------------------------------------------------------------------------**

**17 - pls, as soon as its possible, add multiworld support**

**Comment by Chromaah** [comment]
for 15, pleaaasee dont do that, i dont like it xD

for 16, i dont like the instant death if you leave the arena limit either, i think it should be after 5 seconds or so..

**Comment by Chromaah** [comment]
Also, GoodestEnglish, can you add a team placeholder or a placeholder that displays the color of the team they r in, or green and red for the enemy

**Comment by serumanooo** [comment]
> for 15, pleaaasee dont do that, i dont like it xD Edit: just realised you said add, so they can be different, thats fine, i agree
> 
> for 16, i dont like the instant death if you leave the arena limit either, i think it should be after 5 seconds or so..

ill reformulate the 16

**Comment by serumanooo** [comment]
> Also, GoodestEnglish, can you add a team placeholder or a placeholder that displays the color of the team they r in, or green and red for the enemy

GoodestEnglish, does eden have a placeholder list? if no, you should create one

**Comment by GoodestEnglish** [comment]
> > Also, GoodestEnglish, can you add a team placeholder or a placeholder that displays the color of the team they r in, or green and red for the enemy
> 
> GoodestEnglish, does eden have a placeholder list? if no, you should create one

Yes, in here: https://github.com/diamond-rip/Eden/wiki/Placeholders

**Comment by GoodestEnglish** [comment]
> **12 - Small bug when the match ends** I tried to reproduce the bug but i could not, this is what happens: when the player wins (if i remember it happens also in modes that have point system off) the loser gets insta teleported to the lobby instead of the title saying "you lose", it happened so many times but i dont know whats the cause, maybe its a random thing
> 
> ill not post the video trying to reproduce it here because like i said, i could not make the bug happen, but a thing happened, i dont think its eden fault and its just a bug of minecraft or something like this that i dont need to worry about, when the battle rush match started, the enemy player could not see me until i died i dont think its eden fault because its the first time it happened, if it persist ill make a new commend here
> 
> **-----------------------------------------------------------------------------------------------------------------------------------------------**
> 
> **13 - The cactus nos is breakable by blocks, but the arena does not despawn the dropped item** ![image](https://user-images.githubusercontent.com/132185379/239623504-dccb738b-21cd-4650-b388-34552057ac1a.png)
> 
> **-----------------------------------------------------------------------------------------------------------------------------------------------**
> 
> **14 - Can you make the bow damage alert optional?** I dont particularly like this ![image](https://user-images.githubusercontent.com/132185379/239623658-ccb921e8-e461-4458-b35a-a798a52d5d6f.png)
> 
> **-----------------------------------------------------------------------------------------------------------------------------------------------**
> 
> **15 - Can you make the solo match and party match prefixes separately?** Because i would like the players to have white nametags when in solo match, and green and red nametags when they are in team match ![image](https://user-images.githubusercontent.com/132185379/239623970-3ffb1cdb-7472-4a3f-91a2-0629b8f70892.png) ![image](https://user-images.githubusercontent.com/132185379/239623938-8d024bbf-c2ae-490c-9594-9412406b4074.png)
> 
> **-----------------------------------------------------------------------------------------------------------------------------------------------**
> 
> **16 - Instant death**
> 
> The instant death when the player pass the arena limit is terrible for the players, but its good to spectators, because this prevents the spectator to explore the map while flying
> 
> So here is my idea: make a new option just for spectators, and when they try to go further out of the arena limit they get tp back to the spectator location (make it like 30-35 blocks larger on each side of the real arena limit, make it a really big area, or make this limit configurable in the config.yml [i personally prefer the configurable limit because i can see whats better for my arenas])
> 
> (without this i need to set areas with worldguard on every arena, it would be easier if you add that)
> 
> **-----------------------------------------------------------------------------------------------------------------------------------------------**
> 
> **17 - pls, as soon as its possible, add multiworld support**
> 
> **-----------------------------------------------------------------------------------------------------------------------------------------------**
> 
> **18 - Victory title when someone /leave or /giveup**
> 
> ![image](https://user-images.githubusercontent.com/132185379/239653189-b5d6145e-1171-4e4e-a3b7-770f978f71d9.png)
> 
> **-----------------------------------------------------------------------------------------------------------------------------------------------**
> 
> **19 - If i activate the drop items option, to make the player drop his inventory when he dies, in bedfight ALL the deaths drop items even if the bed isnt broken**
> 
> **-----------------------------------------------------------------------------------------------------------------------------------------------**
> 
> **20 - Pls make the post match inventory have a historic, because its so annoying not being able to see the previous inventory because the last one override it**
> 
> **-----------------------------------------------------------------------------------------------------------------------------------------------**
> 
> **21 - Also, idk if its Eden fault but the players dont have optifine capes, i think its because of the prefix system, its like my nick isnt "serumano_" the server recognize it as "Owner serumano_"
> 
> **-----------------------------------------------------------------------------------------------------------------------------------------------**
> 
> **22- Help pls**
> 
> Idk what is happening, i just cant save the last arena i made I made like, 10 arenas in a row, and only one didnt save, i thought it could be a bug that does not let me save a arena if i dont save another one But i discovered that it just dont work (the first time it happened, there wasnt a arena there, just air, so i copypasted a arena here, tried to change the ground and then it happens like i show in the video)
> 
> https://youtu.be/mj4-oL3nQys (without saving a new arena) https://youtu.be/dHLblYKbF5Q (with new arena) (i have no errors in console)
> 
> maybe its something about the quantity of arenas that i made? (i have 77 arenas, the arena that is not saving is the number 76, the arena 77 also does not save as i showed in the video) (sorry about the quality of the videos, my pc and a toaster can be considered the same thing)

16 - You can disable instant death in config.
18 - It is normal. Because /giveup actually means the player giveup, so it counts as a win.
19 - Because drop items literally means drop items xd. It drops all your items. Normally in bedfight, you should disable this.
20 - Coming soon. Yes I said coming soon a lot of time but there's a lot of suggestions and enhancement. I might start not accepting other suggestions from now on.
21 - No, it is not a Eden problem.
22 - Because your world didn't save. Use `/save-all` after edit a world.

**Comment by serumanooo** [comment]
> 16 - You can disable instant death in config.
18 - It is normal. Because /giveup actually means the player giveup, so it counts as a win.
19 - Because drop items literally means drop items xd. It drops all your items. Normally in bedfight, you should disable this.
20 - Coming soon. Yes I said coming soon a lot of time but there's a lot of suggestions and enhancement. I might start not accepting other suggestions from now on.
21 - No, it is not a Eden problem.
22 - Because your world didn't save. Use /save-all after edit a world.

---------------------------------------

16- it is disabled, what i am saying is: if its off, the spectators can fly and explore the entire world, so it would be cool if they couldnt, because there is arenas that dont have barriers, like the bridge, bedfight, battlerush

17- oh ok

19- yes i know, but it would be good if it only drop items after the real death, like in minemen

20- ok ok, i mentionated it because i completely forgot about some suggestions, so i wrote it here before i forgot, ill not mentionate it anymore

22- I tried /arena saveall, or is /save-all a different command? idk, ill try later, but if it isnt, i already tried this

**Comment by Chromaah** [comment]
For 22, /save-all is a built in minecraft command i believe, it saves the worlds itself

And for the last thing, I cant find where to change the color of the names either, i dont think its a thing

**Comment by serumanooo** [comment]
> For 22, /save-all is a built in minecraft command i believe, it saves the worlds itself
> 
> And for the last thing, I cant find where to change the color of the names either, i dont think its a thing

thats weird, because i can change the colors in a solo match

**Comment by serumanooo** [comment]
a small bug here:
![image](https://github.com/diamond-rip/Eden/assets/132185379/4d11c23c-5f29-456f-ae6a-20861e6aa61c)
i can send a party to a player that already is in a party

(ill not add more issues to that list, ill make a new one when i discover like, 5 more issues)

**Comment by GoodestEnglish** [comment]
The list is getting bigger and bigger which makes me very hard to read the message history. From now on please make one issue for each bug. Spamming issue isn't the problem.

I've fixed most of the bug in this list. If there's something I missed, please open another issue and say it again, I am sorry if I missed something.

For enhancement, yes you can still suggest but please limit the amount of enhancement so I can add some very-long planned feature like match history.

**Comment by serumanooo** [comment]
> The list is getting bigger and bigger which makes me very hard to read the message history. From now on please make one issue for each bug. Spamming issue isn't the problem.
> 
> I've fixed most of the bug in this list. If there's something I missed, please open another issue and say it again, I am sorry if I missed something.
> 
> For enhancement, yes you can still suggest but please limit the amount of enhancement so I can add some very-long planned feature like match history.

@GoodestEnglish yeah, i stopped adding things here, it was so confusing even for me, ill make separate issues now, if i need to do a list ill limit at 5 thigs or less
