### ISSUE TITLE
Bugs and some suggestions

### ISSUE THREAD

**Issue by lenstyy** [diamond-rip/Eden#308]
So here are the bugs I found:
1. Book bug: Before the match starts you can take the book from hotbar and wait before kit takes (the book won't be removed) Here's the video: https://www.youtube.com/watch?v=zjx136HBNDc

2. Sometimes when you use ender pearl, it doesn't being thrown, but the cooldown applies.
3. Sometimes players don't get teleported on arena.
4. I don't know why, but in leaderboards kits are randomly placed. Would be great if it was as like in queue kit selection.

Also some suggestions:
1. Make /l (/leave) command to leave from game and teleport to spawn
2. Make GUI selection like on MMC
3. And please, make in config so that we can disable/enable lightning (it ruins death effects)

**Comment by Chromaah** [comment]
for suggestion 3, like i said before, I think it'd be better to wait until you can add custom commands to the lobby items, so that you can make your own menu, I have a nice and clean menu, but cant use it because the sword wont open by executing the open menu command

**Comment by GoodestEnglish** [comment]
I've never received a bug report about player didn't get tped into arena. May I get more details about this issue, perfectly a video?

The kit in leaderboard is sorted, well, at least in my perspective and in my testing. Have you setup the kit priority? The kit priority is used in this scenario.

**Comment by GoodestEnglish** [comment]
I am also doing more testing about enderpearl issue. But the others should be coming soon, except for gui creation (but it will come soon)

**Comment by Chromaah** [comment]
by gui creation, do you mean lobby item commands? xD

**Comment by GoodestEnglish** [comment]
> by gui creation, do you mean lobby item commands? xD

Half right. Because I want to let user to customize the queue menu with things like item amount which delexemenu cannot be done. This is a huge upgrade if I am doing it, so it will takes some time.

Meanwhile, lobby item commands are coming soon.

**Comment by Chromaah** [comment]
and thats why deluxe menus is garbage, for a gui plugin, i recommend BetterGUI
