### ISSUE TITLE
How to connect a mysql database to eden?

### ISSUE THREAD

**Issue by miguelYT1** [diamond-rip/Eden#309]
mongo:
  enabled: true
  uri-mode: false
  normal:
    host: 15.2*****
    port: 3306
    auth:
      enabled: true
      username: ' '
      password: ' '
  uri:
    database: database
    connection-string: mongodb://127.0.0.1:27017/Eden

**Comment by Chromaah** [comment]
eden doesnt support mysql databases.

mongodb and mysql are NOT the same thing!!!!

Eden wont be supporting mysql anytime soon.
