### ISSUE TITLE
cPractice

### ISSUE THREAD

**Issue by HierarchyMan** [diamond-rip/Eden#31]
cPractice isn't very good but it has a few good open source features you could add

https://github.com/tehShifu/Practice

Like glass pane kit selection gui
A better kit editor (gui)
better tablist
events (some)
And possibly a few more good things 

And it's open src and I have given the link to you

**Comment by RealGoodestEnglish** [comment]
These are what I want to do in the future of Eden's updates. But those requires time so I don't have a estimated time for it.

**Comment by RealGoodestEnglish** [comment]
Just want to clarify that open source doesn't mean I can completely copy other project's source code, especially Eden is a open source project and requires to give credit to other resources, also cPractice doesn't have a license.

**Comment by Elb1to** [comment]
> Just want to clarify that open source doesn't mean I can completely copy other project's source code, especially Eden is a open source project and requires to give credit to other resources, also cPractice doesn't have a license.

Adding into this, I wouldn't recommend using any of cPractice's "code", cuz it's just skidded Yang (Ziue renamed it to cPractice) and stole code from Frost's menus, player settings, ffa system

**Comment by HierarchyMan** [comment]
Oh I didn't know that srry
