### ISSUE TITLE
fawe and worldedit

### ISSUE THREAD

**Issue by TehJays** [diamond-rip/Eden#310]
can someone give me the right fawe and worldedit version? my server keeps crashing cuz of fawe error please help me out. Thanks!

**Comment by TehJays** [comment]
https://pastebin.com/UzXb2Yt6

**Comment by GoodestEnglish** [comment]
https://drive.google.com/file/d/1NFjiRHj_pmB7XnPbSGQLICssNXE3Dd5T/view?usp=share_link

**Comment by TehJays** [comment]
> https://drive.google.com/file/d/1NFjiRHj_pmB7XnPbSGQLICssNXE3Dd5T/view?usp=share_link

i still get the same error

**Comment by GoodestEnglish** [comment]
> > https://drive.google.com/file/d/1NFjiRHj_pmB7XnPbSGQLICssNXE3Dd5T/view?usp=share_link
> 
> i still get the same error

Use java 8, you are using other java version

**Comment by TehJays** [comment]
Alright i updated the version but roght after i did i got this mongo error related to eden

https://pastebin.com/KEsL9L1q

**Comment by GoodestEnglish** [comment]
> Alright i updated the version but roght after i did i got this mongo error related to eden
> 
> https://pastebin.com/KEsL9L1q

Authentication failed - Means you set your mongodb user/password wrong.

**Comment by TehJays** [comment]
ah alright, thanks for the help broski
