### ISSUE TITLE
Non-op players can't build

### ISSUE THREAD

**Issue by lenstyy** [diamond-rip/Eden#311]
I'm trying to make BedFight, but non-op players can't place blocks everywhere. For example, they can place blocks on some parts of their island, but can't do that on another or to bridge to another player which is weird. I don't have any plugins that can prevent players from building too, so I thought it's the plugin's side

**Comment by serumanooo** [comment]
> I'm trying to make BedFight, but non-op players can't place blocks everywhere. For example, they can place blocks on some parts of their island, but can't do that on another or to bridge to another player which is weird. I don't have any plugins that can prevent players from building too, so I thought it's the plugin's side

whats your build limit and minimum/maximum location?

**Comment by Chromaah** [comment]
> I'm trying to make BedFight, but non-op players can't place blocks everywhere. For example, they can place blocks on some parts of their island, but can't do that on another or to bridge to another player which is weird. I don't have any plugins that can prevent players from building too, so I thought it's the plugin's side

check your `spawn-protection` in server.properties
 default is 16, change it to 0 to disable it

**Comment by lenstyy** [comment]
> > I'm trying to make BedFight, but non-op players can't place blocks everywhere. For example, they can place blocks on some parts of their island, but can't do that on another or to bridge to another player which is weird. I don't have any plugins that can prevent players from building too, so I thought it's the plugin's side
> 
> check your `spawn-protection` in server.properties default is 16, change it to 0 to disable it

Thanks a lot, it helped me
