### ISSUE TITLE
make the golden head like minemen

### ISSUE THREAD

**Issue by serumanooo** [diamond-rip/Eden#314]
pls make the golden head like minemen or add a minemen golden head option

eden head:
https://youtu.be/zQLlmh81BXQ

minemen head:
https://youtu.be/GBNx-9TLKGo

**Comment by serumanooo** [comment]
and pls, add aliases to the /party and /p option

with eden, i need to:
create the party
do /party invite <nick>

in minemen i just need to do /party <nick> and it automatically create the party and invite the player

**Comment by GoodestEnglish** [comment]
> pls make the golden head like minemen or add a minemen golden head option
> 
> eden head: https://youtu.be/zQLlmh81BXQ
> 
> minemen head: https://youtu.be/GBNx-9TLKGo

Making an option to let user to control what effect should golden head gives to player

**Comment by GoodestEnglish** [comment]
Added
