### ISSUE TITLE
the maps are still not reseting

### ISSUE THREAD

**Issue by serumanooo** [diamond-rip/Eden#316]
![image](https://github.com/diamond-rip/Eden/assets/132185379/1cf8b153-acf3-4cab-8989-1b759d6ee3ca)

i still think its something with the world saving
yes, i have this enabled
![image](https://github.com/diamond-rip/Eden/assets/132185379/5a377c97-815e-4187-81df-f77ba0770479)
and im trying to do this for saving maps and world: restart the server; do /save-all, restart again
with this i thought the arenas were reseting properly, but i think i have a solution to this

it is related to the world saving, so disabling the world save might fix it, but i forgot to do what i said above one time, and now i have to check 50 maps for blocks placed by player, here is what i think:

eden just reset the arena if another match is queued at this arena, so if i just stop the server without someone using this arena again, the world will save with the blocks placed by the players (thats why i was restarting the server before saving the world)

**so here is my solution (im assuming thats the cause)**
eden should reset the arena some seconds after the match is finished, so there will not be any blocks placed by players
-------------------------------------------------------

in battlerush, im getting so many ghost blocks at the build limit, idk if its eden fault or maybe its related to paper spigot or minecraft
i want to see if the ghost blocks stop appearing if i change the spigot fork, can someone tell me a good one?

**Comment by lenstyy** [comment]
+1

**Comment by serumanooo** [comment]
> Arena cache saves in memory, meaning it will not save in a file format. So the idea you've provided is not possible. You should only use /save-all when you are 100% sure there's no one playing on your server. Modify arena when player is online is a very bad habit. The arena system will most likely not going to change due to most of the server is now using this method.
> 
> About ghost block, since I use NMS to set block to air for a better performance, I will make an option to let server owner to choose if they want to use NMS or bukkit to set the block to air. Alternatively, I saw this plugin before, you can give it a try (UNTESTED, not sure if it works or not: https://www.spigotmc.org/resources/solidfix.54103/)

oh ok, ill try this plugin
and ill just edit the arenas when there is no one at the server
