### ISSUE TITLE
Hunger Bar Change Stuck At Full

### ISSUE THREAD

**Issue by ABIGDachshunch** [diamond-rip/Eden#32]
Hunger Bar Change Stuck At Full
![2023-01-01_06 13 24](https://user-images.githubusercontent.com/120037725/210157356-47fa805a-70ac-4e9e-80e4-6b31e887b77d.png)

**Comment by ABIGDachshunch** [comment]
i set diffucult at normal too

**Comment by RealGoodestEnglish** [comment]
What plugins do you have?
Also, I would recommend to set difficulty to Hard since almost all practice servers set their difficulty to hard.

**Comment by ABIGDachshunch** [comment]
> What plugins do you have? Also, I would recommend to set difficulty to Hard since almost all practice servers set their difficulty to hard.
![Capture](https://user-images.githubusercontent.com/120037725/210164626-40fb2f3a-f878-4526-a172-687708d7cc6a.PNG)
i checked all my settings there is nothing make that problem
'

**Comment by ABIGDachshunch** [comment]
this practice is very good and stable so i hope youll fix it in the  next update****

**Comment by HierarchyMan** [comment]
yeah hunger doesnt deplete for me 2

**Comment by RealGoodestEnglish** [comment]
Fixed in https://github.com/diamond-rip/Eden/releases/tag/1.0.20-BETA-a2aa8c0
