### ISSUE TITLE
does eden support match time limit?

### ISSUE THREAD

**Issue by serumanooo** [diamond-rip/Eden#322]
it would be good in the bridge and other modes, because people loves to pass hours in the match doing everything but finishing the match, so it ocuppies the arena

**Comment by MuriloFangel** [comment]
a custom time limit would be nice, when time is over the match ends and the win goes to the player with most points or just draw if it's the same points (bridges or point related kits)

**Comment by GoodestEnglish** [comment]
Currently no. But can be a feature I can consider afterwards
