### ISSUE TITLE
error in console, idk if its because i changed the spigot im using

### ISSUE THREAD

**Issue by serumanooo** [diamond-rip/Eden#323]
![image](https://github.com/diamond-rip/Eden/assets/132185379/29be0597-306a-4a52-b384-f68b567ec272)
its the only error, so i dont think i need to post the log here

**Comment by HierarchyMan** [comment]
If you don't get this error with normal paper, then it's 100% cuz of the new spigot
Many custom spigots make spigotmc their base instead of papermc which leads to missing events

**Comment by serumanooo** [comment]
> If you don't get this error with normal paper, then it's 100% cuz of the new spigot Many custom spigots make spigotmc their base instead of papermc which leads to missing events

if im right, carbon spigot is a fork of taco spigot, that is a fork of paper spigot

**Comment by GoodestEnglish** [comment]
It is an error from my side. Fixing this in next update.

**Comment by GoodestEnglish** [comment]
Closing this because it is mentioned in #326
