### ISSUE TITLE
does the eden tablist put the players in alphabetical order?

### ISSUE THREAD

**Issue by serumanooo** [diamond-rip/Eden#324]
![image](https://github.com/diamond-rip/Eden/assets/132185379/a9936cac-40e8-482c-a97d-e04f934ec129)
here i have 2 players with a S so its right, but like, a player with a M joins and he is after us

also, sometimes the tablist just break, something like this:
(imagine the red lines are player nicks)
![image](https://github.com/diamond-rip/Eden/assets/132185379/abfc01a1-6866-4838-9ce9-36838d5fe185)
also, already happened to have 2 same nicks at the tablist

**Comment by GoodestEnglish** [comment]
No, tablist won't sort.

The reason why the tablist sometimes break is because player joined the server instantly after the server starts. Rejoin the server should solve the issue.

**Comment by serumanooo** [comment]
i fixed it, but i still think it would be a good idea to make it in alphabetical order like minemen
