### ISSUE TITLE
is tournament creation working?

### ISSUE THREAD

**Issue by serumanooo** [diamond-rip/Eden#327]
![image](https://github.com/diamond-rip/Eden/assets/132185379/b4f34346-4027-4e7e-a383-e665cad79616)
![image](https://github.com/diamond-rip/Eden/assets/132185379/873456e0-2676-4dc4-bf2b-a70a94bf6b0d)
i think its not, because i tried to create a uhc event and could not, it can mean two things:

i need to config the tournament arena, but idk how to do that because i havent found any config about it
or
tournament creation is not possible for now
(yes i know the sumo event is working)

**Comment by serumanooo** [comment]
if its not working, make a option to disable it while you dont add it to eden, because it would be bad to see players trying to create a tournament and not being able to do it

**Comment by GoodestEnglish** [comment]
What problem did you face when hosting tournament?

**Comment by serumanooo** [comment]
> What problem did you face when hosting tournament?

2 things: 

1- idk how to set a arena for it, and it would be cool if i could set the kits that i dont want the players to select
2- it goes like this:

https://youtu.be/l0aNqkrEbd8

i think the cause is the first reason: idk how to set arenas for tournaments and i also dont know where the configs of it are, because i havent found anything about it in config.yml

**Comment by GoodestEnglish** [comment]
I can add banned kits in tournament soon.

**Comment by GoodestEnglish** [comment]
It is not 'reset'. The first timer is a waiting state timer, in this state player can join the tournament.
The second timer is round countdown timer. Before each round starts, system will count 30 seconds and start the round.

**Comment by serumanooo** [comment]
> It is not 'reset'. The first timer is a waiting state timer, in this state player can join the tournament. The second timer is round countdown timer. Before each round starts, system will count 30 seconds and start the round. And in this state player cannot join the tournament.

ohhhh, now i understand how it works, ty
