### ISSUE TITLE
please make the arena clone option better

### ISSUE THREAD

**Issue by serumanooo** [diamond-rip/Eden#329]
i have this issue:
https://youtu.be/thfQsV4kKiQ
(it also happens in non bridge arenas, because there are arenas that i setted the minimum and maximum location without the barrier)

here is my idea: instead of making it clone the arena using the exact min/max location, make it clone a bigger area, like 25+ blocks in each side of the cuboid, make it big please, or at least configurable, making it a big area wont cause any problems because there is like, just air around the arena, so there is no problem with making it like this
(if this area isnt big enough, when i try to clone a the bridge arena, it will cut off a part of the back of the island)

**Comment by GoodestEnglish** [comment]
Min and max should cover the whole arena. This will break a lot of stuff like this.

**Comment by serumanooo** [comment]
> Min and max should cover the whole arena. This will break a lot of stuff like this.

But there are situations that we dont want to cover the whole arena, like in the bridge, or like, it dont need to cover the barriers, just the are where we can place blocks

The min/max area is more usefull as a are to determinate the block placement limit

**Comment by serumanooo** [comment]
And making it a larger are wont cause any problem, because no one puts a arena next do another one, so it wont copy parts of another arena, just air

**Comment by GoodestEnglish** [comment]
Min and max do more than you think. 

May I ask why the current portal protection radius system cannot do hippos?

**Comment by serumanooo** [comment]
> Min and max do more than you think.
> 
> May I ask why the current portal protection radius system cannot do hippos?

in this case i dont think you can do what i suggested, ill not persist 
let me explain for you

there are maps that the portal radius sys would be usefull, like this one
i need to have exactly 7 blocks of distance
![image](https://github.com/diamond-rip/Eden/assets/132185379/af240962-e021-486b-92ad-f6ea2e970ed9),
so its sufficient to cover the sides and back of the map

in this one, its four
![image](https://github.com/diamond-rip/Eden/assets/132185379/a61bfff3-3409-404d-90d6-d7e502b93cfa)
but they will be able to put blocks at the side, back and front of the map, wich is something terrible
![image](https://github.com/diamond-rip/Eden/assets/132185379/e68d0a13-89e9-41d1-81df-ee819a74f50b)
![image](https://github.com/diamond-rip/Eden/assets/132185379/fc2867fe-1639-4c30-bc36-b2314c49dbf8)


because what i need is:
![image](https://github.com/diamond-rip/Eden/assets/132185379/3c122953-97ab-4c8a-9b0b-861cf1744908)

**Comment by Chromaah** [comment]
tbh i would just use worldguard lol

**Comment by serumanooo** [comment]
> tbh i would just use worldguard lol
> 
> (would be annoying for cloning tho)

Yes, that would be very annoying, but if i dont have any choice, ill have to make it this way

**Comment by GoodestEnglish** [comment]
I still believe portal protection radius can still do its job, but anyways, expending 20 blocks radius when cloning arenas in next update

**Comment by GoodestEnglish** [comment]
Added
