### ISSUE TITLE
Urgent issues to fix ASAP

### ISSUE THREAD

**Issue by HierarchyMan** [diamond-rip/Eden#33]
The issues are kind of game breaking and need to be fixed soon
- ~~Hunger not depleting (saturation does deplete but hunger bar doesn't even after saturation gets to 0)~~
- ~~Absorption hearts to normal golden apples when instant apples is enabled~~
- ~~Snowballs should break floor when they touch it~~
- option weather to reset position when a round ends
- ~~point should be given to opposite team if player dies without any damage or hit~~

Now these options can be delayed if you want
- kits saved in yml just like arenas
- adding resistance to kits doesn't work
- separate portal protection config for each arena

Keep up the amazing work every update is making the plugin better and better
and also, I would like to know why you are making this premium plugin for free

**Comment by ABIGDachshunch** [comment]
if kits saved in yml then maybe we dont need mongodb anymore but thats hard

**Comment by ABIGDachshunch** [comment]
you can add my discord and we can talk about the eden

**Comment by HierarchyMan** [comment]
sure whats your discord?

**Comment by ABIGDachshunch** [comment]
**telepatia#9063**

**Comment by HierarchyMan** [comment]
i dmd u where r u

**Comment by RealGoodestEnglish** [comment]
Thanks for the list. I will try to push a fix within a next few days

**Comment by RealGoodestEnglish** [comment]
Can you explain why `option weather to reset position when a round ends` is necessary? Right now it automatically send the player back to the match spawn location to prevent any early attack, lava, movement, etc.

**Comment by RealGoodestEnglish** [comment]
Tested in my side and adding resistance effect does work for me. Make sure the potion effect name is typed correctly, which is `DAMAGE_RESISTANCE`

**Comment by HierarchyMan** [comment]
> Can you explain why `option weather to reset position when a round ends` is necessary? Right now it automatically send the player back to the match spawn location to prevent any early attack, lava, movement, etc.

Stick Fight has it
And killing someone in a game with point system should trigger the respawn system instead of resetting round (so spawn protection is activated in order to prevent early attacks and stuff)
But it still needs to reset round for some kits
Which is why I suggested this option
It's entirely up to you I just thought it would be good for some kits

**Comment by RealGoodestEnglish** [comment]
Fixed point 1,2,3,5 in the latest update: https://github.com/diamond-rip/Eden/releases/tag/1.0.20-BETA-a2aa8c0

**Comment by HierarchyMan** [comment]
Works like a charm
