### ISSUE TITLE
event sumo map bug

### ISSUE THREAD

**Issue by serumanooo** [diamond-rip/Eden#330]
![image](https://github.com/diamond-rip/Eden/assets/132185379/4b348624-8878-41b8-94e0-154cdadb9d6c)
its impossible to /duel someone in this map, and it works for the sumo event, but we still can queue in this map

**Comment by GoodestEnglish** [comment]
You shouldn't assign any kit to the event map since it is used by the event.

My bad I forgot to add this into wiki.

**Comment by serumanooo** [comment]
> You shouldn't assign any kit to the event map since it is used by the event.
> 
> My bad I forgot to add this into wiki.

Ok ty
