### ISSUE TITLE
ghost blocks

### ISSUE THREAD

**Issue by serumanooo** [diamond-rip/Eden#332]
https://youtu.be/n2Djt8NXuME

i know i already mentionated that in here:
>ghost blocks, this happens everytime in battlerush, because the arena resets when a player hits a point, the blocks arent real, they disappear when the player break it or put a block at the side of it, but maybe this is happening:
when the server restarts, the ghost blocks that are in the arena turn into real blocks, so now it is part of the arena
i think this could be the cause because i cant see if there is ghost blocks in uhc or the bridge, because the arena resets just after the match ends

i dont think anymore that this is the cause of the arenas not reseting properly, because i already confirmed that the cause was the world auto saving, so i havent found any problem with it anymore

but these ghost blocks appear all the time, and its not client sided, because it appears for both players

its like this: someone make a tall bridge and strike a point, the arena resets and these ghost blocks appear

i remember you said something about the way that eden registrates the blocks and you said you will add a option for something like this, so idk if its related to that

(yes im using the solidfix plugin, i think its related to eden because it only happens in gamemodes that the arena resets mid-match)

**Comment by Chromaah** [comment]
ghost blocks happen in canilla minecraft, happens on all servers, even mmc. and if its not client sided, and both players can see it, then isnt it a real block?

**Comment by serumanooo** [comment]
> ghost blocks happen in vanilla minecraft, happens on all servers, even mmc. and if its not client sided, and both players can see it, then isnt it a real block?

No, check the video, i tried to jump on it and it disappeared, and i if i it dont disappear, the anticheat would try to ban me for "flying"
Also, if i click the block or if i try to place a block at the side of it, it disappear

Yes, ghost blocks are normal in vanilla minecraft, and yes, it happens in other servers, a common thing is lava and water ghosting. But in this cases, its client sided

This is a issue that should be fixed because it happen all the time with me and my friends in battle rush
Idk why but it usually happens in high blocks, like in the video (im sure its not the build limit or maximum position, so idk whats the cause, but ill check it again later)

I started to record it after the ghost block appeared, so here is what happened:
I made a bridge to the portal, i scored a point, then when we respawned, just part of the bridge disappeared

**Comment by GoodestEnglish** [comment]
I am going to make an option which allow user to change how block disappears. Currently Eden uses NMS which makes block disappear sightly faster, but since this uses NMS, unexpected might happen. Alterative is to use bukkit default setBlock function. But if this doesn't help, then I can't do anything with it since it is client sided but not server sided.

**Comment by serumanooo** [comment]
> I am going to make an option which allow user to change how block disappears. Currently Eden uses NMS which makes block disappear sightly faster, but since this uses NMS, unexpected might happen. Alterative is to use bukkit default setBlock function. But if this doesn't help, then I can't do anything with it since it is client sided but not server sided.

Ok i think this should work, i dont think you can do anything about it if this does not work, but i dont think its client sided, the ghostblocks appear for all players

**Comment by GoodestEnglish** [comment]
> > I am going to make an option which allow user to change how block disappears. Currently Eden uses NMS which makes block disappear sightly faster, but since this uses NMS, unexpected might happen. Alterative is to use bukkit default setBlock function. But if this doesn't help, then I can't do anything with it since it is client sided but not server sided.
> 
> 
> 
> Ok i think this should work, i dont think you can do anything about it if this does not work, but i dont think its client sided, the ghostblocks appear for all players

It is client sided. The anticheat detected you flying is the evidence

**Comment by serumanooo** [comment]
> > > I am going to make an option which allow user to change how block disappears. Currently Eden uses NMS which makes block disappear sightly faster, but since this uses NMS, unexpected might happen. Alterative is to use bukkit default setBlock function. But if this doesn't help, then I can't do anything with it since it is client sided but not server sided.
> > 
> > 
> > Ok i think this should work, i dont think you can do anything about it if this does not work, but i dont think its client sided, the ghostblocks appear for all players
> 
> It is client sided. The anticheat detected you flying is the evidence

so idk what to do, i cant make a battlerush kit if everytime someone strikes a point, it makes ghost blocks, this isnt normal, but i understand that you dont know whats causing it, because the arena is reseting, if it was not reseting, the blocks would be real

i hope that what you said before can fix it
>I am going to make an option which allow user to change how block disappears. Currently Eden uses NMS which makes block disappear sightly faster, but since this uses NMS, unexpected might happen. Alterative is to use bukkit default setBlock function. But if this doesn't help, then I can't do anything with it since it is client sided but not server sided.

**Comment by GoodestEnglish** [comment]
So I added a new option in config.yml called `set-block-fast`. This option will uses original bukkit setBlock method instead of an optimized setBlock method with NMS. If this doesn't solve the issue, then I am not too sure what I should do.

**Comment by HierarchyMan** [comment]
I'm pretty sure if you load the chunks that are resetting with your client
It's the client that bugs out
Cuz so many packets being sent it counts some blocks as not deleted and ghost blocks appear

**Comment by serumanooo** [comment]
> I'm pretty sure if you load the chunks that are resetting with your client It's the client that bugs out Cuz so many packets being sent it counts some blocks as not deleted and ghost blocks appear
> 
> Make sure the arena isn't too close to spawn

i think it stopped with the new option that was added
and no, its not close to spawn, its like 90000 blocks away

**Comment by GoodestEnglish** [comment]
Great to hear that!
