### ISSUE TITLE
New spigot support

### ISSUE THREAD

**Issue by lenstyy** [diamond-rip/Eden#333]
Can you add the support of this spigot? 
https://builtbybit.com/resources/rocketspigot-smooth-knockback.22238/

**Comment by GoodestEnglish** [comment]
Should be a yes but i am unsure. I will let you know soon

**Comment by GoodestEnglish** [comment]
They have an API which allows me to add support, so yes I can add. Except this come in the next update.

Note that although I will add support into Eden, it does not mean I will fully support it, one major reason is because I don't own the spigot and I cannot do testing with that spigot.
