### ISSUE TITLE
Proporsal

### ISSUE THREAD

**Issue by liexes** [diamond-rip/Eden#334]
Price ($) to add compatibility with the plugin party and friends?

**Comment by GoodestEnglish** [comment]
Not adding PAF support due to the complexity and time. 

I am also not doing any commissions.

**Comment by liexes** [comment]
> Not adding PAF support due to the complexity and time.
> 
> I am also not doing any commissions.

But is it taken into account?

**Comment by Chromaah** [comment]
aw man, was looking forward to see if PAF would be added. RIP, guess no compatibility between my bedwars server and eden

**Comment by GoodestEnglish** [comment]
Add PAF support is gonna change 50% of the party system of Eden. Well I could add after I add those todo's in discussion. But currently no plan on adding it.

**Comment by GoodestEnglish** [comment]
> > Not adding PAF support due to the complexity and time.
> > I am also not doing any commissions.
> 
> But is it taken into account?

No

**Comment by liexes** [comment]
> Add PAF support is gonna change 50% of the party system of Eden. Well I could add after I add those todo's in discussion. But currently no plan on adding it.

That's the idea, that Eden is compatible with other game modes. Many people who have downloaded the plugin I think think the same.
