### ISSUE TITLE
Support for lightspigot

### ISSUE THREAD

**Issue by djtheta** [diamond-rip/Eden#335]
plz add support for this spigot:

https://builtbybit.com/resources/lightspigot-8-lite-for-pvp-servers.16933/

**Comment by GoodestEnglish** [comment]
Yes I can add support into lightspigot. Except this come in the next update.

Note that although I will add support into Eden, it does not mean I will fully support it, one major reason is because I don't own the spigot and I cannot do testing with that spigot.

**Comment by HierarchyMan** [comment]
> Yes I can add support into lightspigot. Except this come in the next update.
> 
> Note that although I will add support into Eden, it does not mean I will fully support it.

Ahh yes I recently got back to the community after a long break
Light spigot was the first thing I tried and it didnt disappoint
It has way better kb than wind spigot
Also make sure to add support for the lite version if you were only going to add support for the full version

**Comment by GoodestEnglish** [comment]
> > Yes I can add support into lightspigot. Except this come in the next update.
> > Note that although I will add support into Eden, it does not mean I will fully support it.
> 
> Ahh yes I recently got back to the community after a long break Light spigot was the first thing I tried and it didnt disappoint It has way better kb than wind spigot Also make sure to add support for the lite version if you were only going to add support for the full version

I am not sure if they changed anything in premium version in the knockback and movement handler. But I am currently using the lite version for the support.

I didn't find any API from their support server so I did some investigation in their lite jar file. But if they changed their file path in the premium version, unfortunately I cant do anything.

**Comment by HierarchyMan** [comment]
When support?

**Comment by GoodestEnglish** [comment]
> When support?

Oppsie, it is secertly added :P, along with RocketSpigot
