### ISSUE TITLE
Can't Right Click in 1.1.16-BETA-7916368

### ISSUE THREAD

**Issue by djtheta** [diamond-rip/Eden#336]
When I right click I get 
![image](https://github.com/diamond-rip/Eden/assets/108408871/cd6b3585-54f6-421d-963b-54109358f39e)
the unknown command message with no errors or messages in console.
This bug only occurs on the latest version of Eden, v1.1.16-BETA-7916368

**Comment by djtheta** [comment]
this is fixed, but i still cant right click the play again paper

**Comment by Chromaah** [comment]
Right click what? Im guessing the play again paper. Someone already reported this, GoodestEnglish is aware, and it will be fixed in the next update.

**Comment by GoodestEnglish** [comment]
Closing this because of duplicate with #320
