### ISSUE TITLE
problem with snow blocks

### ISSUE THREAD

**Issue by serumanooo** [diamond-rip/Eden#338]
make the option in the config that make snow balls break snow blocks per kit, because this happens in modes with snow balls:
https://youtu.be/dccpnfoM-WU

**Comment by HierarchyMan** [comment]
I think you should make it only break snow blocks when spleef enabled. Issue fixed no kit configuration needed

**Comment by serumanooo** [comment]
> I think you should make it only break snow blocks when spleef enabled. Issue fixed no extra kit configuration needed

yes, thats way better

**Comment by serumanooo** [comment]
> Too late, I already made an option in kit game rules 😟
> 
> This will come in the next update.

its fine, it will fix the problem anyway

**Comment by HierarchyMan** [comment]
> I think you should make it only break snow blocks when spleef enabled. Issue fixed no extra kit configuration needed

@GoodestEnglish  hey can u please reconsider doing that?
Eden already has too many kit customisation options
You wouldn't want to make everything look unorganised right?

**Comment by GoodestEnglish** [comment]
> > I think you should make it only break snow blocks when spleef enabled. Issue fixed no extra kit configuration needed
> 
> @GoodestEnglish hey can u please reconsider doing that? Eden already has too many kit customisation options You wouldn't want to make everything look unorganised right?

Alright
