### ISSUE TITLE
a little bit more of suggestion

### ISSUE THREAD

**Issue by ABIGDachshunch** [diamond-rip/Eden#34]
first new thing is the **scoreboard**
-fight duration
second is the **hunger** bar change need to be fix

**Comment by RealGoodestEnglish** [comment]
Use ```{match-duration}``` in any match scoreboard should work.
About the hunger bar issue, it will be fixed soon.

**Comment by RealGoodestEnglish** [comment]
Fixed hunger issue: https://github.com/diamond-rip/Eden/releases/tag/1.0.20-BETA-a2aa8c0
