### ISSUE TITLE
Simple addon request (Cages)

### ISSUE THREAD

**Issue by HierarchyMan** [diamond-rip/Eden#340]
This is cage addon
This spawns the player 5-7 blocks above the already set spawn location (so no extra setup steps are needed)
The player spawns inside a cage determined by a schematic
The player can move freely in the cage
The cage is removed when round starts
When the player respawns they dont spawn in the cage, they spawn at already set spawn location
The cage and cage spawn location is brought back after every point scored
This addon adds an extra game rule "Cages" that determines if this feature will be used

Very useful for: Bridges, Skywars

Totally cosmetic but if you do not decide to add this I will close this request no questions asked.

**Comment by GoodestEnglish** [comment]
Can be a feature request, but in a very very low priority

**Comment by GoodestEnglish** [comment]
Moved to #342
