### ISSUE TITLE
qol fixes and feature requests

### ISSUE THREAD

**Issue by HierarchyMan** [diamond-rip/Eden#341]
Fireball
- So the amount of damage a fireball does to the player who launches it should be different than the opponent (config)
- This is to achieve results like 0 dmg to urself but sufficient damage to the opponent
- If the fireball is thrown back towards the player who launched it (using melee), it should do the damage it would've done to the opponent. 
- ~~make fireballs faster (the blast seem delayed when the fb is casted towards the ground, it should be almost instant or about 2X the current speed.~~ (just make an offset) 

Kits
- ~~gamerule use durability (if you want the rod to break or Armor to break in some kits but not in others).~~
- add option for per kit breakable blocks (and dont remove from config, there should also be universal breakable blocks) this won't change how bedfight and bridges have breakable blocks, this will just add extra blocks that can be broken to them. 
- a new kit option called nospeed kb (used only for boxing) switches kb for players in that boxing match after they've /nospeed (this goes well with the 2nd boxing suggestion below)

Boxing
- [BUG] so the current combo counter merely shows the difference btwn hits and not the actual combo. It should show how many times I've hit the opponent without the opponent hitting me. It should set to zero if opponent hits me and turn red if the opponent of comboing me regardless of hit difference. 
- so when in boxing, one person being able to /nospeed is kinda dumb so when a player does /nospeed can u make it so it doesn't take away or give the effect until the other player has accepted it (give opponent a chat clickable message saying your opponent wants nospeed or speed back).

**Comment by GoodestEnglish** [comment]
About durability, Minecraft 1.8 has a new NBT tag called unbreakable. You can simply set your item to unbreakable by using external plugin, or I can make a command for it.

About fireball, I will see what I can do with it.

**Comment by GoodestEnglish** [comment]
Yes sure. Should be a 5-mins command :p

**Comment by HierarchyMan** [comment]
> Yes sure. Should be a 5-mins command :p

One more thing don't increase fireball speed yet
Add an offset (a little further)  in this update so that it's closer to the ground and explosion happens sooner 
The speed is fine I think

**Comment by HierarchyMan** [comment]
I've suggested more (edited main comment)
And dont forget to add fireball offset for faster explosion near ground

**Comment by Chromaah** [comment]
Another suggestion, maybe add a victory dance(s) to the plugin? or atleast just fireworks on the player that wins? (obviously making it an option in config.yml since some people dont want this)

**Comment by HierarchyMan** [comment]
@GoodestEnglish I've suggested more (edited main comment)
And dont forget to add fireball offset for faster explosion near ground

**Comment by HierarchyMan** [comment]
@GoodestEnglish ?

**Comment by GoodestEnglish** [comment]
What do you mean by 'It should set to zero if opponent hits me and turn red if the opponent of comboing me regardless of hit difference'? Can't you just use a different placeholder for this scenario?

I have no clue why /nospeed needs your opponent to confirm. This is just going to give you a disadvantage if you use this command.

Also, the suggestion you've mentioned is really, really unpopular. Since there's tons of todos in the list, I will most likely not gonna add those into Eden.

About 'add option for per kit breakable blocks', this will be considered.

**Comment by HierarchyMan** [comment]
> What do you mean by 'It should set to zero if opponent hits me and turn red if the opponent of comboing me regardless of hit difference'? Can't you just use a different placeholder for this scenario?
> 
> I have no clue why /nospeed needs your opponent to confirm. This is just going to give you a disadvantage if you use this command.
> 
> Also, the suggestion you've mentioned is really, really unpopular. Since there's tons of todos in the list, I will most likely not gonna add those into Eden.
> 
> About 'add option for per kit breakable blocks', this will be considered.

 1- So the combo counter should only work when someone is getting hit constantly
 like go to minemen club and check their combo counter
 
2= nospeed confirmation cuz if one player wants do play in nospeed it will be a disadvantage but if both players agree to play with nospeed its okay
 
3-  i do understand kb switching after nospeed is not on the top of the list but pair it with the Number 3 and and it should work amazing
