### ISSUE TITLE
match inventory

### ISSUE THREAD

**Issue by serumanooo** [diamond-rip/Eden#344]
i already asked this before
please make the match inventory clickable while in match, and also make a match inventory history, at least like, the last 3 matches, everyone click on play again after finishing a match, so its impossible to see the previous match inventory
https://youtu.be/OMjeBDAodi0

**Comment by GoodestEnglish** [comment]
Cooldown will be added. Match inventory clickable while in match will be added also

**Comment by serumanooo** [comment]
> Cooldown will be added. Match inventory clickable while in match will be added also

will you add like a match inventory history too? that would be great, in minemen i can see previous match inventories (it has a expiration time, i think its like, 3-5 minutes)

so what im saying is, dont limit it, just add a expiration time, or make it expire after you play like, 2-4 other matches (+ the expiration time)

**Comment by GoodestEnglish** [comment]
Added in latest release

**Comment by Chromaah** [comment]
tried latest release, there is still no cooldown on when play-again item gets added to player's inventory

**Comment by GoodestEnglish** [comment]
> tried latest release, there is still no cooldown on when play-again item gets added to player's inventory

Ah, by what I mean 'added' is I added the "match inventory clickable while in match". Play again item cooldown is not added. Will add in next update.
