### ISSUE TITLE
problem with invisible projectiles

### ISSUE THREAD

**Issue by serumanooo** [diamond-rip/Eden#345]
idk if its eden related, no errors in console, it just happened 2 times, dont know how to reproduce, and after i recorded this video, the projectiles were visible again
https://youtu.be/rpUfzxgi0UY

**Comment by GoodestEnglish** [comment]
The current entity hider is using Array Practice's, which is kinda old and unreadable at some point. But this isn't an issue for me.

Anyways, I will keep tracking for this issue.
