### ISSUE TITLE
bedfight

### ISSUE THREAD

**Issue by serumanooo** [diamond-rip/Eden#347]
i broke my enemy's bed and he just picked it up and put it in front of me lmao
![image](https://github.com/diamond-rip/Eden/assets/132185379/b816188d-6d1c-419c-a0b4-b38294553763)

**Comment by serumanooo** [comment]
i figured out what happened
i put the bed here using //set because i cant normally put a bed on a glass block
![image](https://github.com/diamond-rip/Eden/assets/132185379/acdf9417-3cce-45cb-8670-ff2dd5d96260)
so, does anyone know how can i put a bed on a glass block without //set or /setblock?

**Comment by GoodestEnglish** [comment]
Dropped item shouldn't able to spawn when player breaks the bed tho.

Anyways, adding a check in the next update.

**Comment by serumanooo** [comment]
> Dropped item shouldn't able to spawn when player breaks the bed tho.
> 
> Anyways, adding a check in the next update.

Its not spawning normally, its spawning because i used worldedit to set each part of the bed separately and it only drops if i break the pillow part, but if you can do something about it i would appreciate that

**Comment by HierarchyMan** [comment]
First place the best and then //set blocks below to glass 🤨

**Comment by serumanooo** [comment]
> First place the bed and then //set blocks below to glass 🤨

you are a genius

**Comment by GoodestEnglish** [comment]
Fixed in latest release
