### ISSUE TITLE
parkour

### ISSUE THREAD

**Issue by serumanooo** [diamond-rip/Eden#348]
you could add a parkour option in kit editor, like, a iron preassure plate would be a checkpoint and a golden one would make the player win

**Comment by liexes** [comment]
Exact, i like this idea

**Comment by miguelYT1** [comment]
I like this idea

**Comment by miguelYT1** [comment]
> I also think that it is something that should be added in the plugin that will make it more complete.

**Comment by HierarchyMan** [comment]
I previously suggested this
He put this on the list but won't work on it until other features are complete.

**Comment by Chromaah** [comment]
@GoodestEnglish hey bro, I have some questions about the api of the plugin and stuff. Can you add me on discord? 

My Discord:
> Chromaah#1992

(Didnt want to open a whole issue just for this)

**Comment by GoodestEnglish** [comment]
Moved to #353
