### ISSUE TITLE
Stolen Classes from Frost without Rights?

### ISSUE THREAD

**Issue by egirldevs** [diamond-rip/Eden#35]
Hello,

I am speaking on behalf of @Elb1to & @GatitoUwU.

The following classes are stolen from Frost's arena chunk regeneration system.

https://github.com/diamond-rip/Eden/blob/master/src/main/java/rip/diamond/practice/arenas/ArenaDetail.java
https://github.com/diamond-rip/Eden/blob/master/src/main/java/rip/diamond/practice/arenas/cache/ArenaChunk.java
https://github.com/diamond-rip/Eden/blob/master/src/main/java/rip/diamond/practice/arenas/cache/ArenaCache.java

Anything to say on this?

**Comment by Elb1to** [comment]
smh

**Comment by GatitoUwU** [comment]
well, yes, that's my code and it belongs to Frost Practice.

**Comment by RealGoodestEnglish** [comment]
None of the code are stolen from Frost. Arena cache system are from Array Practice, which I stated in README.

**Comment by Elb1to** [comment]
It is from Frost, Array took it from there.

**Comment by RealGoodestEnglish** [comment]
I would like to talk to one of you in discord dms. My discord is GoodestEnglish#0821

**Comment by egirldevs** [comment]
> GoodestEnglish#0821

You are not accepting fr. Emily.#7478 add me

**Comment by RealGoodestEnglish** [comment]
Solved in dms
