### ISSUE TITLE
problem with spectator

### ISSUE THREAD

**Issue by serumanooo** [diamond-rip/Eden#352]
https://youtu.be/lEHtHRbAxWc
i thought it was because of the area that the spectator needs to be in, but i dont think thats the reason

**Comment by GoodestEnglish** [comment]
Yes it is. The spectator still needs to be in the arena bounding box. Set your max to become higher should solve the problem.

**Comment by serumanooo** [comment]
Ok, but the spectator area is too tiny, it would be good if you expand it by 20 blocks like the arena cloning area
https://youtu.be/lydNg4zilXA
(Sorry about the quality of the video, i had 3 open games, so it was killing my computer)

**Comment by GoodestEnglish** [comment]
> Ok, but the spectator area is too tiny, it would be good if you expand it by 20 blocks like the arena cloning area https://youtu.be/lydNg4zilXA (Sorry about the quality of the video, i had 3 open games, so it was killing my computer)

Alright, changing it to 20 in next update

**Comment by HierarchyMan** [comment]
Btw when a player dies in a respawnable gamemode can u make it so they dont respawn at  their respective spawn?
Either set their gamemode spectator wherever they are or teleport them to the spectator location. 

Disable the death packet to make the server more smooth just count it as win/loose/kill without you actually taking the last bit of damage that actually kills you

Question: in sumo even, are the participants first teleported to the spectator location?
Like Minemen Club has this view ring

**Comment by GoodestEnglish** [comment]
> Btw when a player dies in a respawnable gamemode can u make it so they dont respawn at their respective spawn?
> Either set their gamemode spectator wherever they are or teleport them to the spectator location.

I will add an option which allows user to disable the teleportation after dies in respawnable kit gamemode

> Disable the death packet to make the server more smooth just count it as win/loose/kill without you actually taking the last bit of damage that actually kills you

Not sure what you mean by this. Could you explain more?

> Question: in sumo even, are the participants first teleported to the spectator location?
> Like Minemen Club has this view ring

Yes. All player spawn location in the sumo event match will be the spectator location


Also if you could make a new issue when asking a new question would be appreciated. This makes the chat readable and the update log of the plugin will actually mention the correct thing.

**Comment by GoodestEnglish** [comment]
Fixed and added in latest update.
