### ISSUE TITLE
match countdown

### ISSUE THREAD

**Issue by serumanooo** [diamond-rip/Eden#357]
https://youtu.be/K6UI49eYQVc
add a title on the screen showing the countdown, it would be very clean
but i think you should add a option in the config.yml for us to choose if we want to:
use the chat countdown
use the title countdown
or use both

**Comment by serumanooo** [comment]
also, can you make this some messages removable?
![image](https://github.com/diamond-rip/Eden/assets/132185379/c5df4b6c-2cef-49e3-bfad-1757d6fdb378)
like, i think it would be good if we could just leave a message empty in language.yml and eden would not send it, because if i do this, the console sends a blank message

**Comment by serumanooo** [comment]
https://youtu.be/6f5rfyYjb1U
make the last point teleport the players back to the spawn location, like in minemen club

also, make the death message with the color of the teams in modes that have point system or break goal, etc
![image](https://github.com/diamond-rip/Eden/assets/132185379/b748c4d3-56fa-4d76-b292-20a518510e5d)

**Comment by Chromaah** [comment]
i already suggested all of this in discussions

https://github.com/diamond-rip/Eden/discussions/355 

also the title for bridge already is a thing, it says 'player scored!'

**Comment by serumanooo** [comment]
> i already suggested all of this in discussions
> 
> #355
> 
> also the title for bridge already is a thing, it says 'player scored!'

oh i havent seem this

about the title, no, im not talking about the "player scored" title, i want him to add a title for the countdown, but just for the respawn, not when the match starts

**Comment by serumanooo** [comment]
![image](https://github.com/diamond-rip/Eden/assets/132185379/aa3a3065-c53e-491d-a7d0-1465d3414e34)
also, i found an issue, the 30 seconds cooldown is not working, i just cant invite him again

**Comment by GoodestEnglish** [comment]
> ![image](https://user-images.githubusercontent.com/132185379/244242184-aa3a3065-c53e-491d-a7d0-1465d3414e34.png) also, i found an issue, the 30 seconds cooldown is not working, i just cant invite him again

Fixing this in next update

> also, can you make some messages removable? i personally dont think this one is necessary ![image](https://user-images.githubusercontent.com/132185379/244226212-c5df4b6c-2cef-49e3-bfad-1757d6fdb378.png) like, i think it would be good if we could just leave a message empty in language.yml and eden would not send it, because if i do this, the console sends a blank message

In the next update, you can disable the message being sent if you change the message to `null`. (config should looks like this: `view-inventory: "null"`)


> https://youtu.be/K6UI49eYQVc add a title on the screen showing the countdown, it would be very clean but i think you should add a option in the config.yml for us to choose if we want to: use the chat countdown use the title countdown or use both

Adding this in next update
