### ISSUE TITLE
please get kit and profile to save to yml  because mongodb wont work with my ubuntu pc i cant host

### ISSUE THREAD

**Issue by ABIGDachshunch** [diamond-rip/Eden#36]
Error occurred while enabling Eden v1.0.20-BETA-a2aa8c0 (Is it up to date?)
com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting for a server that matches com.mongodb.client.internal.MongoClientDelegate$1@50dd1618. Client view of cluster state is {type=REPLICA_SET, servers=[{address=????, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketReadException: Prematurely reached end of stream}}, {address=???, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketReadException: Prematurely reached end of stream}}, {address=???, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketReadException: Prematurely reached end of stream}}]

**Comment by ABIGDachshunch** [comment]
**i love this plugin it work good but with ubuntu i cant host because of this error but on my win 10 pc it work like a cham**

**Comment by ABIGDachshunch** [comment]
**i mostly host with my ubuntu because it has 32Ram So Please Change It**

**Comment by RealGoodestEnglish** [comment]
I've edited the error you sent because the error you sent contains sensitive information (Your MongoDB IP address). Please do not public any private information.
MongoTimeoutException means that the plugin cannot connect to the database, which usually because you have incorrect mongo ip/password. Windows and linux doesn't make any difference between MongoDB. Eden is tested with windows and linux and it works fine. Please double check your config.yml and make sure all the mongodb info is set correctly.

**Comment by ABIGDachshunch** [comment]
> I've edited the error you sent because the error you sent contains sensitive information (Your MongoDB IP address). Please do not public any private information. MongoTimeoutException means that the plugin cannot connect to the database, which usually because you have incorrect mongo ip/password. Windows and linux doesn't make any difference between MongoDB. Eden is tested with windows and linux and it works fine. Please double check your config.yml and make sure all the mongodb info is set correctly.

yes it is all right i copy my config from window to ubuntu and window work fine?

**Comment by RealGoodestEnglish** [comment]
Should be fine. Have you tried to connect to mongodb with those login information via linux console to ensure your machine can connect?

**Comment by ABIGDachshunch** [comment]
> Should be fine. Have you tried to connect to mongodb with those login information via linux console to ensure your machine can connect to MongoDB?

ill try with another machine of my friend who use linux

**Comment by ABIGDachshunch** [comment]
> Should be fine. Have you tried to connect to mongodb with those login information via linux console to ensure your machine can connect to MongoDB?



> Should be fine. Have you tried to connect to mongodb with those login information via linux console to ensure your machine can connect to MongoDB?

mongo wont work with my ubuntu

**Comment by ABIGDachshunch** [comment]
> Should be fine. Have you tried to connect to mongodb with those login information via linux console to ensure your machine can connect to MongoDB?

**can you please get kit and profile to save in yml.**

**Comment by ABIGDachshunch** [comment]
i try to use oracle vm instance and the same problem appear.

**Comment by ABIGDachshunch** [comment]
Actual problem was instance was taking more than expected time to connect to the Mongo Atlas server. and instance was stoping before connection is successful and which was ending with Connection Timeout issue. I am keeping this question, so that if someone face this kind of issue they should look into it from this perspective as wel
please make kit.yml and profile.yml.

**Comment by RealGoodestEnglish** [comment]
kit.yml is planned. profile.yml is not coming because that will break a lot of stuff such as leaderboard, stats searching, etc.
