### ISSUE TITLE
Suggestion: Add Kit Categories

### ISSUE THREAD

**Issue by endygame** [diamond-rip/Eden#360]
It may be a little complicated but it would be great to improve the queue menu by adding multiple categories and/or making it paginated.

**Comment by GoodestEnglish** [comment]
So basically lunar practice.

But atm I do not think a server will reach 54 kit gamemodes. Also lunar practice queue menu got so many negative feedback.

**Comment by HierarchyMan** [comment]
> It may be a little complicated but it would be great to improve the queue menu by adding multiple categories and/or making it paginated.

I have some implementation ideas 
So like if an arena is added to a certain kit category
All kits can be used with the arena
It's customisable weather to choose categories when quing or not
(Also pls add glass pan border in kit selection we don't want to use 3rd party)

**Comment by Chromaah** [comment]
by glass pane border you mean like as a filler item right?

**Comment by GoodestEnglish** [comment]
I assume you mean menu customization. It is in my todo list, but in a low priority. 

I will mostly follow this todo list https://github.com/diamond-rip/Eden/discussions/categories/to-do-list. Whichever suggestion has a higher upvote will have a higher priority.
