### ISSUE TITLE
help please

### ISSUE THREAD

**Issue by serumanooo** [diamond-rip/Eden#362]
[latest (6).log](https://github.com/diamond-rip/Eden/files/11710784/latest.6.log)
no one can join the server, ill try to remove eden to see if its related to it, but i think it is because of the console errors

**Comment by serumanooo** [comment]
> [latest (6).log](https://github.com/diamond-rip/Eden/files/11710784/latest.6.log) no one can join the server, ill try to remove eden to see if its related to it, but i think it is because of the console errors

yes it is related to eden

**Comment by serumanooo** [comment]
idk what caused it, i changed the host i was using for the server, if i open the server with the previous host, i can join it, but i cant with the new one

**Comment by serumanooo** [comment]
oh i think i figured it out, i add the ip of the new host in the mongo db

**Comment by GoodestEnglish** [comment]
Yea it is related to your mongodb config.
