### ISSUE TITLE
Issue with falling into the void in the lobby

### ISSUE THREAD

**Issue by Miab0** [diamond-rip/Eden#364]
Hi! Players are not teleported back to spawn when they fall into the void in the lobby. I didn't find anything related to this in the configuration file, so I'm posting it here assuming it's a bug.

**Comment by liexes** [comment]
I also have the same error, additionally, when the player dies in a game he tp the lobby/spawn and the message respawn? Also, when you fall into a void in an arena, like the bridge, the void kills you and the exact same thing happens. @GoodestEnglish

**Comment by GoodestEnglish** [comment]
> Hi! Players are not teleported back to spawn when they fall into the void in the lobby. I didn't find anything related to this in the configuration file, so I'm posting it here assuming it's a bug.

Forgot to add this into the plugin. I will add it soon

**Comment by GoodestEnglish** [comment]
> I also have the same error, additionally, when the player dies in a game he tp the lobby/spawn and the message respawn? Also, when you fall into a void in an arena, like the bridge, the void kills you and the exact same thing happens. @GoodestEnglish

Need more info. Is it happening everytime? And what does your kit.yml looks it? (Assuming you set something wrong in kit gamerules)

**Comment by miguelYT1** [comment]
> 

I have already fixed it, now it happens that the spleef does not work as it should and the spleef option is enabled

**Comment by GoodestEnglish** [comment]
> > 
> 
> I have already fixed it, now it happens that the spleef does not work as it should and the spleef option is enabled

Fix what? Are you @liexes ?

**Comment by liexes** [comment]
> > > 
> > 
> > 
> > I have already fixed it, now it happens that the spleef does not work as it should and the spleef option is enabled
> 
> Fix what? Are you @liexes ?
> 
> Anyway, what does your kit.yml looks like

Yes, this is my other account, sorry for the confussion, i send the kit.yml soon wait.

**Comment by liexes** [comment]
This is my error @GoodestEnglish:

https://www.dropbox.com/s/xiclrtbz70mqzdl/2023-06-23%2012-14-11.mp4?dl=0

The items added in additional, cannot be broken, for some reason you can only break land, but I don't have it in additional. Do I have to activate something?

Another error that happens is that when a user sets gamemode 1 and builds, when playing the map again, it does not reset or if some players are playing, you become tp and with gm 1 or another you put blocks, the same thing happens.

**Comment by liexes** [comment]
I forgot to add that if you place chests with loot inside, when the game is restarted, the loot disappears, this is not good for skywars

**Comment by GoodestEnglish** [comment]
> This is my error @GoodestEnglish:
> 
> https://www.dropbox.com/s/xiclrtbz70mqzdl/2023-06-23%2012-14-11.mp4?dl=0
> 
> The items added in additional, cannot be broken, for some reason you can only break land, but I don't have it in additional. Do I have to activate something?
> 
> Another error that happens is that when a user sets gamemode 1 and builds, when playing the map again, it does not reset or if some players are playing, you become tp and with gm 1 or another you put blocks, the same thing happens.

You cannot break blocks which is not placed by a player. And also skywars isn't possible to make yet.

You should not edit the map while player is playing on your server. That is a VERY bad behavior and should be avoided.

**Comment by GoodestEnglish** [comment]
> I forgot to add that if you place chests with loot inside, when the game is restarted, the loot disappears, this is not good for skywars

And that being said, the arena will only regenerate blocks, not tile entities.

**Comment by miguelYT1** [comment]
He did not edit it when we were playing, it was already edited, the spleef has an error and that is that you can only break the snow with the snowballs and not with the shovel, even if the option is activated in the kit manager

**Comment by GoodestEnglish** [comment]
> He did not edit it when we were playing, it was already edited, the spleef has an error and that is that you can only break the snow with the snowballs and not with the shovel, even if the option is activated in the kit manager

Have you enable build in kit gamerules?

**Comment by HierarchyMan** [comment]
> He did not edit it when we were playing, it was already edited, the spleef has an error and that is that you can only break the snow with the snowballs and not with the shovel, even if the option is activated in the kit manager

Enable build and set build max to one above ur arena ground y level
