### ISSUE TITLE
can you make a permission for the /spec command?

### ISSUE THREAD

**Issue by serumanooo** [diamond-rip/Eden#365]

**Comment by GoodestEnglish** [comment]
Why? Spectate command should be used by everyone.

**Comment by serumanooo** [comment]
> Why? Spectate command should be used by everyone.

im actually in doubt about how i want to use /spec on my server, because i know servers that only allow VIP to use this command and others that everyone can use it (minemen for example)
because, like, its annoying not being able to /spec if you dont have vip, but also making it a VIP only feature, makes the VIP more valued

tbh idk whats the best option

**Comment by serumanooo** [comment]
> > > Why? Spectate command should be used by everyone.
> > 
> > 
> > im actually in doubt about how i want to use /spec on my server, because i know servers that only allow VIP to use this command and others that everyone can use it (minemen for example)
> > because, like, its annoying not being able to /spec if you dont have VIP, but also making it a VIP only feature, makes the VIP more valued, and i need to add more things for the VIPs, and i cant because eden, at least for now, doesnt support multi-worlds
> > tbh idk whats the best option
> 
> Disagree this would make the server seem more money hungry a simple feature like such should be used by everyone

Yeah, i agree, i also forgot about this issue i opened, im actually letting everyone use the /spec command
