### ISSUE TITLE
Add an option to print stats (similar to hypixel)

### ISSUE THREAD

**Issue by djtheta** [diamond-rip/Eden#367]
Add a button next to the Post-Match Inventories (click to view) that sends a message displaying the stats, not inventories, side by side so the player doesn't have to switch back and forth between inventories. 
![image](https://github.com/diamond-rip/Eden/assets/108408871/3dd82f97-49c1-40f5-9907-6b10e454486f)
somewhat similar to this

**Comment by GoodestEnglish** [comment]
Not possible. Eden doesn't store that much data. Plus Eden is designed to be similar to Lunar/MMC, not hypixel.

**Comment by djtheta** [comment]
I understand, a friend suggested this anyway, thank you.
