### ISSUE TITLE
about tab sorting

### ISSUE THREAD

**Issue by serumanooo** [diamond-rip/Eden#368]
i discovered eden is the reason i cant sort nicks at the tablist, im not using eden's tablist, but eden actually change the display names, and it conflits with the leaftags plugin im using even if i disable the sorting on it (it should sort alphabetically, but with the eden display names, it doesnt)

so, i know there isnt a way to prevent eden confliting with it, but can you make eden sort the nametags alphabetically? (i dont know if the minecraft already do it with tablist, but if it does, when im using eden + the leaftags plugins, it doesnt)

**Comment by GoodestEnglish** [comment]
Then it is the plugin you are using's problem. The plugin you are using is most likely using the wrong method (I assume it used `getDisplayName()` instead of `getName()`).

However, I will note this as todo as of right now.

**Comment by serumanooo** [comment]
> Then it is the plugin you are using's problem. The plugin you are using is most likely using the wrong method (I assume it used `getDisplayName()` instead of `getName()`).
> 
> However, I will note this as todo as of right now.

Ill talk about it with the leaftags creator too

**Comment by serumanooo** [comment]
also, this happens sometimes https://youtu.be/22SrUKOaSTc

**Comment by GoodestEnglish** [comment]
> also, this happens sometimes https://youtu.be/22SrUKOaSTc (no errors in console)

Are you using other nametags or scoreboard related plugin?

**Comment by serumanooo** [comment]
> > also, this happens sometimes https://youtu.be/22SrUKOaSTc (no errors in console)
> 
> Are you using other nametags or scoreboard related plugin?

Yes i am but i disabled the displaynames and things about it
But now that you mentionated it,  i think maybe i setted it to true at the past week while testing the tab sorting (i normally use it at false so its not the reason of the sorting issue)
Ill check it tomorrow

**Comment by GoodestEnglish** [comment]
Hello, is this issue fixed?

**Comment by serumanooo** [comment]
> Hello, is this issue fixed?

The second one, yes
The first one, no
