### ISSUE TITLE
battlerush and bridge

### ISSUE THREAD

**Issue by Cryzis** [diamond-rip/Eden#371]
this isn't really an issue it's more like a suggestion

is it possible for the play to receive a certain color block in bridge and battlerush (for example team A receives red and team B receives blue)

also with battlerush when you place blocks, there's normally a 5 second cooldown before the blocks start to break, could you possible add it in?

**Comment by GoodestEnglish** [comment]
If you give player white wool, when you join the game it will turn into colored wool.

You can set the block break cooldown in our kit menu. Visit https://github.com/diamond-rip/Eden/wiki/Kits-Setup#edit-a-kit for more info.
