### ISSUE TITLE
Spectators can't fly

### ISSUE THREAD

**Issue by djtheta** [diamond-rip/Eden#374]
I can't fly while spectating and I didn't toggle my fly or anything.

**Comment by GoodestEnglish** [comment]
Do you have your lobby and arena world separated?

**Comment by djtheta** [comment]
No, should that make a difference?

**Comment by djtheta** [comment]
Actually they are in a separate world.

**Comment by GoodestEnglish** [comment]
> No, should that make a difference?

Right now Eden only supports single world, and I would recommend to do all stuff in a single world to prevent issues like dirt screen.

**Comment by djtheta** [comment]
When will Eden support multiple worlds?

**Comment by GoodestEnglish** [comment]
> When will Eden support multiple worlds?

Cant tell you the time but i can say it is in the todo list. But as a practice server you should make everything in a single world.

**Comment by GoodestEnglish** [comment]
Can you try the latest version and see if it is fixed or not?

**Comment by djtheta** [comment]
Still doesn't work. Thanks for trying though.

**Comment by pixeledge-verify** [comment]
@djtheta If you still didn't find a way around. I used Skript for it. 
```
on world change:
	wait 20 ticks
	if player has red dye:
		allow flight to player
```

Worked Great for me. And also it requires this. 

> https://github.com/Matocolotoe/Skript-1.8/releases

**Comment by serumanooo** [comment]
> @djtheta If you still didn't find a way around. I used Skript for it.
> 
> ```
> on world change:
> 	wait 20 ticks
> 	if player has red dye:
> 		allow flight to player
> ```
> 
> Worked Great for me. And also it requires this.
> 
> > https://github.com/Matocolotoe/Skript-1.8/releases

tried it and it didnt work for me, any idea?

**Comment by pixeledge-verify** [comment]
Did you use the Skript Version I provided?

**Comment by serumanooo** [comment]
> Did you use the Skript Version I provided?

fixed it, i downloaded the right version but i put the wrong version at the plugins folder

**Comment by GoodestEnglish** [comment]
Fixed
