### ISSUE TITLE
i got this error when i queue any match

### ISSUE THREAD

**Issue by serumanooo** [diamond-rip/Eden#377]
![image](https://github.com/diamond-rip/Eden/assets/132185379/ded06a93-c5f7-4f08-87d0-93f817630b86)

im using foxspigot

**Comment by serumanooo** [comment]
also, i still have this mongodb spam in my console
![image](https://github.com/diamond-rip/Eden/assets/132185379/1969c0a4-393c-4fff-8592-bb0785cb23ac)

tried to talk with the foxspigot creator but he said its not foxspigot fault, but idk, i just get this error with foxspigot

**Comment by GoodestEnglish** [comment]
This is hard to fix because of I don't own foxspigot. I have no control in this scenario. ATM I can only say consider to use other fork of spigot.

**Comment by serumanooo** [comment]
> This is hard to fix because of I don't own foxspigot. I have no control in this scenario. ATM I can only say consider to use other fork of spigot.
> 
> But of course, I will keep tracking.

oh, ok
unfortunely i cant use other fork, i need a spigot fork that let me change the knockback, i was using a leaked version of carbon to test it and make a good kb config (i was going to buy it, ill not open a public server using leaked things), but carbon is too expensive for me

30€ = 150R$, its almost 10% of a minimum wage in brazil
so i bought foxspigot because its cheaper and now i have to use it

**Comment by Chromaah** [comment]
i dont recommend foxspigot.

**Comment by serumanooo** [comment]
> i dont recommend foxspigot.

I prefer carbon or immanity but i have no money

**Comment by HierarchyMan** [comment]
> > i dont recommend foxspigot.
> 
> I prefer carbon or immanity but i have no money

Use windspigot, it's a lot better and you can fix bow boosting with it
Plus I never really got the error even with fox spigot
You should check kb name capitalisation

**Comment by serumanooo** [comment]
> > > i dont recommend foxspigot.
> > 
> > 
> > I prefer carbon or immanity but i have no money
> 
> Use windspigot, it's a lot better and you can fix bow boosting with it Plus I never really got the error even with fox spigot You should check kb name capitalisation

ill try windspigot, but if my memory is good, i cant use it because its uncompatible with my plugins

**Comment by serumanooo** [comment]
> > > > i dont recommend foxspigot.
> > > 
> > > 
> > > I prefer carbon or immanity but i have no money
> > 
> > 
> > Use windspigot, it's a lot better and you can fix bow boosting with it Plus I never really got the error even with fox spigot You should check kb name capitalisation
> 
> ill try windspigot, but if my memory is good, i cant use it because its uncompatible with my plugins

i fixed the issues, it works, its compatible
but it have more  kb options than foxspigot or carbonspigot, so ill take a while to make a good config if i want to use it
