### ISSUE TITLE
Hearts are at 0

### ISSUE THREAD

**Issue by djtheta** [diamond-rip/Eden#379]
![image](https://github.com/diamond-rip/Eden/assets/108408871/5c1d31b0-0da6-4259-a741-31599d8ccebe)
Hearts are at 0 in the beginning of the match on the nametag.
I am running version 1.7.10.

**Comment by Chromaah** [comment]
it always happens to me as well, as soon as you hit the player it displays correct health.

**Comment by pixeledge-verify** [comment]
It would be great if Kits had Toggleable Health Bars

**Comment by Chromaah** [comment]
> It would be great if Kits had Toggleable Health Bars

They do. 'Show Health' in kit editor

**Comment by HierarchyMan** [comment]
> ![image](https://github.com/diamond-rip/Eden/assets/108408871/5c1d31b0-0da6-4259-a741-31599d8ccebe)
> Hearts are at 0 in the beginning of the match on the nametag.
> I am running version 1.7.10.

+1 fix it

**Comment by GoodestEnglish** [comment]
Smh another vanilla minecraft bug :/
Fixing this soon

**Comment by GoodestEnglish** [comment]
Fixed in latest release.
