### ISSUE TITLE
PlayerProfileLoadedEvent

### ISSUE THREAD

**Issue by HappyAreaBean** [diamond-rip/Eden#38]
Hello! I'm currently had a thing that is modifying player flight state on `PlayerJoinEvent`.
I have tried to change my EventPriority to `HIGHEST`, but after I check the code, I see it get overrides after the profile is loaded:
https://github.com/diamond-rip/Eden/blob/a2aa8c0e26985007f78a48975654fe673f072eea/src/main/java/rip/diamond/practice/profile/listener/ProfileListener.java#L54
My only idea right now is to have a `PlayerProfileLoadedEvent` will fire when the profile is loaded.

**Comment by GoodestEnglish** [comment]
Fixed in latest version
