### ISSUE TITLE
Boxing Bug

### ISSUE THREAD

**Issue by IMudee** [diamond-rip/Eden#381]
Always when the player reaches 10 hits in boxing he wins directly
It cannot be completed to 100 hits

Is there a solution

**Comment by GoodestEnglish** [comment]
Are you using the latest version?

**Comment by Antoniova1** [comment]
> Are you using the latest version?

the same thing happens to me, I have the latest version

**Comment by IMudee** [comment]
yp  the latest version

**Comment by GoodestEnglish** [comment]
I realized that i didn't change the version tag. So there's two 1.1.19 versions. This is the correct one. https://github.com/diamond-rip/Eden/releases/tag/1.1.19-BETA-8595586

Try this and let me know the result.

**Comment by Antoniova1** [comment]
> I realized that i didn't change the version tag. So there's two 1.1.19 versions. This is the correct one. https://github.com/diamond-rip/Eden/releases/tag/1.1.19-BETA-8595586
> 
> Try this and let me know the result.

yes, this works correctly

**Comment by GoodestEnglish** [comment]
Good to hear that!
