### ISSUE TITLE
Party bug 

### ISSUE THREAD

**Issue by Antoniova1** [diamond-rip/Eden#383]
I don't know if the same thing happens to someone, but when you're at a party and when a fight ends, the leader is sent to a random arena, this has happened to me a few times, I have arenas and lobby in separate worlds, I don't know if that will have What to see, but it only happens when you are at a party, in solo mode it has never happened, and no error appears on the console

**Comment by Antoniova1** [comment]
![2023-06-24_16 57 04](https://github.com/diamond-rip/Eden/assets/108409110/fee337b9-d3ad-43cd-b9ee-8fd6c7e918d5)

this is an arena, i was in ffa mode

**Comment by GoodestEnglish** [comment]
Same, never experienced this before. But I will keep tracking

**Comment by Antoniova1** [comment]
> Same, never experienced this before. But I will keep tracking

It's still happening, I'm removing plugins to see if any are responsible for it

**Comment by GoodestEnglish** [comment]
Still can't reproduce. What spigot and what plugins are you using?

**Comment by Antoniova1** [comment]
> Still can't reproduce. What spigot and what plugins are you using?

yeah it's still happening and now it's happened to me 2-3 times in solo mode i've been removing plugins but haven't had much time to do them with all of them i'm using pandaspigot

**Comment by Antoniova1** [comment]
> > Still can't reproduce. What spigot and what plugins are you using?
> 
> yeah it's still happening and now it's happened to me 2-3 times in solo mode i've been removing plugins but haven't had much time to do them with all of them i'm using pandaspigot

these are my plugins
![20230714_201312](https://github.com/diamond-rip/Eden/assets/108409110/9b8e4eeb-0e21-4e84-8cd6-f2ffa9101129)

**Comment by Antoniova1** [comment]
and one question, could you add support for pandaspigot?
https://github.com/hpfxd/PandaSpigot

**Comment by GoodestEnglish** [comment]
> > Still can't reproduce. What spigot and what plugins are you using?
> 
> yeah it's still happening and now it's happened to me 2-3 times in solo mode i've been removing plugins but haven't had much time to do them with all of them i'm using pandaspigot

What if you test with only Eden, Fawe and ProtocolLib?

**Comment by GoodestEnglish** [comment]
> and one question, could you add support for pandaspigot? https://github.com/hpfxd/PandaSpigot

Should be able to

**Comment by Antoniova1** [comment]
> > > Still can't reproduce. What spigot and what plugins are you using?
> > 
> > 
> > yeah it's still happening and now it's happened to me 2-3 times in solo mode i've been removing plugins but haven't had much time to do them with all of them i'm using pandaspigot
> 
> What if you test with only Eden, Fawe and ProtocolLib?

that way i haven't tested it, but i think the problem happened with the essentials plugin, i think it was sending me to my death location when i was in OP mode, and when i removed the OP mode it hasn't happened anymore

**Comment by Antoniova1** [comment]
It hasn't happened lately, I think it's been fixed

**Comment by Antoniova1** [comment]
It hasn't happened lately, I think it's been fixed
