### ISSUE TITLE
Scored title in kits with point system enabled

### ISSUE THREAD

**Issue by Miab0** [diamond-rip/Eden#384]
Hi! The '**scored-title'** title is not displayed with the new update. The new '**title'** title is displayed instead.

A suggestion: You could put a toggle in the configuration to enable or disable the second mentioned title

![image](https://github.com/diamond-rip/Eden/assets/94245081/137fe5e1-597e-499e-a5e6-f68eb9dd0e0e)

**Comment by serumanooo** [comment]
how do you even enable this title? i tried and i cant, could you send your language.yml for me to see it?

**Comment by IMudee** [comment]
> Hi! The '**scored-title'** title is not displayed with the new update. The new '**title'** title is displayed instead.
> 
> A suggestion: You could put a toggle in the configuration to enable or disable the second mentioned title
> 
> ![image](https://user-images.githubusercontent.com/94245081/248516495-137fe5e1-597e-499e-a5e6-f68eb9dd0e0e.png)

its work for me with the last version !
check your config of language.yml file

**Comment by serumanooo** [comment]
> > Hi! The '**scored-title'** title is not displayed with the new update. The new '**title'** title is displayed instead.
> > A suggestion: You could put a toggle in the configuration to enable or disable the second mentioned title
> > ![image](https://user-images.githubusercontent.com/94245081/248516495-137fe5e1-597e-499e-a5e6-f68eb9dd0e0e.png)
> 
> its work for me with the last version ! check your config of language.yml file

Yes i updated my language.yml after the last update, but idk if i did something wrong

**Comment by serumanooo** [comment]
![image](https://github.com/diamond-rip/Eden/assets/132185379/00ea7102-b1b7-492d-9d79-85b4602e919e)
i think i need to enable an option but idk what option

**Comment by GoodestEnglish** [comment]
> Hi! The '**scored-title'** title is not displayed with the new update. The new '**title'** title is displayed instead.
> 
> A suggestion: You could put a toggle in the configuration to enable or disable the second mentioned title
> 
> ![image](https://user-images.githubusercontent.com/94245081/248516495-137fe5e1-597e-499e-a5e6-f68eb9dd0e0e.png)

In the next update, you can disable `match.new-round-start.title` title by setting the string to 'null'. This will prevent the system sending the title and overlap the original title.

**Comment by serumanooo** [comment]
> ![image](https://user-images.githubusercontent.com/132185379/248580244-00ea7102-b1b7-492d-9d79-85b4602e919e.png) i think i need to enable an option but idk what option

@GoodestEnglish help, the title does not work for me

**Comment by GoodestEnglish** [comment]
> > ![image](https://user-images.githubusercontent.com/132185379/248580244-00ea7102-b1b7-492d-9d79-85b4602e919e.png) i think i need to enable an option but idk what option
> 
> @GoodestEnglish help, the title does not work for me

It is because another title overlap the countdown title. You have to disable one of them in the next update to fix it.

**Comment by serumanooo** [comment]
> > > ![image](https://user-images.githubusercontent.com/132185379/248580244-00ea7102-b1b7-492d-9d79-85b4602e919e.png) i think i need to enable an option but idk what option
> > 
> > 
> > @GoodestEnglish help, the title does not work for me
> 
> It is because another title overlap the countdown title. You have to disable one of them in the next update to fix it.

oh ok ty

**Comment by GoodestEnglish** [comment]
Please disable match.new-round-start.title title by setting the string to 'null' in the latest version from now on. This will prevent the system sending the title and overlap the original title.
