### ISSUE TITLE
Creating BedWars arena

### ISSUE THREAD

**Issue by RainFallDev** [diamond-rip/Eden#386]
can i get the comand for select teams beds

**Comment by IMudee** [comment]
just set A and B spawn location, the beds will be set automatically.  

Note:
A: is the red
B: is the blue

**Comment by RainFallDev** [comment]
no not this like
/setbed red
/setbed blue

**Comment by GoodestEnglish** [comment]
It doesn't work like that. Eden will automatically generate the team bed location by using the team spawn location. When player breaks the bed, Eden will calculate which team spawn location is near the bed.

**Comment by Chromaah** [comment]
> can i get the comand for select teams beds

use bedwars1058 plugin for real bedwars stuff, if u want bedfight do what they said

**Comment by RainFallDev** [comment]
>ok thx

**Comment by HierarchyMan** [comment]
> just set A and B spawn location, the beds will be set automatically.  
> 
> Note:
> A: is the red
> B: is the blue

A is blue and vice versa (ur wrong)
