### ISSUE TITLE
how to create a combo kit

### ISSUE THREAD

**Issue by IMudee** [diamond-rip/Eden#387]
how to create combo kit

**Comment by serumanooo** [comment]
you would need to use the eden api to use a different kb config with the combo kit, but its not possible

@GoodestEnglish you could create an option for combo kits, because we cant use eden api

**Comment by pixeledge-verify** [comment]
> how to create combo kit

which spigot are you using? If using any supported ones you can do it easily

**Comment by GoodestEnglish** [comment]
> how to create combo kit

You should be using a spigot fork which can modify knockback and hit delay. I heard WindSpigot is a decent spigot fork which can modify knockback. (Untested, I recommend CarbonSpigot or ImanitySpigot but those are paid spigot forks.)

**Comment by pixeledge-verify** [comment]
I have been using Imanity and its sweet running with Eden. I recommend it over Carbon. The Knockback is a bit of a hatle to setup. If need I can help. Discord @ssquadteam

**Comment by serumanooo** [comment]
> > how to create combo kit
> 
> You should be using a spigot fork which can modify knockback and hit delay. I heard WindSpigot is a decent spigot fork which can modify knockback. (Untested, I recommend CarbonSpigot or ImanitySpigot but those are paid spigot forks.)

Wait, so i dont need eden api to change the kb profile at the kit config??

**Comment by pixeledge-verify** [comment]
Yep you dont

> > > how to create combo kit
> > 
> > 
> > You should be using a spigot fork which can modify knockback and hit delay. I heard WindSpigot is a decent spigot fork which can modify knockback. (Untested, I recommend CarbonSpigot or ImanitySpigot but those are paid spigot forks.)
> 
> Wait, so i dont need eden api to change the kb profile at the kit config??

**Comment by HierarchyMan** [comment]
> you would need to use the eden api to use a different kb config with the combo kit, but its not possible
> 
> @GoodestEnglish you could create an option for combo kits, because we cant use eden api

Eden api is not required for ob switches. If u use any of of the suggested spigots the kb profiles are already set accordingly

**Comment by serumanooo** [comment]
> > you would need to use the eden api to use a different kb config with the combo kit, but its not possible
> > @GoodestEnglish you could create an option for combo kits, because we cant use eden api
> 
> Eden api is not required for kb switches. If u use any of of the suggested spigots the kb profiles are already set accordingly Plus there's an option for hit delay ticks in Eden kit settings. Set it to 3 for best experience (not 0)

ohhh i didnt know that, thank you so much, i got confused after reading about eden api, i thought i would need that

@IMudee im sorry for the misinformation

**Comment by pixeledge-verify** [comment]
Eden api is for integrating Eden KB system and other Eden systems into your own Spigot or Plugin

> > > you would need to use the eden api to use a different kb config with the combo kit, but its not possible
> > > @GoodestEnglish you could create an option for combo kits, because we cant use eden api
> > 
> > 
> > Eden api is not required for kb switches. If u use any of of the suggested spigots the kb profiles are already set accordingly Plus there's an option for hit delay ticks in Eden kit settings. Set it to 3 for best experience (not 0)
> 
> ohhh i didnt know that, thank you so much, i got confused after reading about eden api, i thought i would need that
> 
> @IMudee im sorry for the misinformation

**Comment by IMudee** [comment]
i need help with config of knockback

**Comment by serumanooo** [comment]
> i need help with config of knockback

Ive spent like 80 hours trying to make a good kb config and i could not make it

**Comment by HierarchyMan** [comment]
> > i need help with config of knockback
> 
> Ive spent like 80 hours trying to make a good kb config and i could not make it
> Idk how good servers do it

DM me on dc when u can
Name: cystol

**Comment by serumanooo** [comment]
> > you would need to use the eden api to use a different kb config with the combo kit, but its not possible
> > @GoodestEnglish you could create an option for combo kits, because we cant use eden api
> 
> Eden api is not required for kb switches. If u use any of of the suggested spigots the kb profiles are already set accordingly Plus there's an option for hit delay ticks in Eden kit settings. Set it to 3 for best experience (not 0)

hey i tried this option with windspigot and it didnt work for me, ill try restarting my server

**Comment by GoodestEnglish** [comment]
So I looked for this. Looks like some spigot have knockback settings but do not allow to modify combo ticks. 
I can add the settings back.
