### ISSUE TITLE
skin problem

### ISSUE THREAD

**Issue by serumanooo** [diamond-rip/Eden#388]
im using skinsrestorer, and i found a problem that might be related to eden

if im in the lobby and i do /skin, everything goes normal
but if im in a match, the entire server lags (thats why i think this can be related to eden)
(no errors in console)

if you wanna try to reproduce this bug, the version of skinsrestorer is 13.5.2, i know its not the latest version, but its because im using a skript that requires that version
but ill try it with the latest version, because it can be a bug related to skinsrestorer

**Comment by pixeledge-verify** [comment]
huh. Weird issue. Everything is normal on our server.

**Comment by pixeledge-verify** [comment]
I don't think Eden is related with it.

**Comment by serumanooo** [comment]
> I don't think Eden is related with it.

I think its not related to it, but its at least weird that it just lag when someone is in a match

Anyway, im trying to find a plugin to replace skinsrestorer

**Comment by HierarchyMan** [comment]
> im using skinsrestorer, and i found a problem that might be related to eden
> 
> if im in the lobby and i do /skin, everything goes normal
> but if im in a match, the entire server lags (thats why i think this can be related to eden)
> (no errors in console)
> 
> if you wanna try to reproduce this bug, the version of skinsrestorer is 13.5.2, i know its not the latest version, but its because im using a skript that requires that version
> but ill try it with the latest version, because it can be a bug related to skinsrestorer

Skin restorer actually doesn't work as smoothly as you would expect, it actually forces all chunks near you to load again
And when ur in a match, change like that could lag (only) the player out (server shouldn't lag try doing /tps)
Which is why I think we need an option to block commands while in a match

**Comment by serumanooo** [comment]
> Skin restorer actually doesn't work as smoothly as you would expect, it actually forces all chunks near you to load again And when ur in a match, change like that could lag (only) the player out (server shouldn't lag try doing /tps) Which is why I think we need an option to block commands while in a match

the problem is that it literally lags the entire server, like, if there are 2 players in a match and im at the lobby and i do /skin, they will lag too

ill try the latest version of skinsrestorer to see if this will stop, but do you guys know an alternative /skin plugin?

**Comment by serumanooo** [comment]
> https://dev.bukkit.org/projects/changeskin

tried this one, nothing happens when i do /setskin <nick>

**Comment by serumanooo** [comment]
i found that with the latest version of skinsrestorer this issue does not happens, so i asked the creator of a skript im using that has 13.5.2 skinsrestorer as dependency, to update the skript to the latest version of skinsrestorer

ill close this issue because its not even eden related
