### ISSUE TITLE
suggestions

### ISSUE THREAD

**Issue by HierarchyMan** [diamond-rip/Eden#389]
Suggestions
- ~~allow TNT placing above build limit.~~
- when start freeze is enabled and when we try to move, it teleports us one block above so change that and make it only reset the x and z cords not the y and also make it not change your look direction.
- ~~what's the status on parkour kit?~~
- allow us to add settings from our core in Eden:settings (direct messages and stuff).
- ~~some options in the config should be turned on by default (eg: gapple effects should be true, imanity teleport should be false cuz not everyone uses imanity).~~
- ~~add a field "server-ip" and position determiner so we don't have to manually add it to the bottom of every scoreboard.~~
- fireball fight is perfect but add just a little offset to fireball so explosion occurs faster (optional).

Bugs
- ~~player armor not visible until the player is hit. does eden have anythign to do with it?~~
- ~~DONT allow playing on original arenas MAKE IT MANDATORY to clone an arena and only play on cloned area (cuz it still doesn't reset sometimes)~~
- ~~Fix combo counter video showcasing the difference: https://youtu.be/PU-Hoo07NtE~~
- ~~remove effects like absorption when jump in void if portalgoal (or just void death in general) is enabled~~
- ~~set saturation to 10 (not 20) and add it back I made a mistake I'm really sorry~~

**Comment by HierarchyMan** [comment]
and hunger is once again not depleting
plugin list: fawe, aquacore, bowboosting, viaver, mvcore, protocollib, eden, holographicdisplays, deluxe menus

**Comment by HierarchyMan** [comment]
i suggest u fix given issues asap :D
hunger not depleting
remove effects like absorption when jump in void if portalgoal (or just void death in general) is enabled

**Comment by HierarchyMan** [comment]
also, there are two spleef options in kit settings one of them is always enabled by default when making a new kit

**Comment by GoodestEnglish** [comment]
> also, there are two spleef options in kit settings one of them is always enabled by default when making a new kit

which two?

**Comment by GoodestEnglish** [comment]
> i suggest u fix given issues asap :D hunger not depleting remove effects like absorption when jump in void if portalgoal (or just void death in general) is enabled

This is the point of open source a plugin. Because I can't put too much time on developing the plugin. Ofc I will fix those, but if you really that urgent you should fork the plugin.

**Comment by GoodestEnglish** [comment]
> and hunger is once again not depleting plugin list: fawe, aquacore, bowboosting, viaver, mvcore, protocollib, eden, holographicdisplays, deluxe menus

Do you have hunger enabled in kit gamerules?

**Comment by HierarchyMan** [comment]
If I had the knowledge I would've
There's a reason I trust you to make this plugin the best prac plugin that's ever existed
Sure enough when I learn enough Java I will be here to help with any bugs and stuff like that
I'm currently learning and always will and i do understand my tone was a bit hasty, I'll be sure to send one issue report at a time if needed 😀

**Comment by HierarchyMan** [comment]
> 
> 
> 
> > and hunger is once again not depleting plugin list: fawe, aquacore, bowboosting, viaver, mvcore, protocollib, eden, holographicdisplays, deluxe menus
> 
> Do you have hunger enabled in kit gamerules?

Change hunger setting is set to true I've tested  oth true and false and none seems to bring the hunger down

**Comment by GoodestEnglish** [comment]
> > > and hunger is once again not depleting plugin list: fawe, aquacore, bowboosting, viaver, mvcore, protocollib, eden, holographicdisplays, deluxe menus
> > 
> > 
> > Do you have hunger enabled in kit gamerules?
> 
> Change hunger setting is set to true I've tested oth true and false and none seems to bring the hunger down

Thanks for the info, fixing in next update.

**Comment by serumanooo** [comment]
> DONT allow playing on original arenas MAKE IT MANDATORY to clone an arena and only play on cloned area (cuz it still doenst reset sometimes)

about this one, please, add this to eden, its so annoying to fix the arenas every single time to see if they are with blocks or if there is something broken

**Comment by HierarchyMan** [comment]
%eden_leaderboard_winstreak_winstreak_<kit name>_<position>% always outputs 0 instdead of actual ws

**Comment by GoodestEnglish** [comment]
> %eden_leaderboard_winstreak_winstreak__% always outputs 0 instdead of actual ws and when it does work it only updates after a restart

![image](https://github.com/diamond-rip/Eden/assets/45838505/91fc227e-bb67-41de-9f35-75df5aecbaa7)
The placeholder works for me tho. Mind showing your full placeholder?

**Comment by GoodestEnglish** [comment]
> Suggestions
> 
> * allow TNT placing above build limit.
> * when start freeze is enabled and when we try to move, it teleports us one block above so change that and make it only reset the x and z cords not the y and also make it not change your look direction.
> * what's the status on parkour kit?
> * allow us to add settings from our core in Eden:settings (direct messages and stuff).
> * some options in the config should be turned on by default (eg: gapple effects should be true, imanity teleport should be false cuz not everyone uses imanity).
> * add a field "server-ip" and position determiner so we don't have to manually add it to the bottom of every scoreboard.
> * fireball fight is perfect but add just a little offset to fireball so explosion occurs faster (optional).
> 
> Bugs
> 
> * player armor not visible until the player is hit. does eden have anythign to do with it?
> * DONT allow playing on original arenas MAKE IT MANDATORY to clone an arena and only play on cloned area (cuz it still doenst reset sometimes)
> * Fix combo counter video showcasing the difference: https://youtu.be/PU-Hoo07NtE
> * remove effects like absorption when jump in void if portalgoal (or just void death in general) is enabled

https://drive.google.com/file/d/1yOzgD8jG9sSQRlT65R8_tkd1sYJ4EgXm/view?usp=sharing

Can you test this version and let me know if this boxing scoreboard style is what you want?

Change `scoreboard.boxing-counter.text-solo` to `{0}{1} Combo`

**Comment by GoodestEnglish** [comment]
> player armor not visible until the player is hit. does eden have anythign to do with it?
Should be not. Eden doesn't modify visibility of player's armor

**Comment by HierarchyMan** [comment]
hunger still not depleting its not because of saturation
saturation is still going down but hunger bar isnt

**Comment by HierarchyMan** [comment]
update issue fixed: it was aquacore as to enabke hunger-change in config i think u should make saturaiton back to what it was (im so sorry)

**Comment by HierarchyMan** [comment]
set saturation to 10 (not 20) and add it back I made a mistake I'm really sorry

**Comment by HierarchyMan** [comment]
@GoodestEnglish Add hunger tweaks
Allow us to set start match saturation in config.yml
don't allow depletion of saturation when hunger is disabled in match because the hunger bar starts moving makinbg it not look good
only depletion of saturation in matches with hunger enabled

**Comment by HierarchyMan** [comment]
> > %eden_leaderboard_winstreak_winstreak__% always outputs 0 instdead of actual ws and when it does work it only updates after a restart
> 
> ![image](https://github.com/diamond-rip/Eden/assets/45838505/91fc227e-bb67-41de-9f35-75df5aecbaa7)
> The placeholder works for me tho. Mind showing your full placeholder?

Only updates when server restart make it update every 5 minutes

**Comment by GoodestEnglish** [comment]
> > > %eden_leaderboard_winstreak_winstreak__% always outputs 0 instdead of actual ws and when it does work it only updates after a restart
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/45838505/249375763-91fc227e-bb67-41de-9f35-75df5aecbaa7.png)
> > The placeholder works for me tho. Mind showing your full placeholder?
> 
> Only updates when server restart make it update every second

Currently it should update in each hour. I can make this variable configurable.

Prevent to make it each second because the update method actually retrieves data from mongodb. Imagine you grab a lot of data in every second, that will be a disaster.

**Comment by serumanooo** [comment]
Idk if its related to what you guys are talking about, but the ranked leaderboard is not updating (or its updating very very slowly)

**Comment by HierarchyMan** [comment]
> Idk if its related to what you guys are talking about, but the ranked leaderboard is not updating (or its updating very very slowly)

Yes we were actually discussing that
Soon you will be able to customise leaderboards update time

**Comment by HierarchyMan** [comment]
Did you fix the gapple effect still there after falling in the void? Cuz you didn't mention it

**Comment by HierarchyMan** [comment]
> Did you fix the gapple effect still there after falling in the void? Cuz you didn't mention it

Tnt placing above build limit still doesn't work
Allow tnt place before the game start timer ends and also above the build limit
Basically remove all place restrictions for tnt

**Comment by GoodestEnglish** [comment]
> Did you fix the gapple effect still there after falling in the void? Cuz you didn't mention it

Yup, should be fixed



> > Did you fix the gapple effect still there after falling in the void? Cuz you didn't mention it
> 
> Tnt placing above build limit still doesn't work Allow tnt place before the game start timer ends and also above the build limit Basically remove all place restrictions for tnt

Will look into it also.

**Comment by HierarchyMan** [comment]
idea for better freeze spawn system
 Check is start freeze enabled
 If false do nothing
 If true
   Check if match start countdown=0
     If 0 then do nothing
     If greater that 0 then,
       Check if player is at respective spawnpoint
         If yes do nothing
         If no, teleport player to spawn without changing y axis or look direction ({x,y,z} only)


I think this one would be more efficient and send a lot less packets

**Comment by HierarchyMan** [comment]
> Eden is already doing that. But instead of teleporting back without changing y axis, Eden teleport back to the original team spawn point. Since they are doing the same action (teleporting, and same chunk), it will not send less packets.

But it is more annoying
Only changing x and z should be better and smoother looking

**Comment by GoodestEnglish** [comment]
> > Eden is already doing that. But instead of teleporting back without changing y axis, Eden teleport back to the original team spawn point. Since they are doing the same action (teleporting, and same chunk), it will not send less packets.
> 
> Mybad, But it is more annoying Only changing x and z should be better and smoother looking

I can do that. Adding this in next update

**Comment by HierarchyMan** [comment]
> I can do that. Adding this in next update

Is it done?

**Comment by GoodestEnglish** [comment]
Oh yea, should be done @HierarchyMan
