### ISSUE TITLE
about moderation

### ISSUE THREAD

**Issue by serumanooo** [diamond-rip/Eden#390]
i have this problem: when a moderator try to spec someone with /vanish + /tp, the players are invisible, i already reported this issue before

is it an easy thing to fix?

**Comment by GoodestEnglish** [comment]
As I said before , you cannot just tp to the player. A single arena can run multiple matches at the same time. Hence why you cannot see players when you are not a match spectator.

I was planning to make a moderation system for Eden. But well, there's a lot of bug report right now (I already ignored tons of feature requests as of right now to boost the development speed, but there's just a lot which I personally need time to fix.). So this system will prob be delayed.

**Comment by serumanooo** [comment]
> As I said before , you cannot just tp to the player. A single arena can run multiple matches at the same time. Hence why you cannot see players when you are not a match spectator.
> 
> I was planning to make a moderation system for Eden. But well, there's a lot of bug report right now (I already ignored tons of feature requests as of right now to boost the development speed, but there's just a lot which I personally need time to fix.). So this system will prob be delayed.

ohhh i didnt know a single arena could run multiple matches, now i understand, and im sorry for asking it again

and also, take your time to add features and fix bugs
