### ISSUE TITLE
boxing hits not registering and spams error

### ISSUE THREAD

**Issue by manrrr** [diamond-rip/Eden#393]
![image](https://github.com/diamond-rip/Eden/assets/106720465/09dac156-8cd8-4b53-8892-9f371830ef88)
I even left the game on my alt and I'm still in the match in my main account

**Comment by GoodestEnglish** [comment]
> ![image](https://user-images.githubusercontent.com/106720465/249493311-09dac156-8cd8-4b53-8892-9f371830ef88.png) I even left the game on my alt and I'm still in the match in my main account

Noted. But keep in mind you should update your config and language file in each updates. This error occurs because there's missing languages.

**Comment by GoodestEnglish** [comment]
Should be fixed in latest version, let me know the result :)
