### ISSUE TITLE
A new idea to edit a "Error"

### ISSUE THREAD

**Issue by liexes** [diamond-rip/Eden#395]
There is an error, well, I don't know if it is, anyway, there is a message that happens that when the user of a party leaves the game and tries to start another, a somewhat long error message appears that says eden:user@ Edenbla blah blah. Well, I suggest that you please add the option that the party owner can re-enter the players to another game, even if they are in one.

**Comment by Antoniova1** [comment]
![20230629_134444](https://github.com/diamond-rip/Eden/assets/108409110/6672c7ab-b402-40cd-9f05-0ac052d85727)
Same

**Comment by GoodestEnglish** [comment]
Its an error in my side. Will fix soon. Thanks for the report.

**Comment by liexes** [comment]
> Its an error in my side. Will fix soon. Thanks for the report.

Good, but please integrate the idea please

**Comment by liexes** [comment]
> > Its an error in my side. Will fix soon. Thanks for the report.
> 
> Good, but please integrate the idea please

@GoodestEnglish  please add the fuction to replay when the players as playing in arena

**Comment by GoodestEnglish** [comment]
> > > Its an error in my side. Will fix soon. Thanks for the report.
> 
> > 
> 
> > Good, but please integrate the idea please
> 
> 
> 
> @GoodestEnglish  please add the fuction to replay when the players as playing in arena

Do you mean replay feature?

**Comment by liexes** [comment]
> Do you mean replay feature where player can view their previous match?

No, I mean that you can play another new game in another mode, when the party's players are playing, this, in case the party owner makes a mistake in the mode and doesn't want the one he accidentally put, that he go out and put a new one.

**Comment by GoodestEnglish** [comment]
Will prob not going to be added. This will break a lot of the logic. Sorry
