### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by liexes** [diamond-rip/Eden#398]
This error run when have 10 players playing in the server: 
![image](https://github.com/diamond-rip/Eden/assets/121281203/74647252-020c-49a6-93d8-ace3601e5de0)

**Comment by GoodestEnglish** [comment]
This is a bungeecord error message🤣, not from Eden.

**Comment by liexes** [comment]
No bro.

I have all the bungeecord translated into Spanish, therefore if it was the bungeecord that message should be in Spanish, maybe it wasn't Eden that caused it, but the bungeecord is not.

**Comment by GoodestEnglish** [comment]
It is most likely not Eden causing it. Eden won't display that message.
