### ISSUE TITLE
titles

### ISSUE THREAD

**Issue by serumanooo** [diamond-rip/Eden#399]
@GoodestEnglish i think you already explained it but i still dont get it (maybe im dumb)

after the latest updates, the victory titles stopped showing, but idk what i have to do to make it work again

**Comment by GoodestEnglish** [comment]
Just change back the string from `null` to what you want to show :)

**Comment by serumanooo** [comment]
> Just change back the string from `null` to what you want to show :)

But i didnt put 'null' at the titles at language.yml
I actually didnt touch anything about the titles

**Comment by GoodestEnglish** [comment]
The latest version of how the language file handle is somewhat broken. I am going to fix it in next update (Hopefully)

**Comment by serumanooo** [comment]
> The latest version of how the language file handle is somewhat broken. I am going to fix it in next update (Hopefully)

Ok tysm

**Comment by GoodestEnglish** [comment]
Try the latest version and let me know the result.

**Comment by serumanooo** [comment]
@GoodestEnglish im sorry i think there was no problem (i dont actually know if there was one)

i tried the latest update and it didnt work for me, but ive seen in a clip made by my friend, that it was working

so i found that lunar client updated and they added a titles mod (i think they added this, idk, but it somehow auto disabled to me), so i could not see titles

**Comment by GoodestEnglish** [comment]
If you ever want to debug it, try use the default language file and see if it still happens or not.
