### ISSUE TITLE
probably NOT eden related

### ISSUE THREAD

**Issue by serumanooo** [diamond-rip/Eden#407]
i have a problem at my server, and i want suggestions of what it could be (also it can be eden related but i dont think eden has anything to do with this issue)

my server is a little bit laggy sometimes for me and other players (ill change the host of my server so it may be solved), but this happens everytime: i queue a match, when i get teleported to it, for the first like, 5 seconds i have 300 ms, then i get my normal 30 ms or something like that
and when im at a match and i get teleported back to the lobby i have like 400 ms, sometimes it doesnt even go down

i have some guesses

1- its client sidded, so its just my internet connection
2- its a host issue, so when i change the host it will be normal again
3- (i dont actually think its that but im asking it anyways because i want to be sure) could it be eden related? because like, it tends to happen when someone get teleported

also, im sorry for asking this here, i just want some help and i also want to be sure that its not eden related

**Comment by HierarchyMan** [comment]
> i have a problem at my server, and i want suggestions of what it could be (also it can be eden related but i dont think eden has anything to do with this issue)
> 
> my server is a little bit laggy sometimes for me and other players (ill change the host of my server so it may be solved), but this happens everytime: i queue a match, when i get teleported to it, for the first like, 5 seconds i have 300 ms, then i get my normal 30 ms or something like that
> and when im at a match and i get teleported back to the lobby i have like 400 ms, sometimes it doesnt even go down
> 
> i have some guesses
> 
> 1- its client sidded, so its just my internet connection
> 2- its a host issue, so when i change the host it will be normal again
> 3- (i dont actually think its that but im asking it anyways because i want to be sure) could it be eden related? because like, it tends to happen when someone get teleported
> 
> also, im sorry for asking this here, i just want some help and i also want to be sure that its not eden related
> 
> 

Happens when the connection to your database is slow
Consider moving hosts ASAP
I used to get 18tps when I used a bad mongo provider
Now I switched to official mongo and I now get 20tps stable

**Comment by serumanooo** [comment]
> > i have a problem at my server, and i want suggestions of what it could be (also it can be eden related but i dont think eden has anything to do with this issue)
> > my server is a little bit laggy sometimes for me and other players (ill change the host of my server so it may be solved), but this happens everytime: i queue a match, when i get teleported to it, for the first like, 5 seconds i have 300 ms, then i get my normal 30 ms or something like that
> > and when im at a match and i get teleported back to the lobby i have like 400 ms, sometimes it doesnt even go down
> > i have some guesses
> > 1- its client sidded, so its just my internet connection
> > 2- its a host issue, so when i change the host it will be normal again
> > 3- (i dont actually think its that but im asking it anyways because i want to be sure) could it be eden related? because like, it tends to happen when someone get teleported
> > also, im sorry for asking this here, i just want some help and i also want to be sure that its not eden related
> 
> Happens when the connection to your database is slow Consider moving hosts ASAP I used to get 18tps when I used a bad mongo provider Now I switched to official mongo and I now get 20tps stable

ok ill do it tysm
