### ISSUE TITLE
tournament permission not working

### ISSUE THREAD

**Issue by serumanooo** [diamond-rip/Eden#409]
i gave the eden.event.tournament and eden.event.sumo-event permissions for vip players
but they cant host an event, it says that they dont have permission

**Comment by serumanooo** [comment]
idk if its not working at the first time, so ill explain what happened: 
i created an event, we played it (im the server owner so i have op)
then i gave a streamer rank to a player because he wants to make an event at the next saturday, and it says he dont have permissions

**Comment by GoodestEnglish** [comment]
I haven't checked it yet due to i am not at home. Busy with midterm exam right now. I will get back to u in a few days.

**Comment by serumanooo** [comment]
> I haven't checked it yet due to i am not at home. Busy with midterm exam right now. I will get back to u in a few days.

Ok no problem, take your time :)

**Comment by GoodestEnglish** [comment]
I've tested it and it works fine. 
Note that you also have to give `eden.command.event.create` permission so the player can run the `/event create` command.

**Comment by serumanooo** [comment]
> I've tested it and it works fine. Note that you also have to give `eden.command.event.create` permission so the player can run the `/event create` command.

Ohhh ok tysm
