### ISSUE TITLE
player bug

### ISSUE THREAD

**Issue by serumanooo** [diamond-rip/Eden#412]
![image](https://github.com/diamond-rip/Eden/assets/132185379/784aa4ee-c870-4c8e-8bc6-b46131c63cb2)

i was playing a 4v4 at my server and sometimes when someone dies we can see like a clone of the player
i guess there is no errors in console

**Comment by serumanooo** [comment]
> What do you mean by clone? Is it not an actual player but a NPC?

like, the real player is flying and spectating the remaining players, but there is a clone of him at the location that he died
also there is a bug that the respawn screen appears, idk whats the cause, ill put a video here later

**Comment by GoodestEnglish** [comment]
Closing this as this is duplicated
