### ISSUE TITLE
Division system and titles

### ISSUE THREAD

**Issue by RainFallDev** [diamond-rip/Eden#413]
Hello can You add Division system like minemen club and cold network titles like    GodLike I / PlayerName
with command /titles

**Comment by pixeledge-verify** [comment]
> Hello can You add Division system like minemen club and cold network titles like GodLike I / PlayerName with command /titles

It's not really difficult. I used AlonsoLeagues and Skript to make a pretty good Divisions system on our server.

**Comment by pixeledge-verify** [comment]
```
on death:
	if victim is not in world "arena":
		execute console command "/liga removepoints %victim% 1 true"
	else:
		execute console command "/liga removepoints %victim% 3 true"

command /leave:
	trigger:
		set {Leet::%player's uuid%} to true
		make player execute command "/pixelpractice:leave"
		wait 1 seconds
		delete {Leet::%player's uuid%}

command /leavespectate:
	trigger:
		set {LeetingSpectating::%player's uuid%} to true
		make player execute command "/pixelpractice:leavespectate"
		wait 1 seconds
		delete {LeetingSpectating::%player's uuid%}

on world change:
	set {_leagueprog} to placeholder "alonsoleagues_progress" 
	if player's flight mode is false:
		if player is in world "LobbyPractice":
			if {Leet::%player's uuid%} is not set:
				if {LeetingSpectating::%player's uuid%} is not set:
					execute console command "/liga addpoints %player% 5 true"
					send "&fMatch Tier Results &3(+5) (%{_leagueprog}%&3)&r Points"
					delete {LeetingSpectating::%player's uuid%}
					delete {Leet::%player's uuid%}
	else if player's inventory is empty:
		if player is in world "LobbyPractice":
			if {Leet::%player's uuid%} is not set:
				if {LeetingSpectating::%player's uuid%} is not set:
					execute console command "/liga addpoints %player% 5 true"
					send "&fMatch Tier Results &3(+5) (%{_leagueprog}%&3)&r Points"
					delete {LeetingSpectating::%player's uuid%}
					delete {Leet::%player's uuid%}
	else if player has a paper:
		if player is in world "LobbyPractice":
			if {Leet::%player's uuid%} is not set:
				if {LeetingSpectating::%player's uuid%} is not set:
					execute console command "/liga addpoints %player% 5 true"
					send "&fMatch Tier Results &3(+5) (%{_leagueprog}%&3)&r Points"
					delete {LeetingSpectating::%player's uuid%}
					delete {Leet::%player's uuid%}
	else if player has a compass:
		delete {LeetingSpectating::%player's uuid%}
		delete {Leet::%player's uuid%}

on join:
	delete {LeetingSpectating::%player's uuid%}
	delete {Leet::%player's uuid%}

on quit:
	delete {LeetingSpectating::%player's uuid%}
	delete {Leet::%player's uuid%}
```

This is all required for our server, you can modify it to your own. Also you should use this version of Skript https://github.com/Matocolotoe/Skript-1.8/releases as it's up to date. Also you need Ersatz https://www.spigotmc.org/resources/ersatz.49433/

Here on death if player's in world Arena (I keep my boxing, buhc, nd maps and stuffs like these here) and other worlds are gamemodes such as Battle Rush which I cut 1 point from per death. But upon win and or lose I like to give them around 5 points (So they gets +2 points even if they lose) but if they die too much in Bridges and such they can lose points, it's your personal preference and if you don't want them to get points if they lose in nd buhc and stuffs, you could use the Ersatz to match placeholders if they increase or not and give them points via that all works pretty sure. Or you could go

```
on death:
    set {dead::%victim's uuid%} to true
    wait 1 second
    delete {dead::%victim's uuid%}
```

And modify the whole code to make it check if it's not set then give points if it's set don't make it give points.

**Comment by GoodestEnglish** [comment]
> Hello can You add Division system like minemen club and cold network titles like GodLike I / PlayerName with command /titles

Titles are planned! Here's all todo's which I am going to be worked on after some bug fixes. https://github.com/diamond-rip/Eden/discussions/categories/to-do-list?discussions_q=is%3Aopen+category%3A%22To-do+List%22+label%3A%22working+on%22

**Comment by RainFallDev** [comment]
Thank You
