### ISSUE TITLE
winspigot kb not working

### ISSUE THREAD

**Issue by RainFallDev** [diamond-rip/Eden#414]
i specified kb in kit and that kb is present but default kb is used no matter what

**Comment by serumanooo** [comment]
thats weird, for me it works just fine, the only problem i have is that i cant change the hit ticks, so i cant make a combo kit

**Comment by RainFallDev** [comment]
i will try foxspigot

**Comment by serumanooo** [comment]
> i will try foxspigot

Wait, i think i know what is the problem, try disabling asynchronous knockback

Dont use foxspigot, its bad

**Comment by RainFallDev** [comment]
ok

**Comment by RainFallDev** [comment]
do you know what is this ERROR: Cannot find match when explosion happens (X: -43.25 Y: 75.61 Z: 68.19 Pitch: 0 Yaw: 104.07) (ENDER_DRAGON)

**Comment by serumanooo** [comment]
> do you know what is this ERROR: Cannot find match when explosion happens (X: -43.25 Y: 75.61 Z: 68.19 Pitch: 0 Yaw: 104.07) (ENDER_DRAGON)

I actually dont know what this error means, but maybe @GoodestEnglish can help you, but i think you should send your entire console log here

Btw, did you disable the async knockback? Did it work?

**Comment by GoodestEnglish** [comment]
> do you know what is this ERROR: Cannot find match when explosion happens (X: -43.25 Y: 75.61 Z: 68.19 Pitch: 0 Yaw: 104.07) (ENDER_DRAGON)

Set `allow-end` to false and delete your world_end file. As a practice server, the end should not be used and should always be disabled.
