### ISSUE TITLE
Scoreboard

### ISSUE THREAD

**Issue by liexes** [diamond-rip/Eden#415]
My scoreboard dont run i cant see, please help me

**Comment by RainFallDev** [comment]
try chnage the settings /settings

**Comment by RainFallDev** [comment]
turn on scoreboard if this not working delete lang.yml

**Comment by GoodestEnglish** [comment]
Any error in console?

**Comment by liexes** [comment]
> Any error in console?

Noup

**Comment by liexes** [comment]
I can't afford to delete the whole lang.yml because I translated the whole plugin to my language

**Comment by liexes** [comment]
I trying iliminate the lang.yml and nothing continue equals...

**Comment by GoodestEnglish** [comment]
> I can't afford to delete the whole lang.yml because I translated the whole plugin to my language

By what I mean is backup your language.yml file, and try to let the plugin to regenerate the language.yml file. This action will make the language.yml file back to default.

**Comment by liexes** [comment]
I already did it, I deleted the whole language file and nothing, it's something from the version because I put back version 1.20 and the scoreboard is fine, and I can not say that the cause is that I did not add the changes that were made to me in the new update because if I added them to my file

**Comment by liexes** [comment]
> What do you mean by `and I can not say that the cause is that I did not add the changes that were made to me in the new update because if I added them to my file`?

That is, the cause is not my language file, because I implemented the messages of the new update

**Comment by GoodestEnglish** [comment]
So do you still have the scoreboard disappear issue right now?

**Comment by liexes** [comment]
Yes

**Comment by GoodestEnglish** [comment]
I am guessing there's something crashes the scoreboard. What plugins and spigot do you have?

**Comment by liexes** [comment]
No, no, I think that if that were the case, it doesn't work either in version 1.20.0 of the plugin, I don't use any other plugin that alters the scoreboard

**Comment by GoodestEnglish** [comment]
Well, there has to be. You said the default language.yml doesn't show the scoreboard. But everyone managed to get it works except for you. Even me have tested and it works for me. 

![image](https://github.com/diamond-rip/Eden/assets/45838505/250aeabe-b6bf-43ff-88a7-014433b2e595)

**Comment by liexes** [comment]
Yes sorry is a error for me
