### ISSUE TITLE
stats problem

### ISSUE THREAD

**Issue by serumanooo** [diamond-rip/Eden#418]
a player at my server tried to /stats and it said that it was not possible to find the player id and blah blah blah, but thats weird, because this player already played at the server before

he joined a sumo game and his stats was finally created, so idk what happened, it never happened before
i think this will not happen again, but ill keep this issue open for a while in case this continue happening

**Comment by serumanooo** [comment]
also, does someone know what this error means?
[15:42:38 WARN]: Exception in thread "ForkJoinPool.commonPool-worker-2" 
[15:42:38 WARN]: java.util.ConcurrentModificationException
[15:42:38 WARN]:        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1469)
[15:42:38 WARN]:        at java.util.HashMap$ValueIterator.next(HashMap.java:1498)
[15:42:38 WARN]:        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:95)
[15:42:38 WARN]:        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:60)
[15:42:38 WARN]:        at com.google.gson.Gson.toJson(Gson.java:593)
[15:42:38 WARN]:        at com.google.gson.Gson.toJson(Gson.java:572)
[15:42:38 WARN]:        at com.google.gson.Gson.toJson(Gson.java:527)
[15:42:38 WARN]:        at com.google.gson.Gson.toJson(Gson.java:507)
[15:42:38 WARN]:        at net.minecraft.server.v1_8_R3.JsonList.lambda$save$0(JsonList.java:162)
[15:42:38 WARN]:        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
[15:42:38 WARN]:        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[15:42:38 WARN]:        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[15:42:38 WARN]:        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
[15:42:38 WARN]:        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)

**Comment by GoodestEnglish** [comment]
> a player at my server tried to /stats and it said that it was not possible to find the player id and blah blah blah, but thats weird, because this player already played at the server before
> 
> he joined a sumo game and his stats was finally created, so idk what happened, it never happened before i think this will not happen again, but ill keep this issue open for a while in case this continue happening



> also, does someone know what this error means? [15:42:38 WARN]: Exception in thread "ForkJoinPool.commonPool-worker-2" [15:42:38 WARN]: java.util.ConcurrentModificationException [15:42:38 WARN]: at java.util.HashMap$HashIterator.nextNode(HashMap.java:1469) [15:42:38 WARN]: at java.util.HashMap$ValueIterator.next(HashMap.java:1498) [15:42:38 WARN]: at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:95) [15:42:38 WARN]: at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:60) [15:42:38 WARN]: at com.google.gson.Gson.toJson(Gson.java:593) [15:42:38 WARN]: at com.google.gson.Gson.toJson(Gson.java:572) [15:42:38 WARN]: at com.google.gson.Gson.toJson(Gson.java:527) [15:42:38 WARN]: at com.google.gson.Gson.toJson(Gson.java:507) [15:42:38 WARN]: at net.minecraft.server.v1_8_R3.JsonList.lambda$save$0(JsonList.java:162) [15:42:38 WARN]: at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402) [15:42:38 WARN]: at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [15:42:38 WARN]: at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [15:42:38 WARN]: at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [15:42:38 WARN]: at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
> 
> another error [2023-07-06-7.log](https://github.com/diamond-rip/Eden/files/11972220/2023-07-06-7.log)

I am not sure about the first one but the second one is related to protocollib.

**Comment by GoodestEnglish** [comment]
> a player at my server tried to /stats and it said that it was not possible to find the player id and blah blah blah, but thats weird, because this player already played at the server before
> 
> he joined a sumo game and his stats was finally created, so idk what happened, it never happened before i think this will not happen again, but ill keep this issue open for a while in case this continue happening

By any chance do you disable player stats saving for bukkit? (Not Eden player stats saving, I mean bukkit player stats saving)

**Comment by serumanooo** [comment]
> > a player at my server tried to /stats and it said that it was not possible to find the player id and blah blah blah, but thats weird, because this player already played at the server before
> > he joined a sumo game and his stats was finally created, so idk what happened, it never happened before i think this will not happen again, but ill keep this issue open for a while in case this continue happening
> 
> > also, does someone know what this error means? [15:42:38 WARN]: Exception in thread "ForkJoinPool.commonPool-worker-2" [15:42:38 WARN]: java.util.ConcurrentModificationException [15:42:38 WARN]: at java.util.HashMap$HashIterator.nextNode(HashMap.java:1469) [15:42:38 WARN]: at java.util.HashMap$ValueIterator.next(HashMap.java:1498) [15:42:38 WARN]: at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:95) [15:42:38 WARN]: at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:60) [15:42:38 WARN]: at com.google.gson.Gson.toJson(Gson.java:593) [15:42:38 WARN]: at com.google.gson.Gson.toJson(Gson.java:572) [15:42:38 WARN]: at com.google.gson.Gson.toJson(Gson.java:527) [15:42:38 WARN]: at com.google.gson.Gson.toJson(Gson.java:507) [15:42:38 WARN]: at net.minecraft.server.v1_8_R3.JsonList.lambda$save$0(JsonList.java:162) [15:42:38 WARN]: at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402) [15:42:38 WARN]: at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [15:42:38 WARN]: at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [15:42:38 WARN]: at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [15:42:38 WARN]: at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
> > another error [2023-07-06-7.log](https://github.com/diamond-rip/Eden/files/11972220/2023-07-06-7.log)
> 
> I am not sure about the first one but the second one is related to protocollib.

Ok tysm, the second one was crashing my server, now i can do something about it

**Comment by serumanooo** [comment]
> By any chance do you disable player stats saving for bukkit? (Not Eden player stats saving, I mean bukkit player stats saving)

Hmm idk ill check it

**Comment by serumanooo** [comment]
> > a player at my server tried to /stats and it said that it was not possible to find the player id and blah blah blah, but thats weird, because this player already played at the server before
> > he joined a sumo game and his stats was finally created, so idk what happened, it never happened before i think this will not happen again, but ill keep this issue open for a while in case this continue happening
> 
> By any chance do you disable player stats saving for bukkit? (Not Eden player stats saving, I mean bukkit player stats saving)

Whats the option? Is it in bukkit.yml?

**Comment by serumanooo** [comment]
@GoodestEnglish i just found this:
![image](https://github.com/diamond-rip/Eden/assets/132185379/bc15936d-f590-46f5-9f12-3d38026bd0c6)

**Comment by GoodestEnglish** [comment]
I am going to push a new version of /stats in next update. Let me know the results afterward the new update releases.

**Comment by GoodestEnglish** [comment]
Pushed a version to see if this issue still exists.
