### ISSUE TITLE
bridges gapple problem

### ISSUE THREAD

**Issue by serumanooo** [diamond-rip/Eden#419]
the first gapple gives absorption, but if you get hitted and eat another one, it doesnt give you absorption

**Comment by GoodestEnglish** [comment]
Isn't it what bridge gapple does?

I am not 100% sure but If I am not wrong, only the first gapple gives absorption hearts.

**Comment by serumanooo** [comment]
> Isn't it what bridge gapple does?
> 
> I am not 100% sure but If I am not wrong, only the first gapple gives absorption hearts.

im not sure, i dont actually play bridge, but i think all gapples give absorption hearts
anyways, you should create an option that if enabled, only the first gapple will give absorption

**Comment by MuriloFangel** [comment]
bridge player here. actually in hypixel, you have absorption once per life. every time you die your first gapple gives you absorption, but the next ones don't.

**Comment by serumanooo** [comment]
> 

Ill check later if this also happens in mmc

**Comment by HierarchyMan** [comment]
> > 
> 
> Ill check later if this also happens in mmc

In mmc all gapples give you absorption

**Comment by GoodestEnglish** [comment]
I see. I can add a config option for this.

**Comment by MuriloFangel** [comment]
> > > 
> > 
> > 
> > Ill check later if this also happens in mmc
> 
> In mmc all gapples give you absorption

actually it doesn't. see it yourself, after eating a gapple, you'll get absorption, but if you eat again, you will still have absorption, but if you take damage, it will not give you extra hearts.

**Comment by HierarchyMan** [comment]
> > > > 
> > > 
> > > 
> > > Ill check later if this also happens in mmc
> > 
> > In mmc all gapples give you absorption
> 
> actually it doesn't. see it yourself, after eating a gapple, you'll get absorption, but if you eat again, you will still have absorption, but if you take damage, it will not give you extra hearts. 

No

**Comment by HierarchyMan** [comment]
> > > > 
> > > 
> > > 
> > > Ill check later if this also happens in mmc
> > 
> > In mmc all gapples give you absorption
> 
> actually it doesn't. see it yourself, after eating a gapple, you'll get absorption, but if you eat again, you will still have absorption, but if you take damage, it will not give you extra hearts. 

Flawed observation
Minemen club has a heart display and every time you eat a gapple you get absorption even after you get hit and want to regen

**Comment by MuriloFangel** [comment]
> > > > > 
> > > > 
> > > > 
> > > > Ill check later if this also happens in mmc
> > > 
> > > 
> > > In mmc all gapples give you absorption
> > 
> > 
> > actually it doesn't. see it yourself, after eating a gapple, you'll get absorption, but if you eat again, you will still have absorption, but if you take damage, it will not give you extra hearts.
> 
> Flawed observation Minemen club has a heart display and every time you eat a gapple you get absorption even after you get hit and want to regen

bro wtf

**Comment by GoodestEnglish** [comment]
Added in latest release.
