### ISSUE TITLE
nicks showing twice at leaderboards

### ISSUE THREAD

**Issue by serumanooo** [diamond-rip/Eden#421]
![image](https://github.com/diamond-rip/Eden/assets/132185379/8e6b044f-d031-4d91-9995-2ee7bec4ea1f)

**Comment by GoodestEnglish** [comment]
What plugins do you have?

**Comment by serumanooo** [comment]
> What plugins do you have?

hmmm i think i know what is the problem, i think there is one serumano_ that is registered with my uuid, and i think there is another one that was generated before i started using nlogin, ill just delete it from the database

**Comment by GoodestEnglish** [comment]
Possibly. Note that Eden will only not support offline mode servers. Any issues caused by offline mode servers might cause issues and not receive a fix.
