### ISSUE TITLE
ImanitySpigot3 worldedit plugin crash

### ISSUE THREAD

**Issue by RainFallDev** [diamond-rip/Eden#423]
Hello my server using ImanitySpigot3 after i downloaded worldedit plugin and started my server the server has crashed i cant use eden without worldedit please help

**Comment by HierarchyMan** [comment]
yeah worldedit wont work with java 17 
@GoodestEnglish give him the modified ver that works with modern java and pin that message in discussions

**Comment by RainFallDev** [comment]
Thank i fixed this using java11

**Comment by HierarchyMan** [comment]
> Thank i fixed this using java11

Check ur discord

**Comment by RainFallDev** [comment]
ok

**Comment by GoodestEnglish** [comment]
Here's the version which supports java 8: https://drive.google.com/file/d/1NFjiRHj_pmB7XnPbSGQLICssNXE3Dd5T/view?usp=drive_link
