### ISSUE TITLE
Help :)

### ISSUE THREAD

**Issue by liexes** [diamond-rip/Eden#424]
@GoodestEnglish You have discord bro?

It's to talk to you about something in case you're interested

**Comment by GoodestEnglish** [comment]
I prefer github. If you really want to dm me then send me an email: goodestenglish@diamond.rip

**Comment by liexes** [comment]
You are interesed to work in a minecraft network with me?

Actuality: play.draby.us (I use your plugin to arenapvp minigame)

If you accept, we will become the 2 owners of my server, I promise that we will grow a lot, I consider myself a good configurator, although I still don't know java, I am looking for a course to learn and develop, I just hope and think about it and consider my proposal

@GoodestEnglish

**Comment by Chromaah** [comment]
honestly i highly doubt he will accept because of his projects but goodluck with your server lol

**Comment by GoodestEnglish** [comment]
Unfortunately no. I do not have time for more works currently and even if I do, I will choose to put more time to enhance the plugin to give user a better experience. But good luck on making your server!

**Comment by liexes** [comment]
Ok, thx
