### ISSUE TITLE
Saturation 

### ISSUE THREAD

**Issue by djtheta** [diamond-rip/Eden#426]
The saturation is always 0 at the beginning of a nodebuff match, which forces the player to have to eat steak only a few seconds after the match has begun. This is a very recent issue and didn't use to occur, any way I can fix it?

**Comment by GoodestEnglish** [comment]
> The saturation is always 0 at the beginning of a nodebuff match, which forces the player to have to eat steak only a few seconds after the match has begun. This is a very recent issue and didn't use to occur, any way I can fix it?

This is going to be fixed in next version with a configurable value in config. Don't worry :)

**Comment by HierarchyMan** [comment]
> > The saturation is always 0 at the beginning of a nodebuff match, which forces the player to have to eat steak only a few seconds after the match has begun. This is a very recent issue and didn't use to occur, any way I can fix it?
> 
> This is going to be fixed in next version with a configurable value in config. Don't worry :)

Lol (im still sorry)

**Comment by GoodestEnglish** [comment]
Added in latest release.
