### ISSUE TITLE
i have a problem

### ISSUE THREAD

**Issue by serumanooo** [diamond-rip/Eden#427]
i added some cosmetics to my server lobby, but there are some bugs and i want to know if there is a way to solve them
like, if a player throw an ender pearl gadget before the match starts (it happens with other gadgets too), he gets teleported back to the lobby while in match

so like, is there a way to eden prevent that from happening?

**Comment by GoodestEnglish** [comment]
No. Eden has no control to other plugin ender pearl teleportation.

**Comment by serumanooo** [comment]
> No. Eden has no control to other plugin ender pearl teleportation.

Ok ty
