### ISSUE TITLE
Disguise

### ISSUE THREAD

**Issue by TehJays** [diamond-rip/Eden#428]
What disguise plugins does Eden support? specifically FrozedDisguise.

**Comment by RainFallDev** [comment]
cCore Aquacore

**Comment by RainFallDev** [comment]
Aquacore or cCore cCore is fork of aquacore and free you can get it from here https://github.com/RainFallDev/cCore/releases/tag/cCore

**Comment by HierarchyMan** [comment]
Ccore is illegal
it is suggested you remove you messages
