### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by djtheta** [diamond-rip/Eden#429]
- Add an option for players to rate maps by stars at the end of the match (by clicking the text).
- Add setting for players to enable/disable showing players in lobby (this is player-specific)

**Comment by HierarchyMan** [comment]
Add option 2

**Comment by Chromaah** [comment]
hey we should add suggestions in the discussions tab :)

**Comment by GoodestEnglish** [comment]
Not touching any suggestions for now. There's too much enhancement which I couldn't handle atm. Sorry
