### ISSUE TITLE
new option not working for me

### ISSUE THREAD

**Issue by serumanooo** [diamond-rip/Eden#433]
![image](https://github.com/diamond-rip/Eden/assets/132185379/167a40e3-50ec-4362-b6ae-fcb5ea88fc0e)

(i know its an experimental option)

**Comment by RainFallDev** [comment]
what is this? is this clone the arena to other world?

**Comment by HierarchyMan** [comment]
> ![image](https://user-images.githubusercontent.com/132185379/252369955-167a40e3-50ec-4362-b6ae-fcb5ea88fc0e.png)
> 
> (i know its an experimental option)

I was about to report this
it does absolutely nothing
i had one arena and it allowed me to play on that one which shouldnt be the case
it should stop you from playing on arena number 0
AND PLease take note of this
*Everytime match ends PLEASE paste arena 0 onto arena 1 or higher* or else there would be no point

**Comment by GoodestEnglish** [comment]
> > ![image](https://user-images.githubusercontent.com/132185379/252369955-167a40e3-50ec-4362-b6ae-fcb5ea88fc0e.png)
> > (i know its an experimental option)
> 
> I was about to report this it does absolutely nothing i had one single arena (not cloned) and it allowed me to play on that one which shouldnt be the case it should stop you from playing on arena number 0 AND PLease take note of this _Everytime match ends PLEASE paste arena 0 onto arena 1 or higher_ or else there would be no point

This option isn't working rn. Will fix it in next update. Thanks for report.

I've been thinking about your idea and I do not think it works. Because the x coord and z coord of each block can be different. So paste arena 0 to arena 1 is not gonna work.

What am I going to do is I will make big changes in the arena chunk code and see if it works or not. I have some idea in my head. But since I don't have the reset issue. I will most likely tester and test it. I will post updates in discussions soon.

**Comment by serumanooo** [comment]
it actually happens when the server gets restarted (it happens even with auto-save disabled)

**Comment by serumanooo** [comment]
also, i disabled that new option because it was doing nothing, and then when someone queued a match, the player got teleported to the overworld, but idk if the world was corrupted or if its something with the config
but i dont think its something with the world because its a flat world, and the world they got teleported was a normal world

**Comment by HierarchyMan** [comment]
> > > ![image](https://user-images.githubusercontent.com/132185379/252369955-167a40e3-50ec-4362-b6ae-fcb5ea88fc0e.png)
> > > (i know its an experimental option)
> > 
> > I was about to report this it does absolutely nothing i had one single arena (not cloned) and it allowed me to play on that one which shouldnt be the case it should stop you from playing on arena number 0 AND PLease take note of this _Everytime match ends PLEASE paste arena 0 onto arena 1 or higher_ or else there would be no point
> 
> This option isn't working rn. Will fix it in next update. Thanks for report.
> 
> I've been thinking about your idea and I do not think it works. Because the x coord and z coord of each block can be different. So paste arena 0 to arena 1 is not gonna work.
> 
> What am I going to do is I will make big changes in the arena chunk code and see if it works or not. I have some idea in my head. But since I don't have the reset issue. I will most likely tester and test it. I will post updates in discussions soon.

Well they have different cords but there is an offset
So can u like place spawn a from 0 onto spawn a for 1?
Kinda like copy pasting in worldedit

**Comment by HierarchyMan** [comment]
> also, i disabled that new option because it was doing nothing, and then when someone queued a match, the player got teleported to the overworld, but idk if the world was corrupted or if its something with the config
> but i dont think its something with the world because its a flat world, and the world they got teleported was a normal world

Don't use multiple worlds it's not recommendable

**Comment by serumanooo** [comment]
> > also, i disabled that new option because it was doing nothing, and then when someone queued a match, the player got teleported to the overworld, but idk if the world was corrupted or if its something with the config
> > but i dont think its something with the world because its a flat world, and the world they got teleported was a normal world
> 
> Don't use multiple worlds it's not recommendable

even if this was the problem, that makes no sense, i have 2 worlds: 
the first one is a void world, so there is no grass or any blocks, just void and the lobby
the second one is a flat world, so idk how they got teleported to a normal mineceraft world

**Comment by HierarchyMan** [comment]
> even if this was the problem, that makes no sense, i have 2 worlds: 
> the first one is a void world, so there is no grass or any blocks, just void and the lobby
> the second one is a flat world, so idk how they got teleported to a normal mineceraft world
> 
> but anyways, i setted the option back to true and replaced the arenas world with a backup and it started working again

Ahh it seems u never had the unloading issue
If a world is unloaded and a plugin tries to send you there, it generates a normal world

**Comment by GoodestEnglish** [comment]
> > > > ![image](https://user-images.githubusercontent.com/132185379/252369955-167a40e3-50ec-4362-b6ae-fcb5ea88fc0e.png)
> > > > (i know its an experimental option)
> > > 
> > > 
> > > I was about to report this it does absolutely nothing i had one single arena (not cloned) and it allowed me to play on that one which shouldnt be the case it should stop you from playing on arena number 0 AND PLease take note of this _Everytime match ends PLEASE paste arena 0 onto arena 1 or higher_ or else there would be no point
> > 
> > 
> > This option isn't working rn. Will fix it in next update. Thanks for report.
> > I've been thinking about your idea and I do not think it works. Because the x coord and z coord of each block can be different. So paste arena 0 to arena 1 is not gonna work.
> > What am I going to do is I will make big changes in the arena chunk code and see if it works or not. I have some idea in my head. But since I don't have the reset issue. I will most likely tester and test it. I will post updates in discussions soon.
> 
> Well they have different cords but there is an offset So can u like place spawn a from 0 onto spawn a for 1? Kinda like copy pasting in worldedit

Chunk cannot do the offset thing. As chunk works differently. 


> it actually happens when the server gets restarted (it happens even with auto-save disabled)

@HierarchyMan Can you confirm this is true? (ONLY happens when the server restarted)

**Comment by GoodestEnglish** [comment]
At the same time @serumanooo , could you please test this version and see if the arena reset problem still exists?
https://drive.google.com/file/d/1Q4NaZwNjfMVOo2r3voUUA4Oh_QOKwBcK/view?usp=sharing

After you install this version, change `experiment.new-arena-chunk-cache` to true
![image](https://github.com/diamond-rip/Eden/assets/45838505/9b7fdcc4-cadd-4894-9ac2-e61c47cfc3b4)

**Comment by HierarchyMan** [comment]
>@GoodestEnglish Can you confirm this is true? (ONLY happens when the server restarted)

Yes, 100% true this happens after server restart
Could you use bedwars1058 logic? Like create a cache file for each arena when it's made first until /arena save in run again
When the server and and when arena has to reset paste cache onto arena

**Comment by GoodestEnglish** [comment]
> > @GoodestEnglish Can you confirm this is true? (ONLY happens when the server restarted)
> 
> Yes, 100% true this happens after server restart Could you use bedwars1058 logic? Like create a cache file for each arena when it's made first until /arena save in run again When the server and and when arena has to reset paste cache onto arena

Yes. I am going to test a few more logic soon. But if it doesn't work, yes I can use bedwars1058 logic.

**Comment by serumanooo** [comment]
> At the same time @serumanooo , could you please test this version and see if the arena reset problem still exists? https://drive.google.com/file/d/1Q4NaZwNjfMVOo2r3voUUA4Oh_QOKwBcK/view?usp=sharing
> 
> After you install this version, change `experiment.new-arena-chunk-cache` to true ![image](https://user-images.githubusercontent.com/45838505/252614743-9b7fdcc4-cadd-4894-9ac2-e61c47cfc3b4.png)

Ok ill try it, ill let you know if that works

**Comment by serumanooo** [comment]
> > even if this was the problem, that makes no sense, i have 2 worlds:
> > the first one is a void world, so there is no grass or any blocks, just void and the lobby
> > the second one is a flat world, so idk how they got teleported to a normal mineceraft world
> > but anyways, i setted the option back to true and replaced the arenas world with a backup and it started working again
> 
> Ahh it seems u never had the unloading issue If a world is unloaded and a plugin tries to send you there, it generates a normal world Dw ur worlds aren't corrupted restart server and everything should be fine

Yes i did that, i think your right so thats not directly relates to eden

**Comment by serumanooo** [comment]
> > At the same time @serumanooo , could you please test this version and see if the arena reset problem still exists? https://drive.google.com/file/d/1Q4NaZwNjfMVOo2r3voUUA4Oh_QOKwBcK/view?usp=sharing
> > After you install this version, change `experiment.new-arena-chunk-cache` to true ![image](https://user-images.githubusercontent.com/45838505/252614743-9b7fdcc4-cadd-4894-9ac2-e61c47cfc3b4.png)
> 
> Ok ill try it, ill let you know if that works

apparently it works @GoodestEnglish

**Comment by GoodestEnglish** [comment]
> > > At the same time @serumanooo , could you please test this version and see if the arena reset problem still exists? https://drive.google.com/file/d/1Q4NaZwNjfMVOo2r3voUUA4Oh_QOKwBcK/view?usp=sharing
> > > After you install this version, change `experiment.new-arena-chunk-cache` to true ![image](https://user-images.githubusercontent.com/45838505/252614743-9b7fdcc4-cadd-4894-9ac2-e61c47cfc3b4.png)
> > 
> > 
> > Ok ill try it, ill let you know if that works
> 
> apparently it works @GoodestEnglish

Do you mean by setting it to true it solved?
@HierarchyMan if you can, may you also help me to test? That would be much appreciated

**Comment by serumanooo** [comment]
> > > > At the same time @serumanooo , could you please test this version and see if the arena reset problem still exists? https://drive.google.com/file/d/1Q4NaZwNjfMVOo2r3voUUA4Oh_QOKwBcK/view?usp=sharing
> > > > After you install this version, change `experiment.new-arena-chunk-cache` to true ![image](https://user-images.githubusercontent.com/45838505/252614743-9b7fdcc4-cadd-4894-9ac2-e61c47cfc3b4.png)
> > > 
> > > 
> > > Ok ill try it, ill let you know if that works
> > 
> > 
> > apparently it works @GoodestEnglish
> 
> Do you mean by setting it to true it solved? @HierarchyMan if you can, may you also help me to test? That would be much appreciated

yes, i downloaded this version of eden and i setted this option to true, and i tested it sometimes (i also restarted the server while in match to test if this would cause any problem)
and there where no blocks when i restarted the server ( i tested it like 3 times)

**Comment by serumanooo** [comment]
@GoodestEnglish also, how the cloned arenas work? because i think i never played at a cloned arena, everytime i queued something at my server, i was at the original arena and i have like 3 clones of each arena (i havent tested it with more players playing at the same arena)

**Comment by serumanooo** [comment]
@GoodestEnglish just found this bug with the arena limits, can be related with 3 things:
1- i was playing at a clone of the original arena
2- the "disable-original-arena" option was set to true
3- the "new-arena-chunk-cache" option was set to true

or its just a bug related to this version you sent
