### ISSUE TITLE
title issue

### ISSUE THREAD

**Issue by serumanooo** [diamond-rip/Eden#435]
https://youtu.be/nQOrncoDt48

**Comment by Chromaah** [comment]
I have this issue too but they dissapear after quite a while

**Comment by RainFallDev** [comment]
yes i have this too

**Comment by GoodestEnglish** [comment]
Will be fixed soon. Accidentally used paperspigot's title api which makes title stay at the screen for 10 seconds (Oh my god)

**Comment by Chromaah** [comment]
@GoodestEnglish tried latest update (1.1.24) and the titles are still there for very long.

**Comment by serumanooo** [comment]
> > @GoodestEnglish tried latest update (1.1.24) and the titles are still there for very long.
> 
> Which title are you referring to?

https://youtu.be/JZP_LnR96AA

**Comment by Chromaah** [comment]
> > @GoodestEnglish tried latest update (1.1.24) and the titles are still there for very long.
> 
> Which title are you referring to?

Victory/Defeat titles

**Comment by GoodestEnglish** [comment]
> > > @GoodestEnglish tried latest update (1.1.24) and the titles are still there for very long.
> > 
> > 
> > Which title are you referring to?
> 
> Victory/Defeat titles

Will be fixed soon

**Comment by GoodestEnglish** [comment]
Should be fixed
