### ISSUE TITLE
Queue Swords (Air)

### ISSUE THREAD

**Issue by Nqvn** [diamond-rip/Eden#438]
When trying to right click and queue with both unranked and ranked swords, they don't when clicking and aiming in the air, only when aiming on a block. I know this is an easy fix for the source code so hopefully this can get fixed soon even next update.

I am on Java version 8 and am using Carbon spigot 2.3.5

**Comment by HierarchyMan** [comment]
> When trying to right click and queue with both unranked and ranked swords, they don't when clicking and aiming in the air, only when aiming on a block. I know this is an easy fix for the source code so hopefully this can get fixed soon even next update.

Ur prolly on later versions of game where right click air with swords isn't an even cuz sword blocking doesn't exist
So not really needed

**Comment by GoodestEnglish** [comment]
Works for me tho https://youtu.be/r0KoHDlR7yE

What spigot and plugin are you using? Sounds like something cancelled the player interaction

**Comment by HierarchyMan** [comment]
Oh yeah some spigots cancel right click air for performance (like rave spigot)

**Comment by serumanooo** [comment]
> When trying to right click and queue with both unranked and ranked swords, they don't when clicking and aiming in the air, only when aiming on a block. I know this is an easy fix for the source code so hopefully this can get fixed soon even next update.

what java version are you using at your server? you should use java 8, yesterday i tried to open my server with java 11 and i could not queue with the swords (also my server crashed because 80% of my plugins need to use java 8)

**Comment by Nqvn** [comment]
> > When trying to right click and queue with both unranked and ranked swords, they don't when clicking and aiming in the air, only when aiming on a block. I know this is an easy fix for the source code so hopefully this can get fixed soon even next update.
> 
> Ur prolly on later versions of game where right click air with swords isn't a thing cuz sword blocking doesn't exist So not really needed

Im on versions 1.8.9

**Comment by Nqvn** [comment]
> Works for me tho https://youtu.be/r0KoHDlR7yE
> 
> What spigot and plugin are you using? Sounds like something cancelled the player interaction

Carbon spigot

**Comment by Nqvn** [comment]
> > When trying to right click and queue with both unranked and ranked swords, they don't when clicking and aiming in the air, only when aiming on a block. I know this is an easy fix for the source code so hopefully this can get fixed soon even next update.
> 
> what java version are you using at your server? you should use java 8, yesterday i tried to open my server with java 11 and i could not queue with the swords (also my server crashed because 80% of my plugins need to use java 8)

I'm on java 8

**Comment by GoodestEnglish** [comment]
Can't really help if you are using a way too old version of carbon spigot. 
Please update it and test it again.

If you still facing this issue. Open a new issues.
Closing this for now
