### ISSUE TITLE
Still can't fly when spectating out of world. 

### ISSUE THREAD

**Issue by djtheta** [diamond-rip/Eden#440]
^ still can't fly when spectating an arena that isn't in the same world as the spawn.

**Comment by Chromaah** [comment]
multi world isnt supported as GoodestEnglish has mentioned multiple times before.

**Comment by GoodestEnglish** [comment]
> multi world isnt supported as GoodestEnglish has mentioned multiple times before.

^

But I am still testing more possibilities. Hopefully will solve this soon.
