### ISSUE TITLE
projectiles

### ISSUE THREAD

**Issue by serumanooo** [diamond-rip/Eden#441]
is there an option to disable that thing that makes the players able to throw projectiles at their own teammates? (like, egg, snowball and also the rod)

if no, could you add it?

**Comment by GoodestEnglish** [comment]
Forgot rod boosting exists (smh played too much hypixel)

Low priority

**Comment by Chromaah** [comment]
@GoodestEnglish can you also add an option to disable bow boosting in certain games/kits? (i hate it in bridge)

**Comment by serumanooo** [comment]
> @GoodestEnglish can you also add an option to disable bow boosting in certain games/kits? (i hate it in bridge)

YES PLEASE 😭

**Comment by serumanooo** [comment]
> @GoodestEnglish can you also add an option to disable bow boosting in certain games/kits? (i hate it in bridge)

yes please add this, the 90% of the bridge community hates that

**Comment by GoodestEnglish** [comment]
> @GoodestEnglish can you also add an option to disable bow boosting in certain games/kits? (i hate it in bridge)

Sure

**Comment by GoodestEnglish** [comment]
> is there an option to disable that thing that makes the players able to throw projectiles at their own teammates? (like, egg, snowball and also the rod)
> 
> if no, could you add it?

Do you mean to allow player able to throw projectile to teammate?
Because right now you should not able to do that

**Comment by serumanooo** [comment]
> > is there an option to disable that thing that makes the players able to throw projectiles at their own teammates? (like, egg, snowball and also the rod)
> > if no, could you add it?
> 
> Do you mean to allow player able to throw projectile to teammate? Because right now you should not able to do that

no, and yes im able to do that
https://youtu.be/C6rLSiLr5uI
and i remember you saying something about players being able to hit teammates with projectiles because of rod boost, so now im confused

**Comment by GoodestEnglish** [comment]
My bad. Anyway I am going to make this option.

**Comment by GoodestEnglish** [comment]
[Eden-1.1.24-BETA-593114b-all.jar.zip](https://github.com/diamond-rip/Eden/files/12027594/Eden-1.1.24-BETA-593114b-all.jar.zip)
Here's a in development version of Eden, which I added two new kit game rules - `team-projectile` and `bow-boosting` which allows you to configurate.

`team-projectile` means player can use projectile to shoot their teammate
`bow-boosting` mean uh... well self explained 

Let me know if there's any issues :)

**Comment by serumanooo** [comment]
> 

ok ill try it rn tysm

**Comment by serumanooo** [comment]
it works!

**Comment by GoodestEnglish** [comment]
Alright, then I am going to warp things up.

**Comment by Chromaah** [comment]
before you post the next official update, can you add suggestion 2 from the discussion tab list #355 ? i think i'd be cool to have a papi placeholder that displays this too, like %eden_player_team_color% for example, and %eden_player_team_letter%. 


oh also is there a placeholder that displays player status? like %eden_player_status% which returns 'PLAYING' if ingame, 'IN-QUEUE' if in queue and 'IN-LOBBY' if in lobby, etc.

tbh makes everything a lot cleaner, and adds more uses if you dont use integrated nametags

**Comment by Chromaah** [comment]
@GoodestEnglish

**Comment by GoodestEnglish** [comment]
> before you post the next official update, can you add suggestion 2 from the discussion tab list #355 ? i think i'd be cool to have a papi placeholder that displays this too, like %eden_player_team_color% for example, and %eden_player_team_letter%.
> 
> oh also is there a placeholder that displays player status? like %eden_player_status% which returns 'PLAYING' if ingame, 'IN-QUEUE' if in queue and 'IN-LOBBY' if in lobby, etc.
> 
> tbh makes everything a lot cleaner, and adds more uses if you dont use integrated nametags
> 
> (i also want this so that i can make my server look seamless, since this is how it is in bedwars and other of my servers)

Could you open another issues where we can discuss this? Unfortunately the version is ready and I want to prevent to change anything besides bug. But things like this, I can add it after this version.

**Comment by Chromaah** [comment]
Okay

**Comment by GoodestEnglish** [comment]
Added in latest release
