### ISSUE TITLE
battle rush bug

### ISSUE THREAD

**Issue by serumanooo** [diamond-rip/Eden#442]
https://youtu.be/ERZSwRLvjPU
it happens when someone hits a point by jumping the portal, the entire arena resets, but some high blocks dont reset
 (this bug just happens sometimes, i would say that 50% of the matches this bug does not happens)

btw, the blocks appear for all players

**Comment by GoodestEnglish** [comment]
Do you have `optimization.set-block-fast` to true? 
If yes, try to change it to false and see if it still occurs

**Comment by serumanooo** [comment]
> Do you have `optimization.set-block-fast` to true? If yes, try to change it to false and see if it still occurs

I have this issue for a long time, i was with the "optimization.set-block-fast" option disabled, but with that version you uploaded to google drive, i changed it to true, so yes, this option has no effect with this bug

**Comment by GoodestEnglish** [comment]
> > Do you have `optimization.set-block-fast` to true? If yes, try to change it to false and see if it still occurs
> 
> I have this issue for a long time, i was with the "optimization.set-block-fast" option disabled, but with that version you uploaded to google drive, i changed it to true, so yes, this option has no effect with this bug

The ghost block issue is a little complicated. I will need to investigate it further more. 
Will let you know if there's any updates.

**Comment by serumanooo** [comment]
> > > Do you have `optimization.set-block-fast` to true? If yes, try to change it to false and see if it still occurs
> > 
> > 
> > I have this issue for a long time, i was with the "optimization.set-block-fast" option disabled, but with that version you uploaded to google drive, i changed it to true, so yes, this option has no effect with this bug
> 
> The ghost block issue is a little complicated. I will need to investigate it further more. Will let you know if there's any updates.

ok tysm

**Comment by HierarchyMan** [comment]
I also need to report something regarding portal goal in general
Why is the portal goal radius so high?
I can sneak over the goal and I will still count as me jumping in the goal
Make it so that goal only registers when player touches end portal

**Comment by serumanooo** [comment]
> I also need to report something regarding portal goal in general Why is the portal goal radius so high? I can sneak over the goal and I will still count as me jumping in the goal Make it so that goal only registers when player touches end portal And dont allow goal registration 1 block above it's too much

also there is this thing that when a player strikes the last point, the enemy players die and you get stuck into the portal or you keep falling in void, make this so the enemy players dont die, just clear all the items of the players inventory (and also give the play again paper), and make ONLY the player that striked the last point be teleported to his spawn location

(i think thats what happens in minemen club, i can check later and post a video here if you want me to)

**Comment by Chromaah** [comment]
> > I also need to report something regarding portal goal in general Why is the portal goal radius so high? I can sneak over the goal and I will still count as me jumping in the goal Make it so that goal only registers when player touches end portal And dont allow goal registration 1 block above it's too much
> 
> also there is this thing that when a player strikes the last point, the enemy players die and you get stuck into the portal or you keep falling in void, make this so the enemy players dont die, just clear all the items of the players inventory (and also give the play again paper), and make ONLY the player that striked the last point be teleported to his spawn location
> 
> (i think thats what happens in minemen club, i can check later and post a video here if you want me to)

yes this is one of my many NEEDED suggestions in the discussions tab @GoodestEnglish they should be in high priority tbh (after the bugs ofc)

**Comment by GoodestEnglish** [comment]
> I also need to report something regarding portal goal in general Why is the portal goal radius so high? I can sneak over the goal and I will still count as me jumping in the goal Make it so that goal only registers when player touches end portal And dont allow goal registration 1 block above it's too much

Fixing this soon



> > I also need to report something regarding portal goal in general Why is the portal goal radius so high? I can sneak over the goal and I will still count as me jumping in the goal Make it so that goal only registers when player touches end portal And dont allow goal registration 1 block above it's too much
> 
> also there is this thing that when a player strikes the last point, the enemy players die and you get stuck into the portal or you keep falling in void, make this so the enemy players dont die, just clear all the items of the players inventory (and also give the play again paper), and make ONLY the player that striked the last point be teleported to his spawn location
> 
> (i think thats what happens in minemen club, i can check later and post a video here if you want me to)

I can make the scorer teleport back to spawn location. But what do you mean by "enemy players don't die"?

**Comment by serumanooo** [comment]
> > I also need to report something regarding portal goal in general Why is the portal goal radius so high? I can sneak over the goal and I will still count as me jumping in the goal Make it so that goal only registers when player touches end portal And dont allow goal registration 1 block above it's too much
> 
> Fixing this soon
> 
> > > I also need to report something regarding portal goal in general Why is the portal goal radius so high? I can sneak over the goal and I will still count as me jumping in the goal Make it so that goal only registers when player touches end portal And dont allow goal registration 1 block above it's too much
> > 
> > 
> > also there is this thing that when a player strikes the last point, the enemy players die and you get stuck into the portal or you keep falling in void, make this so the enemy players dont die, just clear all the items of the players inventory (and also give the play again paper), and make ONLY the player that striked the last point be teleported to his spawn location
> > (i think thats what happens in minemen club, i can check later and post a video here if you want me to)
> 
> I can make the scorer teleport back to spawn location. But what do you mean by "enemy players don't die"?

If my memory is good, in mmc, when you lose a game like bridges or batte rush, you dont die, you just get the play again paper and the match finishes (and obviously the players cant reach eachother anymore)

**Comment by GoodestEnglish** [comment]
I've personally tested in MMC. MMC teleports all players back to their spawn location, not just only one.

Do you want me to do that or you want only scorer will teleport back to spawn location?

**Comment by serumanooo** [comment]
> I've personally tested in MMC. MMC teleports all players back to their spawn location, not just only one.
> 
> Do you want me to do that or you want only scorer will teleport back to spawn location?

My bad, i forgot about it, i want both players getting teleported

**Comment by GoodestEnglish** [comment]
> > I've personally tested in MMC. MMC teleports all players back to their spawn location, not just only one.
> > Do you want me to do that or you want only scorer will teleport back to spawn location?
> 
> My bad, i forgot about it, i want both players getting teleported
> 
> Also, did you already see the arena limit issue?

Alright. Thanks for clarify.

Yes I am looking into it.
