### ISSUE TITLE
arena limit bug

### ISSUE THREAD

**Issue by serumanooo** [diamond-rip/Eden#443]
@GoodestEnglish just found this bug with the arena limits, can be related with 3 things:
https://youtu.be/peIiKUhl0Rw

its a bug related to the experimental version you sent

also, could you please make the spec area bigger? because of this: https://youtu.be/dKO4w5nR6bo

**Comment by GoodestEnglish** [comment]
> @GoodestEnglish just found this bug with the arena limits, can be related with 3 things: https://youtu.be/peIiKUhl0Rw
> 
> its a bug related to the experimental version you sent
> 
> also, could you please make the spec area bigger? because of this: https://youtu.be/dKO4w5nR6bo

Did you setup portal-goal-protection in your arena edit menu?

I am making a new config option for the spectate arena thing.

**Comment by serumanooo** [comment]
> > @GoodestEnglish just found this bug with the arena limits, can be related with 3 things: https://youtu.be/peIiKUhl0Rw
> > its a bug related to the experimental version you sent
> > also, could you please make the spec area bigger? because of this: https://youtu.be/dKO4w5nR6bo
> 
> Did you setup portal-goal-protection in your arena edit menu?
> 
> I am making a new config option for the spectate arena thing.

My arena limit is not working in general, like, some players queued it and they made a 7k blocks bridge at the side of the arena

Btw, my arena limit does not have the portal in it, so they should not be able to put blocks in there

And like i said before, everything works fine with the stable version of eden

**Comment by GoodestEnglish** [comment]
> > > @GoodestEnglish just found this bug with the arena limits, can be related with 3 things: https://youtu.be/peIiKUhl0Rw
> > > its a bug related to the experimental version you sent
> > > also, could you please make the spec area bigger? because of this: https://youtu.be/dKO4w5nR6bo
> > 
> > 
> > Did you setup portal-goal-protection in your arena edit menu?
> > I am making a new config option for the spectate arena thing.
> 
> My arena limit is not working in general, like, some players queued it and they made a 7k blocks bridge at the side of the arena
> 
> Btw, my arena limit does not have the portal in it, so they should not be able to put blocks in there
> 
> And like i said before, everything works fine with the stable version of eden

What do you mean by "your arena limit does not have the portal in it"?

Can you also send your arena.yml?

May you test this version and see if the cuboid protection is solved or not? (Or something you don't like) https://drive.google.com/file/d/1nnxWSHH4BEEHm53hSekUJ7l6g2VkHgiB/view?usp=sharing

**Comment by serumanooo** [comment]
> 

Like, the portal is outside the arena limit because of the hippo thing i mentionated like one or two months ago

Yes i can send it, just wait a minute

Also ill try to test it rn

**Comment by serumanooo** [comment]
> > > > @GoodestEnglish just found this bug with the arena limits, can be related with 3 things: https://youtu.be/peIiKUhl0Rw
> > > > its a bug related to the experimental version you sent
> > > > also, could you please make the spec area bigger? because of this: https://youtu.be/dKO4w5nR6bo
> > > 
> > > 
> > > Did you setup portal-goal-protection in your arena edit menu?
> > > I am making a new config option for the spectate arena thing.
> > 
> > 
> > My arena limit is not working in general, like, some players queued it and they made a 7k blocks bridge at the side of the arena
> > Btw, my arena limit does not have the portal in it, so they should not be able to put blocks in there
> > And like i said before, everything works fine with the stable version of eden
> 
> What do you mean by "your arena limit does not have the portal in it"?
> 
> Can you also send your arena.yml?
> 
> May you test this version and see if the cuboid protection is solved or not? (Or something you don't like) https://drive.google.com/file/d/1nnxWSHH4BEEHm53hSekUJ7l6g2VkHgiB/view?usp=sharing
> 
> Edit: Use this link instead. This link also added all players teleport back to match spawn location when a team wins https://drive.google.com/file/d/1_7M-vq-qZP_Uq6viN1AjqKQ3TXHTaH8K/view?usp=sharing

ok, btw i have a question, does these characters stand for something? or are they like random characters?
![image](https://github.com/diamond-rip/Eden/assets/132185379/2733f181-3e1c-4cac-95a2-0d3a6af4edc9)

im just curious about it

**Comment by serumanooo** [comment]
@GoodestEnglish 
https://drive.google.com/file/d/1CvIoK9eb17ujz7RTF8-0v_u7SK3LNFiW/view?usp=sharing

**Comment by serumanooo** [comment]
> > 
> 
> Like, the portal is outside the arena limit because of the hippo thing i mentionated like one or two months ago
> 
> Yes i can send it, just wait a minute
> 
> Also ill try to test it rn

https://youtu.be/j5wMAY0Qjf4

**Comment by serumanooo** [comment]
hey @GoodestEnglish i tested this version you just sent me and the arena limit bug was solved, now everything works fine look:
https://youtu.be/jMFVi2uAAoc
(im sorry for sending too much messages)

**Comment by serumanooo** [comment]
ive tested it
as you can see here i still cant fly without the skript
https://youtu.be/9lsDGHyeQlE

and here you can see that the spectator cuboid seems solved (idk if you actually changed something about that, if you didnt change anything, then its just because its a smaller map)
https://youtu.be/OYZqggNkfuo

and here you can see that the teleport thing is fixed at battle rush, but the enemy player still die
https://youtu.be/g91ijdMZtHo

**Comment by serumanooo** [comment]
> The number behind the version tag means which commit is it related to. This allows me to track my old code and locate the issue faster ![image](https://user-images.githubusercontent.com/45838505/252960054-e71216d8-8a2a-46e1-b232-47e0eab0ae44.png)
> 
> I do solve the spectator cuboid thing. The value is now configurable ;) (In next version)
> 
> The "die" thing is an animation. Which means the player didn't actually die. You can disable it by setting config `match.death-animation` to false

ohhh, so i think thats the also thing thats causing the "player clone" sometimes when someone dies

**Comment by GoodestEnglish** [comment]
> > ohhh, so i think thats also the thing thats causing the "player clone" sometimes when someone dies and also ty for the explanation
> 
> @GoodestEnglish https://youtu.be/7YrB2W5fDYY i tried disabling it and the enemy player still dies and i cant see him (i think its because eden kills the player to finish the match, but this should not happen in gamemodes that have point system enabled)

This is because when player go into the portal, it triggers the "die" method which allows Eden to trigger the "win" method. I can do something to the message. But not the visibility due to the complexity. If I have to do that I have to recode the whole visibility system basically.

The option in config only disable the animation of the death. Nothing changes with visibility.

**Comment by GoodestEnglish** [comment]
> > Edit: Use this link instead. This link also added all players teleport back to match spawn location when a team wins https://drive.google.com/file/d/1_7M-vq-qZP_Uq6viN1AjqKQ3TXHTaH8K/view?usp=sharing
> 
> I hope this doesn't break only reset looser position after point Can you confirm goodestenglish or can someone test?

Shouldn't be. Tested with latest version.

**Comment by GoodestEnglish** [comment]
> as you can see here i still cant fly without the skript

May you test it with the latest release? I did some changes and I personally tested it is working now.
