### ISSUE TITLE
player uuid

### ISSUE THREAD

**Issue by RainFallDev** [diamond-rip/Eden#444]
can you change /party  accept uuid                             to
/party accept player                   ?

**Comment by HierarchyMan** [comment]
+1

**Comment by GoodestEnglish** [comment]
Which command are you referring to? There's no party accept command in Eden. Do you mean party join command?

**Comment by arm4xlll** [comment]
maybe he was talking about /duel accept? It seems to be using uuid

**Comment by HierarchyMan** [comment]
> Which command are you referring to? There's no party accept command in Eden. Do you mean party join command?

Whatever command it is just make it use player name instead of uuid cuz illogical

**Comment by RainFallDev** [comment]
can you add player name and remov player uuid

**Comment by GoodestEnglish** [comment]
If that's the case, I can do it.
But the command I can think of which uses UUID is duel accept command. Party join command uses player's username.

**Comment by GoodestEnglish** [comment]
Will be added in next version
