### ISSUE TITLE
hotfix pls

### ISSUE THREAD

**Issue by serumanooo** [diamond-rip/Eden#446]
https://youtu.be/-LL9YCAQNfg

also i can spam /party announce in the chat

**Comment by GoodestEnglish** [comment]
[Eden-1.1.25-BETA-6a824c9-all.jar.zip](https://github.com/diamond-rip/Eden/files/12050892/Eden-1.1.25-BETA-6a824c9-all.jar.zip)

Try this version and let me know if it is fixed or not

**Comment by serumanooo** [comment]
> [Eden-1.1.25-BETA-6a824c9-all.jar.zip](https://github.com/diamond-rip/Eden/files/12050892/Eden-1.1.25-BETA-6a824c9-all.jar.zip)
> 
> Try this version and let me know if it is fixed or not

its fixed, but i found more problems, im going to create a new issue

**Comment by GoodestEnglish** [comment]
Pushed a new update related to this
