### ISSUE TITLE
fireball and tnt not working

### ISSUE THREAD

**Issue by serumanooo** [diamond-rip/Eden#447]
before the latest update, the tnt and fireball were both working, but now the fireball does like 4 hearts of damage and it doesnt give any knockback

https://youtu.be/7UYFFaZt_Pk

also the tnt is invisible, but idk if its eden related (the tnt is working fine, this is the only problem i have with it)
and the fireball was fine too, the damage was low and the knockback was good

im using windspigot

**Comment by serumanooo** [comment]
> before the latest update, the tnt and fireball were both working, but now the fireball does like 4 hearts of damage and it doesnt give any knockback
> 
> https://youtu.be/7UYFFaZt_Pk
> 
> also the tnt is invisible, but idk if its eden related (the tnt is working fine, this is the only problem i have with it)
> 
> im using windspigot

some days ago the tnt was invisible in my server, but i fixed it, it was related to world edit, but now this bug returned and idk what to do

**Comment by serumanooo** [comment]
![image](https://github.com/diamond-rip/Eden/assets/132185379/170649df-5c9a-4928-a49b-eaa9e406a78e)
![image](https://github.com/diamond-rip/Eden/assets/132185379/6b2ea336-f6d8-4343-be07-c7753c842b9e)
![image](https://github.com/diamond-rip/Eden/assets/132185379/2d88bf33-3374-4366-b7ce-088c16fca197)
![image](https://github.com/diamond-rip/Eden/assets/132185379/08cda5bb-da4a-499e-9923-b5bd28a8ced5)

**Comment by GoodestEnglish** [comment]
Pretty sure TNT invisible is not related to Eden. I've personally tested it and doesn't have this error.

About knockback/damage, it is a problem in my side. Will fix soon

**Comment by serumanooo** [comment]
> Pretty sure TNT invisible is not related to Eden. I've personally tested it and doesn't have this error.
> 
> About knockback/damage, it is a problem in my side. Will fix soon

Ok thanks

**Comment by GoodestEnglish** [comment]
Fixed
