### ISSUE TITLE
fly working

### ISSUE THREAD

**Issue by serumanooo** [diamond-rip/Eden#449]
now it works, the only problem is that i dont actually spawn flying

**Comment by GoodestEnglish** [comment]
> now it works, the only problem is that i dont actually spawn flying

What do you mean by spawn flying? Do you mean the player isn't flying when spectating?
I've personally tested and it works.

**Comment by serumanooo** [comment]
> > now it works, the only problem is that i dont actually spawn flying
> 
> What do you mean by spawn flying? Do you mean the player isn't flying when spectating? I've personally tested and it works.

Like, i need to hit space 2 times before i start to fly
