### ISSUE TITLE
Kit saving issue

### ISSUE THREAD

**Issue by HierarchyMan** [diamond-rip/Eden#45]
kittransfer works but only till restart
after restart all kits reset
i even tried creating a new kit normally but it wasnt saved in kit.yml
you need to fix that kits are saved in kit.yml becuz its just blank
otherwise not bad

**Comment by GoodestEnglish** [comment]
The issue is noted. I accidentally mistyped the file name to from kit.yml to arena.yml. Will push a quick fix soon

**Comment by GoodestEnglish** [comment]
Please redownload https://github.com/diamond-rip/Eden/releases/tag/1.0.22-BETA-097ee8b
