### ISSUE TITLE
How can i configure Tab prefixes

### ISSUE THREAD

**Issue by Hwaanx** [diamond-rip/Eden#450]
I want to make people see their ranks in tab but i don't know how  to do it in eden config

**Comment by Chromaah** [comment]
tbh just use TAB plugin

**Comment by Hwaanx** [comment]
> tbh just use TAB plugin

tab plugin f's everything up it doesn't even work.

**Comment by serumanooo** [comment]
> > tbh just use TAB plugin
> 
> tab plugin f's everything up it doesn't even work.

it works, you just need to configure it

but i suggest you to do one of these 2 things:

1- use a combination of luckperms + leaftags + leafscore + placeholder api (disable the scoreboard of leafscore, just use the tab)

or

2- use a core, like aquacore, ccore, etc

but if you just need a plugin to change your tablist, just use TAB or leafscore and you should be fine

**Comment by Hwaanx** [comment]
I have titanium spigot with luckperms and papi and i want to use eden's tab.

**Comment by serumanooo** [comment]
> I have titanium spigot with luckperms and papi and i want to use eden's tab.

Wdym by "i want people to see their ranks in tab"?
Like, do you want a part that says "Rank: <examplerank>", or youre talking about the colored name with the tag at the side of it in tab?

**Comment by serumanooo** [comment]
Well, if its the first option, you just have to get the correct placeholder and put it at your tablist config at language.yml

But if its the second option, youll have to config the tags at luckperms, but i dont recommend making rank tags with luckperms, i just use it for permissions, i prefer to use leaftags

> > I have titanium spigot with luckperms and papi and i want to use eden's tab.
> 
> Wdym by "i want people to see their ranks in tab"? Like, do you want a part that says "Rank: ", or youre talking about the colored name with the tag at the side of it in tab?

**Comment by Hwaanx** [comment]
[Owner] Hwaann in tab.  
![image](https://github.com/diamond-rip/Eden/assets/112027449/69f497e5-8ff6-475e-a0a7-f4538800fdde)
i don't know what to put there.

**Comment by GoodestEnglish** [comment]
> [Owner] Hwaann in tab. ![image](https://user-images.githubusercontent.com/112027449/253630449-69f497e5-8ff6-475e-a0a7-f4538800fdde.png) i don't know what to put there in the format section @serumanooo

I assume you want to do something like `[OWNER] GoodestEnglish`
Then use `%luckperms_prefix%{player-name}`

**Comment by Hwaanx** [comment]
thanks but i figured that out.
