### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by liexes** [diamond-rip/Eden#452]
Since the previous ticket is so long and disorganized, I organized it here with my proposal, you are free to see what I can do with this suggestion in the previous ticket:

Suggestion: New placeholders to add new fuctions (I am willing to work on systems that you cannot implement, to give to users.)

Placeholders

%eden_countdown_start% the same for %eden_countdown_respawn% Gives the kit countdown at the start of the game, this is set in the kit editing menu, for example by default it is at (5) and if the kit creator modifies it, then to walk as assigned (5, 4, 3, 2, 1, 0, -1) I can make when the counter reaches 0 with this placeholder create certain events, create a box at position x, return the player to the x position, send a title to the player, etc. (It is necessary to add the -1 or when reaching 0 it will be executing this action all the time, the 0 can also be changed to "Started" or "Playing"

%eden_arena_name% Returns the name of the arena the player is in, the name is the one imposed by the creator of the arena, for example "Rubiks" if the player is not in an arena then it could return "None"

%eden_kit_name% This gives the name of the kit in which the user is, for example if he is in bedwars it throws the message or in my case variable, "Bedwars" If he is not in any kit playing, it could give "None" or " not playing"

%eden_equip% This will return the player's equipment in an arena, if it is in an arena like bedwars which is custom then it might return the messages set in the message.yml example "Red and blue".

Old ticket: #432

**Comment by GoodestEnglish** [comment]
The only placeholder I will add is %eden_match_arena_name% and %eden_match_kit_name%.

I will not change my codebase just to add placeholders which isn't use a lot.

**Comment by liexes** [comment]
And %eden_countdown% ? for place in the title custom o bossbar

**Comment by liexes** [comment]
This placeholder can be used to place a title or anywhere, to make the server more customizable. @GoodestEnglish

**Comment by liexes** [comment]
Please, only add the placeholders of %eden_countdown% and %eden_position_a% I only need these 2 and I never ask for anything else, they are just simple placeholders that only give text or plugin numbers. Please add them, I ask you please.

**Comment by liexes** [comment]
@GoodestEnglish

**Comment by GoodestEnglish** [comment]
No. Please stop, asking.

**Comment by Chromaah** [comment]
I found some uses for placeholders like these in other plugins, so it would be cool if you had it on your to-do, your choice tho

**Comment by Aleextt** [comment]
I think the same, I have a mode that is survival type where players start with a cabin, the placeholder %eden_position_<a / b> would serve so that the users of my server will be oriented towards the cabin again if they get lost and also the placeholder of the count would serve me to put it in a customizable bar

**Comment by liexes** [comment]
Apparently there are people to whom it would also serve but everything remains in you @GoodestEnglish and forgive and bother you too much.
