### ISSUE TITLE
Suggestion command

### ISSUE THREAD

**Issue by liexes** [diamond-rip/Eden#453]
Add please the command /eden:duel <player> <kit> (optional) <arena>

this is very util for a custom duel menu, example:

![image](https://github.com/diamond-rip/Eden/assets/121281203/dacacd74-0e3e-4f9f-8c66-fdb03e2f54ce)

**Comment by liexes** [comment]
This menu is designer for my using 2 plugins, conditional events and deluxemenus (I can send code)

**Comment by GoodestEnglish** [comment]
Most likely not going to add unless I published the menu customization update.
