### ISSUE TITLE
Tab Suggestion

### ISSUE THREAD

**Issue by Hwaanx** [diamond-rip/Eden#454]
Make the tab increase by player count.
![image](https://github.com/diamond-rip/Eden/assets/112027449/a4bda839-9b53-4bbf-9fe7-ef8b3da42548)
This is just way too much space instead make it like this.
![image](https://github.com/diamond-rip/Eden/assets/112027449/3f1a8901-0c90-4659-9e8a-76fdeff48bb4)

**Comment by Chromaah** [comment]
use TAB by neznamy plugin for something like that.

**Comment by GoodestEnglish** [comment]
> Make the tab increase by player count. ![image](https://user-images.githubusercontent.com/112027449/253692600-a4bda839-9b53-4bbf-9fe7-ef8b3da42548.png) This is just way too much space instead make it like this. ![image](https://user-images.githubusercontent.com/112027449/253693134-3f1a8901-0c90-4659-9e8a-76fdeff48bb4.png)

Eden will stay tablist like this by now. You can always disable Eden's tablist to have your own tablist in config
