### ISSUE TITLE
show health option not working

### ISSUE THREAD

**Issue by serumanooo** [diamond-rip/Eden#455]
![image](https://github.com/diamond-rip/Eden/assets/132185379/f2027cc6-d1b7-4696-928e-1fc37880812a)
![image](https://github.com/diamond-rip/Eden/assets/132185379/c05fbe55-5209-429a-a170-c9b8648b4ae8)

**Comment by Chromaah** [comment]
I dont think thats something that will update ingame immediately, does it not work even if you leave the game and rejoin again?

**Comment by serumanooo** [comment]
> I dont think thats something that will update ingame immediately, does it not work even if you leave the game and rejoin again?

it was disabled and working before the latest updates, i didnt actually change it midgame

**Comment by Chromaah** [comment]
weird

**Comment by GoodestEnglish** [comment]
Not sure but might due to world changes. World changes always makes unexpected problems. This is why I dislike world changes.
But I will look into it cuz this shouldn't happen at first.

**Comment by GoodestEnglish** [comment]
Can't reproduce this. Make sure there's nothing affects the nametag changes. Do you have any plugin which modify nametag/tablist/scoreboard?

**Comment by serumanooo** [comment]
> Can't reproduce this. Make sure there's nothing affects the nametag changes. Do you have any plugin which modify nametag/tablist/scoreboard?

oh i forgot to update this issue, i just restarted my server and it started working, my bad
