### ISSUE TITLE
lag problem

### ISSUE THREAD

**Issue by serumanooo** [diamond-rip/Eden#458]
i was talking with the support of the host im using because my server was lagging, and they found that some plugins were having errors and lagging my server, and one of them is eden, here is my logs:

[latest (11).log](https://github.com/diamond-rip/Eden/files/12065201/latest.11.log)
go to line 894

is there a way to solve it?
they said this error is caused when eden tries to teleport a player from one area to another one

**Comment by GoodestEnglish** [comment]
First of all, I need to have your timings log so I can know what exactly happened.

Second, the error is because the player is logging in too fast. Not because Eden tries to teleport a player. I will solve this in next update. This error have no impact with in game experience.

**Comment by serumanooo** [comment]
> First of all, I need to have your timings log so I can know what exactly happened.
> 
> Second, the error is because the player is logging in too fast. Not because Eden tries to teleport a player. I will solve this in next update. This error have no impact with in game experience.

Sorry, forgot to mention 2 things:

They said Eden is NOT the main reason of the lag
And idk if its really a problem, they said this can be one of the problems

(And i know you said this has no impact in game, i just wanted to clarify)

And ill send you my timings log

**Comment by Chromaah** [comment]
> > First of all, I need to have your timings log so I can know what exactly happened.
> > Second, the error is because the player is logging in too fast. Not because Eden tries to teleport a player. I will solve this in next update. This error have no impact with in game experience.
> 
> Sorry, forgot to mention 2 things:
> 
> They said Eden is NOT the main reason of the lag And idk if its really a problem, they said this can be one of the problems
> 
> (And i know you said this has no impact in game, i just wanted to clarify what they said to me)
> 
> and i also solved the lag of my server, it was being caused by another plugin
> 
> edit: there is nothing wrong with eden in the timings log

i have the same issue but ik its not eden, which plugin was it for you? just incase i also have it @serumanooo

**Comment by serumanooo** [comment]
> > > First of all, I need to have your timings log so I can know what exactly happened.
> > > Second, the error is because the player is logging in too fast. Not because Eden tries to teleport a player. I will solve this in next update. This error have no impact with in game experience.
> > 
> > 
> > Sorry, forgot to mention 2 things:
> > They said Eden is NOT the main reason of the lag And idk if its really a problem, they said this can be one of the problems
> > (And i know you said this has no impact in game, i just wanted to clarify what they said to me)
> > and i also solved the lag of my server, it was being caused by another plugin
> > edit: there is nothing wrong with eden in the timings log
> 
> i have the same issue but ik its not eden, which plugin was it for you? just incase i also have it @serumanooo

Leaftags, it was trying to update the nametags of the players every second
