### ISSUE TITLE
tags issue

### ISSUE THREAD

**Issue by serumanooo** [diamond-rip/Eden#459]
ive found a weird issue at my server, a nametag of a player was going from green to orange, like this:
https://youtu.be/OmP1VBtzpmw

and we found how to do this glitch, it happens when the player try to log in too fast
here is my logs
[2023-07-17-4.log](https://github.com/diamond-rip/Eden/files/12072550/2023-07-17-4.log)
go from line 700 to line 845+

i think it can be eden related because of this: 
[14:44:12] [Server thread/ERROR]: Could not pass event PlayerQuitEvent to Eden v1.1.25-BETA-79af067

also this can be the cause of the error at line 845+
its a very annoying error because it crashes my server

let me know if it is eden's fault and if it can be fixed
(im using windspigot)

**Comment by serumanooo** [comment]
also take a look at this part:
Caused by: java.lang.NullPointerException
    at rip.diamond.practice.party.Party.getByPlayer(Party.java:38) ~[?:?]
    at rip.diamond.practice.party.PartyListener.onQuit(PartyListener.java:37) ~[?:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_312]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_312]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_312]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_312]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:297) ~[WindSpigot-2.1.2.jar:]
    ... 29 more

a friend was taking a look at the logs and he said this part might be important

**Comment by GoodestEnglish** [comment]
> also take a look at this part: Caused by: java.lang.NullPointerException at rip.diamond.practice.party.Party.getByPlayer(Party.java:38) ~[?:?] at rip.diamond.practice.party.PartyListener.onQuit(PartyListener.java:37) ~[?:?] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_312] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_312] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_312] at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_312] at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:297) ~[WindSpigot-2.1.2.jar:] ... 29 more
> 
> a friend was taking a look at the logs and he said this part might be important


It is not important. But you can use this first if you don't want this happen again

[Eden-1.1.26-BETA-79af067-all.jar.zip](https://github.com/diamond-rip/Eden/files/12075011/Eden-1.1.26-BETA-79af067-all.jar.zip)

**Comment by GoodestEnglish** [comment]
> ive found a weird issue at my server, a nametag of a player was going from green to orange, like this: https://youtu.be/OmP1VBtzpmw
> 
> and we found how to do this glitch, it happens when the player try to log in too fast here is my logs [2023-07-17-4.log](https://github.com/diamond-rip/Eden/files/12072550/2023-07-17-4.log) go from line 700 to line 845+
> 
> i think it can be eden related because of this: [14:44:12] [Server thread/ERROR]: Could not pass event PlayerQuitEvent to Eden v1.1.25-BETA-79af067
> 
> also this can be the cause of the error at line 845+ its a very annoying error because it crashes my server
> 
> let me know if it is eden's fault and if it can be fixed (im using windspigot)

Look at line 855. A plugin which is obfuscated by the author of the plugin (Looks like a auth plugin called login? Idk) is the main problem. You have to contact the plugin developer so I can know what exactly happened on the line of the code.

The error looks like something which related to inventory.

**Comment by serumanooo** [comment]
> > ive found a weird issue at my server, a nametag of a player was going from green to orange, like this: https://youtu.be/OmP1VBtzpmw
> > and we found how to do this glitch, it happens when the player try to log in too fast here is my logs [2023-07-17-4.log](https://github.com/diamond-rip/Eden/files/12072550/2023-07-17-4.log) go from line 700 to line 845+
> > i think it can be eden related because of this: [14:44:12] [Server thread/ERROR]: Could not pass event PlayerQuitEvent to Eden v1.1.25-BETA-79af067
> > also this can be the cause of the error at line 845+ its a very annoying error because it crashes my server
> > let me know if it is eden's fault and if it can be fixed (im using windspigot)
> 
> Look at line 855. A plugin which is obfuscated by the author of the plugin (Looks like a auth plugin called login? Idk) is the main problem. You have to contact the plugin developer so I can know what exactly happened on the line of the code.
> 
> The error looks like something which related to inventory.
> 
> About the nametag, do you have any extra tablist/nametag plugin? Looks like something is modifying the nametag.

ok ill talk with them
and what do you mean by related to inventory?
yes im using leaftags, but this should have no incompatibility considering im using leaftags placeholder at eden
![image](https://github.com/diamond-rip/Eden/assets/132185379/a4b0335a-2738-4308-8684-8eee2fcf2f9f)

and it just happens when the server tries to block a player from joining too fast

**Comment by serumanooo** [comment]
> > also take a look at this part: Caused by: java.lang.NullPointerException at rip.diamond.practice.party.Party.getByPlayer(Party.java:38) ~[?:?] at rip.diamond.practice.party.PartyListener.onQuit(PartyListener.java:37) ~[?:?] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_312] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_312] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_312] at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_312] at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:297) ~[WindSpigot-2.1.2.jar:] ... 29 more
> > a friend was taking a look at the logs and he said this part might be important
> 
> It is not important. But you can use this first if you don't want this happen again
> 
> [Eden-1.1.26-BETA-79af067-all.jar.zip](https://github.com/diamond-rip/Eden/files/12075011/Eden-1.1.26-BETA-79af067-all.jar.zip)

ok ill try it

**Comment by serumanooo** [comment]
> > Look at line 855. A plugin which is obfuscated by the author of the plugin (Looks like a auth plugin called login? Idk) is the main problem. You have to contact the plugin developer so I can know what exactly happened on the line of the code.
> > The error looks like something which related to inventory.
> > About the nametag, do you have any extra tablist/nametag plugin? Looks like something is modifying the nametag.


@GoodestEnglish i spoke with the nlogin creator and they said they are going to fix this problem, and now i know what do you mean by this being related to the inventory
![image](https://github.com/diamond-rip/Eden/assets/132185379/4ce61306-a977-4b25-8d0b-8b04cc9bde56)
they told me to disable that option:
![image](https://github.com/diamond-rip/Eden/assets/132185379/77b500bb-3c3a-47da-bf51-1e449230bbc1)


tysm for the help, this error is so annoying and i didnt know what was the cause of it

**Comment by GoodestEnglish** [comment]
> > > Look at line 855. A plugin which is obfuscated by the author of the plugin (Looks like a auth plugin called login? Idk) is the main problem. You have to contact the plugin developer so I can know what exactly happened on the line of the code.
> > > The error looks like something which related to inventory.
> > > About the nametag, do you have any extra tablist/nametag plugin? Looks like something is modifying the nametag.
> 
> @GoodestEnglish i spoke with the nlogin creator and they said they are going to fix this problem, and now i know what do you mean by this being related to the inventory ![image](https://user-images.githubusercontent.com/132185379/254259619-4ce61306-a977-4b25-8d0b-8b04cc9bde56.png) they told me to disable that option: ![image](https://user-images.githubusercontent.com/132185379/254259758-77b500bb-3c3a-47da-bf51-1e449230bbc1.png)
> 
> tysm for the help, this error is so annoying and i didnt know what was the cause of it and about the player nickname changing colors at tablist, ill just add a antibot plugin so the player cant join too fast (i dont actually know if this is going to work)

From the error you've sent. I can only say it is related to inventory. The main cause is from the nlogin plugin and because of the plugin is obfuscated, I have no idea.

**Comment by serumanooo** [comment]
> > > > Look at line 855. A plugin which is obfuscated by the author of the plugin (Looks like a auth plugin called login? Idk) is the main problem. You have to contact the plugin developer so I can know what exactly happened on the line of the code.
> > > > The error looks like something which related to inventory.
> > > > About the nametag, do you have any extra tablist/nametag plugin? Looks like something is modifying the nametag.
> > 
> > 
> > @GoodestEnglish i spoke with the nlogin creator and they said they are going to fix this problem, and now i know what do you mean by this being related to the inventory ![image](https://user-images.githubusercontent.com/132185379/254259619-4ce61306-a977-4b25-8d0b-8b04cc9bde56.png) they told me to disable that option: ![image](https://user-images.githubusercontent.com/132185379/254259758-77b500bb-3c3a-47da-bf51-1e449230bbc1.png)
> > tysm for the help, this error is so annoying and i didnt know what was the cause of it and about the player nickname changing colors at tablist, ill just add a antibot plugin so the player cant join too fast (i dont actually know if this is going to work)
> 
> From the error you've sent. I can only say it is related to inventory. The main cause is from the nlogin plugin and because of the plugin is obfuscated, I have no idea.

they said they are going to fix this, so i dont think i need to worry about it
