### ISSUE TITLE
Match variable 

### ISSUE THREAD

**Issue by Antoniova1** [diamond-rip/Eden#461]
I have a custom menu of the kits and now the number of players in that kit is not detected, this variable "player isn't in a match" appears instead of the numerical quantity as in the default menu of the plugin, and only it returns to being numeric when I'm in a game but the one in the lobby sees that text and not the number value, this is the variable I'm using %eden_match_unranked_examplekit%

Image custom menu
![20230717_163830](https://github.com/diamond-rip/Eden/assets/108409110/b3596052-5a52-4280-8dd2-0c10df8c6b11)

Image default menú
![20230717_163856](https://github.com/diamond-rip/Eden/assets/108409110/a25db92d-58f2-4cdd-b5df-20b32b494cb5)

**Comment by GoodestEnglish** [comment]
Use this as a temp solution as of right now. Will be fixed in next version
[Eden-1.1.26-BETA-79af067-all.jar.zip](https://github.com/diamond-rip/Eden/files/12075058/Eden-1.1.26-BETA-79af067-all.jar.zip)

**Comment by Antoniova1** [comment]
Ty ty
