### ISSUE TITLE
arrows before match start

### ISSUE THREAD

**Issue by serumanooo** [diamond-rip/Eden#464]
https://youtu.be/RaJizNND1ew

you can shoot arrows while freezed

**Comment by serumanooo** [comment]
also, like, when you start a match and you dont select a kit, you get the default kit, could you make this optional?

**Comment by Chromaah** [comment]
> also, like, when you start a match and you dont select a kit, you get the default kit automatically, could you make this optional?

I agree, or like be default make it select their default loadout that they set, unless there is none that they set

**Comment by GoodestEnglish** [comment]
> https://youtu.be/RaJizNND1ew
> 
> you can shoot arrows while freezed

That should be normal. In bridge you should be allow to pre-fire (If I didn't remember wrong)

**Comment by serumanooo** [comment]
> > https://youtu.be/RaJizNND1ew
> > you can shoot arrows while freezed
> 
> That should be normal. In bridge you should be allow to pre-fire (If I didn't remember wrong)

In mmc i think you can only shoot arrows after the start of the match, ill check later

**Comment by HierarchyMan** [comment]
> > https://youtu.be/RaJizNND1ew
> > 
> > you can shoot arrows while freezed
> 
> That should be normal. In bridge you should be allow to pre-fire (If I didn't remember wrong)
> 
> 

You are correct, don't remove that
Just make it so u only get default kit if you die without selecting a book
Otherwise let play player play with a book in their hands

**Comment by HierarchyMan** [comment]
> > > https://youtu.be/RaJizNND1ew
> > > you can shoot arrows while freezed
> > 
> > That should be normal. In bridge you should be allow to pre-fire (If I didn't remember wrong)
> 
> In mmc i think you can only shoot arrows after the start of the match, ill check later

And if you decide to add the arrow thing
Don't use on player interact event if contains right click cancel event true 
Use something that won't allow bow shoot idk which even that it

**Comment by serumanooo** [comment]
> > https://youtu.be/RaJizNND1ew
> > you can shoot arrows while freezed
> 
> That should be normal. In bridge you should be allow to pre-fire (If I didn't remember wrong)

https://youtu.be/gVQp-J7Zxz8

**Comment by GoodestEnglish** [comment]
> > > https://youtu.be/RaJizNND1ew
> > > you can shoot arrows while freezed
> > 
> > 
> > That should be normal. In bridge you should be allow to pre-fire (If I didn't remember wrong)
> 
> https://youtu.be/gVQp-J7Zxz8

Smh another difference between hypixel and MMC :/ Why they can't work the same
I can make a config option for this.



> > > https://youtu.be/RaJizNND1ew
> > > you can shoot arrows while freezed
> > 
> > 
> > That should be normal. In bridge you should be allow to pre-fire (If I didn't remember wrong)
> 
> You are correct, don't remove that Just make it so u only get default kit if you die without selecting a book Otherwise let play player play with a book in their hands

Yea that works



> > > > https://youtu.be/RaJizNND1ew
> > > > you can shoot arrows while freezed
> > > 
> > > 
> > > That should be normal. In bridge you should be allow to pre-fire (If I didn't remember wrong)
> > 
> > 
> > In mmc i think you can only shoot arrows after the start of the match, ill check later
> 
> And if you do decide to add the arrow thing Don't use on player interact event if contains right click cancel event true Use something that won't allow bow shoot idk which even that is

It's called ProjectileLaunchEvent

**Comment by HierarchyMan** [comment]
> > > > https://youtu.be/RaJizNND1ew
> > > > you can shoot arrows while freezed
> > > 
> > > 
> > > That should be normal. In bridge you should be allow to pre-fire (If I didn't remember wrong)
> > 
> > https://youtu.be/gVQp-J7Zxz8
> 
> Smh another difference between hypixel and MMC :/ Why they can't work the same
> I can make a config option for this.
> 
> 
> 
> > > > https://youtu.be/RaJizNND1ew
> > > > you can shoot arrows while freezed
> > > 
> > > 
> > > That should be normal. In bridge you should be allow to pre-fire (If I didn't remember wrong)
> > 
> > You are correct, don't remove that Just make it so u only get default kit if you die without selecting a book Otherwise let play player play with a book in their hands
> 
> Yea that works
> 
> 
> 
> > > > > https://youtu.be/RaJizNND1ew
> > > > > you can shoot arrows while freezed
> > > > 
> > > > 
> > > > That should be normal. In bridge you should be allow to pre-fire (If I didn't remember wrong)
> > > 
> > > 
> > > In mmc i think you can only shoot arrows after the start of the match, ill check later
> > 
> > And if you do decide to add the arrow thing Don't use on player interact event if contains right click cancel event true Use something that won't allow bow shoot idk which even that is
> 
> It's called ProjectileLaunchEvent

Yo thanks
Good luck

**Comment by GoodestEnglish** [comment]
Added in latest update
