### ISSUE TITLE
Fireworks question

### ISSUE THREAD

**Issue by Miab0** [diamond-rip/Eden#468]
Hi! The fireworks when scoring a point on The Bridge (or kits with the portal game rule) last 5 seconds. However, when modifying the countdown for a new round it does not match. So my question is if you can change the duration of the fireworks to the duration of the new round countdown, so that it always matches (something similar to the duration of the titles).
I hope this is understood, thanks!

**Comment by Chromaah** [comment]
there's fireworks??

**Comment by GoodestEnglish** [comment]
Will make it match in the next update. Thanks for the notify.

And yes there's fireworks

**Comment by Chromaah** [comment]
> Will make it match in the next update. Thanks for the notify.
> 
> And yes there's fireworks

What where i dont see them, i know hypixel and other servers have them but i havent seen them in eden @GoodestEnglish

**Comment by GoodestEnglish** [comment]
When you score you should see them. If you don't see them its either something blocked you from seeing the firework, or it is a bug in my side (I am not at home so I cannot test it rn)

**Comment by Chromaah** [comment]
> When you score you should see them. If you don't see them its either something blocked you from seeing the firework, or it is a bug in my side (I am not at home so I cannot test it rn)

when was this added wtf?

and no i dont see them or hear them, where do they spawn? also would using multiple worlds break it? (i have used multi worlds with no issues so far)

**Comment by Chromaah** [comment]
@GoodestEnglish i did some testing and i dont see them at all, using CarbonSpigot

**Comment by GoodestEnglish** [comment]
Tested and it isn't display for me also. Will investigate it further

**Comment by Miab0** [comment]
For reference on my server it works everytime, the arenas and spawn are in the same world and uses PandaSpigot

**Comment by GoodestEnglish** [comment]
So I found the issue. The issue is caused by ProtocolLib version 5.0.0.
Looks like this is a bug from ProtocolLib. If you wish to see the firework effect, downgrade your ProtocolLib version to 4.8.0.
