### ISSUE TITLE
Scoreboard 

### ISSUE THREAD

**Issue by Antoniova1** [diamond-rip/Eden#472]
This usually happens sometimes, when I turn on my server I get this error https://pastebin.com/jhknNPSY, when I am already on the server the scoreboard does not appear and it appears again when I turn the server off and on again

**Comment by Chromaah** [comment]
this doesnt happen to me, please when reporting issues like these provide information about your server and also logs

**Comment by Antoniova1** [comment]
in that pastebin it is the only one that appears in my console, but as I say it only happens sometimes
I use pandaspigot 1.8.8

**Comment by GoodestEnglish** [comment]
It is a bug in my side. Will work on this.
