### ISSUE TITLE
bot duel (LOW PRIORITY)

### ISSUE THREAD

**Issue by serumanooo** [diamond-rip/Eden#475]
i think it would be cool if eden had /botduel in the future, it would probably use citizens as dependency

**Comment by Chromaah** [comment]
Theres priv addon but it doesnt even work well anyways, i believe goodest english said he did not have it planned for the plugin

**Comment by GoodestEnglish** [comment]
> i think it would be cool if eden had /botduel in the future, it would probably use citizens as dependency

As @Chromaah said, there's a private addon which isn't complete, and no plan to complete it because bot isn't something I am interested to work on. You can buy a, I would say, half complete botduel plugin addon which is $15, but you will need an external developer to continue to work on it.
