### ISSUE TITLE
ProtocolLib dependency

### ISSUE THREAD

**Issue by Hwaanx** [diamond-rip/Eden#477]
Why do we need to install protocollib it would be better if i don't have to instal it.

**Comment by Chromaah** [comment]
because the plugin needs features and stuff from it codewise, hence why its called a DEPENDENCY. Just install it its not that hard

**Comment by Hwaanx** [comment]
its not hard but i don't want it. I know protocollib does stuff with packets but i don't know what eden does with packets.

**Comment by Chromaah** [comment]
> its not hard but i don't want it. I know protocollib does stuff with packets but i don't know what eden does with packets.

Whats wrong with having it... huh

**Comment by Chromaah** [comment]
Dont quote me but i believe eden does tons of stuff with packets and protocollib really helps with that..

**Comment by Hwaanx** [comment]
i don't know i'll wait till goodestenglish replies

**Comment by GoodestEnglish** [comment]
> Why do we need to install protocollib it would be better if i don't have to instal it.

It is used for entity hiding. A single arena can have multiple match running. Hence why we need protocollib to hide players and entity like snowball and arrow. So player will not see other stuff which is in another fight.

**Comment by Antoniova1** [comment]
> > ¿Por qué necesitamos instalar protocollib? Sería mejor si no tengo que instalarlo.
> 
> Se utiliza para ocultar entidades. Una sola arena puede tener varios partidos en marcha. Por eso necesitamos protocollib para ocultar jugadores y entidades como bola de nieve y flecha. Entonces el jugador no verá otras cosas que están en otra pelea.

I have a question related to that, I have a plugin that uses victory dances, death effects etc, so if you say that there can be more than one match in an arena, is it possible that these effects are visible to the other match?

**Comment by GoodestEnglish** [comment]
> I have a question related to that, I have a plugin that uses victory dances, death effects etc, so if you say that there can be more than one match in an arena, is it possible that these effects are visible to the other match?

Yes it will display for other players too.
