### ISSUE TITLE
question

### ISSUE THREAD

**Issue by serumanooo** [diamond-rip/Eden#479]
![image](https://github.com/diamond-rip/Eden/assets/132185379/f570c72c-e8a8-43c7-8786-13d44089c2e3)
what is the right way to put commands in here? like this? without the "/"?

**Comment by GoodestEnglish** [comment]
```yml
lobby-only-commands:
- "/fly"
- "/skin"
```

**Comment by serumanooo** [comment]
> ```yaml
> lobby-only-commands:
> - "/fly"
> - "/skin"
> ```

Idk why but the way i showed in the screenshot worked for me, but ill fix my config thanks
