### ISSUE TITLE
party split problem 

### ISSUE THREAD

**Issue by serumanooo** [diamond-rip/Eden#485]
https://youtu.be/Coj9pfp_4iI
basically you dont get teleported and you cant fly, also you receive a "fake" teleportation tool

**Comment by GoodestEnglish** [comment]
[Eden-1.1.27-BETA-795c2d2-all.jar.zip](https://github.com/diamond-rip/Eden/files/12157576/Eden-1.1.27-BETA-795c2d2-all.jar.zip)
Try this version and let me know if this is fixed or not.

**Comment by GoodestEnglish** [comment]
Fixed
