### ISSUE TITLE
team projectiles

### ISSUE THREAD

**Issue by serumanooo** [diamond-rip/Eden#488]
https://youtu.be/O4lTBJbSObE
after the latest update, this option isnt working
also, the "show health" option sometimes does not work (like, 90% of the time it works fine)

**Comment by GoodestEnglish** [comment]
> https://youtu.be/O4lTBJbSObE after the latest update, this option isnt working also, the "show health" option sometimes does not work (like, 90% of the time it works fine)

[Eden-1.1.27-BETA-795c2d2-all.jar.zip](https://github.com/diamond-rip/Eden/files/12157642/Eden-1.1.27-BETA-795c2d2-all.jar.zip)
Test this version and let me know if this is fixed or not.

**Comment by serumanooo** [comment]
> [Eden-1.1.27-BETA-795c2d2-all.jar.zip](https://github.com/diamond-rip/Eden/files/12157642/Eden-1.1.27-BETA-795c2d2-all.jar.zip) Test this version and let me know if this is fixed or not.

https://youtu.be/dCcHSEVMVJY
i dont know if these other issues are fixed but i found a new one with this version you sent me

**Comment by serumanooo** [comment]
> > [Eden-1.1.27-BETA-795c2d2-all.jar.zip](https://github.com/diamond-rip/Eden/files/12157642/Eden-1.1.27-BETA-795c2d2-all.jar.zip) Test this version and let me know if this is fixed or not.
> 
> https://youtu.be/dCcHSEVMVJY i dont know if these other issues are fixed but i found a new one with this version you sent me

ive checked and i dont really know if its something with the version, i think i fixed it but now im using the latest stable version so idk

**Comment by GoodestEnglish** [comment]
Which latest stable version are you using?

**Comment by serumanooo** [comment]
> Which latest stable version are you using? I've personally tested the version I've sent and it works for me

yes, it was a bug with the spigot i was trying to use idk
