### ISSUE TITLE
time limit (please)

### ISSUE THREAD

**Issue by serumanooo** [diamond-rip/Eden#497]
![image](https://github.com/diamond-rip/Eden/assets/132185379/edafc10f-b595-4f0a-8c8e-8738cfa82560)
😭

**Comment by Chromaah** [comment]
have that as an option, i don't like time limit personally

**Comment by serumanooo** [comment]
> have that as an option, i don't like time limit personally
> 
> Edit: maybe kit gamerule? some kits should have time limit.

Yes thats what i meant, sorry for not explaining, i want a kit gamerule that enables match time limit

**Comment by GoodestEnglish** [comment]
Closing this as this is duplicated with #420
