### ISSUE TITLE
AsyncChatPlayer issue

### ISSUE THREAD

**Issue by Hwaanx** [diamond-rip/Eden#499]
![image](https://github.com/diamond-rip/Eden/assets/112027449/d838d080-bdf2-49fe-bc65-972e449182f6)

**Comment by Hwaanx** [comment]
This happened to me when i was trying to remove a potion effect from my kit

**Comment by Hwaanx** [comment]
![image](https://github.com/diamond-rip/Eden/assets/112027449/03d27e96-9fce-4fbe-9cd0-94555276c91f)

but i think this is ./kit in general

**Comment by Hwaanx** [comment]
-{SPEED} doesn't work.

**Comment by GoodestEnglish** [comment]
You are using the wrong syntax. The `{` `}` is just a placeholder. You have to remove those bracket and insert your potion effect.

For example, `-speed`
