### ISSUE TITLE
Knockback per kit

### ISSUE THREAD

**Issue by HierarchyMan** [diamond-rip/Eden#50]
Add option in kit.yml to specify the kb you want to use cuz the current system isn't very efficient

**Comment by GoodestEnglish** [comment]
May you explain why the current system isn't very efficient?

**Comment by HierarchyMan** [comment]
Why do I have to name each kit according to the kb profile I want on it
Why can't I just specify which profile I want to apply

**Comment by GoodestEnglish** [comment]
Fair enough. It will be added soon

**Comment by HierarchyMan** [comment]
@GoodestEnglish 
Do u have a yt channel where u can devlog?

**Comment by GoodestEnglish** [comment]
I do have one, but I don't do dev stream/log there.

**Comment by HierarchyMan** [comment]
Send link I will sub

**Comment by HierarchyMan** [comment]
Also read my latest thing is discussions

**Comment by HierarchyMan** [comment]
I dont mean to spam but any updates?

**Comment by Zhuyuan0907** [comment]
> I dont mean to spam but any updates?

maybe we can just take it easy. If you wanna to have update faster, then maybe you can write code by yourself.
Goodest is busy, we can understand him .w.
sorry for poor English

**Comment by HierarchyMan** [comment]
Yeah I totally understand
You can take as much time as you need
I wish you good luck for your school year
- cystol

**Comment by GoodestEnglish** [comment]
Fixed in https://github.com/diamond-rip/Eden/releases/tag/1.0.26-BETA-f29a0a8
