### ISSUE TITLE
potions bug

### ISSUE THREAD

**Issue by serumanooo** [diamond-rip/Eden#508]
https://youtu.be/jFY2vhNO2TU

i think its related to the fork i was using at this video 
(im using paper + kb plugin, im trying every fork and plugins to see which one has the better kb)

**Comment by liexes** [comment]
What is your kb plugin?

**Comment by serumanooo** [comment]
> What is your kb plugin?

PvPenhanced

**Comment by Miab0** [comment]
it is more convenient to report this to the dev of your spigot, eden does not control that

**Comment by GoodestEnglish** [comment]
Looks like a spigot issue. Report it to your spigot fork dev.

**Comment by serumanooo** [comment]
> it is more convenient to report this to the dev of your spigot, eden does not take control in potions I believe

I know, but because i had this issue before with other spigot forks, i thought it could be somehow related to eden

**Comment by serumanooo** [comment]
> Looks like a spigot issue. Report it to your spigot fork dev.

Ok, i dont really want to use paperspigot, i think im gonna buy immanity

**Comment by GoodestEnglish** [comment]
Then it is some other plugin issues. Eden won't clear your inventory when you throw your potion.

**Comment by serumanooo** [comment]
> Then it is some other plugin issues. Eden won't clear your inventory when you throw your potion.

It is probably related to the spigot, because it started happening with goatspigot and paperspigot

**Comment by GoodestEnglish** [comment]
I highly doubt it is an issue with paper. I tested with paper in my side and didn't get this problem.

I recommend you to investigate your plugin further because of I think it might be some plugin issues.

**Comment by serumanooo** [comment]
> I highly doubt it is an issue with paper. I tested with paper in my side and didn't get this problem.
> 
> I recommend you to investigate your plugin further because of I think it might be some plugin issues.

Probably related to PvPenhanced, but if i buy immanity ill stop using it

**Comment by Hwaanx** [comment]
> > I highly doubt it is an issue with paper. I tested with paper in my side and didn't get this problem.
> > I recommend you to investigate your plugin further because of I think it might be some plugin issues.
> 
> Probably related to PvPenhanced, but if i buy immanity ill stop using it

I am trying other spigots too we also have the same map haha! how can i contact you?

**Comment by serumanooo** [comment]
> > > I highly doubt it is an issue with paper. I tested with paper in my side and didn't get this problem.
> > > I recommend you to investigate your plugin further because of I think it might be some plugin issues.
> > 
> > 
> > Probably related to PvPenhanced, but if i buy immanity ill stop using it
> 
> I am trying other spigots too we also have the same map haha! how can i contact you?

serumano_ on discord

**Comment by HierarchyMan** [comment]
> https://youtu.be/jFY2vhNO2TU
> 
> i think its related to the fork i was using at this video 
> (im using paper + kb plugin, im trying every fork and plugins to see which one has the better kb)

O shii that's PvP enhanced issue
I will fix it in the next release sorry bro
And thanks for the report
For now disable pot optimisation in config
