### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Antoniova1** [diamond-rip/Eden#510]
add in the configure the option to activate and deactivate that there is more than one fight in an arena, and that the display-players option can be activated and deactivated by the players, obviously with a low priority

**Comment by Chromaah** [comment]
i like that first option, i think it should clone the arena instead of using the same one, cosmetics plugin i made breaks it 😭

(i think GoodestEnglish should use something similar to the bedwars1058 arena system)

**Comment by serumanooo** [comment]
> i like that first option, i think it should clone the arena instead of using the same one, cosmetics plugin i made breaks it 😭
> 
> (i think GoodestEnglish should use something similar to the bedwars1058 arena system)

i remember he said something about use this bedwars1058 arena system, maybe hes doing something about it

**Comment by serumanooo** [comment]
also, i dont want to open a new issue about it, but i found this "error"
![image](https://github.com/diamond-rip/Eden/assets/132185379/1270522b-aa86-4cef-b296-b11d4751ad7f)

**Comment by GoodestEnglish** [comment]
> also, i dont want to open a new issue about it, but i found this "error" ![image](https://user-images.githubusercontent.com/132185379/257656664-1270522b-aa86-4cef-b296-b11d4751ad7f.png)

There should be a better explained error on top of your log. Send the detailed one to me, otherwise I can't locate what happened.

**Comment by serumanooo** [comment]
> > also, i dont want to open a new issue about it, but i found this "error" ![image](https://user-images.githubusercontent.com/132185379/257656664-1270522b-aa86-4cef-b296-b11d4751ad7f.png)
> 
> There should be a better explained error on top of your log. Send the detailed one to me, otherwise I can't locate what happened.

thats the problem, its just this (but ill check it again later)

**Comment by Antoniova1** [comment]
and another question, eden deactivates the spawning of entities, right?

**Comment by minehostil** [comment]
> add in the configure the option to activate and deactivate that there is more than one fight in an arena, and that the display-players option can be activated and deactivated by the players, obviously with a low priority

edit: if it is possible to add the option to enable or disable entity spawning, this is to make it more compatible with cosmetic plugins
