### ISSUE TITLE
Goldenhead

### ISSUE THREAD

**Issue by HierarchyMan** [diamond-rip/Eden#515]
right clicking goldenhead with kit intant gapple enabled does nothing
instead places it on the groudn
there are absolutely no errors in console 
![image](https://github.com/diamond-rip/Eden/assets/97939376/86392d31-7eff-4c02-91d2-469bae902a36)
heres the kit
![image](https://github.com/diamond-rip/Eden/assets/97939376/2083fb98-de18-4eac-899f-5b6824462a8d)

**Comment by GoodestEnglish** [comment]
That settings is for bridge. For golden head like this you should enable HypixelUHC

**Comment by HierarchyMan** [comment]
Thanks I'm, so dumb

**Comment by HierarchyMan** [comment]
> Thanks I'm, so dumb

And I think this is why you should try and fix the lore menus showing outside the screen with no way of fully reding them
