### ISSUE TITLE
Unable to use /stats command

### ISSUE THREAD

**Issue by HappyAreaBean** [diamond-rip/Eden#52]
Even though the player has logged into the server once, they are still unable to use /stats.
Also, I can't execute the /stats command either.

EDIT: I have player data disabled on my server.

**Comment by HierarchyMan** [comment]
Then you cant

**Comment by HierarchyMan** [comment]
Enable mongo to do /stats

**Comment by HappyAreaBean** [comment]
> Enable mongo to do /stats

Of course I have mongo enabled, lol

**Comment by HierarchyMan** [comment]
But you just said you had player data disabled

**Comment by HappyAreaBean** [comment]
> But you just said you had player data disabled

I should be more specific about that. I'm talking about server player data, which is the `playerdata` folder in your world folder.
Sorry for that.

**Comment by HierarchyMan** [comment]
You should reopen this idk
Ask @GoodestEnglish 
And maybe elaborate further

**Comment by HappyAreaBean** [comment]
GoodestEnglish closed as completed, so I can't reopen it. @GoodestEnglish
