### ISSUE TITLE
add abilities like hypractice

### ISSUE THREAD

**Issue by RainFallDev** [diamond-rip/Eden#522]
this will make the plugin batter
![2023-08-09_15 29 46](https://github.com/diamond-rip/Eden/assets/135520176/49e958e1-00cd-4d79-999c-399f3874b1bf)
![2023-08-09_15 29 51](https://github.com/diamond-rip/Eden/assets/135520176/939935ba-0a36-4621-8d38-fbbdfec3c038)
![2023-08-09_15 29 53](https://github.com/diamond-rip/Eden/assets/135520176/99be510d-c034-44fc-9727-376d1eaf605f)
![2023-08-09_15 30 14](https://github.com/diamond-rip/Eden/assets/135520176/3fc2c048-3985-4597-a44c-abd7957c332e)

![2023-08-09_15 30 06](https://github.com/diamond-rip/Eden/assets/135520176/2a569f97-0742-4cf3-9f46-91006504b57a)

**Comment by HierarchyMan** [comment]
What do these do?
Why did u close this?

**Comment by RainFallDev** [comment]
i will use coldabilitie

**Comment by Antoniova1** [comment]
> What do these do? Why did u close this?

that's for making kits like hcf, trapers and stuff like that, but you can look on spigot, there's a free plugin that adds those abilities

**Comment by RainFallDev** [comment]
yes
