### ISSUE TITLE
ArmorStands

### ISSUE THREAD

**Issue by HierarchyMan** [diamond-rip/Eden#526]
Well my plugin (Eden Parkour Addon) is 99% complete and ready to use with Eden but,
https://www.youtube.com/watch?v=vlTok22Rc00&ab_channel=cystol
Although this is the functionality, Eden wont allow the armor stands to spawn.
heck Eden doesn't allow any mob to spawn
can u add config option or whitelist for this?
cuz without armor stands its gonna be hard to make checkpoints.

**Comment by GoodestEnglish** [comment]
Use bukkit armorstand is really a bad habit and should really not being used. Please use packet instead of bukkit entity.

**Comment by HierarchyMan** [comment]
> Use bukkit armorstand is really a bad habit and should really not being used. Please use packet instead of bukkit entity.
> 

Welp it seems I'm gonna have to learn more stuff ig
