### ISSUE TITLE
problem with slpleef kit

### ISSUE THREAD

**Issue by Mahmoud-0800** [diamond-rip/Eden#532]
when 2 join spleef game one of them got killed random 

See here:
https://youtu.be/mnQ5fxzc_fU

**Comment by arm4xlll** [comment]
any errors in log? and send your kits.yml

**Comment by Mahmoud-0800** [comment]
> any errors in log? and send your kits.yml

no errors .


https://pastebin.com/T0Tc6ANA

**Comment by arm4xlll** [comment]
what spigot are you using?  maybe you configured the arena incorrectly (y-limit)

**Comment by Mahmoud-0800** [comment]
> what spigot are you using? maybe you configured the arena incorrectly (y-limit)
i use papermc

![image](https://github.com/diamond-rip/Eden/assets/141188411/c336ebe5-75f4-41b4-af53-43dfaaccb3c5)


![image](https://github.com/diamond-rip/Eden/assets/141188411/5fc65549-3d92-4cce-8d4a-410c082bcedb)

**Comment by arm4xlll** [comment]
> > what spigot are you using? maybe you configured the arena incorrectly (y-limit)
> > i use papermc
> 
> ![image](https://user-images.githubusercontent.com/141188411/260844197-c336ebe5-75f4-41b4-af53-43dfaaccb3c5.png)
> 
> ![image](https://user-images.githubusercontent.com/141188411/260844364-5fc65549-3d92-4cce-8d4a-410c082bcedb.png)

y-limit is the height at which players die when falling into the void, set it below the spawn point to set the maximum height for building use build-limit

**Comment by Mahmoud-0800** [comment]
okkk is my problem thx you
