### ISSUE TITLE
doesnt work

### ISSUE THREAD

**Issue by HistoryCity** [diamond-rip/Eden#533]
plugin doesnt work

**Comment by DoubleBiscuit** [comment]
If a plugin isn't working as expected, here are some steps you can take to troubleshoot the issue:

• Check Compatibility: Ensure that the plugin is compatible with the software or platform you are using. Sometimes, updates to the main software can break compatibility with older plugins.

• Update the Plugin: If there is an updated version of the plugin available, try installing it. Developers often release updates to fix bugs and improve compatibility.

• Check for Errors: Look for error messages or notifications related to the plugin. These can provide valuable information about what's going wrong.

• Review Documentation: Check the documentation provided with the plugin. It may contain troubleshooting tips or specific instructions for resolving common issues.

• Disable Other Plugins: Sometimes, conflicts between different plugins can cause issues. Try disabling other plugins one by one to see if the problem persists.

• Clear Cache: Clear your browser's cache or the cache of the software you're using. Old data in the cache can sometimes interfere with plugin functionality.

• Contact Support: If you can't resolve the issue on your own, reach out to the plugin developer's support team. They may be able to provide guidance or a solution.

• Check User Reviews: Look for user reviews or forums related to the plugin. Others may have experienced the same issue and posted solutions.

• Update Software: Ensure that your main software or platform is up-to-date. Outdated software can sometimes lead to compatibility issues with plugins.

• Consider Alternatives: If all else fails and the plugin is critical for your needs, consider looking for alternative plugins that offer similar functionality and better support.

Remember to always be cautious when troubleshooting and make backups of your data or settings before making significant changes. This will help you avoid data loss or unintended consequences.

**Comment by GoodestEnglish** [comment]
Please describe more about the issue you've faced

**Comment by HistoryCity** [comment]
I'm using Foxspigot but the latest version of Eden doesn't work

**Comment by minehostil** [comment]
> I'm using Foxspigot but the latest version of Eden doesn't work

java version, do you have the correct FAWE dependency??

**Comment by HistoryCity** [comment]
yes

**Comment by HistoryCity** [comment]
Java8，我用的FAWE:https://www.spigotmc.org/resources/fastasyncworldedit.13932/

**Comment by minehostil** [comment]
> Java8，我用的FAWE:https://www.spigotmc.org/resources/fastasyncworldedit.13932/

Use that versión https://ci.athion.net/job/FastAsyncWorldEdit-Legacy/

**Comment by HistoryCity** [comment]
FAWE and Eden folders are not created

**Comment by HistoryCity** [comment]
![image](https://github.com/diamond-rip/Eden/assets/142790583/ab2eefa0-67a7-40e9-89e1-4b5b9f5cad7a)

**Comment by HistoryCity** [comment]
![image](https://github.com/diamond-rip/Eden/assets/142790583/1a214198-6eba-4b04-bc87-379cd5f39ae1)

**Comment by minehostil** [comment]
> ![image](https://user-images.githubusercontent.com/142790583/263276744-1a214198-6eba-4b04-bc87-379cd5f39ae1.png)

read or send the log from your console, something should appear there  and remove the worldedit plugin, fawe already brings its own worldedit that must be the problem
