### ISSUE TITLE
Unable to use /stats command when `<player>.dat` saving is disabled

### ISSUE THREAD

**Issue by HappyAreaBean** [diamond-rip/Eden#54]
> Corrected details on #52.

Look like it's a little confuse when I said “player data”, let me be more specific is when `<player>.dat` saving is disabled will not let you use /stats command.
Because it will make every player not played before since the player.dat isn't saved.

**Comment by GoodestEnglish** [comment]
<player>.dat is needed because the system needs to detect if the player has joined the server before or not. This is to prevent MongoDB connection spam. Would recommend turn player data saving back, it doesn't affect too much performance anyways.
