### ISSUE TITLE
More

### ISSUE THREAD

**Issue by Mekvil** [diamond-rip/Eden#56]
Make unranked RANDOM MAPS. when my players que unranked he always get on soccer bc it's first map.Make swith inventory when it's duel.

**Comment by HierarchyMan** [comment]
I think random maps should be added.
+1

**Comment by GoodestEnglish** [comment]
Fixed in https://github.com/diamond-rip/Eden/releases/tag/1.0.26-BETA-f29a0a8

**Comment by HierarchyMan** [comment]
Just that latest one in releases

**Comment by Mekvil** [comment]
It's latest src
