### ISSUE TITLE
Arena allow kit menu

### ISSUE THREAD

**Issue by HappyAreaBean** [diamond-rip/Eden#63]
When setting up an arena's allowed kits, it should open a menu with a list of kits to let you choose what kit is allowed.
This is more convenient than typing each kit one at a time, especially when you have 8+ kits in the same arena and need to set up 10 maps.

**Comment by HierarchyMan** [comment]
+1

**Comment by GoodestEnglish** [comment]
Added in https://github.com/diamond-rip/Eden/releases/tag/1.0.27-BETA-cd98a9a
