### ISSUE TITLE
reset position after point is still bugged

### ISSUE THREAD

**Issue by HierarchyMan** [diamond-rip/Eden#76]
this option should only reset the spawn of player who lost the round but keep the position of player who won the round
and this also should trigger respawn system instead of new round time

Every other fix/change works great
ur very skilled

**Comment by GoodestEnglish** [comment]
what do you mean by "trigger respawn system"?

**Comment by GoodestEnglish** [comment]
Not sure what "trigger respawn system" means, but I've tried to fix it in here https://github.com/diamond-rip/Eden/releases/tag/1.0.27-BETA-cd98a9a. Please give it a try and let me know the result.

**Comment by HierarchyMan** [comment]
@GoodestEnglish It shouldn't just start a new round and set the player to spawn
it should set player to spectator and shouldn't start new round even Cuz that freezes you which shouldn't happen.
it should give point set loser to spectator and use respawn time to tp the player back
