### ISSUE TITLE
fox spigot bug and a suggestion

### ISSUE THREAD

**Issue by HierarchyMan** [diamond-rip/Eden#77]
we can still slowly move during kit start time when freeze is enabled (only when using fox spigot)
ability to customise the duration of block reset (battlerush has 10 seconds but stickfight only has 5)

**Comment by GoodestEnglish** [comment]
I don't own foxspigot, so I cannot check about this bug. But if you are sure about it only happens on foxspigot, then it is a foxspigot bug.

**Comment by GoodestEnglish** [comment]
Added block reset duration in https://github.com/diamond-rip/Eden/releases/tag/1.0.27-BETA-cd98a9a
