### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by ABIGDachshunch** [diamond-rip/Eden#84]
Start Freeze Won't Work In The Lastest Version
And death on water too
Kit Bugs Loading They'll appear slow slow slow

**Comment by GoodestEnglish** [comment]
what do you mean by the last sentence?

**Comment by HierarchyMan** [comment]
GoodestEnglish he's using Vega spigot which I tried myself
This isn't a problem with your plugin Vega spigot doesn't have some papermc events which ur plugin relies on
I think you should suggest the use of other forks and close this issue

**Comment by ABIGDachshunch** [comment]
> @GoodestEnglish he's using Vega spigot(or any other unsupported spigot for that matter) which I tried myself This isn't a problem with your plugin Vega spigot doesn't have some papermc events which ur plugin relies on I think you should suggest the use of other forks and close this issue

well I used Vega Spigot in an old version and all the features is normal and it just a problem in the new version.

**Comment by ABIGDachshunch** [comment]
> @GoodestEnglish he's using Vega spigot(or any other unsupported spigot for that matter) which I tried myself This isn't a problem with your plugin Vega spigot doesn't have some papermc events which ur plugin relies on I think you should suggest the use of other forks and close this issue

U never try Vega Spigot? 
and u can try it on version 1.0.24

**Comment by HierarchyMan** [comment]
The issues you listed are only bugged in Vega spigot is what I meant to say try using other papermc fork

**Comment by GoodestEnglish** [comment]
I will verify this once I am free.

**Comment by GoodestEnglish** [comment]
Can't reproduce the bug. Please try normal paperspigot and if paperspigot also has that bug, please record a short video so we can see what happens.

**Comment by ABIGDachshunch** [comment]
> that

Well It work on the 1.0.26
