### ISSUE TITLE
Bug Start freeze

### ISSUE THREAD

**Issue by Shzv** [diamond-rip/Eden#87]
in bridge mode when start with start freeze one of the two players flies and is expelled from the server,
i tried to put spawn high and low but kick for fly

**Comment by GoodestEnglish** [comment]
Can't reproduce the bug, may you please record a short video and let me see what exactly happens?

**Comment by HierarchyMan** [comment]
@GoodestEnglish you should allow head movement and y level change when in round countdown freeze
And x,y movement should be blocked
That should fix 2 kicks i.e. Bad packets/too many packets AND fly kick
Also request users to enable allow-flight in server properties
All the steps mentioned above should fix this issue without even needing a demonstration video

**Comment by Shzv** [comment]
sorry but i read now.
anyway this is the video https://i.imgur.com/rqhSYUS.mp4

**Comment by GoodestEnglish** [comment]
Can you send your kit.yml and your arena.yml?

**Comment by Shzv** [comment]
I lost the kit from github. for arenas I use slimeworldmanager but even without it I have the same problem
https://www.dropbox.com/scl/fo/cseccyqtyq7k5ft806gs5/h?dl=0&rlkey=anzu65x65r846grp7ixmxt3ha

**Comment by GoodestEnglish** [comment]
> sorry but i read now. anyway this is the video https://i.imgur.com/rqhSYUS.mp4

You shouldn't set your team spawn location on air. Make sure it is set on ground.

**Comment by GoodestEnglish** [comment]
> @GoodestEnglish you should allow head movement and y level change when in round countdown freeze And x,y movement should be blocked That should fix 2 kicks i.e. Bad packets/too many packets AND fly kick Also request users to enable allow-flight in server properties All the steps mentioned above should fix this issue without even needing a demonstration video

x,y movement is blocked, y movement isn't blocked, also plugin doesn't block rotation updates.

**Comment by Shzv** [comment]
of course I tried both. and I thought to fix it by putting the spawn in the air but even from the ground I have the same problem

**Comment by GoodestEnglish** [comment]
> of course I tried both. and I thought to fix it by putting the spawn in the air but even from the ground I have the same problem

Send a clip which team spawn is on the ground

**Comment by Shzv** [comment]
sorry my mistake i just tried it and it works fine sorry for wasting my time.
when i tried it i must have set it wrong
