### ISSUE TITLE
Another Bug

### ISSUE THREAD

**Issue by ABIGDachshunch** [diamond-rip/Eden#88]
can't place block in builduhc even if build is already enable...

**Comment by HierarchyMan** [comment]
What spigot?

**Comment by GoodestEnglish** [comment]
Spigot should not matter in this case. I am guessing you messed up your arena configuration. Please send your arena.yml

**Comment by ABIGDachshunch** [comment]
> Spigot should not matter in this case. I am guessing you messed up your arena configuration. Please send your arena.yml

arenas:
  Temple:
    icon: |
      rO0ABXNyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAADbWFwdAAPTGph
      dmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFibGVNYXAk
      U2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAlsABGtleXN0ABNbTGphdmEvbGFuZy9PYmplY3Q7WwAG
      dmFsdWVzcQB+AAR4cHVyABNbTGphdmEubGFuZy5PYmplY3Q7kM5YnxBzKWwCAAB4cAAAAAJ0AAI9
      PXQABHR5cGV1cQB+AAYAAAACdAAeb3JnLmJ1a2tpdC5pbnZlbnRvcnkuSXRlbVN0YWNrdAAFR1JB
      U1M=
    y-limit: 0
    build-max: -1
    kits:
    - Nodebuff
    - Debuff
    enabled: true
    details:
      '0':
        a: '#w;NodebuffArena:#x;-39.62393539646865:#y;79.0:#z;117.47302504089822:#p;-0.9431313:#yaw;-90.12933'
        b: '#w;NodebuffArena:#x;4.680250069189502:#y;79.0:#z;117.48868111194417:#p;-0.9968659:#yaw;-270.17578'
        min: '#w;NodebuffArena:#x;-47.0:#y;78.0:#z;151.0:#p;0.0:#yaw;0.0'
        max: '#w;NodebuffArena:#x;7.0:#y;92.0:#z;87.0:#p;0.0:#yaw;0.0'
  Soccer:
    icon: |
      rO0ABXNyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAADbWFwdAAPTGph
      dmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFibGVNYXAk
      U2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAlsABGtleXN0ABNbTGphdmEvbGFuZy9PYmplY3Q7WwAG
      dmFsdWVzcQB+AAR4cHVyABNbTGphdmEubGFuZy5PYmplY3Q7kM5YnxBzKWwCAAB4cAAAAAJ0AAI9
      PXQABHR5cGV1cQB+AAYAAAACdAAeb3JnLmJ1a2tpdC5pbnZlbnRvcnkuSXRlbVN0YWNrdAAFR1JB
      U1M=
    y-limit: 0
    build-max: -1
    kits:
    - Nodebuff
    - Debuff
    - Boxing
    enabled: true
    details:
      '0':
        a: '#w;NodebuffArena:#x;-463.5208420550542:#y;76.0:#z;939.4318618322475:#p;-0.60842156:#yaw;-180.0022'
        b: '#w;NodebuffArena:#x;-463.49882088130124:#y;76.0:#z;867.4985203410959:#p;-0.6264505:#yaw;-0.031982422'
        min: '#w;NodebuffArena:#x;-424.0:#y;75.0:#z;848.0:#p;0.0:#yaw;0.0'
        max: '#w;NodebuffArena:#x;-504.0:#y;119.0:#z;953.0:#p;0.0:#yaw;0.0'
  Mario:
    icon: |
      rO0ABXNyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAADbWFwdAAPTGph
      dmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFibGVNYXAk
      U2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAlsABGtleXN0ABNbTGphdmEvbGFuZy9PYmplY3Q7WwAG
      dmFsdWVzcQB+AAR4cHVyABNbTGphdmEubGFuZy5PYmplY3Q7kM5YnxBzKWwCAAB4cAAAAAJ0AAI9
      PXQABHR5cGV1cQB+AAYAAAACdAAeb3JnLmJ1a2tpdC5pbnZlbnRvcnkuSXRlbVN0YWNrdAAFR1JB
      U1M=
    y-limit: 0
    build-max: -1
    portal-protection-radius: 3
    kits:
    - Sumo
    enabled: true
    details:
      '0':
        a: '#w;NodebuffArena:#x;-284.550099957964:#y;98.0:#z;-131.6395187271438:#p;1.150812:#yaw;-0.78244185'
        b: '#w;NodebuffArena:#x;-284.3660317593964:#y;98.0:#z;-122.98197318471124:#p;2.1461716:#yaw;-180.00017'
        min: '#w;NodebuffArena:#x;-255.0:#y;79.0:#z;-84.0:#p;0.0:#yaw;0.0'
        max: '#w;NodebuffArena:#x;-315.0:#y;110.0:#z;-164.0:#p;0.0:#yaw;0.0'
  Desert:
    icon: |
      rO0ABXNyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAADbWFwdAAPTGph
      dmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFibGVNYXAk
      U2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAlsABGtleXN0ABNbTGphdmEvbGFuZy9PYmplY3Q7WwAG
      dmFsdWVzcQB+AAR4cHVyABNbTGphdmEubGFuZy5PYmplY3Q7kM5YnxBzKWwCAAB4cAAAAAJ0AAI9
      PXQABHR5cGV1cQB+AAYAAAACdAAeb3JnLmJ1a2tpdC5pbnZlbnRvcnkuSXRlbVN0YWNrdAAFR1JB
      U1M=
    y-limit: 0
    build-max: -1
    portal-protection-radius: 3
    kits:
    - Builduhc
    - Hypixeluhc
    enabled: true
    details:
      '0':
        a: '#w;NodebuffArena:#x;-32.40598796397792:#y;197.0:#z;-360.2573905298433:#p;-1.2059507:#yaw;179.26746'
        b: '#w;NodebuffArena:#x;-32.51646455990961:#y;197.0:#z;-449.3668717618954:#p;-1.1535659:#yaw;359.57864'
        min: '#w;NodebuffArena:#x;-69.0:#y;190.0:#z;-461.0:#p;0.0:#yaw;0.0'
        max: '#w;NodebuffArena:#x;9.0:#y;242.0:#z;-345.0:#p;0.0:#yaw;0.0'
  Chest:
    icon: |
      rO0ABXNyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAADbWFwdAAPTGph
      dmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFibGVNYXAk
      U2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAlsABGtleXN0ABNbTGphdmEvbGFuZy9PYmplY3Q7WwAG
      dmFsdWVzcQB+AAR4cHVyABNbTGphdmEubGFuZy5PYmplY3Q7kM5YnxBzKWwCAAB4cAAAAAJ0AAI9
      PXQABHR5cGV1cQB+AAYAAAACdAAeb3JnLmJ1a2tpdC5pbnZlbnRvcnkuSXRlbVN0YWNrdAAFR1JB
      U1M=
    y-limit: 0
    build-max: -1
    portal-protection-radius: 0
    kits:
    - Nodebuff
    - Debuff
    - combo
    - Archer
    enabled: true
    details:
      '0':
        a: '#w;NodebuffArena:#x;269.4884479913078:#y;167.0:#z;-125.57218525965467:#p;-0.6829588:#yaw;359.75815'
        b: '#w;NodebuffArena:#x;269.4611730077306:#y;167.0:#z;-25.555448081563622:#p;-0.16589688:#yaw;179.98865'
        min: '#w;NodebuffArena:#x;216.0:#y;165.0:#z;-129.0:#p;0.0:#yaw;0.0'
        max: '#w;NodebuffArena:#x;322.0:#y;221.0:#z;-23.0:#p;0.0:#yaw;0.0'
  Stadium:
    icon: |
      rO0ABXNyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAADbWFwdAAPTGph
      dmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFibGVNYXAk
      U2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAlsABGtleXN0ABNbTGphdmEvbGFuZy9PYmplY3Q7WwAG
      dmFsdWVzcQB+AAR4cHVyABNbTGphdmEubGFuZy5PYmplY3Q7kM5YnxBzKWwCAAB4cAAAAAJ0AAI9
      PXQABHR5cGV1cQB+AAYAAAACdAAeb3JnLmJ1a2tpdC5pbnZlbnRvcnkuSXRlbVN0YWNrdAAFR1JB
      U1M=
    y-limit: 0
    build-max: -1
    portal-protection-radius: 0
    kits:
    - Archer
    enabled: true
    details:
      '0':
        a: '#w;NodebuffArena:#x;722.3357612070937:#y;135.0:#z;23.736750393216045:#p;-0.6893971:#yaw;-180.12787'
        b: '#w;NodebuffArena:#x;722.7180635771093:#y;135.0:#z;-36.61532916574464:#p;-0.51770943:#yaw;-0.046844482'
        min: '#w;NodebuffArena:#x;695.0:#y;128.0:#z;23.0:#p;0.0:#yaw;0.0'
        max: '#w;NodebuffArena:#x;739.0:#y;149.0:#z;-41.0:#p;0.0:#yaw;0.0'

**Comment by GoodestEnglish** [comment]
Your build max isnt set yet

**Comment by ABIGDachshunch** [comment]
> Your build max isnt set yet

I have to set it? Oh mbmb

**Comment by ABIGDachshunch** [comment]
Close this
