### ISSUE TITLE
Here's how only reset position of loser after round reset should be

### ISSUE THREAD

**Issue by HierarchyMan** [diamond-rip/Eden#89]
@GoodestEnglish
X- It shouldn't just start a new round and set the loser directly to spawn
- it should set player to spectator and shouldn't start new round event (Cuz that freezes you which shouldn't happen.)
- it should give point
-set loser to spectator
-and use respawn time to tp the player back

**Comment by GoodestEnglish** [comment]
Please don't close the old issue and open a new issue which related to an old issue. I will push a fix within a couple days

**Comment by HierarchyMan** [comment]
Ok srry

**Comment by GoodestEnglish** [comment]
Update: This is more complicated than I originally thought, will need more time to implement this

**Comment by GoodestEnglish** [comment]
Keep this open first, I will close this after I do the changes

**Comment by GoodestEnglish** [comment]
I've pushed an update which attempt to fix the issue you've described. Please check it out ;)

Make sure to enable onlyLoserResetPositionWhenGetPoint

**Comment by HierarchyMan** [comment]
I'm sorry I'm unable to check it rn (school stuff) but I'm sure you did a good job
