### ISSUE TITLE
Build Reset BUG

### ISSUE THREAD

**Issue by Shzv** [diamond-rip/Eden#91]
resetting builds in modes where building is allowed does not completely reset the builds
but leave builds .

modes I've tried: Bridge, BedFigh

![Desktop Screenshot 2023 01 14 - 22 18 28 35](https://user-images.githubusercontent.com/122161612/212559399-c6829f39-8f47-40d7-a1e1-bfd01f219f89.png)

demonstration video Bridge: https://i.imgur.com/dG9svq7.mp4

demonstration video: with slimeworldmanager  https://i.imgur.com/WpsQfSY.mp4.
and without slimeworldmanager https://i.imgur.com/4EkSWK3.mp4. (map placed in the same world as the hub)

**Comment by ABIGDachshunch** [comment]
well maybe that problem is bc your min and max ig😌

**Comment by GoodestEnglish** [comment]
I am guessing you setup the min and max incorrectly, please check [this](https://github.com/diamond-rip/Eden/wiki/Arenas-Setup#edit-arenas-location) for more information

**Comment by Shzv** [comment]
I set the maximum 107y and the minimum 62y
and the build limit is 99y so up to height 99 you can build above no

**Comment by GoodestEnglish** [comment]
Please post your arena.yml and let me know which map you are playing.

**Comment by Shzv** [comment]
Castle:
    icon: "rO0ABXNyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAADbWFwdAAPTGph\r\
      \ndmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFibGVNYXAk\r\
      \nU2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAlsABGtleXN0ABNbTGphdmEvbGFuZy9PYmplY3Q7WwAG\r\
      \ndmFsdWVzcQB+AAR4cHVyABNbTGphdmEubGFuZy5PYmplY3Q7kM5YnxBzKWwCAAB4cAAAAAJ0AAI9\r\
      \nPXQABHR5cGV1cQB+AAYAAAACdAAeb3JnLmJ1a2tpdC5pbnZlbnRvcnkuSXRlbVN0YWNrdAAFR1JB\r\
      \nU1M=\r\n"
    y-limit: 74
    build-max: 86
    portal-protection-radius: 3
    kits:
    - bedfight
    enabled: true
    details:
      '0':
        a: '#w;Castle:#x;21.5:#y;78.0:#z;35.5:#p;-1.9112736:#yaw;89.08496'
        b: '#w;Castle:#x;-19.5:#y;78.0:#z;31.5:#p;2.6023598:#yaw;270.602'
        min: '#w;Castle:#x;29.0:#y;62.0:#z;15.0:#p;0.0:#yaw;0.0'
        max: '#w;Castle:#x;-28.0:#y;107.0:#z;51.0:#p;0.0:#yaw;0.0'
  Treehouse:
    icon: "rO0ABXNyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAADbWFwdAAPTGph\r\
      \ndmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFibGVNYXAk\r\
      \nU2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAlsABGtleXN0ABNbTGphdmEvbGFuZy9PYmplY3Q7WwAG\r\
      \ndmFsdWVzcQB+AAR4cHVyABNbTGphdmEubGFuZy5PYmplY3Q7kM5YnxBzKWwCAAB4cAAAAAJ0AAI9\r\
      \nPXQABHR5cGV1cQB+AAYAAAACdAAeb3JnLmJ1a2tpdC5pbnZlbnRvcnkuSXRlbVN0YWNrdAAFR1JB\r\
      \nU1M=\r\n"
    y-limit: 83
    build-max: 100
    portal-protection-radius: 5
    kits:
    - bridge
    enabled: true
    details:
      '0':
        a: '#w;Treehouse:#x;27.5:#y;99.0:#z;0.5:#p;-4.737089:#yaw;84.58643'
        b: '#w;Treehouse:#x;-26.5:#y;99.0:#z;0.5:#p;2.0298529:#yaw;-88.90066'
        min: '#w;Treehouse:#x;-24.0:#y;85.0:#z;-12.0:#p;0.0:#yaw;0.0'
        max: '#w;Treehouse:#x;24.0:#y;109.0:#z;12.0:#p;0.0:#yaw;0.0'

**Comment by GoodestEnglish** [comment]
Also send me the map of Treehouse, thanks.

**Comment by Shzv** [comment]
https://www.dropbox.com/scl/fo/i9nf45bizsjvmr0lolhz6/h?dl=0&rlkey=58k8wtx77h5bthehadm8678z4

**Comment by GoodestEnglish** [comment]
Please try this version https://drive.google.com/file/d/1n6nnGu8g3h2RaJk5RoRqmNNUmzymue4Z/view?usp=share_link

I've personally tested this and it works with your config and with your map

**Comment by Shzv** [comment]
I was already using that version but I changed it but it doesn't work
https://i.imgur.com/SJ1DqEd.mp4
maybe and some plugins that i use now i try to keep only eden and the plugins i used to serve in eden

**Comment by GoodestEnglish** [comment]
> I was already using that version but I changed it but it doesn't work https://i.imgur.com/SJ1DqEd.mp4 maybe and some plugins that i use now i try to keep only eden and the plugins i used to serve in eden

Please manually reset the arena by yourself and save the map by using /save-all first.

**Comment by Shzv** [comment]
I did /save-all
later i removed the plugins and i tested, but the problem is still there
https://i.imgur.com/Cv2kzt0.mp4

**Comment by Shzv** [comment]
so i don't think it's a problem like i thought about slimeworld or other plugins so i don't know

**Comment by Shzv** [comment]
ok I fixed I had to redo the map I don't know why but redoing it fixed it thanks

**Comment by GoodestEnglish** [comment]
> ok I fixed I had to redo the map I don't know why but redoing it fixed it thanks

Because Eden used your last saved map as cache. Remember not to force close the server, use /stop instead (If you are already using /stop, ignore this)

**Comment by Shzv** [comment]
now when you build a bridge after that until you can't build that bridge it is not reset
![Desktop Screenshot 2023 01 15 - 23 16 25 29](https://user-images.githubusercontent.com/122161612/212570043-38596e33-b931-4c7e-a9b0-1f561d2fb3e4.png)

and i think the problem is that the parts near the invisible cube of the min and max don't reset like in the picture

**Comment by GoodestEnglish** [comment]
> now when you build a bridge after that until you can't build that bridge it is not reset ![Desktop Screenshot 2023 01 15 - 23 16 25 29](https://user-images.githubusercontent.com/122161612/212570043-38596e33-b931-4c7e-a9b0-1f561d2fb3e4.png)
> 
> and i think the problem is that the parts near the invisible cube of the min and max don't reset like in the picture

Send me arena.yml and the map also

**Comment by Shzv** [comment]
https://www.dropbox.com/s/km7nx39a146n43z/arena.rar?dl=0
I don't have the map but I gave you the schematic

**Comment by GoodestEnglish** [comment]
Can't reproduce the bug. Do you have auto-save world on? If yes, disable it. Also, after you modify the arenas. You have to restart the server so the server can save a arena cache to the system.

**Comment by Shzv** [comment]
where do I disable saving the world?

**Comment by GoodestEnglish** [comment]
/save-off or /save off, i forgot which

I will look deeply into this issue. I am currently not at home.

**Comment by Shzv** [comment]
however, I did everything you told me but that part as per photo is not deleted.
I don't use the database of the eden plugin maybe. anyway thanks for the help I'm going now that I have to sleep that tomorrow I have to work

**Comment by GoodestEnglish** [comment]
I see you have maps separate to different world. Could you please try to setup your world in a single world? (Which means all maps and the spawn should be in the same world)

This is also a prefered way to setup a practice server. Every practice server like lunar and minemen do like this

**Comment by Shzv** [comment]
> resetting builds in modes where building is allowed does not completely reset the builds but leave builds .
> 
> modes I've tried: Bridge, BedFigh
> 
> ![Desktop Screenshot 2023 01 14 - 22 18 28 35](https://user-images.githubusercontent.com/122161612/212559399-c6829f39-8f47-40d7-a1e1-bfd01f219f89.png)
> 
> demonstration video Bridge: https://i.imgur.com/dG9svq7.mp4
> 
> demonstration video: with slimeworldmanager https://i.imgur.com/WpsQfSY.mp4. and without slimeworldmanager https://i.imgur.com/4EkSWK3.mp4. (map placed in the same world as the hub)

**Comment by GoodestEnglish** [comment]
So I've made some changes on the arena chunk. Here's the link: https://drive.google.com/file/d/1uZQ52yWgsiWjertUtHfFBTmxFN4PHYKz/view?usp=share_link

Let me know the results after you tested it. Ignore the version tag since I didn't change the tag.

**Comment by Shzv** [comment]
hello i just got back i just tried it and still the same thing
![Desktop Screenshot 2023 01 16 - 08 23 43 52](https://user-images.githubusercontent.com/122161612/212620501-6c7c8d81-2db1-4183-92ba-12d0d548cbdd.png)
I put the maps all on the same word and I'm not using slimeworldmanager anymore and I used eden that you gave

**Comment by GoodestEnglish** [comment]
Do you have OBS? This is kinda getting out of control right now. I cannot reproduce the bug since then and I need a detailed video to see how it happens. Please record a video which shows you start the match, place the block, end the match, proof of the block didn't get cleared. 

I will still try to fix the bug. But uk, school started, so the dev time will be slower.

**Comment by Shzv** [comment]
the version of eden 1.0.28
I set min and max a little too far 😂 but it doesn't change
anyway sorry if the video is a bit long but I tried to put everything
https://www.dropbox.com/s/p0zki8j34pvvszk/2023-01-16%2008-56-07.mkv?dl=0
sorry i couldn't upload it i sent you the download

**Comment by Shzv** [comment]
(anyway a tip why don't you put the command /queue (the game mode) for example /queue Bridge
so instead of making a menu via eden you use other plugins like deluxe menu or others.
it has nothing to do with it but since you have school I think it would save you time)

**Comment by GoodestEnglish** [comment]
Recoded part of the arena chunk system with another magic. Please try this version and let me know the result https://drive.google.com/file/d/1OyMPEjcaA5J6MMpsYuuTkqu7cBwqnxgO/view?usp=share_link

**Comment by Shzv** [comment]
sorry I was a bit busy, however I just tested the bug is solved congratulations great job.
